### ISSUE TITLE
Add AoT with Universal etc

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-angular2-universal#10]

**Comment by tinchou** [comment]
What's keeping us from AoT'ing with Universal and ASP.NET?

**Comment by MarkPieszak** [comment]
I'll get going with it tomorrow @tinchou 
Keep you posted!

**Comment by MarkPieszak** [comment]
Waiting for when we finish the move to Core https://github.com/angular/angular/issues/13822

**Comment by hheexx** [comment]
@MarkPieszak 
Can we expect aot soon ?

**Comment by MarkPieszak** [comment]
Merged in, big changes to structure, it was time to really clean things up there. #151
