### ISSUE TITLE
Add project to "dotnet new" template

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-angular2-universal#104]
Once we are using Ng4.x and the new Universal .NET integration, i want to simply a few things within the app, clean it up and submit it to dotnet new. 

🎈

Waiting on #118 #57 #58 #79

**Comment by manijak** [comment]
Hi @MarkPieszak, will there be a new template any time soon, or can we just download directly from master? 

I used the current template and it installed the "old" structure with angular 2.x.

**Comment by MarkPieszak** [comment]
I was hoping to finish out a few more issues & improvements and I wanted to post it on `dotnet template` yeah :)

For now if you want to at least start playing around with it, you can just pull down from Master, I'll have it in better shape soon! 

The improvements I'll be making would be outside of the `/Client` folder at this point anyway.

**Comment by kannan2106** [comment]
hi...when will you release dotnet template?....very long time we are waiting....pls update.

**Comment by MarkPieszak** [comment]
Apologies I'll add it on there this weekend! @kannan2106 
I was hoping to fix it up a little more but I can always update the template later :)

**Comment by kannan2106** [comment]
@MarkPieszak :  i got aspnetcore spa with angular 4 template from @SteveSandersonMS. Anyway thanks :)

**Comment by isaac2004** [comment]
closing and adding issue to META issue list
