### ISSUE TITLE
Add Authentication via Azure Active Directory

### ISSUE THREAD

**Issue by albrookesplowman** [MarkPieszak/aspnetcore-angular2-universal#105]
Hi Mark,

this is just the starter project that I have been looking for - an angular 2 client with a .net core server that supports server side rendering.

However, I was wondering whether it was possible to add authentication support via the azure active directory. 

So far, I have created an app entry for my server API and configured this via my appsettings.json file and added the following into the startup.cs file.

      app.UseJwtBearerAuthentication(new JwtBearerOptions
      {
        AutomaticAuthenticate = true,
        AutomaticChallenge = true,
        Authority = String.Format(Configuration["AzureAd:AadInstance"], Configuration["AzureAd:Tenant"]),
        Audience = Configuration["AzureAd:Audience"],
      });

When I add the [Authorize] attribute to the controller in the server, it is stopping any browsers calling the API for the data which is wonderful.  However, the call in the api.ts file

        return this._http.get(url, options)
            .map(res => res.json())
            .do(json => { if (isNode) { this._cache.set(key, json); } })
            .share();

is still getting through the authentication regardless of the [Authorize] attribute.  Is there any reason why this is the case?  I would have thought that I would have to integrate some AAD javascript (e.g. ADAL) to authenticate the client with the active directory prior to the call being successful to the server.

Any ideas?

Al

**Comment by albrookesplowman** [comment]
Is this done with the  [ValidateAntiForgeryToken] attribute in the server controllers?  Does this the same effect without the need of linking to active directory?

**Comment by MarkPieszak** [comment]
Let me get back to you soon, apologies swamped this weekend!

**Comment by MarkPieszak** [comment]
Are you providing `options` to the call there? Headers or anything?

**Comment by albrookesplowman** [comment]
Hi Mark,  Sorry for the delay in getting back to you... The day job is quite hectic at the moment.  I will have another look at this over the next few days and I will let you know if I can get it working correctly.  I have found some other templates that show me how to do it so I will try and integrate it into this template.

**Comment by albrookesplowman** [comment]
I have finally had some time to give this some more thought... and I have been reading around and there may be a better solution to what I need to do .... IdentityServer4.   Does this make any sense and would it be of any interest to you?

**Comment by MarkPieszak** [comment]
Is IdentityServer4 just for ActiveDirectory or other login ID situations?

**Comment by albrookesplowman** [comment]
It can be used with other external login providers...

https://blogs.msdn.microsoft.com/webdev/2016/09/19/introducing-identityserver4-for-authentication-and-access-control-in-asp-net-core/

I was going to develop my application to use ActiveDirectory but I am beginning to consider the benefit of linking in with other identity providers e.g. google/facebook etc.. so if you are interested in adding that functionality into this core system then I would be happy to develop/integrate it so you can get the benefit too

**Comment by MarkPieszak** [comment]
I think having Google/FB/Twitter integration would be huge for most people, plus they could just as easily remove it if they don't need it!

**Comment by MarkPieszak** [comment]
I'm actually going to revert a few recent changes do you want to wait and I'll ping you when we're all set and you can try to add those features? @albrookesplowman

**Comment by albrookesplowman** [comment]
No probs - I have done a clone of a couple of days ago so I will try some bits and pieces in that clone and then, once ready, add it in when I have it working.... fingers crossed... :)

**Comment by Adondriel** [comment]
in startup.cs 

     public static void Main(string[] args)
     {
       // FOR USING KESTREL
       // var host = new WebHostBuilder()
       //     .UseKestrel()
       //     .UseContentRoot(Directory.GetCurrentDirectory())
       //     .UseIISIntegration()
       //     .UseStartup<Startup>()
       //     .Build();
      //FOR USING WebListener
      var host = new WebHostBuilder()
        .UseContentRoot(Directory.GetCurrentDirectory())
        .UseStartup<Startup>()
        .UseWebListener(options => 
        {
          options.ListenerSettings.Authentication.Schemes = AuthenticationSchemes.NTLM;
        })
        .Build();

      host.Run();
    }

this should work, if not make sure the web.config looks like: (I'm pretty sure this is for if you are hosting with IIS) This will not work on anything but windows, this does not need to be hosted on IIS. Not even sure if you CAN host this with IIS atm.

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <system.webServer>
        <handlers>
         <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" 
          resourceType="Unspecified"/>
       </handlers>
       <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" 
      stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="true"/>
     </system.webServer>
     </configuration>

**Comment by isaac2004** [comment]
I know you probably already moved on, but there are some adal.js wrappers for ng4 out there that have auth API call wrappers. Here is an example

https://github.com/ranveeraggarwal/ng2-adal-QuickStart

**Comment by isaac2004** [comment]
@MarkPieszak I am closing this one since it seems to be dead. We should add auth (AAD, FB, Google+) to the list of add-on modules
