### ISSUE TITLE
Generated JS not linked in new folder structure

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#106]
Hi, I just have checked new folder structure now.

And found a major bug.

That is this-

![untitled](https://cloud.githubusercontent.com/assets/4152843/23339018/47b98a92-fc43-11e6-85dd-0462336d4a0e.jpg)

Actually, both of the files are generated from webpack-

![untitled](https://cloud.githubusercontent.com/assets/4152843/23339031/96a5d0fc-fc43-11e6-843a-ba98007908a2.jpg)

But they are not found after making a request-

**vendor.js-**
![untitled](https://cloud.githubusercontent.com/assets/4152843/23339046/dd68c26a-fc43-11e6-9382-613f2f2c3812.jpg)

**main-client.js-**
![untitled](https://cloud.githubusercontent.com/assets/4152843/23339054/fb1ff008-fc43-11e6-950c-3142170e98c1.jpg)

So, the main problem is-

**dist folder is not maped as a static resource folder**

I think @MarkPieszak , you get me.

Waiting for the update.

Thanks

**Comment by AbrarJahin** [comment]
I have got the issue.

It is generated because the code folder is not accessible by VS.

So, I have moved the folder or run VS in admin mode, and that solves the problem 🥇

**Comment by MarkPieszak** [comment]
Is it something others need to do we should push into Master, or is everything ok?
