### ISSUE TITLE
** Repo updates ** for Watchers & Contributors

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-angular2-universal#113]
# When is the Angular 4.x upgrade coming?

Official Angular 4.x release is slotted for the *week of March 22nd*, 
but I am hopeful to **release the upgraded Universal solution here in RC form sometime soon**, so we can give it a solid test run to provide any possible feedback / errors we run into with it, with the .NET-Angular SSR integration. I'm sorry for any delay on this! 

We will no longer be using TagHelpers in the Views/Home/index.cshtml (the `asp-prerender`), but the code will be ran within the HomeController, and pass:
`ViewData["Html"], ViewData["Title"], ViewData["Meta"]` 
all down to the MVC Views to be rendered for ultimate SEO 💯 

### Other positives coming from the upgrade:
- 👾 AoT will be coming with this 4.x upgrade, hence why it's taking longer than usual, since I need to make other necessary changes.
- Prod build size is reduced tremendously with the new 4.x compiler 🥇 
  - AoT size is reduced as well 🥇 

---

#  General upcoming Repo updates:

I also plan on doing a big time cleanup of code, styles and organization, to make the repo easier to use for newcomers as well. Hoping to have a very presentable prototype Application for people to just get started with.

- SASS (SCSS) will be added so people can theme the repo's styles.
- Better layout, responsive, etc.
- (For those who might need it) Instructions on how to completely remove all SSR (server-side rendering) if it's not needed at all, *especially since it does raise the difficulty quite a bit*.
- Big time cleanup of Webpack files / moving webpack Polyfills / Vendor into a `.ts` files / etc.

---

Anyway just wanted to give everyone an update who is using or waiting to use the Repo for future projects!

Thanks again to all the Contributors for their help the past few months.
@AbrarJahin @ORuban @Ketrex 

🍺

**Comment by hheexx** [comment]
Hi Mark.

Maybe you should separate 4.0 upgrade and introducing AOT so we can more easily know regression causes?

**Comment by MarkPieszak** [comment]
4.0 Branch here, will merge to Master when more updates are in there:

https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/angular4.0-NEW-wip
