### ISSUE TITLE
hot refresh

### ISSUE THREAD

**Issue by kanpinar** [MarkPieszak/aspnetcore-angular2-universal#115]
I am updating navmenu.component.html and 
If i run application in Visual Studio -> IIS Express it shows changes in success
But if i run with dotnet run it doesnt.

From Debug lines i see difference comes from WebPack... 
webpack building...
webpack built 5cdc4f0080d9135fba3b in 2011ms

How to achive this via dotnet run
What i am missing.

**Comment by kanpinar** [comment]
oh my,

             set ASPNETCORE_ENVIRONMENT=Development

before dotnet run fixed my issue...

**Comment by MarkPieszak** [comment]
Great! Was about to say just set that variable and you'll be all set!
Glad you got it figured out
