### ISSUE TITLE
[proposal] CLI command support

### ISSUE THREAD

**Issue by meteor-learning** [MarkPieszak/aspnetcore-angular2-universal#117]
Now that the Angular CLI is in RC, is it possible to add CLI command support?  Your starter template has much more features than the CLI starter template, which is why I'm interested in your starter, but at the same time I would like to have the ease in adding related files to a component all at once like the CLI allows.  I tried following directions [here](https://github.com/angular/angular-cli/issues/755), but had no success.  Thanks for any help you can provide.

**Comment by MarkPieszak** [comment]
I could try to add the _generator_ aspect of the CLI to the repo, but at least in our case here (with .NET), we have control over the build / prod builds / server / test commands through `npm` and otherwise.

I'll see what I can do! ng 4.x upgrades with SEO, AoT, and other things are coming first but maybe afterwards can try to get it in there.

**Comment by JustasKuizinas** [comment]
So is it possible to use _generator_ now?

**Comment by isaac2004** [comment]
@JustasKuizinas in my opinion, it would be better served for this to be a VS Template (which we have talked about) since there are so many non-angular dependencies. Thoughts @MarkPieszak

**Comment by MarkPieszak** [comment]
@JustasKuizinas @meteor-learning  Apologies for any delay, but I have included the basic angular-cli setup. **Note: This is only really to be used for Generating components, and eventually Tests (once I switch us back to Karma/Jasmine**

Added via: https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/94605d604a4fa0b054da4819017764ce5db1e82c

🍺 

@isaac2004 We're all set now. I think people just wanted the generators and such, now you can do `ng g c components/my-component` and bam, it works at least. Just never had the time to finally get this in there 👍
