### ISSUE TITLE
Add fixes for Angular 2.1.1+

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-angular2-universal#12]
Awaiting necessary fixes from Angular Core. 
TBD

**Comment by cormacrelf** [comment]
This results in an `Error: cannot find module '@angular/compiler'` in that `__2.2.1.workaround.js` in the console output when ASPNET_ENVIRONMENT is set to Production.

**Comment by MarkPieszak** [comment]
Let me take a look at this today, thanks for making the issue Cormac!

**Comment by MarkPieszak** [comment]
@cormacrelf It should be all set now! Won't have time to get AoT in there with Thanksgiving and all, but next week for sure 👍

**Comment by cormacrelf** [comment]
Nice one, cheers for the quick fix!
