### ISSUE TITLE
Request to add a CRUD app in app showcase

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#122]
Hi @MarkPieszak ,

Currently, we have a REST API in here-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/docs/RESTAPI-ENTITY.MD

So, we can easily add a CRUD example in here-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/src/AspCoreServer/Server/Api/UserController.cs

So, we can use this to create a CRUR app in Angular2 on this page-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/src/Angular2Spa/Client/containers/rest-test/rest-test.component.ts

And also create a service folder for storing all API services like this-

![da0b9cb4cf](https://cloud.githubusercontent.com/assets/4152843/23660400/83d9be3e-0373-11e7-8523-98f2c736c22f.png)

For being a template, I think only 1 API is OK for us for our CRUD-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/docs/RESTAPI-ENTITY.MD

I think u got me @MarkPieszak 

If we can add a CRUD in our template, it will be more useful and more acceptable for the developers.

Because then it will be a perfect starter pack I think.

Waiting for your suggestion @MarkPieszak

**Comment by MarkPieszak** [comment]
Finished via #148
