### ISSUE TITLE
Project Entry point is not OK

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#123]
Hi, in current project structure, I am getting this error-

![image](https://cloud.githubusercontent.com/assets/4152843/23690778/74edf216-03ee-11e7-8704-8ce2390c279c.png)

To solve this we need to choose default project to `AspCoreServer`

But it needs to be done every time when the project is copied.

It is better if it is done automatically so that if project is cloned and we try to run the project, it runs for us.

**Comment by MarkPieszak** [comment]
Just merged #119 is that what we needed here?

**Comment by AbrarJahin** [comment]
Thanks @MarkPieszak for merging the solution 👍

**Comment by MarkPieszak** [comment]
Course thanks for figuring that one out! 
We need to port it over to VS2017 asap as well since it's coming out tomorrow 🗡 

I'm busy until the weekend :(

**Comment by AbrarJahin** [comment]
Sure.

Understand your condition.

Thanks for your help
