### ISSUE TITLE
PrePublish scripts are not called

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#124]
Hi, currently if we run the script from cmd, it is working fine, but if we try to restore the **npm package**s from Visual Studio, it is not working. NPM packages are not restoring automatically.

Because this line-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/src/AspCoreServer/project.json#L72

is not called automatically when we are trying to run the app.

Can u please have a look in here @MarkPieszak when u have time, please?

Thanks in advance

**Comment by AbrarJahin** [comment]
And also, this URL - http://aspnetcore-angular2-universal.azurewebsites.net/

is not working-

![image](https://cloud.githubusercontent.com/assets/4152843/23706964/978022b2-043a-11e7-8bd3-c2024d263090.png)

**Comment by MarkPieszak** [comment]
I'll have to check my azure, thanks for letting me know!!

**Comment by AbrarJahin** [comment]
And also, please check this issue also- "PrePublish scripts are not called"

Thanks @MarkPieszak

**Comment by MarkPieszak** [comment]
I think I might need to revert some of the updates done in that last move from AspClient -> AspServer layout, I thought it would work without a hitch but seems it has inherently lots of problems with VS :(

Need to get the repo in good working order so I can make some bigger updates for Angular4 etc

Closing this for now so I can revert those changes
