### ISSUE TITLE
Demo application *aspnetcore-angular2-universal.azurewebsites.net* is stopped

### ISSUE THREAD

**Issue by siudeks** [MarkPieszak/aspnetcore-angular2-universal#126]
[Demo site](http://aspnetcore-angular2-universal.azurewebsites.net/) does not work.

**Comment by MarkPieszak** [comment]
Thank you for letting me know! Must be something with my Azure account / setup. Let me fix that :)

**Comment by asadsahi** [comment]
@MarkPieszak happens to me all the time. :) Azure sites aren't getting stable with alot of moving parts around .net versions and tools.

**Comment by MarkPieszak** [comment]
😓 is it from the shift due to vs2017 I'm guessing? 
I need to update the repo to the newest .NET, 2017, etc. 
Need to spend a solid entire day to get this baby fixed up. Haha

**Comment by asadsahi** [comment]
:) I am waiting for these things to stable. I deploy my personal projects using web deploy from command line since last time I spent that same day figuring out why subsequent deployments of same project failed with 502.x errors. 

But you are right, it must be shifing of csproj shift or something.

**Comment by MarkPieszak** [comment]
Yeah I hope by now things will be more "stable", everything has been rough enough from all ends with all this beta software, I know you've been going through the same pains! 😆 

I'll give it a shot this week and see how bad it is :P lol

**Comment by MarkPieszak** [comment]
@siudeks Fixed :dancer: 
Thanks for letting me know!
