### ISSUE TITLE
HMR not found

### ISSUE THREAD

**Issue by netpoint** [MarkPieszak/aspnetcore-angular2-universal#127]
I am getting a problem with HMR. It will occasionally work, but the majority of times I get the following error message. Does anyone have any suggestions.

Thanks
Steve

GET http://localhost:43786/dist/039336adc28987bf069a.hot-update.json 404 (Not Found)
(anonymous) @ VM40:2
n @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:856
e.scheduleTask @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
n.scheduleMacroTask @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
(anonymous) @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:856
send @ VM60:3
(anonymous) @ bootstrap 95329df…:51
e @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
hotDownloadManifest @ bootstrap 95329df…:43
hotCheck @ bootstrap 95329df…:245
check @ process-update.js:64
module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:37 [HMR] Cannot find update (Full reload needed)
cb @ process-update.js:37
(anonymous) @ process-update.js:68
e.invoke @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
n.run @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
(anonymous) @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
e.invokeTask @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
n.runTask @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
o @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
invoke @ vendor.js?v=_4S4IlOKC9fD4KzgZ7M1WkEivdrqwl5_qEbGmyeOBic:863
process-update.js:38 [HMR] (Probably because of restarting the server)

**Comment by AbrarJahin** [comment]
Currently, we have a little problem with scripts.

https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/124

So, we have to do this part manually.

1. To do that, after cloning the repo, in command prompt, please go to the cloned directory.

2.  Then run this command-

    ./src/AspCoreServer/prepublish.cmd

By running this command all node modules will be installed and vendors and js files will be generated.

This works for me. Hope, this will also work for you 🥇

**Comment by MarkPieszak** [comment]
@netpoint did that fix it for you by any chance?

**Comment by netpoint** [comment]
I have not downloaded the latest code to use in my current project. Since the latest is split into server and client projects it will take me a while to split my project. I am using a commit from the end of Feb. I did clone the latest version and try running  the .\src\AspCoreServer\prepublish.cmd but got some errors. When I get time I will try it again and post the errors.

The HMR problem is odd. On a clean reboot, the first time I run the project it works fine. As soon as I stop the project and then run it again, I get the error. I then have to clean the project and rebuild for it to recognise any changes to the typescript or html code otherwise just runs the old code.
