### ISSUE TITLE
`npm install` does not on Linux because the filesystem is case sensitive

### ISSUE THREAD

**Issue by Axure** [MarkPieszak/aspnetcore-angular2-universal#131]
The directory is called `Angular2Spa`, but in the `package.json` it is `angular2spa`.

**Comment by MarkPieszak** [comment]
Thanks for letting me know! I'll have to clean that up as well.
I'll make sure that's fixed in the next iteration of the project!

**Comment by MarkPieszak** [comment]
Master now has 4.0.0, and is only for VS2017, can you give it a shot there and see if it helped fix this issue? Let me know if not, we can re-open!
