### ISSUE TITLE
Run with VS code

### ISSUE THREAD

**Issue by heqiao** [MarkPieszak/aspnetcore-angular2-universal#133]
Noob here. I tried the latest ag4 starter and it works in VS 2017. But with VS code, the changes I made in .ts or .html files did not show on the browser after `dotnet run`, webpack didn't seem running. 
Does it require any configs to run correctly with VS code?

**Comment by MarkPieszak** [comment]
So you need to set do: (if windows)

    set ASPNET_ENVIRONMENT=Development

To set the environment variable.

Would be nice to get the Vscode launch files back in the repo, there's an easy way to get it to set it automatically for you on Launch as well.

**Comment by heqiao** [comment]
I set the environment, then(not sure if related) it shows error message 

`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.`  

Does not happen in VS 2017.

**Comment by alvirtuoso** [comment]
It works on my Visual Studio Mac preview version.  I just opened the .csproj file, built it and all good to go.

**Comment by MarkPieszak** [comment]
If anyone can figure out what's going on with VSCode and setup launch files that'd be amazing!

**Comment by LiverpoolOwen** [comment]
It works for me on a windows machine

**Comment by LiverpoolOwen** [comment]
I will have a go at setting up the vscode launch tomorrow.

**Comment by LiverpoolOwen** [comment]
I have just sent a pull request with the launch files. As for the 
`EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.` 
I am not sure what is causing this at the moment but it does this in production mode in visual studio also so we can probably close this thread.

**Comment by MarkPieszak** [comment]
🎈 great job! Closing.
