### ISSUE TITLE
has no exported member 'AnimationDriver'.

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#136]
Hi Mark. I am trying to update project to use angular 4. but got 
ERROR in [at-loader] ./node_modules/angular2-platform-node/node-platform.d.ts:1:10 
node_modules/@angular/platform-browser/platform-browser"' has no exported member 'AnimationDriver'.
ERROR in [at-loader] ./node_modules/angular2-platform-node/node-renderer.d.ts:2:10 
node_modules/@angular/platform-browser/platform-browser"' has no exported member 'AnimationDriver'.

do you have any ideas what am I missing?

**Comment by MarkPieszak** [comment]
You have to remove and delete _all_ references to angular2universal and platform-node libraries and imports, they're pointing to old 2.x stuff.

**Comment by TomasKatz** [comment]
anyone working on this?
Why is the docs of universal using outdated/deprcted angular classes.
