### ISSUE TITLE
components templates not included

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#139]
Hi, Mark
trying to sync to use latest and greatest (new webpack config and angular 4) but if fails to use html templates. it trying to get it over http without success. before templates was included in build.
Unhandled Promise rejection: Failed to load navmenu.component.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load navmenu.component.html
    //templateUrl: './home.component.html' - this will try to load it over http 
    template:`<h1>hello world</h1>` this works just fine.
Any ideas what am I doing wrong? with 2.4 templateUrl was working just fine and templates was included in build

**Comment by MarkPieszak** [comment]
This line here is what gets it working:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.js#L19

The angular2-template-loader, is that missing for you perhaps?

**Comment by consigliory** [comment]
thanks for quick response. I do have this line in config.
it works only if I use template: require('./home.component.html')

**Comment by MarkPieszak** [comment]
It must not be installed maybe? Is it in your package.json as well?

**Comment by consigliory** [comment]
at any case - plugin is installed but for some reason did not work. I changed to user webpack require which works just fine. Thanks for your work. It is super helpful and your quick responses is really impressive.

**Comment by MarkPieszak** [comment]
Just made some major changes via #151 (we now have AoT, bootstrap SCSS & ng2-bootstrap)
Can you give it a try now? I'll close this out for now but let me know if it still isn't working I can try to take a look. Couldn't repro it though :(
