### ISSUE TITLE
Missing Bootstrap4 and ng2-bootstrap

### ISSUE THREAD

**Issue by neilgibert1234** [MarkPieszak/aspnetcore-angular2-universal#143]
Apologies if i have got this wrong but looking in the package.json it's still using bootstrap 3. I also can't find ng2-bootstrap in the package.json file.

My package.json shows  - "bootstrap": "^3.3.7"

**Comment by MarkPieszak** [comment]
Yeah we need to add back in the demo of ng2-bootstrap, you're totally right! It's still in the git history so super easy fix 👍

Thanks for reminding me though, almost forgot!

**Comment by LiverpoolOwen** [comment]
Is ng2 bootstrap better than ng bootstrap?

**Comment by neilgibert1234** [comment]
I would say so... they seem to update and clear issues quicker. I also find the documentation on the site easier to follow.

On 2 Apr 2017, at 18:07, Owen <notifications@github.com<mailto:notifications@github.com>> wrote:


Is ng2 bootstrap better than ng bootstrap?

**Comment by MarkPieszak** [comment]
They're both great I've just been more familiar with ng2bootstrap.

**Comment by MarkPieszak** [comment]
I'm going to keep it at Bootstrap 3 (just for older browser support) but you could upgrade it yourself pretty easy, latest PR just added bootstrap SCSS (so it's themeable) & ng2-bootstrap back in.
