### ISSUE TITLE
import from "app-shared" barrel no longer working

### ISSUE THREAD

**Issue by pjmagee** [MarkPieszak/aspnetcore-angular2-universal#144]
I was using the old template with the tsconfig file to have barrels for various services (injected into angular components and other services etc) however these no longer work. I also noticed this is removed from the new Angular4 template. Should this approach still work? I have to fully define the paths separately now.

**Comment by pjmagee** [comment]
Ah, I had to update my tsconfig file with a root directory for the paths.

**Comment by MarkPieszak** [comment]
Glad you got it working! 
Does webpack handle the script aliases automatically now? Check to see if it's able to bundle them correctly.

I previously had a helper function help insert them all: https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/old-2.x-universal-branch/src/Angular2Spa/webpack.config.js#L124 (The setTypescriptAlias method here)

**Comment by pjmagee** [comment]
Actually, I thought I solved the problem but soon realised it still wasn't picking up the barrels. I think we might still need this helper you have in the new Angular4 Template! ...checking it now

**Comment by pjmagee** [comment]
What I don't understand is why it isn't picking up the default `tsconfig.json` configuration...there is a Config plugin you can use with `awesome-typescript-loader` to load in a specific tsconfig file, but i don't see how that would fix the problem.

**Comment by pjmagee** [comment]
Hmm, from `awesome-typescript-loader`...

> if you want to use new paths and baseUrl feature of TS 2.0 please include TsConfigPathsPlugin. This feature is available only for webpack@2.1.

**Comment by pjmagee** [comment]
Yep. I had to include your original method to get the barrels to work.

**Comment by MarkPieszak** [comment]
Yeah the alias's can be entered manually, or in my case I just loop through the tsconfig and add them into the resulting webpack config object, just incase you add new `paths: []`, so you don't have to enter it in multiple places! 

I'll have to double check whether ts paths work with AoT.

**Comment by pjmagee** [comment]
I'm assuming we'll be adding this back in as part of the new template then.

**Comment by MarkPieszak** [comment]
Yeah as long as it works for AoT I'll add it back in no doubt!
Sorry in a bind getting everything together before ngConf 🙈

**Comment by MarkPieszak** [comment]
So the problem is, they don't work will AoT compilation just yet :(
You can see the issue here: https://github.com/angular/angular/issues/13008

If they become available then we can definitely add it back in, but for now we can't since AoT is huge for Prod :(

**Comment by pjmagee** [comment]
This is sad. We have a couple of projects which heavily rely on the use of barrels. For now it should be possible for us to disable AoT and continue to use this template?

**Comment by MarkPieszak** [comment]
Yeah you could change a few things and get some things in that empty webpack prod config to just mini ft uglify things instead of using the env.aot flag for prod builds.

Yeah it's a major bummer, since it is native TS feel it'd help for it to be available to us with AoT as well. Although I do understand the complexity it creates for the compiler.

I'll ask around see if anyone knows if it's on the radar.

**Comment by pjmagee** [comment]
Hey @MarkPieszak  someone replied to the comment left on the Angular repo essentially saying barrels are supported but there is one limitation with not being able to import from siblings within the same barrel by using the barrel alias name in an import statement, you have to give the actual path to the sibling.

**Comment by MarkPieszak** [comment]
Interesting really, well that's pretty good news so it works as long as you don't go crazy with barrel inception?

**Comment by pjmagee** [comment]
Yep. According to the replies there, so long as you don't reference other siblings within the same barrel and instead reference them relatively, it should be fine. However others in the issue said they see no problems at all even if you reference using named paths within the same barrel. So really I don't know what the official stance is. 💃
