### ISSUE TITLE
client side code not working (current updated code)

### ISSUE THREAD

**Issue by kannan2106** [MarkPieszak/aspnetcore-angular2-universal#149]
current updated code - server side code (prerendering) working fine. but client side code not working. it show "jquery.js" is missing. so everytime calls serverside when click any menus.
![error](https://cloud.githubusercontent.com/assets/22908062/24647762/ca8b577a-1953-11e7-9f88-580e48fb1f57.PNG)

**Comment by pjmagee** [comment]
Did you include the Jquery inside WebPack? when the template got migrated from the Angular2 to Angular4 Template the Webpack file had a lot of  the noise removed and commented back out again. Its probably still commented out in `Webpack.vendor.js`

**Comment by MarkPieszak** [comment]
Just added https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/372ceebb629fcf0e750ab402b7cc31261abe3016 can you see if that fixes it? Might of been my fault I was having strange issues with the SignalR last night !

**Comment by MarkPieszak** [comment]
This should be fixed now, but let me know if it needs to re-opened!

**Comment by kannan2106** [comment]
hi..current version webpack.config.vendor.js is missing. is it no more need webpack.config.vendor.js? Now project running but its shows some error. please find attached screen(vendor.css not found).
![error](https://cloud.githubusercontent.com/assets/22908062/24686612/922d2586-19e7-11e7-80dd-42628588f611.PNG)

**Comment by MarkPieszak** [comment]
Yeah there's an open issue to fix the sass glyphicons, and for right now vendor isn't separated manually, going to add a way for it to be created automatically 🎈
Hold tight more updates to come 🎁

**Comment by kannan2106** [comment]
ok am waiting...thanks :)
