### ISSUE TITLE
Glyphicons aren't loading properly through bootstrap-sass

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-angular2-universal#152]
Good first time contributor issue here as well :+1: 

Icons path is 404'ing

> GET http://localhost:5000/~bootstrap-sass/assets/fonts/bootstrapglyphicons-halflings-regular.woff2 
> home:6049 GET http://localhost:5000/~bootstrap-sass/assets/fonts/bootstrapglyphicons-halflings-regular.woff 
> home:6049 GET http://localhost:5000/~bootstrap-sass/assets/fonts/bootstrapglyphicons-halflings-regular.ttf 

For other good ones, [go here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues?q=is%3Aissue+is%3Aopen+label%3A%22PRs+welcome%21%22)

**Comment by markphillips100** [comment]
The paths are missing a / in the app.component.scss but regardless I couldn't get the resources to pack
