### ISSUE TITLE
how to make docker image on mac

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#153]
hi. do you have any suggestion how to make docker image on macos? I used to have 
FROM microsoft/dotnet:1.1.0-sdk-projectjson

RUN apt-get update
RUN wget -qO- https://deb.nodesource.com/setup_4.x | bash -
RUN apt-get install -y build-essential nodejs

COPY . /app

WORKDIR /app

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

EXPOSE 5000/tcp

CMD ["dotnet", "run", "--server.urls", "http://*:5000"]

but now it complains about project.json

**Comment by MarkPieszak** [comment]
Might be because of the top FROM line maybe?

You want 1.1-sdk I believe. I don't do much docker but something like this might work?

```
FROM microsoft/dotnet:1.1-sdk-msbuild

RUN apt-get update
RUN wget -qO- https://deb.nodesource.com/setup_6.x | bash -
RUN apt-get install -y build-essential nodejs

COPY . /app

WORKDIR /app

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

EXPOSE 5000/tcp

CMD ["dotnet", "run", "--server.urls", "http://0.0.0.0:5000"]
```
