### ISSUE TITLE
<html>< Styles issue

### ISSUE THREAD

**Issue by danielnajera** [MarkPieszak/aspnetcore-angular2-universal#157]
When running using SSR,  ViewData["Styles"] = prerenderResult.Globals["styles"]; in the Index controller value is set to "<html><".  Generating "<" at the top of page upon rendering.  commenting out the     @*@Html.Raw(ViewData["Styles"])*@ in the view layout page temporarily fixes issue.

**Comment by MarkPieszak** [comment]
Are you using the latest from Master? I can't see this one on Mac/windows.
Is this from a fresh repo pull down or with modifications?

**Comment by danielnajera** [comment]
Latest update to Visual Studio resolved issue.
