### ISSUE TITLE
Error running the 'npm test' command

### ISSUE THREAD

**Issue by mosswgreentea** [MarkPieszak/aspnetcore-angular2-universal#160]
I've downloaded the repo and am running through it. While executing the 'npm test' command, I saw an error and realized that the path specified in package.json ('Client/test/karma-conf.js') is not found. The 'test' sub-folder does not exist. Also could you include a few unit tests in the repo?

**Comment by MarkPieszak** [comment]
I need to reconfigure that I moved them out of the Client folder on accident :)
PRs welcome!
It's just pointing to the incorrect file.

**Comment by mosswgreentea** [comment]
After modifying the path to the correct path, the test execution is still failing. I'll submit PR shortly.

**Comment by mosswgreentea** [comment]
Sorry, I had closed issue accidentally.

**Comment by mosswgreentea** [comment]
I'm not having permissions to push changes. This was the only change I made in the 'package.json': 
"test": "karma start karma.webpack.conf.js.

**Comment by MarkPieszak** [comment]
You need to fork the repo and create a PR from there if you wanted to add it otherwise I can change that no worries! Thanks for letting me know!

**Comment by DjolePetrovic** [comment]
How's the progress on this one? Any help needed?

**Comment by MarkPieszak** [comment]
It'd be great to at least fix the script, I have no computer at the moment in the middle of a Move. Eventually wanted to have some example unit tests for a few components / services as well if you'd like to put anything like that together? Would be a great help!! 🎁 @DjolePetrovic

**Comment by DjolePetrovic** [comment]
Could someone have a look at my fork? I can't quite figure out why the tests are not running.  I'm sure I've done something wrong, but I can't figure out what.

**Comment by HunterMob** [comment]
We're trying to get tests to work as well. We found that creating a test folder in Client and moving karma.conf.ts and boot-tests.ts into that folder and removing the vendor.js reference from 'files' in karma.conf.ts would allow the tests to run. 

However, we also found that when we save a change, compile fails and all of the tests show as missing. If we save a second time, the tests all compile and run correctly.

If anyone has any alternative solutions to our work-around, please let us know!

**Comment by andersk2** [comment]
Would it be an alternative to throw out karma and use Jest instead?
I can create a PR for that

**Comment by MarkPieszak** [comment]
Merged! @andersk2 has us using Jest now 🎁🎈
