### ISSUE TITLE
Prerendering failed because of error: Cannot find module '..\aspnetcore-angular2-universal\Client\dist\main-server'

### ISSUE THREAD

**Issue by novopashinmm** [MarkPieszak/aspnetcore-angular2-universal#166]
Hi!

Previous error was on the work, there maybe not installed last version vs2017.
And I decide run this project in my own computer. Install latest vs2017 15.1 (26403), npm 4.1.2, node 7.5.0.
Get this error, when running project and go to localhost:5000/. Please, help.
![image](https://cloud.githubusercontent.com/assets/7537491/24840252/71d2a052-1d72-11e7-9d1e-9b48d846aa6a.png)
![image](https://cloud.githubusercontent.com/assets/7537491/24840257/91df3c66-1d72-11e7-9043-4397e0881702.png)
![image](https://cloud.githubusercontent.com/assets/7537491/24840262/a905d26a-1d72-11e7-8200-70f26490ec29.png)

**Comment by Gaulomatic** [comment]
Did you try to `npm install` and `npm run webpack`? If there are any errors related to node or webpack you will see them in the console. You can try to run it in VS by F5'ing it as well.

**Comment by MarkPieszak** [comment]
Try running npm run build:dev to build them first

**Comment by rphilp** [comment]
If `npm run webpack` doesn't work (no webpack installed error), try `npm run build:dev -- --verbose`. Learned that little trick from Mark in an earlier post.

**Comment by markphillips100** [comment]
Are the webpack scripts supposed to run automatically on hitting FT or
should the readme be updated?

**Comment by rphilp** [comment]
In the past it was run after npm i. Looks like the post install was changed. 
Old:
```
"scripts": {
    "test": "karma start Client/test/karma.conf.js",
    "postinstall": "npm run build:webpack",
    "build:webpack": "npm run webpack-vendor && npm run webpack",
    "webpack": "webpack --progress --color",
    "webpack-vendor": "webpack --config webpack.config.vendor.js --progress --color"
  }
```
New:
```
"scripts": {
    "test": "karma start Client/test/karma.conf.js",
    "build:dev": "webpack --progress --color",
    "build:aot": "webpack --env.aot --env.client & webpack --env.aot --env.server"
  }
```

Short term, add the `"postinstall": "npm run build:dev",` line in there and npm i should kick off the dev build.

I'll see if I can finally figure out how to submit a PR for that and the IE Shims.

**Comment by MarkPieszak** [comment]
I removed it mainly because of Azure builds (or other cloud / production builds), having a Dev webpack build after just makes things take longer since we want it to build:AoT to get the prod bundles. Otherwise it was great in postinstall, wish postinstall had hooks for dev / prod modes.

Think we should just updated the readme to say install && npm run webpack for now, you're right.

**Comment by novopashinmm** [comment]
I execute in cmd "npm run build:dev" and get it.
![image](https://cloud.githubusercontent.com/assets/7537491/24879409/7d5bb828-1e3f-11e7-82e2-1eef8a254732.png)

**Comment by novopashinmm** [comment]
I do how wrote there "npm rebuild node-sass --force" and project is running.
![image](https://cloud.githubusercontent.com/assets/7537491/24879676/504fd700-1e40-11e7-83b9-d81e6efbc349.png)
Only one fail happened. 
![image](https://cloud.githubusercontent.com/assets/7537491/24879696/5d9dc5ca-1e40-11e7-969d-73d47cb81c70.png)

**Comment by Gaulomatic** [comment]
SASS is a little princess, but this is simple. VS is using Node 5.x internally and you have Node 6.x or 7.x installed. Let VS use the Node Version you have installed. Go to

`Tools -> Options -> Projects and Solutions -> Web Package Management`

and paste the path of you installation directory in. Make sure that it is on top of `$(VSINSTALLDIR)\Web\External`. In my case (sorry for my German VS) it is `C:\Program Files\Anwendungen\Entwicklung\Node`:

<img width="1020" alt="bildschirmfoto 2017-04-10 um 21 49 41" src="https://cloud.githubusercontent.com/assets/7631781/24879667/e89a1da8-1e37-11e7-8fcc-c55574315619.png">

Delete the folder `node-sass` in your `node_modules` and run `npm install` again.

**Comment by NelsonLamprecht** [comment]
So, I can't hit f5 in visual studio and get it to run the build:dev task? The postinstall hint above doesn't seem to kick that off...

**Comment by rphilp** [comment]
If you're running into problems with it when you first run the project in Visual Studio, then you'll need to open a command prompt, nagivate to the project directory then run "npm run build:dev" manually. That should force the first build and generate the main.server file.

After that, the subsequent changes are automatically built when you save any changes to the project files in the Client folder.
