### ISSUE TITLE
build:dev problem

### ISSUE THREAD

**Issue by dev-siberia** [MarkPieszak/aspnetcore-angular2-universal#168]
E:\DOCUMENTS\Visual Studio 2017\Projects\aspnetcore-angular2-universal\webpack.config.js:7
const **{** getAotPlugin } = require('./webpack/webpack.aot');
______^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)

Node,js 6.10.1 x64 version., vs2017.

**Comment by dev-siberia** [comment]
The problem was on the way to npm in the visual studio. The first one was "$(VSINSTALLDIR)\Web\External". I chose the first" $(PATH)"
![vsnpmfirst](https://cloud.githubusercontent.com/assets/15089615/24846752/dd7067ee-1de6-11e7-9aa2-c533321fc198.JPG)

**Comment by MarkPieszak** [comment]
Yes! It's quite strange VS comes with its own version of Node and by default uses it over the globally installed one. Glad you got it working 👍
