### ISSUE TITLE
two times loading issue - Server doing Http then Client doing it again 

### ISSUE THREAD

**Issue by kannan2106** [MarkPieszak/aspnetcore-angular2-universal#170]
run your project and refresh this url "http://localhost:65060/users". its loading two times (server side and client side). how to avoid the second time loading?

**Comment by MarkPieszak** [comment]
I've been swamped but I'll be posting the cache transfer story / example shortly. Apologies for the delay

**Comment by hheexx** [comment]
I see that as a feature :)

What I am doing is heavily caching prerendering output.
So users get little stale data very fast and app then grabs fresh data using ajax and updates it.

Works great for me!

**Comment by MarkPieszak** [comment]
Not typically, but it always just depends on your Application, whether it's very dynamic in nature, or static etc.

Typically I only put those most important GET Http calls in HttpTransfer logic that reuses them on the client again, just to remove any flicker etc. if calls are very data intensive and take a long Ike to return the result I usually ignore them all together on the server render, and let the client take its time to run them.

Always a million ways you could do any of this stuff right 🙈

I have the working HttpTransfer service/module and Transfer mechanism finished as of last night, just double checking everything and I'll try to get in pushed up to Master this morning. 🎈
