### ISSUE TITLE
[feature request] SignalR publish updates from server

### ISSUE THREAD

**Issue by nstohler** [MarkPieszak/aspnetcore-angular2-universal#171]
I want to push some real-time data from the server to the connected browsers using SignalR. I have a working solution that uses Firebase, but I would like to switch it to SignalR. It would be great if the chat example could be extended like that.

**Comment by MarkPieszak** [comment]
@hakonamatata Jan actually set up the SignalR goodness, I can't imagine it'd be too too difficult though! I don't have the bandwidth right now to take that one on, but maybe he can take a look?

**Comment by hakonamatata** [comment]
I might take a look at it again this week or the one after that, but can't make any promises.

**Comment by MarkPieszak** [comment]
No worries!

**Comment by donstarkey** [comment]
any movement on this?

**Comment by isaac2004** [comment]
@donstarkey are you looking for the same thing here? Is the goal to have a MessageHub on server side? Just trying to follow the request.

**Comment by isaac2004** [comment]
@donstarkey closing, please reopen if you want to discuss
