### ISSUE TITLE
random http post failures from node

### ISSUE THREAD

**Issue by hheexx** [MarkPieszak/aspnetcore-angular2-universal#174]
From time to time i log http requests that fail from node.
I'm not sure if it's server-side problem but error object i receive is pretty empty.
How can it be empty? No status code?

```
e {
  _body: 
   t {
     type: 'error',
     target: 
      n {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: '',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [Object],
        _method: 'POST',
        _url: [Object],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     currentTarget: 
      n {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: '',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [Object],
        _method: 'POST',
        _url: [Object],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     lengthComputable: false,
     loaded: 0,
     total: 0 },
  status: 0,
  ok: false,
  statusText: '',
  headers: t { _headers: Map {}, _normalizedNames: Map {} },
  type: 3,
  url: null }
```

**Comment by MarkPieszak** [comment]
I was actually seeing this the other day, and it seemed to be happening when I didn't have a WiFi connection, but then once I did, everything worked perfectly fine. Not sure how that would have any affect on the Http calls or local host, but I never saw them again once connected. Very bizarre 🙈

Was this happening to you in a similar scenario?

**Comment by hheexx** [comment]
Got it.

http host was wrong and unreachable (http://prod).
Error should be more friendly. This is on angular part I guess?


btw. host was unreachable because params.origin is taken from host field from incoming http request.
There is nginx load balancer in frond of backend that changed http host so it was wrong. Probably better value for ajax host is http://localhost:<port from kastrel>

**Comment by MarkPieszak** [comment]
Great!
Was this because of a Relative URL in an Http? Like: `http.get('/api/whatever/')` ?

**Comment by hheexx** [comment]
I make absolute urls with params.origin and relative part.
params.origin was wrong because nginx changed host field.

**Comment by MarkPieszak** [comment]
Ahh ok ! :)
Having an easy enough time combining Nginx on top of this stack?

**Comment by hheexx** [comment]
Yea it's easy for basic parts but I just had some nasty problems with forwarded headers and Identity.
Lost 2 days :(

**Comment by MarkPieszak** [comment]
Did you grab headers (during the server render) through the next REQUEST InjectionToken?

**Comment by hheexx** [comment]
Problem was Request.scheme is not replaced with forwareded headers.
So I had to do 

`
 app.Use( ( context, next ) => {
                if ( context.Request.Headers.TryGetValue( "X-Forwarded-Proto", out StringValues proto ) ) {
                    context.Request.Scheme = proto;
                }
                return next();
} );
`

Request.scheme is used by asp identity when they generate return url for facebook auth.
