### ISSUE TITLE
WebPack Errors after upgrading

### ISSUE THREAD

**Issue by dguisinger** [MarkPieszak/aspnetcore-angular2-universal#175]
I upgraded my project to use your new code.

I am getting the following:
Uncaught ReferenceError: vendor_243a0387f5d4925254fb is not defined

at Object.<anonymous> (main-client.js:85)
    at __webpack_require__ (main-client.js:20)
    at Object.<anonymous> (main-client.js:49185)
    at __webpack_require__ (main-client.js:20)
    at Object.<anonymous> (main-client.js:25694)
    at __webpack_require__ (main-client.js:20)
    at Object.<anonymous> (main-client.js:49236)
    at __webpack_require__ (main-client.js:20)
    at main-client.js:66
    at main-client.js:69

Also, I see you no longer have a webpack.config.vendor.js.  Maybe this is related to the errors above, or maybe not.  Should I be deleting the one that was previously there?

**Comment by MarkPieszak** [comment]
Yes if you can delete it for now! It will be back eventually, but all of those changes will be cosmetic and exterior to your App itself. (Webpack files and webpack folder)

**Comment by dguisinger** [comment]
Hmm, removing that file doesn't seem to have fixed my issue.  Any ideas?

**Comment by MarkPieszak** [comment]
I'm not sure, how did you try upgrading?
There are a lot of big differences since the older 2.x version.
Even the browser/server modules / etc.

You might need to wipe out both your dist folders, there is no separate vendor right now (but there will be eventually).

**Comment by dguisinger** [comment]
That fixed it, i cleared out the dist folder and noticed the js filename changed and had to change the name in the razor view.

Thanks
