### ISSUE TITLE
Dotnet publish incorrectly produces main.js

### ISSUE THREAD

**Issue by markphillips100** [MarkPieszak/aspnetcore-angular2-universal#176]
Running npm publish completes successfully however a main.js file is produced instead of the expected main-server.js.  Consequently server-side prerendering fails to locate the file.

If we run "npm run build:dev" followed by "npm publish" the output will contain both main.js and main-server.js.  Importantly, the latter file is not the aot file I believe but it will be the file used in the prerender.

I'm guessing the AoTPlugin may have something to do with the file name but not sure.

**Comment by MarkPieszak** [comment]
You never do an `npm publish` that's if you were publishing a library to **npm** :)

Maybe you mean `dotnet publish`?

**Comment by markphillips100** [comment]
yes sorry I meant dotnet publish

**Comment by markphillips100** [comment]
So basically this line "node node_modules/webpack/bin/webpack.js --env.aot --env.server" produces main.js rather than main-server.js

**Comment by mcm-ham** [comment]
Just noticed this issue myself. Basically in web.config.js replace:
```
entry: options.aot ? './client/main.server.aot.ts' : serverPartial.entry, // Temporary
```
With
```
entry: options.aot ? { 'main-server': './client/main.server.aot.ts' } : serverPartial.entry, // Temporary
```
I next got an error related to zone.js, to fix just add `import 'zone.js/dist/zone-node';` to the top of `main.server.aot.ts`.

**Comment by markphillips100** [comment]
Yep that did the trick.  Thanks @mcm-ham

**Comment by MarkPieszak** [comment]
@mcm-ham thank you Michael! Would you like to add a PR so we can get that fix in for everyone?
Nice job, didn't notice that one 😓 👍
