### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by curcas** [MarkPieszak/aspnetcore-angular2-universal#178]
I have the latest Node version (7.9.0) installed and installed all the node packages "npm install".
When I run the build afterwards with "npm run build:dev" I get the following error:

```
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./client/app/app.component.scss
    Module build failed: Error: Missing binding C:\Users\curdin\Documents\GitHub\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor\win32-x64-51\binding.node
    Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 7.x

    Found bindings for the following environments:
      - Windows 64-bit with Node.js 5.x
```

**Comment by MarkPieszak** [comment]
What shell / prompt are you trying to run these commands from? Regular command prompt or something else within an IDE / etc?

Can you try 

```
npm rebuild node-sass
```

Then retry `npm run build:dev` again. @curcas

**Comment by curcas** [comment]
I'm using the default Windows Command Prompt.
Well, that worked. Miss configuration of my system or just bad luck?
Thanks for your help!

**Comment by MarkPieszak** [comment]
Might of been either, but I've seen it happen from time to time. It's a bizarre node-sass issue.
Glad it works! Cheers.
