### ISSUE TITLE
sass-resource-loader: Zone already loaded error

### ISSUE THREAD

**Issue by nemad** [MarkPieszak/aspnetcore-angular2-universal#183]
Hi Mark,

I'm using bootstrap 4 and trying to include some scss mixins with sass-resource-loader. The problem is when I try to specify the path to include I get "Zone already loded error". I replaced scss loader with this in webpack.common.js:

    {
      test: /\.scss$/,
      use: [
        'to-string-loader',
        'css-loader',
        'sass-loader',
        {
          loader: 'sass-resources-loader',
          options: {
            // Provide path to the file with resources
            resources: root('./node_modules/bootstrap/scss/mixins/mixin.scss'),
          },
        },
      ],
    },

Do you have any idea to solve this? 

Thanks

**Comment by MarkPieszak** [comment]
I haven't ran into that one, is this using the latest updates from the repo as well?

Also does the error come up during the server or browser render?

**Comment by nemad** [comment]
Actually, it happened (during server side prerendering) because the loader is not working, and I used a mixin inside an scss file. The funny thing is if I load the whole bootstrap like you did in app.component.scss I still cant use mixins..

**Comment by MarkPieszak** [comment]
Does it work now what did you need to do?

**Comment by nemad** [comment]
Sorry, but it wasnt your awesome template's but it was my fault. The problem was that **the order is matters** when you load your assets in your resoures section.
