### ISSUE TITLE
support for angular-cli

### ISSUE THREAD

**Issue by webnegar** [MarkPieszak/aspnetcore-angular2-universal#189]
hi, does it support for angular-cli ?

**Comment by MarkPieszak** [comment]
So what you can do is add an `.angular-cli.json` file to reap the benefits of the Generator, but the .NET process is intertwined with everything so we can't use the CLI outright, dev & prod builds are built manually with `npm` scripts as opposed to `ng`. 

Maybe someday we can add it in potentially.

Closing as duplicate of #117
