### ISSUE TITLE
IE 11 Throws - SCRIPT5007: Unable to get property 'apply' of undefined or null reference, main-browser.js (22037,5)

### ISSUE THREAD

**Issue by TimHarker** [MarkPieszak/aspnetcore-angular2-universal#190]
IE 11 Throws - SCRIPT5007: Unable to get property 'apply' of undefined or null reference, main-browser.js (22037,5), and all subsequent JavaScript fails.

![help](https://cloud.githubusercontent.com/assets/5775607/25109715/bbad1956-23ac-11e7-87b5-00ed2220b246.gif)

**Comment by MarkPieszak** [comment]
I need to update it in the Readme, but in the `polyfills` folder open up the polyfills.ts file, and uncomment out the import polyfills needed for ie9 -> 11.
That should take care of it :)

By default the project doesn't import them right away to keep bundle sizes down.

**Comment by rekrah** [comment]
Which read me?  I'll see if I can do a pull request and update.

**Comment by MarkPieszak** [comment]
Just the main one, maybe in the FAQ section, how can I support IE9-11 or something.
Excellent thank you! @rekrah
