### ISSUE TITLE
Lazy Loading with Webpack?

### ISSUE THREAD

**Issue by dguisinger** [MarkPieszak/aspnetcore-angular2-universal#191]
Is there a way to setup lazy loading with webpack?

When I use lazy loading in my routes, it seems inconsistent, sometimes it works, sometimes it tells me it can't find the module.  But more than that, obviously we are packing the whole project into a single JS file which is the opposite of lazy loading.

Is there an easy way to add a module that lazy loads to the example that has its JS loaded on the fly vs in the main client js file?

**Comment by MarkPieszak** [comment]
You should be able to just do `{ path: 'whatever', loadChildren: 'app/whatever/whatever.module#WhateverModule' }`

Is that not working?
We use ngtools here, so it's just like the angular-cli

**Comment by dguisinger** [comment]
It wasn't working consistently.  I'm not sure where the problem would be originating from.
I have a App Routing module located in app/modules/routingmodule.... i couldn't get to work consistently... which is weird.   Sometimes I would run the project and routing links would work fine, other times I'd run it and it would tell me it couldn't find the modules... the fact that it wasn't being consistent was confusing.

Does it only work if I define the routes in the main app module?  The Angular website recommends having a routes specific module.

**Comment by MarkPieszak** [comment]
Added lazy loading demo into application, take a look at PR #197 to see what you were missing!
Hope that helps 👍

**Comment by dguisinger** [comment]
Man, you sure are fast.... Thanks

Interesting, doesn't look like you were doing anything different.
I bet the issue was I had switched to a App Routing module (which is
recommended off the angular website)...  I wonder if either Angular or
Webpack weren't properly identifying paths.
I was setting the routing up from app/modules/routing/routing.module...
 but like i said, sometimes it would work, sometimes it wouldn't.... just
weird

I'll just try falling back and putting my routes in the root module and see
if it makes my life easier again

**Comment by MarkPieszak** [comment]
Yeah I just kept everything in the app.module mainly to keep things easier for people, so they don't have to import things twice, once in the declarations, and once again in a different routing file.

Glad it's working at least now, I can't imagine why having a routing module would affect anything, bizarre!

**Comment by youssefsharief** [comment]
Yes that is so strange
