### ISSUE TITLE
Error encountered resolving symbol values statically. Calling function 'InjectionToken'

### ISSUE THREAD

**Issue by pjmagee** [MarkPieszak/aspnetcore-angular2-universal#194]
Would you happen to know why trying to use `InjectionToken` as a `Provide` value in my Providers for an Angular Module would blow up?
    
    
```
[31mERROR in Error encountered resolving symbol values statically. Calling function 'InjectionToken', function calls are not supported. Consider rep
lacing the function or lambda with a reference to an exported function, resolving symbol ORIGIN_URL in
```

**Comment by MarkPieszak** [comment]
Can you show how you're doing it?
Is this the ORIGIN_URL we're automatically providing in the engine?

**Comment by pjmagee** [comment]
Yeah it's the same code from the repo. I think something funny is going on here. I pulled down a fresh repo and added barrels in to see if our project was having side effects and after adding barrels/paths into the project for this for things like app-models, app-modules, app-shared I'm getting similar errors like this....

```
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in c:/projects/github/aspnetcore-angular2-universal/node_modules/@angular/core/core.d.ts, resolving symbol ServerTransferStateModule in c:/projects/github/aspnetcore-angular2-universal/Client/modules/transfer-state/server-transfer-state.module.ts, resolving symbol ServerTransferStateModule in c:/projects/github/aspnetcore-angular2-universal/Client/modules/transfer-state/server-transfer-state.module.ts
```

**Comment by MarkPieszak** [comment]
There's definitely some kind of error when it's trying to statically analyze the code, not sure why it's pointing at server transfer that's a pretty basic NgModule that doesn't even use useFactory, browser one does, but it's being exported properly.

I'm wondering if it's the barrels themselves that are causing this issue, right? Are you doing export * or export { Whatever } for everything.

**Comment by pjmagee** [comment]
With the barrles I have the index.ts files with `export * from './something'`

**Comment by MarkPieszak** [comment]
Yeah try to export the actual item `export { Something } from './something';`
I think `*` is one of the (many) things AoT static analysis isn't a fan of.

**Comment by pjmagee** [comment]
Yeah, I updated the `*` and replace it with export `{ ActualClass } from './actual-class'` but the same problems occur. I think I've spent far too much time on just getting something to work 💃

**Comment by MarkPieszak** [comment]
Haha I feel you on that one 😿 
So I just tried and was able to get Paths working, I only setup `app-shared` so far, but seems to work after I setup the neccessary Webpack updates to setTypeScriptAlias, installed js.clone etc

I'll check it in so at least we have some of the paths setup for those who might want to use them.
With VSCode now auto importing these aren't really helpful/needed anymore.

**Comment by Flood** [comment]
I get a similar error.

```
Unhandled Promise rejection: No provider for InjectionToken ORIGIN_URL! ; Zone: <root> ; Task: Promise.then ; Value: { Error: No provider for InjectionToken ORIGIN_URL!
          at Error (native)
          at injectionError (c:\dev\***\src\B***\Client\dist\main-server.js:2157:92)
```

Anyone else experienced this error? I have no changes in the constant, app-engine or browser/server modules.
