### ISSUE TITLE
Question: how to make './ngfactory/app/server-app.module.ngfactory';

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#195]
it looks like to build it I need to run command ng build --prod but it complains that it is not ng project.

**Comment by MarkPieszak** [comment]
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/package.json#L4-L8

    npm run build:aot 

Then you could switch your Aspnetcore_Env or use the launch.json to run Prod mode:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/.vscode/launch.json#L36

When you dotnet publish or push to Azure it runs build:AoT automatically for you as well. 🎁
