### ISSUE TITLE
Question: docker support

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#196]
I need to pack production build to docker image and on docker run  command  - > dotnet publish
it fails with message:
> fsevents@1.1.1 install /app/node_modules/fsevents
  > node install

  npm WARN prefer global node-gyp@3.6.0 should be installed with -g
  npm ERR! Linux 4.9.13-moby
  npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
  npm ERR! node v4.8.2
  npm ERR! npm  v2.15.11
  npm ERR! code EPEERINVALID

  npm ERR! peerinvalid The package @angular/core@4.0.2 does not satisfy its siblings' peerDependencies requirements!
  npm ERR! peerinvalid Peer @angular/animations@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/common@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/compiler@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/compiler-cli@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/forms@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/http@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/platform-browser@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/platform-server@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @angular/router@4.0.2 wants @angular/core@4.0.2
  npm ERR! peerinvalid Peer @ngx-translate/core@6.0.1 wants @angular/core@>=2.0.0 || >=4.0.0-beta.0
  npm ERR! peerinvalid Peer angular2-moment@1.3.3 wants @angular/core@>=2.0.0 <5.0.0
  npm ERR! peerinvalid Peer ng-lightning@1.3.0 wants @angular/core@>=2.0.0
  npm ERR! peerinvalid Peer ng-selectize@1.0.9 wants @angular/core@^2.4.0
  npm ERR! peerinvalid Peer ng2-bootstrap@1.6.3 wants @angular/core@^2.3.1 || >=4.0.0
  npm ERR! peerinvalid Peer ngast@0.0.15 wants @angular/core@^4.0.0-rc.5
  npm ERR! peerinvalid Peer codelyzer@3.0.0-beta.4 wants @angular/core@>=4.0.0-rc <5.0.0

  npm ERR! Please include the following file with any support request:
  npm ERR!     /app/npm-debug.log
/app/Asp2017.csproj(50,5): error MSB3073: The command "npm install" exited with code 1.
The command '/bin/sh -c dotnet publish Asp2017.csproj' returned a non-zero code: 1

I guess it something related to webpack and files. On my mac dotnet publish works without issues.

**Comment by MarkPieszak** [comment]
`dotnet publish` is error'ing with that, or Docker?

Just tried publish on windows with a fresh repo and it worked fine.

Is it something related to these wanting 2.x?
npm ERR! peerinvalid Peer ng-lightning@1.3.0 wants @angular/core@>=2.0.0
npm ERR! peerinvalid Peer ng-selectize@1.0.9 wants @angular/core@^2.4.0

**Comment by consigliory** [comment]
on my mac it also works dotnet publish without any issues. But once Asp2017.csproj runs npm install it fails with massage from top comment

**Comment by consigliory** [comment]
just tried to build seed project with docker and got kind of same error. looks like it requires zone.js@^0.8.4 but in project 0.7.6 . I seed there was latest 0.8.4 at some point of time and then it was reverted back to 0.7.6 . Is it because it is not supported yet?!

**Comment by MarkPieszak** [comment]
Don't think that'd be an issue, but I did update it to 0.8.5.

**Comment by consigliory** [comment]
looks like ngx translate has strict dependancy not higher then beta.0 @ngx-translate/core@6.0.1 wants @angular/core@>=2.0.0 || >=4.0.0-beta.0

**Comment by MarkPieszak** [comment]
@ocombe Is there an issue with the peerDependencies it looks like they're still >=2.0.0 for ngx-translate 6.0.1 ?

**Comment by ocombe** [comment]
Yes the peer dependencies are >=2.0.0 which means Angular v2 or v4 (both work)

**Comment by MarkPieszak** [comment]
Excellent ok thank you Olivier, just making sure!

**Comment by lacroixdavid1** [comment]
Just in case, here is my DockerFile

```
FROM microsoft/aspnetcore:1.1.2

RUN apt-get update
RUN apt-get install -y nodejs
RUN ln -s `which nodejs` /usr/bin/node

ARG source=./src/bin/release/netcoreapp1.1/publish
WORKDIR /app
COPY $source .

ENV ASPNETCORE_ENVIRONMENT="Production"

EXPOSE 80
ENTRYPOINT ["dotnet", "As3dUserReporting.dll"]
```
