### ISSUE TITLE
Question: How to use browser specific modules in app.module?

### ISSUE THREAD

**Issue by nemad** [MarkPieszak/aspnetcore-angular2-universal#198]
I'd like to use SimpleNotifications with my app, but cant seem to find a way to include it in my app.module since it uses 'document' which does not exists on the server. The documentation says that I should include it in the browser-app.module.ts which works fine (I see it in the browser, that its loaded) but I dont understand how should I use it from there.

I'm very new to these recent client side technologies, sorry if its a dummy question.

**Comment by MarkPieszak** [comment]
Using browser specific component libraries is actually pretty complicated, but that library looks like it has a lot of random problems with AoT, etc. It involves mocking components / DI / etc. I'd really only do that if you have no other option...

When being Universal, and picking libraries, be *very* careful which ones you pick! You always want to go with ones that are crafted in the best way, and not touching document and many other things.

http://valor-software.com/ngx-bootstrap/#/alerts

ngx-bootstrap has alerts that'd I'd just suggest creating your own real quick Notification system. It'll be a lot easier to just make that real quick then try to figure out how to get all of that working. ngx-bootstrap is also 100% universal compatible 👍

**Comment by nemad** [comment]
Thank you for your patience and advices :)
