### ISSUE TITLE
Add Material design 2 example

### ISSUE THREAD

**Issue by Ardevik** [MarkPieszak/aspnetcore-angular2-universal#20]
I try to use your template, and change the ng2-bootstrap with the material2 but I always get an error. Can you add the sample for material2

**Comment by MarkPieszak** [comment]
Sure, not a problem.
I wasn't sure whether to go bootstrap or material for the Starter, but I can showcase how to set that up. There's a few gotchas with Universal & Material.

**Comment by MarkPieszak** [comment]
Also, how are you setting it up now, and what is the error you're getting?

**Comment by MarkPieszak** [comment]
So it looks like Material2 doesn't work with Universal or Webworkers at the moment, they're still in Alpha so I'm not sure exactly when we'll be in sync, so we'll have to delay that Integration unfortunately!

Although if you shut off server-side rendering for now, you'll be able to use Material2. 
You can just remove the `asp-prerender` tags in Views/Home/Index.cshtml to disable it.

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Views/Home/Index.cshtml#L5-L6

**Comment by mahbub-a-rob** [comment]
We are trying to use your template with Material2 as well. Waiting for the example app.

**Comment by MarkPieszak** [comment]
Hey @mahbub-a-rob, I spoke with a few Material devs the other day and it's on their priority list especially for their 1.0 release but at this moment it doesn't work right out of the box. I believe there might be some very hacks ways to get Material to work when server rendering, but they would keep changing release to release. :(

For the time being, would it be fine to shut off server side rendering and use Material? That way you could at least get going with the App itself, while the Universal integration gets finalized for it.

**Comment by MarkPieszak** [comment]
Waiting on https://github.com/angular/material2/issues/308

**Comment by Mahbub-A-Rob** [comment]
Hey, @MarkPieszak, yeah, sure, as we have no other option right now. In that case, I guess, it would be better to provide an example for the users on "How to use Material2 in this app" until we get the facility with server side rendering.

**Comment by MarkPieszak** [comment]
Good idea, I'll add a section to the readme to point it out! @Mahbub-A-Rob

**Comment by MarkPieszak** [comment]
Added the note! I'll close this out for now. I'll let you know when Material gets full Universal support 👍

**Comment by MarkPieszak** [comment]
@Mahbub-A-Rob Here's a hack/workaround to get Material up and running with Universal in the meantime, if you still needed it: https://github.com/angular/material2/issues/308#issuecomment-275361791

Putting it here in case others need it as well.

**Comment by Mahbub-A-Rob** [comment]
@MarkPieszak Thank you for the link. I will check it out.

**Comment by MarkPieszak** [comment]
We're about to release ng4 in March sometime, so hopefully after that Material can make the necessary changes and will be able to work without any problems at all 👍

**Comment by Mahbub-A-Rob** [comment]
Eagerly waiting for ng4.

**Comment by ElderJames** [comment]
It seem that material 2.0.0 stable version would fully support the angular/platform-server

**Comment by odahcam** [comment]
So what can be done now (with Ng 5 + NgMaterial 2 or 5)? 😃
