### ISSUE TITLE
Add option to turn off SSR(Server Side Rendering)

### ISSUE THREAD

**Issue by skorunka** [MarkPieszak/aspnetcore-angular2-universal#202]
Add an option to turn off rather than force user to delete/comment things.

**Comment by hheexx** [comment]
Also maybe disable SSR for development?
It would speed up webpack compilation twice.


We just did that yesterday.
No problems for now.

**Comment by skorunka** [comment]
Hi, could you share your code please? And BTW: How do you bundle CSS and include it in HTML master page when you turn off SSR?

**Comment by MarkPieszak** [comment]
This would be a nice idea actually, make it a little easier for people to Opt-in/out of it.

I think by default it might almost be easier to have it *Off*, as I don't think most apps need the benefits of SSRendering. Let me see what I can come up with! Good idea @skorunka

**Comment by TimHarker** [comment]
Especially since things like Material 2 don't support it (at this point) - I've turned mine off 👍 .

**Comment by skorunka** [comment]
@TimHarker When you turn off SSR, how do you bundle CSS and insert it into page? I had to do this: https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/161#issuecomment-295829586

**Comment by vicver82** [comment]
@TimHarker Could please kindly share how you totally disabled SSR and cleaned both your Angular and .NET server code? Thanks!

**Comment by MarkPieszak** [comment]
You can just comment out the code in HomeController, make it do nothing but `return View();` for the Index Route.  Return the _index.cshtml file to `<app></app>` instead of `ViewData["SpaHtml"]` and that should do it, there might be a few more things, but that'll work I believe. @vicver82

**Comment by vicver82** [comment]
@MarkPieszak Thank you Mark!

**Comment by isaac2004** [comment]
@vicver82 this issue good to close?

**Comment by vicver82** [comment]
Yes, thank you.

**Comment by MarkPieszak** [comment]
Yeah we can close it for now, eventually we can work on some type of flag that handles turning it on/off for us.
