### ISSUE TITLE
npm run build:dev: Exit status 2 at EventEmitter.<anonymous>  in lifecycle.js

### ISSUE THREAD

**Issue by NelsonLamprecht** [MarkPieszak/aspnetcore-angular2-universal#203]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\userabc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:dev' ]
2 info using npm@4.5.0
3 info using node@v7.9.0
4 verbose run-script [ 'prebuild:dev', 'build:dev', 'postbuild:dev' ]
5 info lifecycle angular4-aspnetcore-universal@1.0.0-rc3~prebuild:dev: angular4-aspnetcore-universal@1.0.0-rc3
6 silly lifecycle angular4-aspnetcore-universal@1.0.0-rc3~prebuild:dev: no script for prebuild:dev, continuing
7 info lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:dev: angular4-aspnetcore-universal@1.0.0-rc3
8 verbose lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:dev: unsafe-perm in lifecycle true
9 verbose lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:dev: PATH: C:\Users\userabc\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;D:\G\aspnetcoreangular2\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\CCM;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Users\userabc\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\nodejs\;C:\Users\userabc\AppData\Roaming\npm;C:\Users\userabc\.nuget\packages\newtonsoft.json\9.0.1\tools;C:\Users\userabc\.nuget\packages\microsoft.codeanalysis.analyzers\1.1.0\tools
10 verbose lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:dev: CWD: D:\G\aspnetcoreangular2
11 silly lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:dev: Args: [ '/d /s /c', 'webpack --progress --color' ]
12 silly lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:dev: Returned: code: 2  signal: null
13 info lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:dev: Failed to exec build:dev script
14 verbose stack Error: angular4-aspnetcore-universal@1.0.0-rc3 build:dev: `webpack --progress --color`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\userabc\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\userabc\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular4-aspnetcore-universal@1.0.0-rc3
16 verbose cwd D:\G\aspnetcoreangular2
17 verbose Windows_NT 6.1.7601
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\userabc\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:dev"
19 verbose node v7.9.0
20 verbose npm  v4.5.0
21 error code ELIFECYCLE
22 error errno 2
23 error angular4-aspnetcore-universal@1.0.0-rc3 build:dev: `webpack --progress --color`
23 error Exit status 2
24 error Failed at the angular4-aspnetcore-universal@1.0.0-rc3 build:dev script 'webpack --progress --color'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the angular4-aspnetcore-universal package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     webpack --progress --color
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs angular4-aspnetcore-universal
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls angular4-aspnetcore-universal
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

**Comment by MarkPieszak** [comment]
Why is it running a pre & post hook for the npm script?
There's only a `build:dev` script, that's really strange.

How are you triggering this, what terminal / OS / etc ?

**Comment by NelsonLamprecht** [comment]
Brand new clone from repo on Windows 7 with VS 2017  (15.1 26403.3) triggered in VS Package manager window via "npm run build:dev".  Really new to this so if I should be doing something else...

**Comment by NelsonLamprecht** [comment]
Did a npm clean and clear and a rebuild of node-sass; issue went away..?

**Comment by MarkPieszak** [comment]
Yes sometimes you need to rebuild node-sass, that might be because of whatever terminal you're using has a different version of Node in process so it gets confused.

Strange issue but I don't think even the node-sass guys know how to fix it besides rebuilding it. Strange right :laughing:  

Glad you got it fixed though!
