### ISSUE TITLE
How to add 3th party(npm module) CSS?

### ISSUE THREAD

**Issue by skorunka** [MarkPieszak/aspnetcore-angular2-universal#204]
How to add ie ngPrime CSS files? It used to be in webpack.config.vendor.js file. Im not using SSR.
My Index action in HomeController.cs is:

		public IActionResult Index()
		{
			ViewData["SpaHtml"] = "<app></app>";

			return View();
		}

Thank you.

**Comment by MarkPieszak** [comment]
You can even just import the css directly into your `main.browser` file.

`import '...etc';`

I'm going to make it easier to do all of this, just need to update a few things with the way we're doing webpack to make life easier for everyone :)

**Comment by skorunka** [comment]
@MarkPieszak how does the CSS "<link ..." gets into a HTML page? it has to be bundled somewhere, and output file manually referenced, or am I wrong? I had to create a "webpack.vendor.config.js" whci now only processes CSS files and output a vendor.css file and then I had to update Home.Index action: `ViewData["Styles"] = "<link rel=\"stylesheet\" href=\"/dist/vendor.css\" />";`

**Comment by Trapulo** [comment]
ViewData["Styles"] = "<link rel=\"stylesheet\" href=\"/dist/vendor.css\" />"; instead of ViewData["Styles"] = prerenderResult.Globals["styles"] ?

**Comment by MarkPieszak** [comment]
You can just add `<link rel="stylesheet" href="/dist/vendor.css" />` to your `<head>` within `__layout.cshtml` page (before your `ViewData["Styles"]`). I had it there previously but never added back in the css and js vendor chunking back. But that's how it was done previously!

**Comment by donstarkey** [comment]
Please pardon my ignorance.  I am trying to add, font awesome and alertify to the project but do not know where to begin.  Any help is greatly appreciated.

**Comment by kyse** [comment]
refer to #228 for an example.

**Comment by donstarkey** [comment]
I am still doing something wrong.
![image](https://user-images.githubusercontent.com/16799754/26848219-4678415c-4ac5-11e7-8109-225b6c34157b.png)

**Comment by kyse** [comment]
Oops, #288 rather.

**Comment by isaac2004** [comment]
No updates from @donstarkey for some time. Closing, please create new issue if needed
