### ISSUE TITLE
Does not work with IE11

### ISSUE THREAD

**Issue by JihedHalimi** [MarkPieszak/aspnetcore-angular2-universal#206]
Hello,

The template works fine with Visual Studio 2017 but does not work with IE11 missing polyfills etc...
IE11 support is very important to allow for script debugging within visual studio.

Thanks!

**Comment by TimHarker** [comment]
See the FAQ section on the [readme](https://github.com/MarkPieszak/aspnetcore-angular2-universal#faq---also-check-out-the-faq-issues-label).

**Comment by JihedHalimi** [comment]
Thank you @TimHarker it works well now.
Have a great day!
