### ISSUE TITLE
SSR not waiting for Axios http calls to complete

### ISSUE THREAD

**Issue by markphillips100** [MarkPieszak/aspnetcore-angular2-universal#210]
I'm not sure if this an issue with platform-server or Axios http lib so please tell me if it should be moved.

I'm having an issue with using the Axios npm package for http calls instead of angular http.  Server-side pre-rendering fails to wait for the http response and trigger update of the UI template before sending html to the browser.

I've forked to [https://github.com/markphillips100/aspnetcore-angular2-universal](https://github.com/markphillips100/aspnetcore-angular2-universal) to demonstrate the issue.  The fork just includes an HttpDemoComponent that is consumed from two routes; /httpdemo/angular and /httpdemo/axios.  Also provided links to the routes from the navmenu and commented the browser bootstrap code so we can see just the server response.

I don't know the axios internals at all.  I only know it returns a promise rather than an observable.  I've tried wrapping in a zone.run with no effect.

**Comment by markphillips100** [comment]
Looking through Axios doco and code shows they use node http at server so I attempted to narrow the issue to just that.

I've modified the issue's title and extended [https://github.com/markphillips100/aspnetcore-angular2-universal](https://github.com/markphillips100/aspnetcore-angular2-universal) to demo using only a Node http.get call.

Just using node's http.get I experience the same issue as Axios.  The console in VS2017 will show the response data fine, no exceptions occur, the subscription executes (and I have also checked it is in NgZone which it is) but the rendered response has not been updated.

I am currently running node v6.10.2

**Comment by MarkPieszak** [comment]
Why/where are you using Axios? Is this before prerendering?

**Comment by MarkPieszak** [comment]
You're going to have to keep track of the count for all the Http calls you're making and run prerendering after it.

**Comment by markphillips100** [comment]
What is the trigger for pre-rendering currently?  I maybe incorrectly assumed it was when the NgZone was done.

If pre-rendering is bound to zone completion, shouldn't I be able to wrap the http callback in a zone run?

**Comment by MarkPieszak** [comment]
It isn't, it's actually firing when the App becomes stable. But axios is outside of Angulars regular Http, so it doesn't take them into account.

Why do you need axios, that's more for node Http?

You could just extend Http and always return .toPromise() automatically if that's what you needed?

**Comment by markphillips100** [comment]
Thanks Mark.  It's a similar issue to [this one](https://github.com/angular/angular/issues/15278) then, and delving deeper into [platform-server/src/http.ts](https://github.com/angular/angular/blob/master/packages/platform-server/src/http.ts) shows the use of Zone.current.MacroTask which I believe is what makes things zone aware.

I was hoping for a simple solution to make node http zone aware but looking at the angular code shows it's a little more complicated than I first thought.

I'm dependent on axios because it's hard-wired into [contentfuljs](https://github.com/contentful/contentful.js).  They use it so they can intercept and handle rate-limiting.  Axios itself uses adapters for the comms which are wrappers over specific http libs; xhr for client and node http for server.  You can write your own adapter but I couldn't figure out a way to inject a dependency into the adapter - axios is not an angular library after all.

In lieu of a simple solution to use the existing lib I'm going to switch to angular http. I'd much prefer to use the angular Http module anyway. but I need to work out how to handle 429 rate-limiting using RxJs.  That's a separate issue though!
