### ISSUE TITLE
Pre-rendering timeout?

### ISSUE THREAD

**Issue by mb2140** [MarkPieszak/aspnetcore-angular2-universal#211]
Trying to implement my existing project into the Angular4 template and I'm getting a timeout during pre-rendering.  I've tried increasing the timeout period inside both the controller and startup.cs (NodeServices) and ultimate I end up with 

```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware:Error: An unhandled exception has occurred: A task was canceled.

System.Threading.Tasks.TaskCanceledException: A task was canceled.
```

How would I go about figuring out what exactly is causing my app to timeout?  

Also I noticed that 'ServerAppModuleNgFactory' inside main.server.aot.ts is looking for './ngfactory/app/server-app.module.ngfactory' which seems to be a missing file.  Not sure if this is related or not.

**Comment by MarkPieszak** [comment]
That error will always be there, you don't need to worry about that one as tsconfigs for dev etc ignore it.
It's used for when you build prod mode. (That has AoT)

Basically if a timeout is happening you're stuck in limbo somewhere, are you porting your existing app that worked in 2.x aspnet core with universal into this Repo?

**Comment by mb2140** [comment]
Yep, I have the app working in another branch using the 2.x template from JavascriptServices.  Again not sure if this is related, but I see a lot of weird template errors in the VS17 debug console like this:

```
Microsoft.AspNetCore.NodeServices:Error: 
                           <div style="margin-top: 0" [ERROR ->]*ngIf="pageVM?.isLoggedIn && pageLoaded">
Microsoft.AspNetCore.NodeServices:Error: 
                               <p "): ng:///AppModule/AppComponent.html@139:24
   Can't bind to 'ngStyle' since it isn't a known property of 'div'. ("
```

Any suggestions for working backwards to untangle this?  BTW thanks so much for putting this template together!

**Comment by MarkPieszak** [comment]
You must not be including BrowserModule? (which in turn imports CommonModule itself for you), that's where if style etc are.

Thank you! 👍
Just here to make life easier for folks !

**Comment by mb2140** [comment]
That was it!  Apparently I was missing CommonModule in my app.module.  I am still getting an error while building about 'import { ServerAppModuleNgFactory } from './ngfactory/app/server-app.module.ngfactory';' missing.  Is this a file that gets dynamically generated?  I'm not seeing this inside the project folder.

**Comment by MarkPieszak** [comment]
Yes it's dynamic and it'll always error out but that's why you need multiple tsconfigs, the normal one ignores that file.
