### ISSUE TITLE
Visual Studio 2015: is it possible?

### ISSUE THREAD

**Issue by mvasiliev** [MarkPieszak/aspnetcore-angular2-universal#212]
Hi guys.
Unfortunatelly, we are still using VS2015.
Is it possible to adapt this template for VS2015?
Is moving all files from one solution to another enough to do this?

Thanks.

**Comment by MarkPieszak** [comment]
You'd probably want to start with a new MVC 2015 project and start porting this project over into it.
2017 uses csproj not project.json, otherwise it shouldn't be too much of a difference, just need to make sure you have all the .net dependencies installed as well.

**Comment by mvasiliev** [comment]
It's enterpise, pal :) We can't just download VS2017 community and use it in our virtual machines. So, we should wait for official upgrade for enteprise edition. In the same time, we need to upgrade to Angular 4 since we have some 3d party dependencies that need it. By the way, your template is the one that we have found workable and meet our needs. Thank you for the job.

**Comment by MarkPieszak** [comment]
Glad it's working, hope you guys can eventually upgrade to make life easier! GL 👍
