### ISSUE TITLE
zonejs already loaded

### ISSUE THREAD

**Issue by VibhakarPathak** [MarkPieszak/aspnetcore-angular2-universal#221]
@MarkPieszak 
Getting following error: "zone already loaded", while trying to prerender two main-server files.
These two server files are used to bootstrap two different angular module.
See below code:

```
**Index action method**
** This is to load first module**
var prerenderResult = await Prerenderer.RenderToString(
                "/",
                nodeServices,
                new JavaScriptModuleExport(applicationBasePath + "/Client/dist/main-server"),
                unencodedAbsoluteUrl,
                unencodedPathAndQuery,
                transferData, 
                30000,
                Request.PathBase.ToString()
            );

**This is to load second module**
 var prerenderResultTwo = await Prerenderer.RenderToString(
                "/",
                nodeServices,
                new JavaScriptModuleExport(applicationBasePath + "/Client/dist/main-server-two"),
                unencodedAbsoluteUrl,
                unencodedPathAndQuery,
                transferData, 
                30000,
                Request.PathBase.ToString()
            );

**Webpack changes for two modules:**
**webpack.client.js changes:**
entry: {
        'main-browser': root('./Client/main.browser.ts'),
        'main-two-browser': root('./Client/main.two.browser.ts')
    },

**webpack.server.js changes:**
entry: {
        'main-server': root('./client/main.server.ts'),
        'main-two-server': root('./client/main.two.server.ts')
    },
```

I think the issue is because both files i.e. main-server and main-two-server have zone references. While first prerender request goes it loads zone and while we make second prerender request it also tried to load zone which is already there. We have tried to segregate vendor module using webpack, but no luck.

Do we have any work arround to make it working somehow?

**Comment by pravmd06** [comment]
Any possibility to load two different application on the page? 

@MarkPieszak
Any help on above queries?

**Comment by MarkPieszak** [comment]
I haven't tried to load up 2 different apps, can you remove a Zone reference from the second main server file?

Also it might be good to only try to handle a client entry, ignore that second server one.

Is there any reason you don't want to just combine the two Modules?

**Comment by pravmd06** [comment]
Thanks @MarkPieszak for quick reply!

I tried to remove zone reference from second file, but then after second request is getting time out.

The reason why I don't want to combine two module, as I have MVC application and have to use angular for partialy. 

For example if my page is devided in four section then for first & third section I have to use Angular and second & fourth from MVC Razor. 

The idea for first & third section is to inject html in razor using server side rendering when the page initial loaded and then after client side angular will handle rest of the work like pagination sorting etc.

Hope you got the context! :)

**Comment by MarkPieszak** [comment]
If you figured this one would love to hear how you pulled it off. Hoping to meet/sync up with Steve on how we can make the rendering process easier again.

**Comment by VibhakarPathak** [comment]
@MarkPieszak 
First of all thanks of all to your efforts and quick replies :thumbsup:

Problem:
"zonejs already loaded" error while trying to load mutiple app

Cause:
The problem was due to relative path dependency in temporary-aspnetcore-engine.ts file. These dependencies are for REQEST and ORIGIN_URL providers. Because of this, the second app doesn't get resolved, as the relative path for second app differs from this.

Solution:
Take out mentioned provider dependencies from temporary-aspnetcore-engine.ts to main.server.ts and main.server.aot.ts

However, if we ignore multiple app rendering use case for now, it is good to take out these dependecies for below reasons:
- Lossely coupled from npm package (ngAspnetCoreEngine, which is planned in future)
- Facilitate user to change the relative path whatever they want

Raised pull request #255 
Have a look on it and share your comments

**Comment by MarkPieszak** [comment]
Did we ever figure this one out?
