### ISSUE TITLE
ADD MORE AND MORE LINKS

### ISSUE THREAD

**Issue by futugyou** [MarkPieszak/aspnetcore-angular2-universal#224]
Every time you click 'Home','counter','API','Bootstrap'，'Link' will add two.
After a few times...

`<link rel="canonical" href="http://blogs.example.com/chat/something">
\<link rel="alternate" hreflang="es" href="http://es.example.com/users">
\<link rel="canonical" href="http://blogs.example.com/counter/something">
\<link rel="alternate" hreflang="es" href="http://es.example.com/counter">
\<link rel="canonical" href="http://blogs.example.com/chat/something">
\<link rel="alternate" hreflang="es" href="http://es.example.com/users">
\<link rel="canonical" href="http://blogs.example.com/counter/something">
\<link rel="alternate" hreflang="es" href="http://es.example.com/counter">
\<link rel="canonical" href="http://blogs.example.com/chat/something">
 `

**Comment by MarkPieszak** [comment]
This is a client only issue and will be fixed soon when there's an overall DocumentService.
Link canonical and such only matters for initial server renders as its used by blogs for SEO and such. 

I'll clos this one out as we have a duplicate at #172 but thanks for letting us know! We'll get a better LinkService out there soon enough. It'll all work fine for now though.
