### ISSUE TITLE
publish is not working for me

### ISSUE THREAD

**Issue by zandoleinc** [MarkPieszak/aspnetcore-angular2-universal#225]
In Windows environment, using VS2017, I can run this fine.  However, when I do a dotnet publish, it errors with the following: 
error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.aot --env.client" exited with code 2.

**Comment by MarkPieszak** [comment]
Do you have the latest code as of yesterday by any chance?
https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/220#issuecomment-297534949

See if your users component has those private properties (they can't be)

**Comment by TimHarker** [comment]
Regarding Mark's comment above, one thing I learnt while working through the exercise with Mark the other day was that when you receive the error you're receiving you should look in the Output window and fix any "publish" errors you might see.  Don't forget that "running" your app will not produce all the errors unless you visit the component in error whereas "publishing" your app runs all areas of your app.  I hope that communicates and helps.

**Comment by TimHarker** [comment]
Mark, may I update the FAQ section with something such as the above?  Perhaps...  Why can I run my app but it publishes with error "The command 'node node_modules/webpack/bin/webpack.js --env.aot --env.client' exited with code 2."?  I think this might be a common situation while ones developing, or perhaps (even better) there's someway to redirect the output to the error window???

**Comment by MarkPieszak** [comment]
I'm not sure how we could output the error window somewhere else, I wish we could that'd be so helpful!
Yeah of course Tim, any faq info will help people tremendously, there's so much more I'd love to add.

Hoping to start a video series & blog posts about things in a month or so as well.

**Comment by TimHarker** [comment]
I've been thinking (dangerous, some people tell me :-))...  One thing that's common that we might want to show case that's fairly common is, in and around, authentication.  I'm working on integrating that into my project (which uses this codebase) as we speak - using JWT and [openiddict](https://github.com/openiddict/openiddict-core).  Might retrofit in your solution with your permission/blessing and once I get it working, lol.

**Comment by zandoleinc** [comment]
That was it. I fixed the errors and it publishes fine now.  Thanks for the tip on where to find them.

**Comment by hesampour** [comment]
I have the same problem. how you fix the error?

**Comment by MarkPieszak** [comment]
Can you check your console when you run `npm run build:prod` and see which AoT / other errors come up? There must be some issues there. Hope that helps! @hesampour

**Comment by hesampour** [comment]
thank MarkPieszak the problem was with modals. I removed the ngx bootstrap modal and everything is fine now.
