### ISSUE TITLE
Update to ngx-bootstrap

### ISSUE THREAD

**Issue by binoypatel** [MarkPieszak/aspnetcore-angular2-universal#226]
ng2-bootstrap is deprecated for NG4, can we please update to ngx-bootstrap@next?

Thanks,
Binoy

**Comment by MarkPieszak** [comment]
Definitely! It has been officially released with the 4.0 version as well? We can definitely get that in there!

**Comment by binoypatel** [comment]
I have tested with 2.0 beta2 and working fine

Thanks

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by Adondriel** [comment]
The page says that it uses ngx-bootstrap, and ngx-bootstrap supports BS4, but how do I update this app to use bootstrap 4 instead of bootstrap 3? No matter what I do it keeps installing bootstrap-sass 3.3.7 and then including that in the site css, and if I uninstall it, it says the app requires it.

**Comment by Adondriel** [comment]
Deleted old comment, because it was off topic. I have successfully transitioned to ngx-bootstrap, it's fairly easy. My branch I did this in has a lot of other changes that I made, so I will have to redo those when I'm not working.

**Comment by Adondriel** [comment]
I believe my fork branch has the changes that were needed + other for updating to ngx-bootstrap, sadly they were combined with a ton of others, so I or someone else will have to replicated them at some point in the future. https://github.com/Adondriel/aspnetcore-angular2-universal/tree/master-forgit
