### ISSUE TITLE
Create AoT (Ahead-of-time compilation) production build

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-angular2-universal#23]

**Comment by ylibrach** [comment]
@MarkPieszak I noticed this is closed, but #10 is still open. Is AoT implemented? I'm also not seeing any commits relating to AoT in the past few weeks. Thanks!

**Comment by MarkPieszak** [comment]
Hey there, sorry yeah I didn't realize I had duplicate issues for the same thing so I closed this one out.
I haven't put it in yet, but hoping to either today or tomorrow. Apologies!

**Comment by ylibrach** [comment]
Makes sense, thanks @MarkPieszak. Great job on this project!

**Comment by shahrukh192** [comment]
@MarkPieszak is latest version **support** AOT and Build Optimizer
