### ISSUE TITLE
How to watch dev when file changes faster

### ISSUE THREAD

**Issue by thanhdevapp** [MarkPieszak/aspnetcore-angular2-universal#230]
When i change write new code, i need npm run build:dev to change view in browser, pls help

i using dotnet watch run

**Comment by thanhdevapp** [comment]
I found using bold `dotnet watch run` and `npm run watch:dev`

**Comment by markoj21** [comment]
I found webpack-dev-server to be the fastest option as it keeps all the files in memory and it compiles the files the quickest. The HRM rebuild still takes about 2-3 seconds, this is dependent on your machine and browser (Chrome was the quickest).

https://webpack.github.io/docs/build-performance.html (from the website)
Make sure you don’t do a full rebuild. Webpack has a great caching layer that allows you to keep already compiled modules in memory. There are some tools that help to use it:

webpack-dev-server: Serves all webpack assets from memory. Best performance.
webpack-dev-middleware: The same performance as webpack-dev-server for advanced users.
webpack –watch or watch: true: Caches stuff but write assets to disk. Ok performance.

**Comment by Adondriel** [comment]
Have you found a way to watch the server side files, and rebuild the serverside? Idk if it's the changes I made, or if the server side files just don't get watched...

**Comment by isaac2004** [comment]
@Adondriel what do you mean by server side files? Compiled js files?
