### ISSUE TITLE
font-awesome url to woff/tiff/eot

### ISSUE THREAD

**Issue by MaklaCof** [MarkPieszak/aspnetcore-angular2-universal#234]
How can I add font-awesome to the project?

I already added line in package.json:
`"font-awesome": "4.7.0",`
and import it in app.component.scss:
`@import "../../node_modules/font-awesome/scss/font-awesome.scss";`

But I get error that woff/tiff/eot files can not be found. I think I need to copy them (hopefully not by hand) to wwwroot.
 **How?** I think I am missing some webpack configuration.

Error:

> System.Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module "../fonts/fontawesome-webfont.eot?v=4.7.0"
>     at webpackMissingModule (e:\OpPISWeb\trunk\Client\dist\main-server.js:112040:158398)
>     at Object.<anonymous> (e:\OpPISWeb\trunk\Client\dist\main-server.js:112040:158515)
>     at __webpack_require__ (e:\OpPISWeb\trunk\Client\dist\main-server.js:26:30)
>     at Object.module.exports.module.deprecate (e:\OpPISWeb\trunk\Client\dist\main-server.js:119325:22)
>     at __webpack_require__ (e:\OpPISWeb\trunk\Client\dist\main-server.js:26:30)
>     at Object.<anonymous> (e:\OpPISWeb\trunk\Client\dist\main-server.js:95754:18)
>     at __webpack_require__ (e:\OpPISWeb\trunk\Client\dist\main-server.js:26:30)
>     at Object.<anonymous> (e:\OpPISWeb\trunk\Client\dist\main-server.js:108641:73)
>     at __webpack_require__ (e:\OpPISWeb\trunk\Client\dist\main-server.js:26:30)
>     at Object.<anonymous> (e:\OpPISWeb\trunk\Client\dist\main-server.js:107488:70)
> Current directory is: e:\OpPISWeb\trunk
> ......

**Comment by Surgutsky** [comment]
I've added the following code to the app.component.scss

**Comment by MarkPieszak** [comment]
thank you @surgutsky !

**Comment by inunotaisho26** [comment]
@surgutsky Could you give an example of this using LESS? That is what I use.
