### ISSUE TITLE
Argumant of Type (params: BootFuncParams)

### ISSUE THREAD

**Issue by callawey** [MarkPieszak/aspnetcore-angular2-universal#235]
Full Error from console:

Client/main.server.ts (16,37): Argument of type '(params: BootFuncParams) => Promise<{ html: string; globals: { [key: string]: any; styles: string...' is not assignable to parameter of type 'BootFunc'.
  Type 'Promise<{ html: string; globals: { [key: string]: any; styles: string; title: string; meta: strin...' is not assignable to type 'Promise<RenderToStringResult>'.
    Type '{ html: string; globals: { [key: string]: any; styles: string; title: string; meta: string; trans...' is not assignable to type 'RenderToStringResult'.
      Property 'statusCode' is missing in type '{ html: string; globals: { [key: string]: any; styles: string; title: string; meta: string; trans...'.

getting this error on VS2017

**Comment by markoj21** [comment]
Getting the same issue when trying to build on the vso build server, local builds work correctly.

2017-05-04T14:56:53.6533251Z npm ERR! node v6.10.0
2017-05-04T14:56:53.6533251Z npm ERR! npm  v3.10.10
2017-05-04T14:56:53.6533251Z npm ERR! code ELIFECYCLE
2017-05-04T14:56:53.6533251Z npm ERR! @1.0.0 build:aot: `webpack --env.aot --env.client & webpack --env.aot --env.server`
2017-05-04T14:56:53.6533251Z npm ERR! Exit status 2

**Comment by MarkPieszak** [comment]
So it looks like aspnet-prerendering updated, can you pin it to a lower 2.x version and see if that fixes it? I'm going to remove that Type soon and create our own here.

**Comment by callawey** [comment]
yes, its working with 2.0.3 but not with latest 2.0.4

**Comment by MarkPieszak** [comment]
Thank you @callawey! Want to make a quick PR so we can pin that version in the package.json?
