### ISSUE TITLE
project.json file is missing

### ISSUE THREAD

**Issue by alaatek** [MarkPieszak/aspnetcore-angular2-universal#237]
I cloned project and try to run it via visual studio code when executing the `dotnet run` command it returns a message that the project isn't valid because it doesn't contain project.json file  
the message is:

The current project is not valid because of the following errors:
/home/alaa/angular2-universal(1,0): error DOTNET1017: Project file does not exist '/home/alaa/angula
r2-universal/project.json'.

**Comment by MarkPieszak** [comment]
You need to have the latest .NET and VS2017 installed now that project.json is no longer supported by Asp.net. We can't support both 2015 and 2017 for that reason anymore sadly 😓.

 Let me know if that fixes it for you! I'll close this one out for now.

**Comment by alaatek** [comment]
Thank you so much :)  so,  the project in this state work only on windows machine, I will try your solution on windows machine as soon as possible

**Comment by MarkPieszak** [comment]
It works on Linux Mac as well, just need the latest vs 2017. Sorry about that! Following what the aspnet team repos are doing.

**Comment by alaatek** [comment]
Sorry for question but how can I run visual studio 2017 on mac or Linux I searched on Microsoft website I didn't find version for Linux, how can I run it without virtual machine

**Comment by MarkPieszak** [comment]
https://www.visualstudio.com/vs/visual-studio-mac/ Mac preview.
Or download the .net SDK and runtime and use Vscode 👍

**Comment by alaatek** [comment]
I work on Linux, the previous project (universal old branch) work like a charm on my machine because it has  project.json file I have .NET SDK and run time on my machine, I'm wondering if I could generate project.json file from csproj file I think this would solve my problem

**Comment by MarkPieszak** [comment]
Yeah you could rework it backwards to get the project json back that should work! Apologies so many things changed, you know how tech is 🙈
