### ISSUE TITLE
Turn off server rendering and keep TransferData

### ISSUE THREAD

**Issue by MaklaCof** [MarkPieszak/aspnetcore-angular2-universal#239]
I do not need server rendering, but I would like to transfer some variables.
I already tried with `null` instead `new JavaScriptModuleExport`, but I get error.
```
 var prerenderResult = await Prerenderer.RenderToString(
                "/",
                nodeServices,
                null, //new JavaScriptModuleExport(applicationBasePath + "/Client/dist/main-server"),
                unencodedAbsoluteUrl,
                unencodedPathAndQuery,
                transferData, // Our simplified Request object & any other CustommData you want to send!
                60000,
                Request.PathBase.ToString()
            );
```

Is it possible to transfer only data, but not entire Angular app?

**Comment by MarkPieszak** [comment]
So you'd want to comment out that entire section, so no prerendering gets fired, and change your Home/index.cshtml View from the ViewData to just <app></app>.

Where we put ViewData for TransferData you'd just need to create your own script tag with some object on window that you pluck on the Client side.

I'll try to clean that process up in the future as well as add more info in the Readme! Apologies time has been tight recently.
