### ISSUE TITLE
The name 'InnerExceptionCount' does not exist in the current context

### ISSUE THREAD

**Issue by jtcoyle** [MarkPieszak/aspnetcore-angular2-universal#240]
This project was working two days ago but today when I went to run the project I am getting the following  error "Count = error CS0103: The name 'InnerExceptionCount' does not exist in the current context".

InnerExceptionCount is found in startup.cs.

I have not made any changes to the code since I have cloned the repository.

**Comment by jtcoyle** [comment]
This seemed to be an issue with VS 20017.  After closing it down and restarting the project starts up without any errors.  If there was a way to delete this I would.

**Comment by MarkPieszak** [comment]
It's ok, it's good to keep here just in case someone else runs into it!
Glad you got it working though 👍

Anything else comes up, or ideas you have, we're all ears!
