### ISSUE TITLE
How properly use isPlatfromBrowser

### ISSUE THREAD

**Issue by michzio** [MarkPieszak/aspnetcore-angular2-universal#243]
I would like do do Leaflet Map Component that I could place in chosen part of my application. 
I have tired to use isPlatformBrowser() like in the code below. But after npm run build:dev I think this code also gets prerendered on the server side and when running the app I'm getting the error that window object not exists. 

```
import {Component, OnInit, Inject} from '@angular/core';
import { PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser, isPlatformServer } from '@angular/common';
import * as L from 'leaflet';


@Component({
    selector: 'leaflet-map',
    templateUrl: 'leaflet-map.component.html',
    styleUrls: ['leaflet-map.component.css', '../../../..//node_modules/leaflet/dist/leaflet.css'],
})
export class LeafletMapComponent implements OnInit { 

    constructor(@Inject(PLATFORM_ID) private _platformId: Object) { 
        isPlatformBrowser(this._platformId); 
     }

    ngAfterViewInit() { 

       
    }

    ngOnInit() {  
        if (isPlatformBrowser(this._platformId)) {
             L.map('leafletMap').setView([50.08, 19.93], 13);
        }
        if (isPlatformServer(this._platformId)) {
            // Server only code.
            // https://github.com/angular/universal#universal-gotchas
        }
    }
  
}
```

Could you tell how properly add component that will be rendered in the browser and not prerendered on the server side i.e. like component with maps?

**Comment by michzio** [comment]
I am building app using this command: 

> $ webpack --config webpack.config.js --progress --color

**Comment by MarkPieszak** [comment]
I haven't used Leaflet, but typically you're going to want to include `leaflet` only in your `main.browser` file.

In your Component just use a declaration (so that Typescript is happy), as to what leaflet is.

    declare var L: any;

Give that a shot, that might do the trick for you.

**Comment by michzio** [comment]
I have some errors in bootstrap (as I was upgrading my project from ASP.NET Core + Angular 2 => ASP.NET Core + Angular 4) and that was the reason while client side rendering and server side prerendering doesn't works well. When I adjusted my starter project to totally compliance with your sample project it started works fine.

**Comment by MarkPieszak** [comment]
Great! Everything is working well now?
