### ISSUE TITLE
Prerendering failed because of error: Error: Cannot find module

### ISSUE THREAD

**Issue by darthg8r** [MarkPieszak/aspnetcore-angular2-universal#244]
I've been unable to get the starter working with server side rendering.  I've gone as far as building a Windows 10 VM from scratch.  I installed VS 2017, NodeJS 6.9.4 and cloned this repo.  Node 6.9.4 is in my path variable, running node -v returns the correct version number.  $(PATH) is at the top of my Visual Studio Web Tools list, followed by .\node_modules\.bin.  Running the app with F5 results in this error.  

System.Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module 'C:\Projects\aspnetcore-angular2-universal\Client\dist\main-server'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)

**Comment by MarkPieszak** [comment]
What about if you do npm run build:dev first? 
Strange VS should (or at least used to) run that automatically.

**Comment by darthg8r** [comment]
Yup, run build:dev did it.  I found the thread in the FAQ that took me there.  The only remaining issue is:

      Template parse warnings:
      The <template> element is deprecated. Use <ng-template> instead ("
      [WARNING ->]<template [ngIf]="!isClosed">
        <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0

They appear to be warnings, should I be concerned?

**Comment by MarkPieszak** [comment]
No those are fine and will go away when ngx-bootstrap releases out of beta for its changes for angular 4+.
You're all set! 👍
