### ISSUE TITLE
VS2017 Typescript debugging/breakpoints

### ISSUE THREAD

**Issue by ynotlaugh** [MarkPieszak/aspnetcore-angular2-universal#245]
I'm not able to hit any breakpoints when trying to debug Typescript in VS2017.  I saw issues with debugging in VSCode but didn't know if this was working in VS2017 or if there is an issue there as well.  If it's not set up for VS2017 debugging, is there a plugin or configuration anyone can point me to to help me get this working for it?  Thanks.

**Comment by MarkPieszak** [comment]
So unfortunately it won't be available until VS can maybe attach itself to a Chrome protocol, if that ever happens. With Typescript that's been built through webpack and ran through a webpack-dev-server with HMR on top I can't imagine it'll be easy (if it's doable).

On the bright side though, you can open up chrome devtools and debug the front end of the application when you go to sources. Do ctrl-p when there to search for a specific Ts file, add a breakpoint and voila 🎁 debugging.

Hope that helps get you going!

**Comment by surgutsky** [comment]
I found that once you run the project VS populates 'Script Documents' in the Solution tree.
Just find the .ts file you'd like to debug in the list under main-browser.js and set a breakpoint.
You may also see variables' values in Locals section.

I'm a beginner in Angular/NET CORE, so I'm tot sure if this is the correct way to debug TS, but it works for me.

**Comment by MarkPieszak** [comment]
Very nice! I'm sure in time we'll get even better Debugging support (fingers crossed) from VS. With all of the webpack / typescript / etc, I can only imagine it's not very easy :)

Give Chrome devtools a shot as well, it's a great debugging experience.

**Comment by jrmcdona** [comment]
@MarkPieszak Is Chrome devtools still the way we need to debug TypeScript via VS Code?

When launching the setting "[Development] Debug TypeScript" in VS Code.  The app tries to load in the browser but fails.  Not sure if that is know behavior for now.  

Thanks
