### ISSUE TITLE
const { getAotPlugin } = require('./webpack/webpack.aot');       SyntaxError: Unexpected token {

### ISSUE THREAD

**Issue by Trapulo** [MarkPieszak/aspnetcore-angular2-universal#246]
Hi,
opening the project, when I try to compile webpack.config.js it reports:

webpack.config.js:7
const { getAotPlugin } = require('./webpack/webpack.aot');
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (F:\UnSorted\aspnetcore-angular2-universal-master\node_modules\webpack\bin\convert-argv.js:96:18)
    at F:\UnSorted\aspnetcore-angular2-universal-master\node_modules\webpack\bin\convert-argv.js:109:17
    at Array.forEach (native)
Process terminated with code 1.

Why? :(

**Comment by MarkPieszak** [comment]
What version of Node do you have installed on your machine? @Trapulo

**Comment by Trapulo** [comment]
v6.9.1

I tried via VS task runner, and also from command line,

**Comment by MarkPieszak** [comment]
Is webpack and everything installed?
`node --version` 6.9.1 comes up?

`npm i && npm run build:dev` 

VS comes with a built in (very old) version of Node, you can change that by making sure $(PATH) takes precedence over it in the Options/settings menu.

**Comment by Trapulo** [comment]
Upgraded and cleared node, webpack, etc.. now seem I can run compile webpack from CLI. VS still have the problem, but also VS 20127 has this legacy problem I remember in VS 2015? My external tools settings are .\node_modules\.bin then $(VSINSTALLDIR)\etc then $(PATH) then other teamfundation. Is this wrong?

**Comment by MarkPieszak** [comment]
There it is, so yes you want $(PATH) above it, so go there and move it up above everything else. You want VS to use your locally installed things before the old versions that come built-in. (I'm hoping this is something that gets fixed soon, they shouldn't be including a version of Node, especially a dated one)

Let me know, hope that fixes everything!

**Comment by Trapulo** [comment]
All works now, thanks!

**Comment by StefanKern** [comment]
I had the same problem, with Visual Studio Community 2017. So still not fixed in VS

**Comment by MarkPieszak** [comment]
Tried looking into it further, not sure what it is exactly on their end that's causing it to happen. Hope you figured it out with the above fixes? @StefanKern
