### ISSUE TITLE
Any suggestion for oauth2?

### ISSUE THREAD

**Issue by enterprisebug** [MarkPieszak/aspnetcore-angular2-universal#247]
Do you have any suggestions or plans to implement oauth?

Which implementation could you use? Do you have any tip?

**Comment by MarkPieszak** [comment]
Hey Daniel, I'm not sure if we'd need it in by default but a README about it could be very helpful for others!

Were you having issues implementing it?

I mean in general you'd basically just want to have your `/api` calls that go to WebAPI handle the OAuth, which then calls the external API (let's say Twitter, for example), and then return *that* result back down through WebAPI.  It shouldn't be much different than you'd normally do, and should work without a problem during server or client render (as the oauth happens in the WebAPI itself).

@enterprisebug

**Comment by enterprisebug** [comment]
Hi Mark,

basically my intention was to get an answer to the question: Which oauth implementation should i use. E.g. like: https://www.npmjs.com/package/angular2-oauth2
You have any clue on that?

If i have a successful implementation i will contribute it.

@MarkPieszak

**Comment by iberodev** [comment]
The IdentityServer guys have a client implementation for OpenId Connect + OAuth2
https://github.com/IdentityModel/oidc-client-js

I have used it successfully with AngularJs, not yet with Angular 2+ but it has its own tokenManager and it's easily configurable to retrieve id_tokens and access_tokens and to store them in localStorage or sessionStorage and to manage its expiration so that you can, for example, request a new token before the current one expires in a silent way (through an iframe that later on would trigger an event where you can handle the new token)

**Comment by MarkPieszak** [comment]
Damien just released a nice article that I believe hits this exact issue here: 

https://damienbod.com/2017/06/02/implementing-a-silent-token-renew-in-angular-for-the-openid-connect-implicit-flow/

**Comment by isaac2004** [comment]
I actually used that article for something else where I needed auth using this project as a start. Damien walks you though the whole process, but at the end of the day, you would AddAuthentication in your middleware and setup a key (I have a key that just sits in my appsettings). 

````
      services.AddAuthentication(options =>
      {
        options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
      }).AddJwtBearer(o =>
      {
        o.TokenValidationParameters = new TokenValidationParameters
        {
          ValidateIssuerSigningKey = true,
          ValidateIssuer = false,
          ValidateAudience = false,
          IssuerSigningKey = new SymmetricSecurityKey(Encoding.ASCII.GetBytes(Configuration["AppConfiguration:Key"])),
        };
        o.Events = new JwtBearerEvents()
        {
          OnAuthenticationFailed = c =>
          {
            c.NoResult();

            c.Response.StatusCode = 500;
            c.Response.ContentType = "text/plain";
            return c.Response.WriteAsync("An error occurred processing your authentication.");
          }
        };
      });
    }
````

and in the Api call that auths the token (Login in my case)
````
    [AllowAnonymous]
    [HttpPost("authenticate")]
    public IActionResult Authenticate([FromBody]User userDto)
    {
      var user = _userService.Authenticate(userDto.Username, userDto.Password);

      if (user == null)
        return Unauthorized();

      var tokenHandler = new JwtSecurityTokenHandler();
      var key = Encoding.ASCII.GetBytes(_appSettings.Key);
      var tokenDescriptor = new SecurityTokenDescriptor
      {
        Subject = new ClaimsIdentity(new Claim[]
          {
                    new Claim(ClaimTypes.Name, user.Id.ToString())
          }),
        Expires = DateTime.UtcNow.AddDays(7),
        SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
      };
      var token = tokenHandler.CreateToken(tokenDescriptor);
      var tokenString = tokenHandler.WriteToken(token);

      // return basic user info (without password) and token to store client side
      return Ok(new
      {
        Id = user.Id,
        Username = user.Username,
        FirstName = user.FirstName,
        LastName = user.LastName,
        Token = tokenString
      });
    }
````

At this point, the Api returns a Bearer token. Your Angular service would just need to save it (local storage for instance) and you are good to go.

Please close this ticket if this all makes sense and you can go from there

**Comment by isaac2004** [comment]
end to end JWT flow in howto/auth branch
