### ISSUE TITLE
Module build failed because of no such file:  node-sass\vendor

### ISSUE THREAD

**Issue by MapleYe** [MarkPieszak/aspnetcore-angular2-universal#249]
Downloaded the repository and tried running on vs 2017, but got the error: 
Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Zest\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor'

**Comment by MarkPieszak** [comment]
You need to rebuild node-sass, this is the stem of your other issue as well since this is breaking here already.

**Comment by MapleYe** [comment]
Thank you. It works.

**Comment by simeyla** [comment]
How come sometimes when I wipe out my node_modules folder I have to do this, and other times I don't? (yes it worked but very puzzled)
