### ISSUE TITLE
Cannot Find Module in the Server Side

### ISSUE THREAD

**Issue by MapleYe** [MarkPieszak/aspnetcore-angular2-universal#250]
Got exception as follows: 
Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module "es6-shim"

If I comment out "import es6-shim" in main.server.ts, the next imported file won't be found.

**Comment by MarkPieszak** [comment]
Stemming from #249 I would imagine let me know if clearing that up takes care of this one as well. This could be your Node version as well.

**Comment by MapleYe** [comment]
No, it doesn't work for this one. Still get the same error.

**Comment by MapleYe** [comment]
The exception is as follows: 
Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Cannot find module "zone.js/dist/zone-node"
at Object.<anonymous> (C:\Zest\SkiShopAngular2\SkiShopAngular2\ClientApp\dist\server.js:2137:7)
at __webpack_require__ (C:\Zest\SkiShopAngular2\SkiShopAngular2\ClientApp\dist\server.js:20:30)
at c (C:\Zest\SkiShopAngular2\SkiShopAngular2\ClientApp\dist\server.js:66:18)
at Object.<anonymous> (C:\Zest\SkiShopAngular2\SkiShopAngular2\ClientApp\dist\server.js:69:10)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
Current directory is: C:\Zest\SkiShopAngular2\SkiShopAngular2
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

**Comment by MapleYe** [comment]
node version is v6.10.3

**Comment by MarkPieszak** [comment]
Are you running `npm run build:dev` before running the project?

**Comment by MapleYe** [comment]
Most of the time, vs2017 will get errors and restart before  npm run build:dev finish its work. 
Got 3 errors:
ERROR in Error encountered resolving symbol values statically. Calling function 'Subject', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol ShopModule in C:/Zest/SkiShopAngular2/SkiShopAngular2/ClientApp/app/Shop/shop.module.ts, resolving symbol ShopModule in C:/Zest/SkiShopAngular2/SkiShopAngular2/ClientApp/app/Shop/shop.module.ts
    
    ERROR in ./ClientApp/temporary-aspnetcore-engine.ts
    Module not found: Error: Can't resolve 'fs' in 'C:\Zest\SkiShopAngular2\SkiShopAngular2\ClientApp'
     @ ./ClientApp/temporary-aspnetcore-engine.ts 6:9-22
     @ ./ClientApp/app/app-client.module.ts
     @ ./ClientApp/client.ts
    
    ERROR in [at-loader] ./ClientApp/server.aot.ts:12:42 
        TS2307: Cannot find module './ngfactory/app/server-app.module.ngfactory'.

The first  error doesn't show up for the same project without server prerendering setup.

**Comment by MapleYe** [comment]
If I move modules of node_modules to the same folder of server.ts(mail.server.ts in your project), they work well. It seems that  nodejs cannot search node_modules folder for any modules imported in server.ts.

**Comment by MapleYe** [comment]
just installed @nguniversal/aspnetcore-engine, but failed to get response, so ended due to time out.

**Comment by MarkPieszak** [comment]
Can you give more info about your machine:
OS / version / etc?

This is with a fresh pull down of the repo as well right?

Haven't seen this myself in any environment so not sure why all these would come up. The server-app.module.ngfactory can be ignored (it only exists in memory when you run prod mode).

Make sure Env mode is set as well:

```bash
# on Windows:
set ASPNETCORE_ENVIRONMENT=Development
# on Mac/Linux
export ASPNETCORE_ENVIRONMENT=Development 
```

You might need to even delete node_modules entirely, and reinstall everything `npm i && npm run build:dev`

**Comment by MapleYe** [comment]
Windows 8.1 Pro
VS2017 Version 15.2
node v6.10.3
npm  v3.10.10

**Comment by MapleYe** [comment]
Reinstalled package.json and made a few changes for webpack configurations.  Run "npm run build:dev" successfully now.  It's quite weird that the navigation menu cannot be loaded on the server side. Here;'s my app.component.html:
<shophead></shophead>
<router-outlet></router-outlet>

shophead is like nav-manu in your project. If I comment out <shophead></shophead>, the home page without the navigation bar pops up. But  if <shophead></shophead> stays where it is supposed to be in app.component.html, it ends like:  Prerendering timed out after 30000ms because the boot function in 'C:\Zest\myproject/Client/dist/main-server' returned a promise that did not resolve or reject....

**Comment by MapleYe** [comment]
Figured out that the failure of loading navigation bar was caused by the shopping cart which had a syntax error in its code. Now the only issue here is the failure of loading a picture ( sent by img tag  in an html file) from the server side.

**Comment by MapleYe** [comment]
All worked now. Gotta set up a folder for the image loaded from the server in the wwwroot folder because the server.js is not in the wwwroot folder. Thanks @MarkPieszak. I have learnt a lot from your work here.

**Comment by MarkPieszak** [comment]
Glad to help! If you any improvements as well, feel free to let me know any ideas, or make a PR! 👍
