### ISSUE TITLE
Prerendering failed to due to unexpected token

### ISSUE THREAD

**Issue by GPavlovic** [MarkPieszak/aspnetcore-angular2-universal#251]
Having some trouble getting up and running with my `boot-server.ts`, when I run my Angular 4 app, I receive this error:
`System.Exception: Call to Node module failed with error: Prerendering failed because of error: C:\Users\___\Documents\MyWorkspace\PrimeMI\Prime\Prime\node_modules\@nguniversal\aspnetcore-engine\index.js:1
(function (exports, require, module, __filename, __dirname) { export { ngAspnetCoreEngine } from './src/main';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous>`

I can see that npm has installed @nguniversal/aspnetcore-engine, and all seems fine there. Here is my `boot-server.ts`: 

```typescript
import 'zone.js';
import 'es6-promise';
import 'es6-shim';
import 'reflect-metadata';

import { enableProdMode } from '@angular/core';
import { INITIAL_CONFIG } from '@angular/platform-server';
import { AppModule } from './app/app.module';
import { createServerRenderer, RenderResult } from 'aspnet-prerendering';
import { ngAspnetCoreEngine, IEngineOptions } from '@nguniversal/aspnetcore-engine';

enableProdMode();

export default function (params: any): Promise<{ html: string, globals?: any }> {
    const providers = [{
        provide: INITIAL_CONFIG,
        useValue: {
            document: `<app></app>`,
            url: params.url
        }
    }];

    let engineOptions: IEngineOptions = {
        request: params,
        appSelector: '<app></app>',
        providers: providers,
        ngModule: AppModule
    };

    return ngAspnetCoreEngine(engineOptions).then(response => {
        return ({
            html: response.html,
            globals: response.globals
        });
    });

}
```

Any ideas what could be going wrong?

**Comment by MarkPieszak** [comment]
Let me take a look! Are you adding the aspnetcore engine to a fresh repo here or JSservices?

**Comment by GPavlovic** [comment]
This is a fresh repo. I eventually switched to the temporary aspnetcore engine that was written, but with it I was getting a null reference which was caused by line 88, where the provider is set for the REQUEST token. Changing it from ```useValue: options.request.data.request``` to ```useValue: options.request``` seems to have resolved that, but I am by no means under the impression that it is a fix. 

The cause of this unexpected token error, I have not yet managed to figure out. All seems to be functional now with my current setup.

**Comment by MarkPieszak** [comment]
Ah this is good to know! I'll have to make some tweaks with the aspnetcore engine then to make sure it aligns with everything perfectly. Thanks for the help! 👍👍

**Comment by isaac2004** [comment]
@MarkPieszak did you make the needed changes here, is it safe to close?

**Comment by MarkPieszak** [comment]
Not yet, let's leave this open for now.
I need to update a few things in the aspnetcore-engine over in universal, we're trying to figure out an upgrade path for future breaking/big changes within the libraries there.

**Comment by struxoje** [comment]
Any news on this?

**Comment by isaac2004** [comment]
@struxoje check the PR, it has an update

**Comment by struxoje** [comment]
Ahh great. Thank you

**Comment by MarkPieszak** [comment]
I'll close this one out since it's all set now with the 5.0 updates!
