### ISSUE TITLE
Enabling node debugging causes reentrant error in asp.net

### ISSUE THREAD

**Issue by JohnGalt1717** [MarkPieszak/aspnetcore-angular2-universal#252]
enabling the node services debugging like so:

`                services.AddNodeServices(options =>
                {
                    options.LaunchWithDebugging = true;
                    options.DebuggingPort = 5858;
                });
`

causes a crash in the asp.net code with a task has already been finalized reentrant error.

Any work arounds because this is very handy when server side pre-rendering goes nuts and you can't figure out why.

**Comment by MarkPieszak** [comment]
Let me investigate, thanks for pointing this one out John!

**Comment by isaac2004** [comment]
@JohnGalt1717 do have an example of this failing? I can't reproduce

**Comment by JohnGalt1717** [comment]
It's fixed as of .net 2.0. Closing.

**Comment by isaac2004** [comment]
@JohnGalt1717 I assumed that was the case, but I didn't want to just say "It works for me" :)
