### ISSUE TITLE
Dot.Net Core 2.0 Upgrade

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#253]
.NET Core 2.0 is on the way.

https://www.microsoft.com/net/core/preview?wt.mc_id=AID533228_EML_5056889#windowscmd

Will we upgrade this awesome project to new .Net version?

**Comment by isaac2004** [comment]
I did this locally to see how hard it would be. I had to delete global.json, than remove all the references in csproj. After that I changed the target to 2.0 an ran dotnet restore. Once I installed NodeServices and SpaServices manually, it all worked as expected.

**Comment by AbrarJahin** [comment]
@MarkPieszak , think we should make an upgrade after making some test :)

**Comment by isaac2004** [comment]
@AbrarJahin My only comment to that is Core 2.0 is in preview and the tooling is ever changing. Since this template is pretty robust, it may make sense to have a separate branch or repo for that.

**Comment by AbrarJahin** [comment]
@isaac2004 , that would be better if we create a separate branch for upgradations because there may be many changes and may create many issues.
So, I think we can create a separate branch for version 2.0 and then if everything works fine and Dot.Net Core version 2.0 becomes stable, we can merge that to the master.

What do you suggest @MarkPieszak ?

**Comment by MarkPieszak** [comment]
Hey guys, so I'm meeting with Steve Sanderson this week, and since we don't know when 2.0 is coming out just yet, it might be best to wait. I'm going to try to talk with him about overall strategy for aspnet and angular integration and hopefully we'll have some direction for how to update everything here & in JavaScriptServices.  I'll let you know when I learn more!

**Comment by isaac2004** [comment]
@MarkPieszak any update on the aspnet core engine? Just curious

**Comment by MarkPieszak** [comment]
Have to update some small things with it and add it in here as well. 
Were you running into any new issue? @isaac2004

**Comment by isaac2004** [comment]
Not at all, just waiting for the fully baked to see if anything needs changing.

**Comment by isaac2004** [comment]
@AbrarJahin have you tried to upgrade to 2.0? If not I could help with that.

**Comment by isaac2004** [comment]
@MarkPieszak you could close this as I am working on a PR to solve the other issue

**Comment by donstarkey** [comment]
I am very interested in the steps necessary to move this to 2.0 any help, documentation etc.. is greatly appreciated. Thank you

**Comment by MarkPieszak** [comment]
Oh ok great, I'll close it, thank you Isaac!
