### ISSUE TITLE
Is this valid javascript and if so, which release?

### ISSUE THREAD

**Issue by mdelgadov** [MarkPieszak/aspnetcore-angular2-universal#257]
The current webpack.config.js  has this line at num 8:

const { getAotPlugin } = require('./webpack/webpack.aot');

I got the usual error message: sintax error unexpected token {
I looked for the sintax in more modern js, didn't find anything...

should be easy to get rid of the curly brackets but hey, you never know...

**Comment by MarkPieszak** [comment]
You'll get this error if you have an older Node version, check which one you have with `node --version`, you need at least 6 or higher to run everything. This is the latest es2015 JS (also which higher versions of Node can handle natively now, which is nice).

That should fix it up though!

**Comment by mdelgadov** [comment]
now I feel so embarrassed...

**Comment by MarkPieszak** [comment]
No worries!
