### ISSUE TITLE
aot build failed

### ISSUE THREAD

**Issue by MapleYe** [MarkPieszak/aspnetcore-angular2-universal#263]
I'm using ` @ngtools/webpack`  1.3.1 and angular 4.1.2, but cannot get aot work. 
npm run build:aot

Got errors like: 

ERROR in ./ClientApp/client.ts
    Module not found: Error: Can't resolve './$$_gendir/app/app-client.module.ngfactory' in 'C:\Zest\SkiShopAngular2\SkiShopAngular2\ClientApp'
     @ ./ClientApp/client.ts 8:0-87

ERROR in ./ClientApp/server.aot.ts
    Module not found: Error: Can't resolve './ngfactory/app/app-server.module.ngfactory' in 'C:\Zest\SkiShopAngular2\SkiShopAngular2\ClientApp'
     @ ./ClientApp/server.aot.ts 8:0-87

**Comment by MapleYe** [comment]
It works out after making my code AOT compatible.

**Comment by MarkPieszak** [comment]
@MapleYe Glad you got it!
I'll add some notes for dos and dont's when it comes to AoT to help people avoid some crazy pitfalls
