### ISSUE TITLE
Spec files for testing client-side

### ISSUE THREAD

**Issue by cbeldacap** [MarkPieszak/aspnetcore-angular2-universal#265]
Hi, 

Where are `*.spec.ts` files supposed to be localted? Can't find them on Client folder.

Thanks in advance

**Comment by MarkPieszak** [comment]
There aren't *many* spec files yet, but there is at least one (that I can think of) in Counter (https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/master/Client/app/containers/counter)

Hoping someone can make a PR to implement a few others through out the application, or I'll get them in there once I get some more time!

You could put them next to your components/services/etc as you create them.
Hope that helps!
