### ISSUE TITLE
Error in webpack when injecting service as dependency

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#266]
Something strange happens to me

I have created a component and injected several services and consumed them normally

But when I inject another simple service (it's like a copy of another service that already works correctly) in the same component and run webpack:

`npm run build:dev`

The console generates a generic error that does not give me details of the "problem"

![image](https://cloud.githubusercontent.com/assets/25587867/26165133/78481e90-3af4-11e7-949b-bb513294574a.png)

I already checked the npm-debug.log file but I do not see details of my problem

[npm-debug.txt](https://github.com/MarkPieszak/aspnetcore-angular2-universal/files/1008456/npm-debug.txt)

Can someone give me a hand? Thank you

**Comment by MarkPieszak** [comment]
When scrolling up in cmd prompt what issues is webpack throwing?

**Comment by cristiancamiloperezlopez** [comment]
This is the top of the cmd

![image](https://cloud.githubusercontent.com/assets/25587867/26165861/1af11d2a-3af7-11e7-87fc-dff6daf410f5.png)

**Comment by MarkPieszak** [comment]
Can you try changing the npm script for build:dev and add a `--verbose flag to the end of it as well` try rerunning it and see if any other info comes up? Strange it doesn't say anything is wrong here!

**Comment by cristiancamiloperezlopez** [comment]
Of course

![image](https://cloud.githubusercontent.com/assets/25587867/26170467/2571e440-3b07-11e7-8fda-6f1f09c5a7e4.png)

[npm-debug.txt](https://github.com/MarkPieszak/aspnetcore-angular2-universal/files/1008803/npm-debug.txt)

**Comment by MarkPieszak** [comment]
Strange, what version of Node do you have installed? `node --version`

Try a quick wipe of node_modules & reinstall everything as well. Must be something strange that's cached / installed incorrectly messing things up.

**Comment by cristiancamiloperezlopez** [comment]
The version of node is

![image](https://cloud.githubusercontent.com/assets/25587867/26173605/14f4e076-3b12-11e7-98c9-5570504ea541.png)

Already delete and reinstall the folder node_modules, but I still do not get details about my problem...
I'm going to try other things in my code and I'll be giving you feedback

Muchas gracias !!

**Comment by MarkPieszak** [comment]
You end up figuring this one out? @cristiancamiloperezlopez

**Comment by cristiancamiloperezlopez** [comment]
The problem was solved with these instructions:

> Try a quick wipe of node_modules & reinstall everything as well. Must be something strange that's cached / installed incorrectly messing things up.

Thanks !!
