### ISSUE TITLE
Tree Shaking?

### ISSUE THREAD

**Issue by JohnGalt1717** [MarkPieszak/aspnetcore-angular2-universal#271]
Right now it appears that while this is doing AOT it isn't doing tree shaking (i.e. UglifyJsPlugin isn't enabled).

Is there any intent to add it? (I've added it manually at this point and it really shrinks files)

**Comment by MarkPieszak** [comment]
Hey John without a doubt, the webpack build system in general needs some love. 
We need to add Vendor & Polyfill chunking/splitting as well as add some better tree shaking, uglify, rollup and gzip would be great to have for Prod builds.

**Comment by JohnGalt1717** [comment]
Ok, well here's what I did for tree shaking. Tell me what you think:

In the webpack.prod.js I added this:

var webpack = require('webpack');

module.exports = {
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                drop_console: true,
                dead_code: true,
                drop_debugger: true,
            },
            mangle: {
                // Skip mangling these
                except: ['$super', '$', 'exports', 'require']
            },
            output: {
                comments: false
            }
        })
    ]
};

and then in webpack.config.js I added this around line 29:

    if (options.client && (options.prod || webpackOptions.prod)) {
        console.log('Use Client-side Production Deploy (tree shaking)');
        clientConfig = webpackMerge({}, clientConfig, prodPartial);
    }


And then I updated the .csproj to have env.prod=true

Obviously it would be better if it only set env.prod=true if dotnet publish was set with -c Release

**Comment by hheexx** [comment]
I think your config changes nothing. Those are mostly defaults.
Tree shaking is broken currently for trypescript. It will be fixed in future webpack version.

**Comment by JohnGalt1717** [comment]
@hheexx I'm definitely seeing a difference and you have to have uglify installed with the right branch and the plugin enabled. In package.json I have this in devDependencies:

    "uglify-js": "git://github.com/mishoo/UglifyJS2.git#harmony",
    "uglifyjs-webpack-plugin": "^0.4.3"


This makes tree shaking work with webpack and typescript properly unlike the default version that is indeed broken.

**Comment by hheexx** [comment]
Does not work for me.
Do I have to reference that new uglifyjs from webpack or it uses new version just by including it in packages?

**Comment by JohnGalt1717** [comment]
Add the lines above to your package.json and then follow my instructions from 13 days ago and then build with the new flag on webpack and it will enable it and work.

**Comment by hheexx** [comment]
I have Uglify plugin included. I tried with your params and without params and it does not work.
There is small file size difference but I think it's mostly because of output: { comments: false }

**Comment by JohnGalt1717** [comment]
You must have the exact version that I have above of the uglify plugin otherwise it won't work and treeshaking is disabled automatically because of issues that that version fixes in typescript as you noted. And it must be done after AOT is complete otherwise it will do nothing because it can't tree shake HTML so it has to include everything.

**Comment by hheexx** [comment]
I did c/p of your versions.
My plugin order is:
ContextReplacementPlugin
aotPlugin
UglifyJsPlugin

**Comment by chrisvfabio** [comment]
Works for me. Thanks!

Before:
![image](https://user-images.githubusercontent.com/5626828/27725236-fa3af0d2-5da7-11e7-9d91-955238e4121d.png)
After:
![image](https://user-images.githubusercontent.com/5626828/27725277-29c96072-5da8-11e7-8f2b-d37cf2dddd6b.png)

Should tree-shaking be applied to main-server.js? The file size is 19.2mb... Or would vendor splitting help reduce the size?

**Comment by JohnGalt1717** [comment]
In development if you have your webpack.config file set properly for target node this will be TINY because it will only be your code and it doesn't have to do a vendor rebuild.

For production you'll want to tree shake and AOT it just like the browser because all of the vendor stuff has to be loaded in because node_modules doesn't exist.

Vendor splitting is only for development to speed up HMR rebuilds so they don't take ages. 

However in production there are things that you do want:

1. Vendor css should be bundled separately and linked at the top of your <head> so that all of the styling is applied before the page displays so that users don't get horrible views. (this is easy with the code I've done so far)
2. Your application root styling should be loaded so that your base styling is loaded before the JS but not lazy loaded bundle css. (I can make it load ALL css but not the lazy loaded bundles at this point)
3. vendor.js gets loaded and then yours at the bottom of the page. Because it's 2 requests and with CSS possibly 4 with http instead of http/2 you're still under the limit and it should load simultaneously.

With all but the lazy loaded css we're down to under 1 second to load everything for a site that in development is 35 megs of chunks etc plus vendor. (yes it's a BIG site)

Once ng/tools is fixed to work with webdll.plugin and loads the chunks properly we should be able to get that down even lower and faster with AOT.

**Comment by isaac2004** [comment]
@JohnGalt1717 do you have a sample repo of your prod configs. I would be curious to see it.

**Comment by JustasKuizinas** [comment]
@JohnGalt1717 would be interesting to see your configs

**Comment by peterdobson** [comment]
@JohnGalt1717  I'd be very interested too!

**Comment by JohnGalt1717** [comment]
Update your .csproj and replace the items accordingly like this:

  <Target Name="DebugRunWebpackVendor" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And (!Exists('wwwroot\dist\vendor.js') Or !Exists('Client\dist\vendor.js'))">
    <Message Importance="high" Text="Installing Performing Webpack Vendor build..." />
    <Exec Command="node --max_old_space_size=32768 node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --progress --color" />
  </Target>
  <Target Name="DebugRunWebpack" BeforeTargets="Build" Condition=" '$(Configuration)' == 'Debug' And (!Exists('wwwroot\dist\main-browser.js') Or !Exists('Client\dist\main-server.js'))">
    <Message Importance="high" Text="Performing first-run Webpack build..." />
    <Exec Command="node --max_old_space_size=32768 node_modules/webpack/bin/webpack.js --progress --color" />
  </Target>
  <Target Name="RunWebpack" AfterTargets="ComputeFilesToPublish">
    <Message Importance="high" Text="Performing Production Webpack Publish..." />
    
    <Exec Command="npm run build:prod" />
    <ItemGroup>
      <DistFiles Include="wwwroot\dist\**; Client\dist\**" />
      <ResolvedFileToPublish Include="@(DistFiles->'%(FullPath)')" Exclude="@(ResolvedFileToPublish)">
        <RelativePath>%(DistFiles.Identity)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
[Portal.zip](https://github.com/MarkPieszak/aspnetcore-angular2-universal/files/1181671/Portal.zip)

Use the files in the attached updating your vendor.css.ts and vendor.ts according to your needs. 

Here's the devdependencies I have in my package.json, you can pick and choose what you need. 

  "devDependencies": {
    "@angular-devkit/build-optimizer": "0.0.7",
    "@angular/compiler-cli": "4.3.1",
    "@ngtools/webpack": "1.5.3",
    "@types/chai": "4.0.1",
    "@types/jasmine": "2.5.53",
    "@types/jest": "^20.0.4",
    "@types/webpack": "3.0.5",
    "angular-router-loader": "0.6.0",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.2.1",
    "chai": "^4.1.0",
    "codelyzer": "^3.1.2",
    "css": "2.2.1",
    "css-hot-loader": "^1.3.0",
    "css-loader": "0.28.4",
    "css-to-string-loader": "^0.1.3",
    "expose-loader": "0.7.3",
    "extract-text-webpack-plugin": "3.0.0",
    "file-loader": "0.11.2",
    "html-loader": "0.4.5",
    "ignore-loader": "^0.1.2",
    "jasmine-core": "^2.6.4",
    "jest": "^20.0.4",
    "jest-preset-angular": "^2.0.5",
    "json-loader": "0.5.7",
    "ngo": "github:angular/ngo",
    "node-sass": "^4.5.3",
    "raw-loader": "0.5.1",
    "resolve-url-loader": "^2.1.0",
    "rimraf": "^2.6.1",
    "sass-loader": "6.0.6",
    "source-map-loader": "^0.2.1",
    "string-replace-loader": "^1.3.0",
    "style-loader": "0.18.2",
    "to-string-loader": "1.1.5",
    "ts-node": "3.3.0",
    "tslint": "5.5.0",
    "typescript": "2.4.2",
    "uglify-js": "3.0.26",
    "uglifyjs-webpack-plugin": "0.4.6",
    "url-loader": "0.5.9",
    "webpack": "3.4.0",
    "webpack-merge": "4.1.0",
    "webpack-node-externals": "1.6.0",
    "webpack-sources": "1.0.1"
  }

This won't work with AOT nor does it work with the new purify plugin because of issues with rxjs.  AOT can be enabled by following the comments in the production.js webpack file to try. It might work on really small projects but it won't work on anything of any significant size even with 16gb of memory allocated to node.

use npm run build:vendor to rebuild all vendor files and it will also build the actual application.

npm run build:prod does a full production build. If you need to build just your site code for some reason npm run build:dev.

The csproj updates will automatically build vendor and dev if they're not there when you run the project for debug etc.

Hope that helps someone, although it's still infuriating because no AOT nor proper tree shaking. If someone can figure out how to get hose working reliably with large projects I'd be eternally grateful.

**Comment by peterdobson** [comment]
Thanks @JohnGalt1717  I'm giving this a whirl, but getting "missing script: build:vendor" on running npm run build:vendor. What needs to be specified in the scripts section of package.json to get the scripts section?

**Comment by JohnGalt1717** [comment]
"scripts": {
    "test": "jest",
    "test:watch": "npm run test -- --watch",
    "test:ci": "npm run test -- --runInBand",
    "test:coverage": "npm run test --coverage",
    "build:dev": "webpack --progress --color",
    "build:vendor": "rimraf wwwroot/dist && rimraf Client/dist && webpack --config webpack.config.vendor.js --progress --color && webpack --progress --color",
    "build:prod": "rimraf wwwroot/dist && rimraf Client/dist && webpack --config webpack.config.vendor.production.js --progress --color --env.prod && webpack --config webpack.config.production.js --progress --color --env.prod",
    "webpack": "set UV_THREADPOOL_SIZE=100 & node --max_old_space_size=32768 --webdriver-update node_modules/webpack/bin/webpack.js"
  },

You'll also need these commands. Note that the webpack command is aliased so that larger projects will even build because angular is running up against major issues of memory and threatpools so you must use this alias for all of your scripts to get successful compiles on any real-world application.

**Comment by JohnGalt1717** [comment]
Note that when you use this in dev your vendor stuff will be HUGE for the browser side and tiny for the server side. The server side uses the node_modules folder for resolution so it doesn't have to build it which speeds things up significantly.  In production, in an attempt to get AOT working which doesn't work with vendor splitting (and would defeat tree shaking) it doesn't actually create a vendor.js split, all of the vendor code gets loaded into the main.browser.js but it doest create a vendor.css that you need to include on your site (for both production and dev).  This is because in any case where SSR isn't used your site will look a lot better loading if the css is pre-loaded.

Once the endless bugs in Angular and the webpack stuff are fixed this configuration should just work for AOT and the tree shaking that it's already doing will get significantly better because of the PrestinePlugin which even though it errors gives a 25% improvement in size of the bundles when enabled.

**Comment by Adondriel** [comment]
So, @JohnGalt1717 you're saying I shouldn't do the above if my build server, for some reason only has 8GB of ram? (IKR, I was wondering why builds are so slow... they really need to upgrade that.)

**Comment by JohnGalt1717** [comment]
@Adondriel I'm saying that it nodejs will never use more than 2 gb of memory per process so no matter how high you set that number over 2gb it won't matter which causes AOT and Treeshaking to fail on any substantial project because they will absolutely use more than 2 gb of memory and fail.

**Comment by Adondriel** [comment]
My project isn't TOO big, but the current size is at 7.3-7.7MB, with your earlier changes, the uglify stuff took it down a good bit. also, I updated my comment, which command do you use?

**Comment by JohnGalt1717** [comment]
npm run build:prod.

npm run webpack is what is used internally by the debugging etc. in C#.

**Comment by Adondriel** [comment]
ah, right gotcha. that will result in 2 files, the main file, and the vendor file? no, that's for dev, the prod will compile it all into one big file if I understand you correctly.

**Comment by Adondriel** [comment]
@JohnGalt1717 I confused by what you mean when you said:

> %(DistFiles.Identity) PreserveNewest
Use the files in the attached updating your vendor.css.ts and vendor.ts according to your needs.

What changes did you make to your .csproj file?

**Comment by JohnGalt1717** [comment]
The file is attached at the bottom of that message. GitHub ate it the first time. Basically just set the production version to use npm run build:prod and added functionality for it to automatically build the vendor stuff if it doesn't exist.

**Comment by Adondriel** [comment]
I'm trying to compile the client stuff, and i'm getting this error. Do I need version 6 of rxjs? 
![image](https://user-images.githubusercontent.com/1113496/28892976-cf07a9e0-779d-11e7-84d0-b3150f529036.png)

**Comment by JohnGalt1717** [comment]
That's typescript complaining while compiling. You'll need to fix the typescript errors. It's far more strict when compiling in production mode.

Make sure you only have one version of typescript installed and it's 2.4.2 if you're using Angular 4.x

**Comment by Adondriel** [comment]
I had ^2.4.0 earlier, then I updated to 2.4.2, after updating the RXJS 6, the error still persists... it has to be a version mismatch right?

**Comment by JohnGalt1717** [comment]
One would guess so but I can't say for sure.

**Comment by Adondriel** [comment]
I should probably delete all the old webpack files, yea?

**Comment by JohnGalt1717** [comment]
Yes, but it won't use them as long as you overwrote with what I included.

**Comment by Adondriel** [comment]
It's still getting hung up on main.server.aot.ts for some reason, can't find the stupid ngFactory module thing. Do your files go in the webpack folder? or in the root? I have them in the root ATM.

**Comment by JohnGalt1717** [comment]
In the root. You need to replace your tsconfig.json etc. In the door as well so that it ignores that file.

________________________________

**Comment by Adondriel** [comment]
Currently stuck trying to figure out how the hell to update rxjs, it refuses to update to branch 6, which is what contains the fix for the errors i'm seeing.

**Comment by Adondriel** [comment]
ok, this doens't make sense... I have rxjs installed, with 6.0.0, but npm ls can't find the damn thing... 
![image](https://user-images.githubusercontent.com/1113496/28895362-12fc6bba-77a6-11e7-96a0-efb09f3fbbff.png)
I think my pc is due for a restart... the only time it find rxjs, is when it's included under @angular/cli...

**Comment by Adondriel** [comment]
I had to set:     "skipLibCheck": true
in the tsconfig.json file, in order to make it stop checking the rxjs version of sub-modules.
This works wonders, Vendor css is 58KB, main-browser is 1.3MB, and vendor.js is 1.7KB... seems a little small, lol.

**Comment by JohnGalt1717** [comment]
Ya... I had to learn webpack which is a disaster that only people that haven't experienced the wonders of Visual Studio would love.

On the vendor stuff, make sure you update the imports in the vendor.ts and vendor.css.ts files otherwise you won't get anything.

But on production it should do a lot of tree shaking and uglification and vendor.js will be tiny in that case because it puts it all into the main.browser.js so that it can tree shake etc. It only splits the vendor.js in development to speed that up. If it did that in production it would defeat treeshaking when it finally works properly.

**Comment by isaac2004** [comment]
@JohnGalt1717 do you know of an easy way to disable sourcemaps with this solution? I want my PROD builds TS not be readable with a Browser plugin

**Comment by JohnGalt1717** [comment]
1. The TS won't be deployed so the maps are useless.
2. You can remove the maps by just going into the webpack.config.production and vendor.production and removing the devtool entries. (should be 2 per file)

**Comment by Adondriel** [comment]
@JohnGalt1717 Did you happen to get this error as well? 
![image](https://user-images.githubusercontent.com/1113496/29127129-308ea510-7cee-11e7-9b0a-879792e85899.png)

**Comment by JohnGalt1717** [comment]
Yup. Routinely after Webpack 3.x

**Comment by Adondriel** [comment]
Hmm, did you ever find a fix for it?

**Comment by JohnGalt1717** [comment]
No. It just comes and goes.

**Comment by Adondriel** [comment]
hmm, mine just always happens... >.<

**Comment by JohnGalt1717** [comment]
Let me count the ways that I absolutely HATE Webpack...

**Comment by Adondriel** [comment]
Hmm, I shall investigate... it seems like, it just isn't doing the .dispose() before .accept()?

**Comment by JohnGalt1717** [comment]
I haven't touched that code but in main.browser.ts it clearly has a dispose() function.

**Comment by Adondriel** [comment]
yea, which is what is confusing me. I'm sitting here screaming at it: "I AM TRYING TO DELETE YOU, YOU JUST WON'T LISTEN!"

**Comment by JohnGalt1717** [comment]
Just noticed that there was an updated to the code 9 days ago that removes a bunch of stuff. Check it out. It might solve it.

**Comment by Adondriel** [comment]
so, I got rid of the error, but didn't fix the fact that HMR still breaks my stylesheet stuff. I'll check that out, the code for Webpack, or the HMR plugin(if that exists)?

**Comment by Adondriel** [comment]
I kinda just disabled it all together in main.browser.ts, it grabs the hmr bundle, but doesn't do anything with it... sadly. I'll have to figure out what's going on. They way I fixed the error being created was by getting rid of the stuff in the .dispose() and just having 
```
    module['hot'].accept(() => {
         if (modulePromise) {
             modulePromise.then(appModule => {
                 appModule.destroy();
             });
         }
    });
```

**Comment by Adondriel** [comment]
is there a way to just tell it to do a full page reload, on hmr?

**Comment by JohnGalt1717** [comment]
Sorry can't help there. Never looked into it. I don't trust HMR at all so I always hit refresh.

**Comment by Adondriel** [comment]
replace your main.browser.ts with:
```
// // Enable either Hot Module Reloading or production mode
if (module['hot']) {
    module['hot'].accept(() => {
        // if (modulePromise) {
        //     modulePromise.then(appModule => {
        //         appModule.destroy();
        //     });
        // }
        window.location.reload();
    });
    module['hot'].dispose(() => {
        // Before restarting the app, we create a new root element and dispose the old one
        // const oldRootElem = document.querySelector(rootElemTagName);
        // const newRootElem = document.createElement(rootElemTagName);
        // oldRootElem.parentNode.insertBefore(newRootElem, oldRootElem);
        // modulePromise.then(appModule => {
        //     appModule.destroy();
        // });
    });
} else {
    enableProdMode();
}
```

**Comment by Adondriel** [comment]
it won't work with SSR, but I don't think that works with 90% of everything else out there, tbh.
