### ISSUE TITLE
Cannot find module './ngfactory/app/server-app.module.ngfactory'

### ISSUE THREAD

**Issue by isaac2004** [MarkPieszak/aspnetcore-angular2-universal#272]
I am getting this error in main.server.aot.ts when I open the solution, run build:dev and start the app. The app seems to be starting fine, but I get this error in the error list. Is there a dependency that I am missing on my machine?

**Comment by MarkPieszak** [comment]
Hey Isaac no everything is fine actually, you can ignore that. It's only for Prod builds which use different tsconfigs and different main.server.aot file. Ngtools just merged a PR which when gets into npm we will be able to get rid of that file and extra tsconfig, it'll handle it the same way main.browser automatically handles it. 🎁👍

**Comment by MarkPieszak** [comment]
Closing out but let me know if anything else you're wondering about it!
