### ISSUE TITLE
Dynamic Meta Data possible with current Meta Data Implementation? 

### ISSUE THREAD

**Issue by Defmetalhead** [MarkPieszak/aspnetcore-angular2-universal#275]
Currently meta data is static and set in the following way: 

```
    {
            path: 'venuedetail/:id', component: VenueDetailComponent,
            data: {
                title: 'Venue Title',
                meta: [{ name: 'description', content: 'This is User REST API example page Description!' }],
            
           }
    },
```

Is there a way to set the meta data tags dynamically from within the routed component, or do I need to import a separate class?

**Comment by consigliory** [comment]
Just wanted to ask same question

**Comment by MarkPieszak** [comment]
I'd say if you wanted it to be dynamic like that, I'd maybe add a check to see if that `data{}` exists (leave it blank for situations you want very dynamic), and inside the `app.component` where we're plucking and setting all of these, simple add some logic to get them from other parts of the Route, maybe you want the parameters / etc.

Around here is where you'd want to update the logic a little bit. 

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/app/app.component.ts#L83-L84

But yea, we can't have do anything async or get data from the Route itself within that `data{}` within our `Routes[]` Array.

Hope that is enough to get you going in the right direction?
