### ISSUE TITLE
Strange loop in ngAfterViewChecked()

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#276]
Hi Mark,

I'm observing strange behavior in the ngAfterViewChecked event, apparently creating an infinite loop ...
Simply I modify the component Home adding the event

![image](https://cloud.githubusercontent.com/assets/25587867/26356638/52bddd2a-3f92-11e7-8f03-eccb07672280.png)

Then run webpack `npm run build:dev` and we are ok

But simply with this change the template does not start

![image](https://cloud.githubusercontent.com/assets/25587867/26356803/eae34bc6-3f92-11e7-95da-8e58d3ede06b.png)

Then I was reviewing a little, install Microsoft.AspNetCore.NodeServices and found in the visual studio output an apparent infinite loop :(

![image](https://cloud.githubusercontent.com/assets/25587867/26356976/8200003a-3f93-11e7-96b8-7932827f88fb.png)

The loop continues, I hope you can help me. Thanks

**Comment by MarkPieszak** [comment]
Thanks for posting this @cristiancamiloperezlopez  !!
I haven't ran into this myself, let me take a look and see if it's something with `@angular/platform-server` itself that we haven't seen yet!

**Comment by MarkPieszak** [comment]
Ok repro'ing it now, taking a look

**Comment by cristiancamiloperezlopez** [comment]
Hi Mark,
I just did the same exercise, but the loop continues

![image](https://cloud.githubusercontent.com/assets/25587867/26467803/b5fecaac-4159-11e7-9fcf-c1cb329fea30.png)

**Comment by MarkPieszak** [comment]
Yeah, brought it up to the team, it's quite a strange issue.

**Comment by cristiancamiloperezlopez** [comment]
Update
I was reviewing and as I suppose console.log runs in the browser I made this change

`import { isPlatformBrowser, isPlatformServer } from '@angular/common';

    constructor(
        @Inject(PLATFORM_ID) private platformId: Object,
        public translate: TranslateService
    ) { }

    ngAfterViewChecked(): void {
        **if (isPlatformBrowser(this.platformId)) {**
            // Client only code.
            console.log("ngAfterViewChecked");
        }
    }`

Now the application starts, however I see that the console.log runs several times, you know why? Is it something that has to do with the type of event?

![image](https://cloud.githubusercontent.com/assets/25587867/26640572/b5bb4bea-45ed-11e7-9565-0832733a2474.png)

Thanks !

**Comment by JustasKuizinas** [comment]
[http://take.ms/v4rRv](url)

**Comment by MarkPieszak** [comment]
Logged a bug in `@angular/core` https://github.com/angular/angular/issues/17180, I'll take a look and hopefully we'll have a fix for it soon in an upcoming release.

**Comment by cristiancamiloperezlopez** [comment]
@MarkPieszak  Thanks bro

**Comment by MarkPieszak** [comment]
Fixed as zones PR went through to clean it up. 👍
