### ISSUE TITLE
temporary-aspnetcore-engine missing reject

### ISSUE THREAD

**Issue by kyse** [MarkPieszak/aspnetcore-angular2-universal#277]
There's a missing reject around line 211 of temporary-aspnetcore-engine.  This causes any rendering errors to show up in the browser while debugging as renderer timed out rather than spitting out the actual error message.  Might be good to add that final promise's error function to reject the promise, then on the server side just make sure proper debugging output is toggled based on debug/prod state.

**Comment by MarkPieszak** [comment]
👍 
Adding that final reject made those bubble up for you and template rendering errors showed up during the server rendering process?

If you'd like to submit a PR about it that'd be great to fix that missing piece! I wasn't aware that's happening, but I know we're working on Error throwing on the platform-server Angular side.

**Comment by kyse** [comment]
I think it's missing the last 2 nests of error promise handlers actually.

**Comment by MarkPieszak** [comment]
Fixed now, thanks for the heads up!! Should of known something was missing 
Thanks again 👍
