### ISSUE TITLE
Can't add System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by digibum** [MarkPieszak/aspnetcore-angular2-universal#278]
I added System.IdentityModel.Tokens.Jwt from NuGet but I can't use it.
using System.IdentityModel.Tokens.Jwt => "IdentityModel does not Exists in this namespace".

I need this for JWT token authentication when creating new Claims (JwtRegisteredClaimNames.Sub...). Why would this happen?
Thank you.

**Comment by kyse** [comment]
https://blogs.msdn.microsoft.com/webdev/2017/04/06/jwt-validation-and-authorization-in-asp-net-core/

Perhaps that library isn't meant for dotnet core?  Try the library mentioned in that link: Microsoft.AspNetCore.Authentication.JwtBearer.

**Comment by digibum** [comment]
Sorry, this was a Visual Studio IntelliSens problem. It is working now with System.IdentityModel.Tokens.Jwt.
Thank you for your help :)
