### ISSUE TITLE
[proposal] Add Electron support

### ISSUE THREAD

**Issue by Mahbub-A-Rob** [MarkPieszak/aspnetcore-angular2-universal#28]
Wonder if you could add electron support as well.

**Comment by MarkPieszak** [comment]
Good idea, sure why not !

**Comment by AnderssonPeter** [comment]
the following could be used https://github.com/kexplo/electron-edge

**Comment by MarkPieszak** [comment]
Seems like this would really be out of the scope as you'd want to just have a separate project probably handling this.
