### ISSUE TITLE
old branch throw an error after take the publish folder content to IIS

### ISSUE THREAD

**Issue by alaatek** [MarkPieszak/aspnetcore-angular2-universal#280]
the old branch work like a charm locally in visual studio, but when try to publish the generated app everything goes as expected without throwing any error or exception, but when copy the content of publish folder to IIS and run the app the message shown to me that some error occured without any details 
the content of message is:
**Error.
An error occurred while processing your request**.

![publish error](https://cloud.githubusercontent.com/assets/5349694/26418241/22cf01b0-40c4-11e7-9cc5-99e82ea84945.PNG)

how can I track the error, where things goes wrong, or any further details, is it IIS problem or should I have special configuration in IIS, even I tried to publish Test ASP Core Web Application to IIS everything goes as expected and the app hosted successfully

Any Help would be appreciated

**Comment by MarkPieszak** [comment]
Do you have Node 6+ installed as well?

**Comment by alaatek** [comment]
I have node version 7.10, I catch the issue, I run dotnet command in generated publish folder with main dll file as argument when the app run I discovered from error shown in cmd that Client folder didn't moved to publish folder I copied it and all things goes as expected
