### ISSUE TITLE
Request to add a Scheduler

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#282]
Hi, I think, we can add a schedule to this template so that we can do any scheduled tasks like-

1. Sending the mail
2. Background tasks
3. Automatic backup
4. Managing request queue for heavy works **_etc._**

If you ( @MarkPieszak  ) agree with me, then I think, this one (**HangFire**) is one of the best choices for the job-

https://github.com/HangfireIO/Hangfire

An easy tutorial to do that can be found in here-

http://dotnetthoughts.net/integrate-hangfire-with-aspnet-core/

Will we add this to the template @MarkPieszak ?

There is also a **NuGet** package for this-

https://www.nuget.org/packages/Hangfire/

**Comment by MarkPieszak** [comment]
Hey @AbrarJahin ! 
Unfortunately I don't know if we'd need that in here as it's more specific to if someone needs that in a project. We could always add a Wiki or Readme markdown file on how to get it setup if you figure out how to do it?

**Comment by AbrarJahin** [comment]
Sure @MarkPieszak .

I will add that in this project and let you know if I can and will update the wiki 👍
