### ISSUE TITLE
Typescript: Cannot find module './ngfactory/app/server-app.module.ngfactory'

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#284]
Hi Mark,

In this file:
[main.server.aot.ts](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/main.server.aot.ts)

Typescript tells me Cannot find the module './ngfactory/app/server-app.module.ngfactory'

![image](https://cloud.githubusercontent.com/assets/25587867/26513587/ebd5d688-4231-11e7-8871-2bf6790baaa9.png)

And I see that the file is not on the path
Thanks

**Comment by vicver82** [comment]
This file is built at aot compile time. It didn't exist yet / wasn't compiled yet when you took the screenshot.

**Comment by MarkPieszak** [comment]
Yeah Victor is spot on, you don't have to worry about that error, also that main.server.aot file will be going away soon now that ngtools merged a PR to handle the server similarly to the way it handles main.browser (notice that we only have 1 version of that file).
