### ISSUE TITLE
main.browser.ts - module['hot'].accept() error

### ISSUE THREAD

**Issue by kyse** [MarkPieszak/aspnetcore-angular2-universal#285]
In VS 2017 the module['hot'].accept() doesn't play well until I added @typings/webpack-env, and updated tsconfig.json to include webpack-env in the types array.

**Comment by kyse** [comment]
I must have been tired when I wrote this. Just to clarify to fix errors that might annoy you like ReSharper solution evaluation.  Run npm install @typings/webpack-env --save-dev then do the above, add it to then tsconfig.

**Comment by MarkPieszak** [comment]
What was the problem? I haven't seen this one happen with VS2017.
