### ISSUE TITLE
Consider individual examples vs all-in-one?

### ISSUE THREAD

**Issue by georgiosd** [MarkPieszak/aspnetcore-angular2-universal#286]
Hi!

Thanks for piecing this together.

I find myself getting quite frustrated with this type of starter because there's so much going on in there that I can hardly follow what's going on - and find it difficult to start hacking around.

Plus, I don't really need a lot of the features.

Would you consider slowly converting this all-in-one to individual configurations?

e.g. /configurations/pre-render: contains minimal configuration for SSR
etc.

**Comment by iberodev** [comment]
I agree, I'm in the same situation.
Also a tutorial or a step by step on who this has been configured could help, so that we could decide what pieces do we integrate and which ones we don't need. It's a great project anyway, so thanks

**Comment by MarkPieszak** [comment]
This is a great idea, it might be tough to pull off besides creating a yoeman template with many options for each situation.

Are you saying having separate projects in each `/configurations/*whatever*` section?

**Comment by georgiosd** [comment]
Yeoman is definitely one better but it wouldn't really help us isolate the components for comprehension purposes. 

What's the complexity you see in the separate configurations solution? 

In my mind, it's simpler, because you only have to update each branch whenever something changes for that particular branch, rather than trying to make everything trying to play together which I'm sure you agree that from experience can be very hard as version-specific incompatibilities appear from time to time.

**Comment by isaac2004** [comment]
@georgiosd We have updated master with a lighter version of the template. The plan is to have branches(or PRs) with features available for testing. Let us know if this works for you

**Comment by georgiosd** [comment]
@isaac2004 thank you! This is great!
