### ISSUE TITLE
Pass NgRx State from Server -> Client

### ISSUE THREAD

**Issue by MarkPieszak** [MarkPieszak/aspnetcore-angular2-universal#29]
Currently we have NgRx Store on the Server, but we need to pass these easily to the client, then initialize the Store with those values. This way if someone uses the Store to handle a lot of their application they can transfer cache/state here instead.

This is another option as opposed to [HttpCacheService](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/shared/cache/api.ts).

(Could be connected with https://github.com/ngrx/store/issues/294)

**Comment by pjmagee** [comment]
@MarkPieszak Is this still a problem for being able to add ngrx store rehydration/hmr ngrx store rehydration to the template?

**Comment by MarkPieszak** [comment]
I have an example of how it can be used with HttpTransfer and everything let me find it.

**Comment by pjmagee** [comment]
I've currently gone through migrating our application from the old Angular2 template to this current template on Master, however we are now using ngrx and ngrx effects for our api, user state, however I'm still pretty new to the angular/js world and I've been struggling to figure out how to rehydrate...a little mockup would be awesome 👍

**Comment by MarkPieszak** [comment]
@pjmagee 
You can see it here in this PR, it'd be along these lines.
They're both using TRANSFER_STATE etc like we are here, so it should be very similar.

Hope that helps!
