### ISSUE TITLE
ServerAppModuleNgFactory problem

### ISSUE THREAD

**Issue by AlexLubinski** [MarkPieszak/aspnetcore-angular2-universal#290]
Hi, Mark! Thanks for your project!

Firstly I added your project into my solution. And there wasn't any problem with Azure deployment. 

But then I copied all files into another project. In this case, same publish fails with error:

Error	TS2307	Cannot find module './ngfactory/app/server-app.module.ngfactory'.	MarketPlace.Web (tsconfig project)	MarketPlace.Web\Client\main.server.aot.ts	11	Active

Could you suggest something? May be some additional settings.

Thanks!

**Comment by digibum** [comment]
This happen to me to. After coding for some time, made some changes and bum. I can't get it back to working.
Cannot find module:
`import { ServerAppModuleNgFactory } from './ngfactory/app/server-app.module.ngfactory';`

**Comment by AlexLubinski** [comment]
Update.

I moved some code from Asp 2017.csproj to my csproj file. That helped with Azure deployment

But error Cannot find module './ngfactory/app/server-app.module.ngfactory' remained.

**Comment by digibum** [comment]
Hm that is interesting indead.
I get
`Prerendering failed because of error: Error: Cannot find module 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\MojCuvaj_v.2\Client\dist\main-server'`

**Comment by Jewismer** [comment]
This error happened to me after I let Visual Studio 2017 auto adjust to fix dependencies after changing the name of one of the files.  I fixed this by reverting to a point prior to this auto change, and pasting in the new files I added.

**Comment by AlexLubinski** [comment]
One observation. In publish process, on error event, the visual studio shows an error list. But constantly, these are fake errors, without any useful information. Real errors are in the output panel.

**Comment by digibum** [comment]
OMG @AlexLubinski this is it. You are my saver! The problem is my code of course hehe.
This sould be mentioned in redme.

**Comment by MarkPieszak** [comment]
Apologies for the delay, yes this is very common and also an issue with Visual Studio (as VSCode doesn't display these I don't believe). That ngFactory file error can be ignored, as it's only used when building Production builds (which have their own tsconfig), everything else knows to ignore that file. Eventually Visual Studio will be better at handling these and not show people those errors.

What did we need mentioned in the README, I can add it, unless you'd like to make a PR for it? @digibum

**Comment by bencameron00** [comment]
Hi Mark

How would you get around this error when doing a production build?

**Comment by MarkPieszak** [comment]
When you're doing a production build with build:aot npm script, it'll generate the file virtually when using that main.server.aot and it will build the dist folder for you.

Is that part not working?

**Comment by bencameron00** [comment]
I have it working now, thanks for the response though :)
