### ISSUE TITLE
Problem with colapsed navigation bar (bootstrap). 

### ISSUE THREAD

**Issue by Anovi-Soft** [MarkPieszak/aspnetcore-angular2-universal#292]
I have some problems with collapsed navigation bar layout(bootstrap). 
Сollapsed bar is unvisiable.
And yours [live demo](http://aspnetcore-angular2-universal.azurewebsites.net) has the same problem.
[Screenshot](http://skrinshoter.ru/p/030617/FYVJxK)

**Comment by MarkPieszak** [comment]
Thanks for logging this one, looks like the background color isn't showing up somehow? I'll take a look

**Comment by kyse** [comment]
More than likely because it's missing bootstrap js cdn?  At least in bs4 it wants a js plugin for navbar collapse to work.

**Comment by MarkPieszak** [comment]
This should be fixed now via #372
