### ISSUE TITLE
IIS not routing direct url to specific subroute

### ISSUE THREAD

**Issue by digibum** [MarkPieszak/aspnetcore-angular2-universal#295]
I have angular route like 'home/profile'...
If user tries to load direct url to this route it is redirected to default 'home' route.

This is probably because IIS does not know anything about angular routing. How to solve this?

**Comment by MarkPieszak** [comment]
It should work fine, did you setup the Route correctly in Angular for home/profile ?
It's already setup in Startup to let the client side handle any route.
