### ISSUE TITLE
Slow HMR

### ISSUE THREAD

**Issue by ccaymaz** [MarkPieszak/aspnetcore-angular2-universal#296]
When I update html, HMR refresh my screen at least after 10 seconds.

**Comment by MarkPieszak** [comment]
This is in the works, it's just that vendor files aren't split out separately so it's rebuilding the entire thing (instead of just the app). 

Very busy ATM but want to add the vendor webpack stuff as soon as I can. Apologies

**Comment by ccaymaz** [comment]
Thank you @MarkPieszak for your detailed answer. Now make sense why it is slow.

**Comment by KangJiYoung** [comment]
Any updates on this issue? HMR is still very slow around 12 seconds.
