### ISSUE TITLE
1.0.0-rc2 'multiple modules with names that only differ in casing' Issue

### ISSUE THREAD

**Issue by danielnajera** [MarkPieszak/aspnetcore-angular2-universal#298]
I've been running into this issue while running the solution, it doesn't present a problem running or publishing.  I'm using March build of template before rc3, using new template without any modifications.

[HMR] connected  main-client.js:43013:22
%c[HMR] bundle has 2 warnings color: #999933;main-client.js:43106
./~/rxjs/Observable/throw.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Visual Studio 2017\Projects\PSMS\node_modules\rxjs\Observable\throw.js
    Used by 1 module(s), i. e.
    C:\Visual Studio 2017\Projects\PSMS\node_modules\awesome-typescript-loader\dist\entry.js?silent=true!C:\Visual Studio 2017\Projects\PSMS\node_modules\angular2-template-loader\index.js!C:\Visual Studio 2017\Projects\PSMS\Client\polyfills\rx-imports.ts
* C:\Visual Studio 2017\Projects\PSMS\node_modules\rxjs\observable\throw.js
    Used by 1 module(s), i. e.
    C:\Visual Studio 2017\Projects\PSMS\node_modules\rxjs\add\observable\throw.js
./~/rxjs/Observable/ErrorObservable.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Visual Studio 2017\Projects\PSMS\node_modules\rxjs\Observable\ErrorObservable.js
    Used by 1 module(s), i. e.
    C:\Visual Studio 2017\Projects\PSMS\node_modules\rxjs\Observable\throw.js
* C:\Visual Studio 2017\Projects\PSMS\node_modules\rxjs\observable\ErrorObservable.js
    Used by 1 module(s), i. e.
    C:\Visual Studio 2017\Projects\PSMS\node_modules\rxjs\observable\throw.js

**Comment by isaac2004** [comment]
Do you get this issue with other projects you import rxjs into? Seems like it's an issue there

**Comment by danielnajera** [comment]
Latest update to Visual Studio resolved issue.
