### ISSUE TITLE
Add ASP.NET View Template

### ISSUE THREAD

**Issue by ajayppeter** [MarkPieszak/aspnetcore-angular2-universal#30]
Hi,

Can you please add a sample on loading ASP.NET View as template, with server rendering feature

**Comment by MarkPieszak** [comment]
In Views/Home/Index.cshtml, we're loading a View there, loading in its Controller [here](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Server/Controllers/HomeController.cs#L11-L14). Or did you mean something else? This View is creating the entire Angular2 process.

**Comment by ajayppeter** [comment]
Yes, initial view loaded with root component. There after no ASP.NET views has been used, all templates are made up with .html static files. We can implement angular 2 application with ASP.NET Views giving templateUrl as path to controller. But I didn't get any reference for ASP.NET View implementation on component (using templateUrl) with angular universal. Any technical difficulties with this?

**Comment by MarkPieszak** [comment]
Yeah once the application starts, you're no longer using / need ASP.NET's views. We simply need to use it (in this case MVC) so that we can get the server-rendered portion of Angular2. 

We don't reference the ASP.NET View file or anything inside the app, you can think of it as the `index.html` you'd typically see to start up an application.

If you'd want to simultaneously have some separate sections completely .NET MVC (let's say some internal admin section or something), just make a .NET Route for them. Just remember it will be totally isolated from the angular2 application. 

Hope that makes sense?

**Comment by ajayppeter** [comment]
Yes, but when it comes to development features like master page, helpers not possible with static files. I have seen in your sample fetching data from ASP.NET server with node. I want to know is this a limitation of angular universal? Or may available in future

**Comment by MarkPieszak** [comment]
Well it does technically have a masterpage for the SPA, it's here (https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Views/Shared/_Layout.cshtml)

If you're saying you want to load a *different* ASP.NET *View* inside of the Angular2 app, then yes that's just a limitation in general, we can't load .NET things once the App has started. You could _redirect_ to an ASP.NET View, that's about it.

Everything once inside the app is its own Component, which has its own logic & template. Unfortunately, aside from loading an iFrame that in turn renders an ASP.NET View, I don't think there's much we can do at the moment.

Is there something specific you need to do that for? It might help if I understand the context better.

**Comment by ajayppeter** [comment]
How you go about a Layout switch, I have Layout 1 & Layout 2 (master pages), depends on them I'll choose which Layout to use. In some situation I have to rework on html too

**Comment by MarkPieszak** [comment]
If you need to make different style decisions based on layouts, you could also just create different Main wrapper/app Components that are rendered depending on different circumstances, let's say a different user type, client, etc.

I believe you also could make these decisions quickly on the .NET side and renders different Controller View, here we only use the Home/Index. Give it a shot!

**Comment by ajayppeter** [comment]
Thanks Mark, Let me try

**Comment by helloneoberg** [comment]
@ajayppeter Hi, are you able to achieve loading a ASP.NET View inside the angular project?
Can you share how you achieve it?
Thank you.
