### ISSUE TITLE
Webpack error / npm run build:dev

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#302]
I just downloaded the project, push F5 and when compiling webpack with the command:

`npm run build: dev`

I have this error that says nothing

![image](https://user-images.githubusercontent.com/25587867/27093182-5e797954-502b-11e7-9968-7c270069f9b1.png)

I already tried

`npm rebuild node-sass`

Y delete node_modules entirely, and reinstall everything
`npm i && npm run build: dev`

But I still get the same generic message

I hope you can help me. Thank you

**Comment by isaac2004** [comment]
I recommend installing WebPackTaskRunner in VS and Run - Development. Do you get a more detailed error?

**Comment by cristiancamiloperezlopez** [comment]
Do you have the WebPackTaskRunner link for vs 2017?
I only see these that are for vs2015

https://github.com/madskristensen/WebPackTaskRunner

https://visualstudiogallery.msdn.microsoft.com/5497fd10-b1ba-474c-8991-1438ae47012a/viewDiscussions/Reviews

**Comment by cristiancamiloperezlopez** [comment]
Or does that serve me?

![image](https://user-images.githubusercontent.com/25587867/27099862-da0d624a-5041-11e7-8e9c-f72048ca959f.png)

Thank you

**Comment by cristiancamiloperezlopez** [comment]
The error solved it well
In package.json
Change
"ng2-signalr": "^ 2.0.2"
by
"ng2-signalr": "2.0.4",

But I want to know webpack why it generates a generic error message without any hint of the problem, it would be very useful to fix the problem fast. Thanks

**Comment by MarkPieszak** [comment]
Do we need to pin ng2-signalr to 2.0.4?
It is quite strange, sometimes webpack doesn't give any information (not positive on why it does that occasionally), sometimes it helps to add a `--verbose` flag at the end of that script for npm run build:dev, maybe you'll at least see where it was when it quit so abruptly.

I'm going to try to pull down a fresh repo and see if I get the same issue.

**Comment by MarkPieszak** [comment]
I pulled down a fresh repo on Windows 10 as well, but didn't have any problems.

I did git clone then
`npm i && npm run build:dev && dotnet restore && dotnet run`

Let me know if there's anything we need to document that got this working for you that others might need! I'll close it out for now, but feel free to comment!
