### ISSUE TITLE
Replace NGX-Bootstrap with NG-Bootstrap

### ISSUE THREAD

**Issue by Adondriel** [MarkPieszak/aspnetcore-angular2-universal#304]
I was previously using NGX-bootstrap on my current app, but the repo has not been updated in ages and they have several modules that do not work the way they should. For example: The "tabs" component, if you use a *ngFor on the tabs, and then the data that it is looping over changes, it does not clear the tabs before creating new tabs, it will just keep creating new tabs. infinitely. Changing from NGX to NG-Bootstrap fixed this.

I will attempt to find a link to the ticket that I'm referencing... but they have >275 tickets in their issues list, while NG-bootstrap has <100, and most of them are just feature requests.

**Comment by kyse** [comment]
Isn't NG-Bootstrap authored by Angular-UI-bootstrap authors?  Seems like a good team.  I've had good success with NG-Bootstrap with BS 4 so far.

A little off topic, I tried PrimeNG recently, sadly, it's not very compatible with SSR.  At least the data table module wasn't.  Looking for a suggestion on a data table component library that would work with SSR so I don't have to reinvent the wheel.

**Comment by Adondriel** [comment]
Same on the BS 4 front. For datatables our team is using NGX-Bootstrap, NOT authored by Valorsoft, but some other team works on that. Sadly, it uses material design. Yea, I kinda hate PrimeNG, I don't like how they feel the need to use their own shitty style-system, that just steals all the code of bootstrap, but just doesn't look as good.

**Comment by MarkPieszak** [comment]
I love both as they're typically both great libraries, no doubt!

Another reason I initially picked ngx-bootstrap was because it supported BS3, as ng-bootstrap is only BS4. 

We could definitely make the switch you guys think it's a better idea! We could just make note that if IE9-10 support is needed then they'd have to switch to ngx.
