### ISSUE TITLE
Reload jQuery plugins

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#305]
My application is using a jquery plugin and thanks to these instructions it works partially

https://github.com/MarkPieszak/aspnetcore-angular2-universal#how-can-i-use-jquery-andor-some-jquery-plugins-with-angular-universal

When I say Partially I mean that in the initial load of the application it works fine, but if I change component by Routing the plugin stops working

The same thing happens when I use the plugin inside * ngIf, I guess since the plugin is not yet rendered, it does not take the scripts loaded in main.browser.ts

So my question is how do I reload the scripts I've included inside main.browser.ts when I've changed components or after using * ngIf

I hope you understand me

**Comment by cristiancamiloperezlopez** [comment]
@MarkPieszak  Any idea ?
Thanks

**Comment by torohima** [comment]
from https://github.com/MarkPieszak/aspnetcore-angular2-universal#how-can-i-use-jquery-andor-some-jquery-plugins-with-angular-universal

this way i use owlcaroul in my project , wrap all plugin code in a function
var myfunc =function(){
// all plugin code
}
then create your Directive, 

import 'jquery';
declare  var myfunc : any;
@Directive({
  selector: `[owlslider]`
})
export class YourDirective{
constructor(@Inject(PLATFORM_ID) private platformId: Object) {
  }
ngAfterViewInit() {
    if (isPlatformBrowser(this.platformId)) {
      $(document).ready(function () {
        myfunc();
      });
    }
  }
}
Hope this help

**Comment by isaac2004** [comment]
isPlatformBrowser solved this exact issue. Closing this
