### ISSUE TITLE
How can I get  "Zone.current.params" from both side?

### ISSUE THREAD

**Issue by seven1986** [MarkPieszak/aspnetcore-angular2-universal#308]
![image](https://user-images.githubusercontent.com/20808494/27329968-3d4aec62-55ea-11e7-8c87-f8e486ab9bdd.png)

How can I get the "host"?
if not, my code can not work on server side rendering, thanks

**Comment by MarkPieszak** [comment]
It's being passed in with `request` here:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Server/Controllers/HomeController.cs#L32

You can't get things with Zone.current the way you could with `angular2-universal` previously.

It should be within your REQUEST object that came from the server, and is automatically passed into your `main.server` file.
