### ISSUE TITLE
FAQ: can I remove "server side rendering" from csproj

### ISSUE THREAD

**Issue by MaklaCof** [MarkPieszak/aspnetcore-angular2-universal#309]
If I turn off server side rendering following official documentation, is it safe to also remove this line
`
    <Exec Command="node node_modules/webpack/bin/webpack.js --env.aot --env.server" />
`
from [csproj](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Asp2017.csproj) file.

**Comment by MarkPieszak** [comment]
I think you'd be ok, I should update it to make sure it follows VS2017 csproj standards, does everything still work with that?

**Comment by MaklaCof** [comment]
I do not know what you meant with "follows VS2017 csproj standards", but everything seems to work. I also deploy app and it works.
My deploy in VS2017 also happens a lot faster (from 8:50 to 3:40) so I think it would be good to mention in documentation how to remove server rendering.

**Comment by MarkPieszak** [comment]
Will do thanks for letting me know!
