### ISSUE TITLE
Getting error Exception: Call to Node module failed with error: reflect-metadata shim is required when using class decorators

### ISSUE THREAD

**Issue by jmaocanada** [MarkPieszak/aspnetcore-angular2-universal#31]
Just cloned to desktop and loaded the solution into VS 2015. My OS is Win10. 
Packages restored properly. Solution builds nicely.

But after I try to launch the application, the browser shows this error: "Exception: Call to Node module failed with error: reflect-metadata shim is required when using class decorators".

Any idea?

**Comment by MarkPieszak** [comment]
So it sounds like you have an older version of Node & NPM installed (npm 2 or lower).
Can you install the latest Node 7.* (https://nodejs.org/en/) ?

That should make it go away :1st_place_medal: 

Let me know!

**Comment by jmaocanada** [comment]
Thanks Mark, You are correct.
