### ISSUE TITLE
Requested Domain

### ISSUE THREAD

**Issue by darthg8r** [MarkPieszak/aspnetcore-angular2-universal#311]
I have a current app built in ASP.NET MVC.  I'm working to convert it over to Angular 4 with server side rendering.  I'm a bit hung up on a feature in the old site that enables the site to look different based on what domain is used to request it, otherwise known as a skins.  My question/problem is twofold:

1.  What's the best way to pull this off?  My thought has been to hook into main.*.ts and bootstrap a different module based what domain was used to request the app.  I'll separate the common components into their own modules and import them into the appropriate module skins.  Is there a better way to do this?  I'd like to avoid having multiple deployments of the app, one for each domain/skin.
2.  How do I get the domain that was used when server side rendering?

Thank you for input in advance.

**Comment by darthg8r** [comment]
I've come up with this so far inside of server-app.module.ts, but I suspect that this is horribly hacky.  Also, at this point, I  still don't know the domain name.  I've found that I inject the request into a Component with @Inject(REQUEST) private request, but I'm not in that context.


```
var thingToBootStrap = Skin1Component;

if (domain == "skin2.com")
  thingToBootStrap = Skin2Component;

@NgModule({
  bootstrap: [thingToBootStrap],
  imports: [
    BrowserModule.withServerTransition({
      appId: 'my-app-id' // make sure this matches with your Browser NgModule
    }),
    ServerModule,
    NoopAnimationsModule,

    ServerTransferStateModule,

    // Our Common AppModule
    AppModule
  ]
})
```

**Comment by MarkPieszak** [comment]
In main.server just grab the domain and set it to some random class static property.
Have your if logic test again the property in that class and you should be all set! Let me know.
