### ISSUE TITLE
Page layout login

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#315]
Hi Mark

Thanks for the template, I have a simple question but I have not been able to solve it myself

How can I design a component for example login, but do not share the design in app.component

```
<div class="col-sm-3">
    <nav-menu></nav-menu>
</div>
<div class="col-sm-9 body-content">
    <router-outlet></router-outlet>
</div>
```

In the login component I can not display the menu, but in the other components I have to do it

```
    <router-outlet></router-outlet>
```

Thank you

**Comment by darthg8r** [comment]
This seems more like a general purpose angular question.  You would typically do something like this using child routes.

**Comment by MarkPieszak** [comment]
Yes that or you could have some logic to hide let's say the nav-menu when the login is shown. Check out the Router guide in the angular.io docs for some tips and tricks on childRoutes as well! Hope you figure it all out!
