### ISSUE TITLE
HMR Prevents removing compiler from bundle in AOT

### ISSUE THREAD

**Issue by hheexx** [MarkPieszak/aspnetcore-angular2-universal#318]
HMR code in main.browser.ts  (lines 9-18) couses webpack to include compiler in the bundle when in AOT mode.
https://i.gyazo.com/b42010db35a79fc6a6d4d7b730655a50.png

**Comment by MarkPieszak** [comment]
When building Production mode?

**Comment by hheexx** [comment]
yes!

**Comment by MarkPieszak** [comment]
Were you using source-map-explorer after running npm run build:aot and checking the dist folder?

**Comment by hheexx** [comment]
webpack-bundle-analyzer
