### ISSUE TITLE
PWA

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#319]
Would it be straightforward to turn this into a PWA?   I am trying to wrap my head around the whole PWA process and how I can continue to use Angular and ASP.NET Core.

Thanks

**Comment by MarkPieszak** [comment]
Essentially it wouldn't be very difficult, you'd have to have your manifest and all your server-worker stuff setup, it might be a good idea to have this included sometime as part of the Repo actually!
