### ISSUE TITLE
How to setup the project to refresh the page in browser?

### ISSUE THREAD

**Issue by jdimov** [MarkPieszak/aspnetcore-angular2-universal#320]
I get the whole project and start it. It is displayed in browser but when change some content in VS2017 it doesn't update the content automatically in the browser. It is working in VS2017 when I'm using standard Angular SPA template (from dotnet --install  Microsoft.AspNetCore.SpaTemplates::*). Do you know what is the reason for that and how can setup your project to fix this issue? 

Thank you,
Yordan

**Comment by MarkPieszak** [comment]
How are you starting the project? (dotnet run, or VS2017)
It should automatically have HMR enabled as it should have ASPNETCORE_ENVIRONMENT=Development set when running from VSCode or VS. If you're using dotnet run you'll need to set ASPNETCORE_ENVIRONMENT=Development before running.
