### ISSUE TITLE
An unhandled exception occurred while processing the request

### ISSUE THREAD

**Issue by LiveLikeLastDay** [MarkPieszak/aspnetcore-angular2-universal#322]
- Git clone
- Open Asp2017.csproj in VS 2017
- Press F5 and then get following error in FireFox

> An unhandled exception occurred while processing the request.
> Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Module build failed: Error: Missing binding C:\github\aspnetcore-angular2-universal\node_modules\node-sass\vendor\win32-x64-48\binding.node
> Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x
> 
> Found bindings for the following environments:
> - Windows 64-bit with Node.js 5.x
> 
> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass --force` to build the binding for your current environment.
> at module.exports (C:\github\aspnetcore-angular2-universal\node_modules\node-sass\lib\binding.js:15:13)
> at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\node_modules\node-sass\lib\index.js:14:35)
> at Module._compile (module.js:570:32)
> at Object.Module._extensions..js (module.js:579:10)
> at Module.load (module.js:487:32)
> at tryModuleLoad (module.js:446:12)
> at Function.Module._load (module.js:438:3)
> at Module.require (module.js:497:17)
> at require (internal/module.js:20:19)
> at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\node_modules\sass-loader\lib\loader.js:3:14)
> at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:118964:7)
> at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30)
> at Object.module.exports.module.deprecate (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:126744:22)
> at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30)
> at C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:102177:22
> at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:102185:2)
> at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30)
> at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:115036:73)
> at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30)
> at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:114733:70)
> Current directory is: C:\github\aspnetcore-angular2-universal
> 
> Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
> 
>     Stack Query Cookies Headers 
> 
>     Exception: Call to Node module failed with error: Prerendering failed because of error: Error: Module build failed: Error: Missing binding C:\github\aspnetcore-angular2-universal\node_modules\node-sass\vendor\win32-x64-48\binding.node Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x Found bindings for the following environments: - Windows 64-bit with Node.js 5.x This usually happens because your environment has changed since running `npm install`. Run `npm rebuild node-sass --force` to build the binding for your current environment. at module.exports (C:\github\aspnetcore-angular2-universal\node_modules\node-sass\lib\binding.js:15:13) at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\node_modules\node-sass\lib\index.js:14:35) at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\node_modules\sass-loader\lib\loader.js:3:14) at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:118964:7) at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30) at Object.module.exports.module.deprecate (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:126744:22) at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30) at C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:102177:22 at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:102185:2) at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30) at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:115036:73) at __webpack_require__ (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:26:30) at Object.<anonymous> (C:\github\aspnetcore-angular2-universal\Client\dist\main-server.js:114733:70) Current directory is: C:\github\aspnetcore-angular2-universal
>         Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
>         System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>         System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__14.MoveNext()
>         System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>         System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
>         System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>         System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>         System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>         AspCoreServer.Controllers.HomeController+<Index>d__0.MoveNext() in HomeController.cs
> 
>                     var prerenderResult = await Prerenderer.RenderToString(
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__27.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__25.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResourceExecutedContext context)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
>     Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeAsync>d__20.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware+<Invoke>d__3.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__6.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__5.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__5.MoveNext()
>     System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>     Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()
> 
> 
>

**Comment by peterdobson** [comment]
Try npm rebuild node-sass

**Comment by MarkPieszak** [comment]
Yes thank you Peter.
Try rebuilding node-sass, then do an `npm run build:dev` to make sure everything builds properly afterwards.

**Comment by MarkPieszak** [comment]
Let me know, hopefully that fixes it up!
