### ISSUE TITLE
Getting error Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.

### ISSUE THREAD

**Issue by RemotecUK** [MarkPieszak/aspnetcore-angular2-universal#325]
Not sure what I am doing wrong. I pulled down the latest master branch and hit F5 as instructed in the documentation. The site appears and look great but HMR doesn't work.

So I tried running `npm run build:dev` as detailed in the documentation. I then get the following error in the console...

ERROR in C:/Projects/aspnetcore-angular2-universal/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.

If you could let me know what I am doing wrong that would be appreciated.

**Comment by MarkPieszak** [comment]
Did you upgrade typescript to 2.4? 
There's an error from rxjs when using typescript 2.4 since it had a breaking change.

RxJS 6 will have this fixed, but as a temporary workaround, you can use the noStrictGenericChecks compiler option.

In tsconfig.json, put it in "compilerOptions" and set it to true.

```
{
    "compilerOptions": {
        "noStrictGenericChecks": true
    }
}
```

**Comment by Bekhub** [comment]
@MarkPieszak The second error - 
` 
ERROR in /Users/Bek/Desktop/aspnetcore-angular2-universal/Client/app/shared/route.resolver.ts (7,14): Class 'ConnectionResolver' incorrectly i
mplements interface 'Resolve<SignalRConnection>'.
      Types of property 'resolve' are incompatible.
        Type '() => Promise<ISignalRConnection>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => SignalR
Connection | Observable<Sig...'.
          Type 'Promise<ISignalRConnection>' is not assignable to type 'SignalRConnection | Observable<SignalRConnection> | Promise<SignalRConnect
ion>'.
            Type 'Promise<ISignalRConnection>' is not assignable to type 'Promise<SignalRConnection>'.
              Type 'ISignalRConnection' is not assignable to type 'SignalRConnection'.
                Property '_status' is missing in type 'ISignalRConnection'.
`

**Comment by MarkPieszak** [comment]
Pinning TypeScript to "2.3.4" as there are issues with ng2-signalr, rxjs and angular itself with 2.4.
More info on this commit: I https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/a138974dfcf74ed723a4066231e6b808f112ec98

Fixed in master.
