### ISSUE TITLE
Enable Server side script debugging

### ISSUE THREAD

**Issue by davidsekar** [MarkPieszak/aspnetcore-angular2-universal#327]
I'm using transfer Http module for three webapi calls that happen on application initial load. 
The transfer state for the last call succeeds and is maintained in [Transfer_state].

But the first two webapi calls results in unexpected token error.

For debugging this issue, I tried to enable LaunchWithdebugging which resulted in error
https://github.com/aspnet/JavaScriptServices/issues/1084

Kindly a code snippet in the repo that could allow debugging the Server Side execution of scripts

**Comment by MarkPieszak** [comment]
Do these calls work normally if you disable server-side rendering for a second and just try running them in the browser? 

What exact errors come up in the Node console when these errors happen?

**Comment by davidsekar** [comment]
Yes, the client side part of the application works fine, no matter SSR is enabled or disabled.

My issue is related to following SO question:
https://stackoverflow.com/questions/43825058/vs-code-running-asp-net-spa-with-angular-4-and-using-nodeservices-options-launc

**Comment by MarkPieszak** [comment]
NodeServices is part of JavaScriptServices, Steve is the expert there. I'd assume it's a problem with higher versions of Node (7+) that might be culprit!

I'll close this out (as it's an open issue in JSServices) but i'll keep an eye out and see if that's the problem!

**Comment by davidsekar** [comment]
Just an update: Transfer-http calls were failing due to the file encoding issue.

The two JSON files had encoding as UTF8 with BOM. I changed it to just **UTF8**. 
Everything started working fine.

Thanks for your reply, indeed server side script debugging is not working with Node.js 7+.

Thanks,
David.

**Comment by davidsekar** [comment]
[https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/327](url)

**Comment by MarkPieszak** [comment]
Ahh well glad you got it settled! Cheers
