### ISSUE TITLE
HMR not connecting on fresh clone

### ISSUE THREAD

**Issue by mtmulch** [MarkPieszak/aspnetcore-angular2-universal#328]
Hello first off thanks for this awesome starter. I took a fresh clone of this last night and noticed that HMR was not connecting right off the bat. 
![no-hmr](https://user-images.githubusercontent.com/16274513/27838144-5a80378c-60ae-11e7-9f06-3e4abbfe9053.PNG)

Upon further investigation I noticed that at https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/main.server.aot.ts that  ServerAppModuleNgFactory was importing from './ngfactory/app/server-app.module.ngfactory'. 

I was able to get HMR connected by switching that Import name to match 'ServerAppModule' and changing the file path to './app/server-app.module'.
![hmr-works](https://user-images.githubusercontent.com/16274513/27838233-c83d025a-60ae-11e7-9757-764560dcc2eb.PNG)

I am by no means a webpack expert but if this is helpful to anyone checking this project out for the first time, I'd be happy to submit a pull request.

**Comment by MarkPieszak** [comment]
Thank you! I'm working on speeding up HMR speed as well, my main goal was getting AoT working a while back and have been busy, but I have a prototype working for the latest upgrades to the project.

In your case make sure you set your ASPNETCORE_ENVIRONMENT=Development

Check the readme for details on that. Make sure you return main.server.aot back to how it was, those "errors" aren't errors that's just visual studio, not realizing there are multiple tsconfigs and that one is ignored until Prod build time.

Hope that helps clear things up!

**Comment by mtmulch** [comment]
Hey thanks, for the quick reply. For whatever reason, using set through the command line wasn't working. I set the env variable in System Properties and changed everything back to how it was. Working just fine! Thanks again. Feel free to close this out.

**Comment by MarkPieszak** [comment]
Oh great, that's strange usually `set` should do the trick on Windows.
Sounds good! More updates to come shortly...
