### ISSUE TITLE
SignalR error with Interface

### ISSUE THREAD

**Issue by donstarkey** [MarkPieszak/aspnetcore-angular2-universal#331]
ConnectionResolver incorrectly implements interface 'Resolve<SignalRConnection>' types of property 'resolve' are incompatible

**Comment by MarkPieszak** [comment]
What version of typescript are you using? Make sure it's not 2.4.x there were some big breaking changes in there.

**Comment by donstarkey** [comment]
I have 2.2.3 installed.

**Comment by donstarkey** [comment]
![image](https://user-images.githubusercontent.com/16799754/27963396-934b5d64-62fa-11e7-9474-bf95b6a183a5.png)

**Comment by MarkPieszak** [comment]
I think this PR fixes it actually, they decided to rename the interface and add an `I` infront of it 😠 
https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/324/files

Can you double check and see if changing these in route.resolver.ts fixes it, I'll make sure to merge that one through! @donstarkey 

```
import { SignalR, ISignalRConnection } from 'ng2-signalr';

export class ConnectionResolver implements Resolve<ISignalRConnection> {
```

**Comment by donstarkey** [comment]
Thanks Mark that did the trick.  Frustrating when they change signatures.
