### ISSUE TITLE
More Deployment details

### ISSUE THREAD

**Issue by bencameron00** [MarkPieszak/aspnetcore-angular2-universal#332]
Hi
I have built a running app on your framework. Thank you for your work, its been very helpful.
I am a bit unsure about the deployment steps for Azure however.
I have 'dotnet publish' running cleanly.
Once this is run the client dist folder is updated.

On a clean IIS azure website what exactly needs to be deployed? Just this dist folder or the whole code base (for the .net core element)? I am manually copying to the FTP folder on Azure.

Could we please get a little more documentation?

Thank you!

**Comment by MarkPieszak** [comment]
Did it end up working? You ideally want everything that dotnet publish builds up there yes!

**Comment by bencameron00** [comment]
Yes I have it deployed but I do have something wrong still.

Maybe you could help me with a quick look please?


Check out http://tilecasev3.azurewebsites.net/TileCase


The JS version works very well but the non JS version just renders and empty page.


This did work during testing but I have changed something in the code that is stopping it from rendering. There are no errors or exceptions thrown.


Any ideas?


Thank you.

________________________________

**Comment by MarkPieszak** [comment]
It might be your base href, you have it as just `<base href="/" />`, but it looks like you're serving from a `/TitleCase` directory? Give that a shot!

**Comment by bencameron00** [comment]
I did change the routes recently. Would it be possible that could have broke it? I will give it a try shortly.

Out of interest would you like access to the code base?

This one is killing me, I'm about to start cutting code out until I can find what change broke it.

________________________________

**Comment by bencameron00** [comment]
I have it sorted now. It was an issue in one of my components. It was hard to find as there was no error messages being thrown up. Thanks for the ideas though.


By the way is there a way to stop the flick/render between the server side and client side versions in the browser?

My app uses geolocation. The server side version uses a default location (for seo) while the client side uses the clients location. This leads to different data being shown in each mode.

How would you solve this problem? I'm looking for ideas.

________________________________

**Comment by MarkPieszak** [comment]
You might just need to put some kind of CSS overlay on it potentially for the server render, and remove it when the client finishes?
Are there other http calls that aren't using HttpTransfer, because that also can cause a flicker sometimes since calls are being ran twice. Common issue with all SSR solutions unfortunately.

**Comment by MarkPieszak** [comment]
npm run build:AoT can usually help give you errors in the command line as to where those errors are coming from.

**Comment by bencameron00** [comment]
Great, I like the sound of the CSS solution. Is there an an example of this out on the web somewhere?

________________________________

**Comment by MarkPieszak** [comment]
Nothing crazy just use `[ngClass]="{ 'server-overlay': someBooleanFlag }"` and switch that boolean flag when you're truly ready to render.

Also I'm not sure if it got merged, but there's a current bug for lazy loaded routes flickering between server & client renders, not sure if that's what you're doing in this case, but that could be the issue as well :)

**Comment by bencameron00** [comment]
Cool, thanks for your help on this, I know I have lots of questions. I will try it shortly.

And the server side version will still render okay?

________________________________
