### ISSUE TITLE
CustomElements

### ISSUE THREAD

**Issue by jacobbutton** [MarkPieszak/aspnetcore-angular2-universal#333]
Has anyone had any luck integrating [CustomElements](https://github.com/webcomponents/custom-elements) into this or the [ASPNet/JavaScriptServices](https://github.com/aspnet/JavaScriptServices/tree/dev/templates/AngularSpa) project

It doesn't seem to play well with [webpack and es6](https://github.com/webcomponents/custom-elements/issues/90) but it's required for a third party software, [Clarity Design System](https://github.com/vmware/clarity), that I want to utilize in my app.

**Comment by MarkPieszak** [comment]
You shouldn't have much of a problem utilizing some Web Components with Angular in general, but, unfortunately Custom Elements cannot be server-rendered (as they only exist in the Browser-world).

Try Disabling server-side rendering, and you shouldn't have *too many* problems using them here or with JavaScriptServices. 
Just remember that you'll need quite a few polyfills to get those working in older browsers, I believe you can only shim down to IE10+, I dont think IE9 supports them even with shims (I can't remember off hand).

Sidenote, also in the works, there is an initiative to make integrating Web Components with Angular even easier and more fluid 💯 

I'd recommend taking a look at https://github.com/platosha/angular-polymer, as there's a helpful story on integrating Web Components with Angular there.

I'll close this out for now as overall Web Component support isn't something I can add to the repo, but feel free to message me on here!
