### ISSUE TITLE
Error: Can't find Python executable

### ISSUE THREAD

**Issue by ARobsonAxco** [MarkPieszak/aspnetcore-angular2-universal#334]
I get the above error when setting up the project. Firstly I get "Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 6.x" then we I try the suggested fix which is "npm rebuild node-sass --force" I get "Error: Can't find Python executable".

I guess I can fix it by installing Python but how is Python part of this project?

**Comment by MarkPieszak** [comment]
Hey @ARobsonAxco if you check your System variables, do you have ;%PYTHON%; in your `PATH`?
node-sass is used so we can do all the sass magic, which is dependent on node-gyp, which in turn is dependent on Python. 🐎 crazy I know.

Just make sure you have Python 2.7.x installed if not, and make sure you check the "Add to PATH variable" when installing it (for some reason I think it isn't checked by default).

Hope that helps!

**Comment by ARobsonAxco** [comment]
Thanks Mark, I added Python and it fixed it. So far I find that the refresh is very slow when I edit components. Also the UI often gets confused and can duplicate a component on the page or add in other content from a previous component. Are these known issues.

**Comment by MarkPieszak** [comment]
Yes definitely known issues! If you'd like, take the template down from JavaScriptServices which has the webpack config fixed for development but is a bare template, you can then merge in whatever add ons from here. Or you could just take that webpack config and use it here (just change a few names) I was actually going to do a PR this weekend and do that. 

The goal is to stay close together (at least build wise) with that repo, so that people can bounce back and forth easily.

**Comment by ARobsonAxco** [comment]
Thanks for the replies by the way.

I didn’t know the SPA Templates now included Angular 4. Having tried them again they seem do everything we need except AngularCLI integration.

The Server Side Rendering seems to work really well in the SPA Templates. As a matter of interest why is it slower in your project? Is it SignalR that is slowing it down or something else?

**Comment by MarkPieszak** [comment]
this projects goal was to first get AoT compilation working with aspnet etc, so I wasn't worried about development builds just yet, we are going to have the same build HMR speed shortly, we are merging our webpack configs. The goal is for this to be An extension of that, with many add-ons.
