### ISSUE TITLE
HMR - On hot module reload - I get duplicate entire pages showing.

### ISSUE THREAD

**Issue by pjmagee** [MarkPieszak/aspnetcore-angular2-universal#336]
I think there is a bug in the `main.browser.ts` logic somehow.

**Comment by pjmagee** [comment]
` modulePromise.then((appModule) => platformBrowserDynamic().destroy());` 

in the main.browser.ts file fixed it.

**Comment by samkan** [comment]
I'm seeing exactly the same thing. After every hot module reload I the old and the new content stack one above the other (old at the bottom). I have to refresh the page to clean up the mess.

Any suggestions?

**Comment by MarkPieszak** [comment]
Might be something that updated in a newer Angular I might need to patch the HMR for. Let me take a look

**Comment by consigliory** [comment]
+1 also have same thing

**Comment by nemad** [comment]
I had the same issue, this is what worked for me: https://github.com/aspnet/JavaScriptServices/issues/665

**Comment by samkan** [comment]
aspnet/JavaScriptServices#665 fixed my issue as well.

**Comment by MarkPieszak** [comment]
Can anyone put in a PR to fix this issue for others?

**Comment by pjmagee** [comment]
If anyone is still unclear about this. This is what my main.browser.ts looks like now with the fix:

```javascript

if (module['hot']) {
    module['hot'].accept();
    module['hot'].dispose(() => {
        modulePromise.then((appModule) => appModule.destroy());
    });

} else {
    enableProdMode();
}

```

**Comment by MarkPieszak** [comment]
It should be fixed now via https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/a83a6a9bef283c39845467457dd50358b007c6f8 changes.  @pjmagee
