### ISSUE TITLE
IE9 support 

### ISSUE THREAD

**Issue by vasyliv** [MarkPieszak/aspnetcore-angular2-universal#337]
Hello! Thanks for the repo. I tested this site in IE9 and got an error after load browser side in IE9 in navigation http://localhost:49472/home#/home#/home#/home#/home#/home#/home#/home#/home#/home#/home#/home#/home#/home#/home#/home#/home# ...
![image](https://user-images.githubusercontent.com/19407350/28381450-8d04d3fe-6cc3-11e7-8c1f-9a9a231170e8.png)

What can be the error?
Also, I added polyfills from https://angular.io/guide/browser-support

**Comment by MarkPieszak** [comment]
Did you I comment out the polyfills listed in the polfillys.ts file? That should take care of IE9 support!

**Comment by vasyliv** [comment]
Yes, I did, also added polyfills to package.json + fixed a bug with getting origin path in IE, it doesn`t help, (if comment out only polyfills from polyfills.ts routing doesn`t work, if add polyfills from https://angular.io/guide/browser-support - has the bug with navigation )

**Comment by isaac2004** [comment]
@vasyliv do you see this with the latest from master?

**Comment by alxbl** [comment]
I don't know if this may be useful, but I just ran into this issue while trying to iron out IE9 support in my project. I worked around it by going back to hash based URLs.

It looks like the issue is something to do with the html5 urls.

I'm not on latest, and I haven't tried to repro with the latest master changes.

**Comment by MarkPieszak** [comment]
Ah yes I believe you need that for ie9 regardless of framework, even he olde AngularJS requires hash location for ie9.

Can we close this one out for now? Let's reopen a new more specific one if needed.
