### ISSUE TITLE
Add 3 tire archicture

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#339]
Hi @MarkPieszak , can we add a 3 tire architecture in this project so that it can be used in big projects?

1. https://www.onlinebuff.com/article_step-by-step-3-tier-architecture-in-aspnet-using-c-example_45.html
2. http://www.aspdotnet-suresh.com/2010/05/introduction-to-3-tier-architecture-in_17.html

**Comment by pjmagee** [comment]
I'm not sure what this would benefit anyone coming into Angular. This template is more of a UI layer template on how to integrate Angular4 with .NET Core and SSR. Not about Dependency Injection, Services, Layers -> That's up to an architect who would probably know how to map out a new real world project.

**Comment by MarkPieszak** [comment]
Thanks Pj yeah I agree this would just be more of an organizational change that anyone could make on their own, especially since here we have the Rest API coupled with the project, normally we would probably want it separate / micro-services, etc. it's coupled more for examples sake.
