### ISSUE TITLE
Separate mainBrowser in parts.

### ISSUE THREAD

**Issue by borgotecnologia** [MarkPieszak/aspnetcore-angular2-universal#341]
I tried to separate mainBrowser.js in many files to have a better perform, however, How could access MVC/Views/index.cshtml to dynamize this line in chunks:

 <script src="~/dist/main-browser.js" asp-append-version="true"></script>

For exemple:

 <script src="~/dist/main-browser1.js" asp-append-version="true"></script>
 <script src="~/dist/main-browser2.js" asp-append-version="true"></script>

**Comment by markoj21** [comment]
You can use a tag helper with a wildcard, it will include all the files that match. Make sure you empty the folder as this will include all the files that match.

 <script asp-src-include="~/dist/main-browser*.js" asp-append-version="true"></script>
