### ISSUE TITLE
Using data transferred from asp.net in the Angular template

### ISSUE THREAD

**Issue by ernestbofill** [MarkPieszak/aspnetcore-angular2-universal#342]
I am getting started with angular universal. So far I managed to run the project using vs code and .NET Core.

Now I am trying to use the data passed from asp.net HomeController.cs `transferData.thisCameFromDotNET = "Hi Angular it's asp.net :)";` in an Angular component, for example to render a header with that text. How can I do that?

I can see the data is available in the file main.server.ts, but how is it retrieved form an Angular Component or Angular Template?

**Comment by MarkPieszak** [comment]
You should be able to retrieve it from the TransferState class with the .get() method on it. Check it out in the modules/ folder. Let me know !

**Comment by ernestbofill** [comment]
I tried injecting the TransferState to app.component.ts like this:
```ts
    constructor(
        private router: Router,
        private activatedRoute: ActivatedRoute,
        private title: Title,
        private meta: Meta,
        private linkService: LinkService,
        public translate: TranslateService,
        @Inject(REQUEST) private request,
        public transfeState: TransferState
    ) {
        console.log('TRANSFER STATE');
        console.log(transfeState.get('fromDotnet'));
        console.log(transfeState.get('TRANSFER_CACHE'));
    }
```

but the `transfeState.get` return empty objects. So it isn't really working at the moment.

I also tried extending the `getRequest()` method in browser-app.module.ts like this:

```ts
export function getRequest() {
  // the Request object only lives on the server
  return {
    cookie: document.cookie,
    data: (window as any).TRANSFER_CACHE
  };
```

and then the app.component.ts:
```ts
  constructor(
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private title: Title,
    private meta: Meta,
    private linkService: LinkService,
    public translate: TranslateService,
    @Inject(REQUEST) public request
  ) {
```

and finally the app.component.html: 
```html
<div class="col-sm-9 body-content">
  <h2>{{ request.data.fromDotnet }}</h2>
    <router-outlet></router-outlet>
</div>
```

This approach worked one time, but as soon as I refreshed the page it would crash with the following error:

```
fail: Microsoft.AspNetCore.NodeServices[0]
      ERROR TypeError: Cannot read property 'fromDotnet' of undefined
          at Object.eval [as updateRenderer] (ng:///AppModule/AppComponent.ngfactory.js:24:37)
          at Object.updateRenderer (C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:13026:70)
          at checkAndUpdateView (C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:12545:14)
          at callViewAction (C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:12905:21)
          at execComponentViewsAction (C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:12837:13)
          at Object.checkAndUpdateView (C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:12546:5)
          at ViewRef_.detectChanges (C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:10471:18)
          at C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:5109:63
          at Array.forEach (native)
          at ApplicationRef_.tick (C:\Projects\aspnetcore-angular2-universal-master\Client\dist\main-server.js:5109:25)
```

**Comment by ernestbofill** [comment]
Is there some documentation on how to use TransferState?

**Comment by davidsekar** [comment]
The data transferred from .Net is added to Transfer_Cache -> this is helpful for the client side app as it can access that.

but no-where the data is added to TransferState service from ngAspnetCoreEngine :(. So it is not available on the Serverside script.

Any pointer on how to achieve that ? Do I need to create a new provider ? in boot.server.ts

**Comment by davidsekar** [comment]
1) For now I have created a new injectiontoken in **baseurl.constants**
export const SERVICE_URL = new InjectionToken<string>('SERVICE_URL');

2) Added it to providers in **boot.server.ts**
import { ORIGIN_URL, SERVICE_URL } from './app/shared/constants/baseurl.constants';
providers: [
        // Optional - Any other Server providers you want to pass (remember you'll have to provide them for the Browser as well)
        {
            provide: SERVICE_URL,
            useValue: params.data.thisCameFromDotNET
        }
    ]

3) In **app.module.server.ts**, 
 export class ChartingModule {

    constructor(private transferState: TransferState,
        @Inject(SERVICE_URL) private serviceUrl: string
    ) {
        transferState.set('fromDotnet', serviceUrl);
        console.log("my test");
        console.log(transferState);
    }

  // Gotcha (needs to be an arrow function)
  ngOnBootstrap = () => {
    this.transferState.inject();
  }
}

4) Above will enable you to inject TransferState & use it on all component/services etc., alike in both client and server side.

**Comment by davidsekar** [comment]
@MarkPieszak This issue requires HOW TO GUIDE

**Comment by MarkPieszak** [comment]
Definitely, also there are cleaner ways we could do all of this as well.

**Comment by davidsekar** [comment]
@MarkPieszak Thanks for picking up this task.

I know there are cleaner way to handle passing that data within **temporary-aspnetcore-engine**, but I didn't want to touch that file as it was name 'temporary' :) ...

**Comment by MarkPieszak** [comment]
You could post any ideas you have here, or make a PR as well, we can move it to the offficla nguniversal package after we test it out! @davidsekar

**Comment by Crazyht** [comment]
Hi, in my project I do something like : 
- in boot.server.ts : 
```
const setupOptions: IEngineOptions = {
    appSelector: '<app></app>',
    ngModule: ServerAppModule,
    request: params,
    providers: [
        { provide: SERVERPARAMS, useValue: params.data }
      // Optional - Any other Server providers you want to pass (remember you'll have to provide them for the Browser as well)
    ]
  };
```
in app.module.browser.ts : 
```
export function getServerParameters() {
  return window['TRANSFER_CACHE'];
}
```
and : 
```
providers: [
        {
            // We need this for our Http calls since they'll be using an ORIGIN_URL provided in main.server
            // (Also remember the Server requires Absolute URLs)
            provide: ORIGIN_URL,
            useFactory: (getOriginUrl)
        }, {
            // The server provides these in main.server
            provide: REQUEST,
            useFactory: (getRequest)
        }, {
            provide: SERVERPARAMS,
            useFactory: (getServerParameters)
        }
    ]
```

SERVERPARAMS is simply InjectionToken declare in other ts. After I came inject SERVERPARAMS where I need

I hope this help.
