### ISSUE TITLE
Error when debugging in Visual Studio 2017 for Mac

### ISSUE THREAD

**Issue by shima20** [MarkPieszak/aspnetcore-angular2-universal#344]
Does this solution work in Visual Studio Community 2017 for Mac?  I receive the error ```error CS0119: 'WebHostBuilder' is a type, which is not valid in the given context``` when trying to Debug the project.

**Comment by MarkPieszak** [comment]
Do you have all the necessary installs for dotnet on mac as well?
https://www.microsoft.com/net/core#macos

**Comment by shima20** [comment]
I believe so.  It's odd because I have another project that works fine.  I can try and reinstall again.

**Comment by shima20** [comment]
Just tried again and still the same error.

**Comment by Miesvanderlippe** [comment]
Have you ran the command from the readme.md yet?
CD into the project dir and run the following: 
npm install && npm run build:dev && dotnet restore

Project is running fine in the same setup on my Mac.

**Comment by shima20** [comment]
Thanks @Miesvanderlippe .  ```npm install``` looks like it did it.
