### ISSUE TITLE
Question: Azure and WEBSITE_NODE_DEFAULT_VERSION

### ISSUE THREAD

**Issue by NelsonLamprecht** [MarkPieszak/aspnetcore-angular2-universal#348]
So, I was able to deploy this quite easily to azure once I got the build and publish working in visual studio online. The only piece I am not happy with (since it requires a configuration on the webapp) is setting the WEBSITE_NODE_DEFAULT_VERSION in the azure web app. I've read a bit about the iisnode.yml and specifying the server script but unless I set the WEBSITE_NODE_DEFAULT_VERSION to the version on the box, which is 8.1.4, the azure app fails to start. Has anyone gotten a fully setup automated deployment to Azure without having to set the WEBSITE_NODE_DEFAULT_VERSION or some other way ?
(Package json start up script?)

**Comment by MarkPieszak** [comment]
You should be able to do it with the package.json if I'm not mistaken?

    "engines":{ "node": "8.1.4" }

**Comment by NelsonLamprecht** [comment]
that did not seem to have any effect..
I even tried something to do with an iisnode.yml file I found reference to but nothing yet..
Let me know if you (or anyone else) gets around to trying it...

**Comment by isaac2004** [comment]
@NelsonLamprecht I imagine none of the options here worked for you?

https://docs.microsoft.com/en-us/azure/nodejs-specify-node-version-azure-apps

**Comment by isaac2004** [comment]
@NelsonLamprecht closing this, please reopen if you are still having issues
