### ISSUE TITLE
API call returns nothing in SSR

### ISSUE THREAD

**Issue by vfportero** [MarkPieszak/aspnetcore-angular2-universal#349]
Hi Mark!

I'm having problems with the SSR when making an api call to MVC API.

In browser, the API call works fine but when i check the code (CTRL+U) the item list that should be rendered doesn't exists.

The SSR doesn't fails but the api is not called, any idea?

Thanks

**Comment by MarkPieszak** [comment]
It's hard to tell without any code, are there no errors happening in the Output window (or command line / however you're running the project) ?

If you do a console.log of your data is it actually returning something?

**Comment by vfportero** [comment]
You're right! The log give me the key!!!

fail: Microsoft.AspNetCore.NodeServices[0]
      ERROR Error: URLs requested via Http on the server must be absolute. URL: api/games/?page=1&limit=9

Solved using the ORIGIN_URL from './constants/baseurl.constants';

Thanks for the quick response :)

**Comment by MarkPieszak** [comment]
No problem, figured it might be based on a relative path during a server render! 👍
