### ISSUE TITLE
Translation does not work because request is not sent from C# controller to Angular

### ISSUE THREAD

**Issue by dobrinsky** [MarkPieszak/aspnetcore-angular2-universal#350]
Hi, 

I am really struggling for a week now and I do not know what I am doing wrong. I am trying to combine your template with one of mine. I managed to get it done and make the app start with no errors, but the translation does not work.

In the html I get only the json tokens, but not what is in the json files(e.g. HOME_FEATURE_LIST_TITLE, not "What does this Starter offer?").

The problem is that I get "cannot read property "request" of null" in temporary-aspnetcore-engine.ts for 

{
            provide: REQUEST,
            useValue: options.request.data.request
}

I really don't know what I am doing wrong. Can you please help me?

My project is here https://github.com/dobrinsky/AngularDefault

**Comment by isaac2004** [comment]
@dobrinsky have you tried since #376 was merged?

**Comment by dobrinsky** [comment]
Hi,

I have given up on this. I was too deep into problems. I deleted the project, created it again with . NET Core 2 and Angular 4.3.6.

I also had problems with it:

https://github.com/ngx-translate/core/issues/649

But with the help of @icehowler I managed to solve it.

My project can be found here:

https://github.com/dobrinsky/AngularDefault

Hope this helps others.

**Comment by isaac2004** [comment]
@dobrinsky thanks for the link, I am going to close this issue
