### ISSUE TITLE
Question: Building via VS2017

### ISSUE THREAD

**Issue by albrookesplowman** [MarkPieszak/aspnetcore-angular2-universal#351]
Hi,

I have just downloaded this template and built it via VS2017.  One question is whether I need to run NPM from the command line or can I configure VS2017 to do it all?

I.e. debug mode in VS2017 does the debug build of everything and then changing to release mode changes it all to AOT  compilation.  Therefore, controlling everything from inside VS2017 and F5 rather than a command line window as well.

Or am I missing something?

Al

**Comment by peterdobson** [comment]
You should just be able to run via F5 in VS2017 as-is

**Comment by MarkPieszak** [comment]
It should be setup to create the prod builds when you Publish or do a deploy to Azure, so I don't think you'll have to touch command line at all. Let me know if you have any issues there!
