### ISSUE TITLE
[question]:  Redux State Store

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#352]
Hello,
When you say adding Redux state store, are you referring to NGRX/store?

Just wanting to get on the same page with what that feature will be as I was planning to add NGRX store to my project but open to others.

Thanks

**Comment by MarkPieszak** [comment]
Hey @jrmcdona you can see an implementation of NgRx we had here: https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/259

Hope that helps!

**Comment by jrmcdona** [comment]
thanks!
