### ISSUE TITLE
.NET Core Debugger extension for VS Code

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#353]
When I search for .NET Core Debugger in the extensions I am not seeing exactly which extension to use.  Can you provide a link to it?

Visual Studio Code
Note: Make sure you have the C# extension & .NET Core Debugger installed.

Thanks

**Comment by jrmcdona** [comment]
Ah I think is it the Chrome debugger.

https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome

**Comment by MarkPieszak** [comment]
Make sure you have all of these extensions installed as well.
https://johnpapa.net/essential-angular-vs-code-extensions/

But yes you need the C# dotnet core debugger installed as well to debug C#

**Comment by jrmcdona** [comment]
THANKS
