### ISSUE TITLE
[question]: LinkService, HeadService, ScriptService

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#354]
Hello,
So at our company we have many sites and they all use the same Header and Footer, so we have to use a common service endpoint to get <link> and <script> references and into the <head> tag in layout.cshtml.

In the past, in an older AngularJS project we just made the service call to get Header details in HomeController,then populated a model and bound that model to the layout.cshtml.  Very standard stuff.  More or less like the below.

Now we are moving from AngularJs to Angular Universal and have the same requirements for Header/Footer.   Should I not stick with this same approach?

Should I instead create a ScriptService like you did with the link service?   

```
@model Ambassadors.Web.ViewModels.BaseViewModel

<!DOCTYPE html>
<html ng-app="ambassadors" ng-strict-di>

<head>
    @Model.Shell.CssIncludes
    @Model.Shell.JavaScriptIncludes
</head>

<body>
@Model.Shell.HeaderHtml

 <div class="section" id="features">
            <div ui-view="main" class="body-background" ng-cloak></div>
            @RenderBody()

        </div>

@Model.Shell.FooterHtml

</body>
```

simplifed version of the view model that get passed to layout.cshtml

```
var viewModel = new HomeViewModel()
            {
                Shell = shell,
            };

return View(viewModel);
```

Is this the old fashioned non -universal way of doing things?
I figured I might ask before I try!

**Comment by MarkPieszak** [comment]
If these things are totally separate and outside of the angular app itself I don't see anything wrong with it! Especially since they'll be server rendered by dotnet anyway, so everything is still working as it should 👍

**Comment by jrmcdona** [comment]
YEP, works!
