### ISSUE TITLE
Meta and Title not being populated server side

### ISSUE THREAD

**Issue by isaac2004** [MarkPieszak/aspnetcore-angular2-universal#356]
I modified the process in app.component.ts to dynamically get info from the route to build meta tags and update the title, however it doesn't seem to be rendering server side. Here is what I am doing.

````
  let title = '';
        let metaData = event[0]['meta'] || [];


        if (event[0]['post']) {
            title = `${event[0]['post'].title} - ${this.endPageTitle} `;
        } else if (event[1].join('/').toLowerCase().indexOf('category') > -1) {
            let category = event[1][1].path;           
            title = `${category} - ${this.endPageTitle} `;
            metaData.push({ name: 'og:title', content: category });
            metaData.push({ name: 'og:description', content: category });
        } else if (event[1].join('/').toLowerCase().indexOf('tag') > -1) {
            let tag = event[1][1].path;
            title = `${tag} - ${this.endPageTitle} `;
            metaData.push({ name: 'og:title', content: tag });
            metaData.push({ name: 'og:description', content: tag });
        } else {
            title = event[0]['title']
                ? `${event[0]['title'].charAt(0).toUpperCase() + event[0]['title'].slice(1).toLowerCase()} - ${this.endPageTitle}`
                : `${this.endPageTitle}`;
        }

        this.title.setTitle(title);

        // get route related meta
        metaData.push({ name: 'og:url', content: `${this.getBaseUrl()}` });

        if (event[0]['post']) {
            metaData.push({ name: 'og:description', content: event[0]['post'].description });
            metaData.push({ name: 'og:title', content: event[0]['post'].title });
            metaData.push({ name: 'og:type', content: 'article' });
            metaData.push({ name: 'article:published_time', content: event[0]['post'].postedOn });
            metaData.push({ name: 'og:updated_time', content: event[0]['post'].modifiedOn });
            metaData.push({ name: 'article:section', content: event[0]['post'].category.name });
        }

        const linksData = event[0]['links'] || [];

        for (let i = 0; i < metaData.length; i++) {
            this.meta.updateTag(metaData[i]);
        }

        for (let i = 0; i < linksData.length; i++) {
            this.linkService.addTag(linksData[i]);
        }

````
So I am looking for data in the event (this is returned from a Service Resolver) and build the meta tags and title. When I inspect the page it looks good, but View Source shows them missing. Is this something I can do, or do I have to have static data in the meta and title?

**Comment by MarkPieszak** [comment]
Trying to look through the code it seems like everything is ok?
Is this change coming from a child route or something perhaps, I believe the same code is looking for mainly top level routes, but you can always update that to make sure this works for child routes as well. Just a hunch.  Let me know any other info you have so I can take a look!

**Comment by isaac2004** [comment]
It may be more complicated, it seems view source doesn't show the page content at all, so no SSR. Is there a gotcha to SSR that could have been missed. Here is the repo that has this issue.

http://github.com/isaac2004/LevinBlog

**Comment by MarkPieszak** [comment]
Is there an error showing up in the node output? It looks like ssr is failing somehow so you're only seeing the client side rendering happen.

That's strange though it should give you an error screen and never actually render anything. Is ssr disabled somehow?

**Comment by isaac2004** [comment]
How could it be disabled. I moved some services and created a core and shared module but I get no errors at all. The site even runs.

http://isaaclevin.com

**Comment by isaac2004** [comment]
Issue is fixed, was using some browser only things which were breaking SSR

**Comment by cbhatt** [comment]
@isaac2004 I have migrated my project to use this repo. I am facing similar issue, i have cross checked that window, browser, navigator code is in isPlatformBrowser block. I had doubt on few directives so i checked them by adding them to example app of this repo and it worked well.  So i am struggling to find out cause which is breaking SSR.

  Can you guide a little bit what could be causing this issue?

**Comment by isaac2004** [comment]
@cbhatt, what is the issue you are getting, meta tags and title are not being updated?

**Comment by cbhatt** [comment]
@isaac2004 
Thanks for quick reply.
Meta tags, title not being updated so i verified view source to check if SSR is working. View source is showing home page always so it seems SSR is breaking and app is running client side completely.

**Comment by isaac2004** [comment]
Do you have a repo? All my code for my public site (that has this working) is at https://github.com/isaac2004/LevinBlog

**Comment by cbhatt** [comment]
I do not have rights to share repo, i will check that and get back to you.
Meanwhile i will check your site and try to find out cause of this.
Thanks a lot for sharing your repo.

**Comment by isaac2004** [comment]
What I meant by repo was the code in your app.component.ts

**Comment by cbhatt** [comment]
Here is the code of app component, i have not changed this much after cloning from this repo.

`export class AppComponent implements OnInit, OnDestroy {  
  
  private endPageTitle: string = 'Angular Universal and ASP.NET Core Starter';
  
  private defaultPageTitle: string = 'My App';

  private routerSub$: Subscription;

  constructor(
    public store: Store<fromRoot.AppState>,
    private router: Router,
    private activatedRoute: ActivatedRoute,
    private title: Title,
    private meta: Meta,
    private linkService: LinkService,
    public translate: TranslateService,
    @Inject(REQUEST) private request
  ) {
   
  }

  ngOnInit() {    
    this._changeTitleOnNavigation();    
  }

  ngOnDestroy() {    
    this.routerSub$.unsubscribe();
    
  }

  private _changeTitleOnNavigation() {

    this.routerSub$ = this.router.events
      .filter(event => event instanceof NavigationEnd)
      .map(() => this.activatedRoute)
      .map(route => {
        while (route.firstChild) route = route.firstChild;
        return route;
      })
      .filter(route => route.outlet === 'primary')
      .mergeMap(route => route.data)
      .subscribe((event) => {
        this._setMetaAndLinks(event);
      });
  }

  private _setMetaAndLinks(event) {

    // Set Title if available, otherwise leave the default Title
    const title = event['title']
      ? `${event['title']} - ${this.endPageTitle}`
      : `${this.defaultPageTitle} - ${this.endPageTitle}`;

    this.title.setTitle(title);

    const metaData = event['meta'] || [];
    const linksData = event['links'] || [];

    for (let i = 0; i < metaData.length; i++) {
      this.meta.updateTag(metaData[i]);
    }

    for (let i = 0; i < linksData.length; i++) {
      this.linkService.addTag(linksData[i]);
    }
  }
}`

**Comment by cbhatt** [comment]
@isaac2004 Did you get chance to look into app.component ?

**Comment by isaac2004** [comment]
@cbhatt tbh I am not going to have a ton of time to look into your issue. I did a fresh pull and it worked for me. Are you able to get a fresh pull without your changes working?
