### ISSUE TITLE
[Question] : Skins Application

### ISSUE THREAD

**Issue by ProfDan** [MarkPieszak/aspnetcore-angular2-universal#358]
This is a fantastic piece of code. I found it when I was googling problems from another template that I used. I am having a difficult time figuring out how the skins and style are applied in this design. I see the calls to the skins in the wwwroot when I'm looking in the logs. I just don't see where the calls to the skins are being made in code. Any help would be greatly appreciated.

**Comment by MarkPieszak** [comment]
So there's bootstrap sass being used, so you could completely theme the site in anyway you want using the bootstrap variables and simply overriding them (or even picking some sass themed options online and changing it from there). Thanks for the kind words 🙏
