### ISSUE TITLE
[proposal] Make architecture picture a bit cleaner

### ISSUE THREAD

**Issue by OEvgeny** [MarkPieszak/aspnetcore-angular2-universal#36]
The subject of my proposal is [this picture](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/architecture.png) (browser block).

For me it was very easy to understand how universal is working except html hydration part. As described in [docs](https://github.com/angular/universal/blob/master/DOCUMENTATION.md#-how-does-it-work) Angular Universal does not support full hydration from html. The word "hydration" does not appear in the docs at all. Also preboot's repo [readme](https://github.com/angular/preboot#preboot) separates hydration from simple re-rendering which universal uses.

As far as I know for now universal supports only [object catching](https://github.com/angular/universal/blob/master/DOCUMENTATION.md#-what-about-caching).

I think it would be better to replace word "Hydrate" with another one which suits better for case described above.

What are your thoughts on this?

**Comment by MarkPieszak** [comment]
Hey there @OEvgeny 

You're totally right I need to clear up some wording & make things more specific!
In our case we (at least not currently) are replacing the DOM completely with the client-rendered one when it finishes bootstrapping.

I'll fix something up today and get a better one in there so it doesn't cause any confusion. Thanks for pointing that out, forgot I meant to update this, just threw something together really quickly before.

**Comment by MarkPieszak** [comment]
Closed via https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/a808990abbffcd50bd0b7a96689bbf6bff05a2ec hope that helps so that it all makes more sense! Thanks for pointing those things out again :+1:  Appreciate it

**Comment by OEvgeny** [comment]
@MarkPieszak Thanks very mach. Looks nice!
