### ISSUE TITLE
question: nav-menu across top instead of on left?

### ISSUE THREAD

**Issue by albrookesplowman** [MarkPieszak/aspnetcore-angular2-universal#361]
Hi,

Is it possible to explain how to make the nav-menu appear across the top instead of down the left?  I am trying to setup a horizontal menu bar across the top (similar to https://www.bootply.com/PRnQbVMjaK) so that it can change colour from transparent on carassel to white as the user scrolls down the parallax page.  On other pages, when there is no carassel, it should just be white.

I have tried to change the html of the nav-menu component but what ever I seem to do breaks the pages and it no longer appears on an F5.

Do you have any pointers on how to configure this top menu?

Alan

**Comment by isaac2004** [comment]
If you just want horizontal nav, take look at my repo which is a fork of this. The repo is what isaaclevin.com runs on

http://github.com/isaac2004/LevinBlog

**Comment by albrookesplowman** [comment]
Hi Isaac,

Thanks for the info.  I have also started following an article about creating the navbar menu:

https://medium.com/@ct7/the-simple-way-to-make-a-mobile-angular-2-bootstrap-navbar-without-jquery-d6b3f67b037b

And it seems to be working, however the menu appears initially OK but then changes back to the original left menu options, even though I have commented it out from the nav-menu.component html file.  

I am assuming that this has something to do with the switch from server side rendering over to the Angular client side rendering.

**Comment by isaac2004** [comment]
Most likely... When you are running the app, and you save a file in the client folder, do you get a message in the console window or that HMR is loaded?

**Comment by albrookesplowman** [comment]
after some investigation, the switch happens when the url goes from localhost:xxxx to locahost:xxxx/home.  I also seem to get a lot of 500 errors after I have done a rebuild via VS2017... and all I have done is change the navmenu.component.html file....

<div class="main-nav">
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type='button' class='navbar-toggle' data-toggle='collapse' data-target='.navbar-collapse'>
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <a class="navbar-brand">Project Manager</a>
      </div>

      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><a>Link 1</a></li>
          <li><a>Link 2</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>

**Comment by isaac2004** [comment]
You are getting 500 errors saying what? If you are just switching routes it shouldn't be a problem. It sounds like you have a cached version of that component and it isn't serving the new version for the home route

**Comment by albrookesplowman** [comment]
got round the 500 errors.... i had the environment set at production so changed it back to development and did the npm run build:dev trick and that seems to have cured that problem.

Just have to fix the cache problem now as when I change the html file and then press F5, it still shows the old version.

Thanks for all the help so far... :)

**Comment by isaac2004** [comment]
If you save any file while running does it kicks off a webpack build?

**Comment by albrookesplowman** [comment]
core.es5.js:2933 Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///AlertModule/AlertComponent.html@1:0
Console.warn @ core.es5.js:2933
app.component.ts:42 What's our REQUEST Object look like?
app.component.ts:43 The Request object only really exists on the Server, but on the Browser we can at least see Cookies
app.component.ts:44 Object
core.es5.js:2925 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
client.js:67 [HMR] connected
client.js:207 [HMR] bundle rebuilt in 35320ms
process-update.js:27 [HMR] Checking for updates on the server...
dist/ba1f472c23a2401e832b.hot-update.json Failed to load resource: the server responded with a status of 404 (Not Found)
process-update.js:37 [HMR] Cannot find update (Full reload needed)
cb @ process-update.js:37
process-update.js:38 [HMR] (Probably because of restarting the server)
cb @ process-update.js:38
client.js:199 [HMR] bundle rebuilding
client.js:207 [HMR] bundle rebuilt in 351ms
process-update.js:27 [HMR] Checking for updates on the server...
dist/ba1f472c23a2401e832b.hot-update.json Failed to load resource: the server responded with a status of 404 (Not Found)
process-update.js:37 [HMR] Cannot find update (Full reload needed)
cb @ process-update.js:37
process-update.js:38 [HMR] (Probably because of restarting the server)
cb @ process-update.js:38
client.js:199 [HMR] bundle rebuilding
client.js:207 [HMR] bundle rebuilt in 1327ms
process-update.js:27 [HMR] Checking for updates on the server...
zone.js:2622 GET http://localhost:24879/dist/ba1f472c23a2401e832b.hot-update.json 404 (Not Found)
scheduleTask @ zone.js:2622
ZoneDelegate.scheduleTask @ zone.js:410
Zone.scheduleTask @ zone.js:235
Zone.scheduleMacroTask @ zone.js:258
(anonymous) @ zone.js:2646
proto.(anonymous function) @ zone.js:1227
(anonymous) @ bootstrap 1baec931b40df177cec0:53
ZoneAwarePromise @ zone.js:847
hotDownloadManifest @ bootstrap 1baec931b40df177cec0:45
hotCheck @ bootstrap 1baec931b40df177cec0:246
check @ process-update.js:64
module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:37 [HMR] Cannot find update (Full reload needed)
cb @ process-update.js:37
(anonymous) @ process-update.js:68
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:141
(anonymous) @ zone.js:831
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:595
ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1370
globalZoneAwareCallback @ zone.js:1388
process-update.js:38 [HMR] (Probably because of restarting the server)
cb @ process-update.js:38
(anonymous) @ process-update.js:68
ZoneDelegate.invoke @ zone.js:391
Zone.run @ zone.js:141
(anonymous) @ zone.js:831
ZoneDelegate.invokeTask @ zone.js:424
Zone.runTask @ zone.js:191
drainMicroTaskQueue @ zone.js:595
ZoneTask.invokeTask @ zone.js:502
invokeTask @ zone.js:1370
globalZoneAwareCallback @ zone.js:1388

**Comment by albrookesplowman** [comment]
it seem to be doing a rebuild of something

**Comment by isaac2004** [comment]
Try a force cache clear in Chrome

**Comment by albrookesplowman** [comment]
that seems to work - thanks... Do you know any reason why this html wouldn't show buttons on the navbar?  I have followed the bootstrap example but i get the links as a right aligned drop down rather than right aligned buttons:

```
<div class="main-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type='button' class='navbar-toggle collapsed' (click)="toggleState()">
          <span class='sr-only'>Toggle navigation</span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
          <span class='icon-bar'></span>
        </button>
        <a class="navbar-brand">Brand</a>
      </div>

      <div class="navbar-collapse collapse" [ngClass]="{'in': isIn}">
        <ul class="nav navbar-nav navbar-right">
          <li><a>Link 1</a></li>
          <li><a>Link 2</a></li>
          <li><a>Link 3</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
```

The CSS is:

```
.navbar-default {
  background-color: transparent;
  border-color: transparent;
  margin-bottom: 0px;
  position: fixed;
  width: 100%;
  border-radius: 0px;
  z-index: 10007;
}

.page-scroll-header{
  background-color: #ccc !important;
  opacity:0.9;
}

@media (min-width: 768px) {
    /* On small screens, convert the nav menu to a vertical sidebar */
    .main-nav {
        height: 100%;
        width: calc(25% - 20px);
    }
    .navbar {
        border-radius: 0px;
        border-width: 0px;
        height: 100%;
    }
    .navbar-header {
        float: none;
    }
    .navbar-collapse {
        border-top: 1px solid #444;
        padding: 0px;
    }
    .navbar ul {
        float: none;
    }
    .navbar li {
        float: none;
        font-size: 15px;
        margin: 6px;
    }
    .navbar li a {
        padding: 10px 16px;
        border-radius: 4px;
    }
    .navbar a {
        /* If a menu item's text is too long, truncate it */
        width: 100%;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }
}
```

It is probably so simple but I can't see it... ;)

Many thanks, Al
