### ISSUE TITLE
HTML content of page doesn't rendered From Server Side 

### ISSUE THREAD

**Issue by alaatek** [MarkPieszak/aspnetcore-angular2-universal#362]
I have a project which depends on the old branch of this repository, for some reason I the content of HTML doesnt rendered from the server side and the view that is displayed is rendered from client side.

the Code of Index Action In Home Controller

`public async Task<IActionResult> Index()
        {
            var nodeServices = Request.HttpContext.RequestServices.GetRequiredService<INodeServices>();
            var hostEnv = Request.HttpContext.RequestServices.GetRequiredService<IHostingEnvironment>();

            var applicationBasePath = hostEnv.ContentRootPath;
            var requestFeature = Request.HttpContext.Features.Get<IHttpRequestFeature>();
            var unencodedPathAndQuery = requestFeature.RawTarget;
            var unencodedAbsoluteUrl = $"{Request.Scheme}://{Request.Host}{unencodedPathAndQuery}";

            var lang = RouteData.Values["language"].ToString();

            var pageUrl = unencodedPathAndQuery;//.Replace("/" + lang, "");
            if (pageUrl.Contains("/home")) pageUrl = "/home";
            if (pageUrl.Contains("/loads")) pageUrl = "/loads";
            if (pageUrl.Contains("/loadSearch")) pageUrl = "/loadSearch";
            if (pageUrl.Contains("/loadview")) pageUrl = "/loadview";

            var tmp_lang = lang;
            //ViewData["metas"] = metas;
            ViewData["address"] = tmp_lang;

            if (lang == "none") return Redirect(tmp_lang + "/home");
            return View();
        }`

When I view the source of page rendered it just render the root of app as the following image
https://drive.google.com/file/d/0B0pA_7Doysx2VU54ZmlFSkdUQVE/view?usp=sharing

any ideas would be appreciated :)

**Comment by isaac2004** [comment]
It probably is related to you doing something browser dependent and not wrapping in isPlatformBrowser(). How much different are your .TS files to the latest pull?

**Comment by isaac2004** [comment]
Did this work for you? If not you can reopen. Closing for now
