### ISSUE TITLE
using HttpOnly Cookies on Server-side

### ISSUE THREAD

**Issue by timiles** [MarkPieszak/aspnetcore-angular2-universal#364]
Hi, I've run into a problem with my app based on your code, and I'm wondering if you can help me figure it out?

I want the node pre-render to take on all of the cookies from the request, including HttpOnly cookies.  Is this possible?  I'm using the transfer-http get method, providing `{ withCredentials: true }`, but the response is coming back unauthorized.  I've had some luck with methods that work for non-HttpOnly cookies, but can't jump that hurdle to include HttpOnly.

I've followed countless discussions in issues on both here and in the angular repo, but comments that looked promising either didn't work for me, or led to dead links!

Do you know if this should be possible?

Thanks,
Tim

**Comment by isaac2004** [comment]
@timiles do you have some code? I can take a look at what you are doing and see if I can put something together

**Comment by isaac2004** [comment]
@timiles closing this, please re-open if you want to discuss

**Comment by timiles** [comment]
Sorry @isaac2004, it's been hectic.  We might run into this again in the next few weeks, I'll have another go then. Thanks!
