### ISSUE TITLE
versioning for lazy loaded files

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#367]
angular 2 naming lazy loaded components as 0.js 1.js ect. entry point have version prepended but all lazy loaded components remains same as before which results in the inconsistent version of the code in the browser (main.js is new and 0.js browser uses old file). How do you solve this issue?

**Comment by MaklaCof** [comment]
Check [this](https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/287) thread.
