### ISSUE TITLE
Update To Asp.Net Core 2.0

### ISSUE THREAD

**Issue by ElderJames** [MarkPieszak/aspnetcore-angular2-universal#369]
Asp.Net Core 2.0 had been Announced!

**Comment by isaac2004** [comment]
I have a fork of this running on 2.0, I will try to do a PR of that and Angular 4.3.4 in a few days.

**Comment by OceansideBill** [comment]
For those that upgraded to the new VS 2017 (15.3) and .NET Core 2.0 a few tips...
If your project is failing to load with an error: 'Microsoft.NET.Sdk.Web' specified could not be found.  This is probably related to the Global.json file within the project.  Within it you'll find a reference to sdk version: 1.0.0 - this is the cause.  I modified mine to 2.0.0 and the load problem was resolved.  Note I also updated my csproj file based on the information posted here: https://docs.microsoft.com/en-us/aspnet/core/migration/1x-to-2x/

**Comment by OceansideBill** [comment]
One more note, on attempting to run you may get a compile error within HomeController.cs.  It appears the signature for the Prerenderer.RenderToString method has changed.  It has a new 3rd parameter which is a cancel token.  To create a cancel token I added the following two lines prior to this call following the creation of the transferData structure.

      System.Threading.CancellationTokenSource cancelSource = new System.Threading.CancellationTokenSource();
      System.Threading.CancellationToken cancelToken = cancelSource.Token;

Then I'm modified the parameter list to include the new cancel token in the Render to string call:
      var prerenderResult = await Prerenderer.RenderToString(
                "/",
                nodeServices,
                cancelToken,
                new JavaScriptModuleExport(applicationBasePath + "/Client/dist/main-server"),
...

This seems to make the project operational.

**Comment by ElderJames** [comment]
@OceansideBill Year,it work!

And I think this project can upgrade to Angular 5.x and there some warning while building the client app:

```bash
Warning: Can't resolve all parameters for SignalR in C:/Users/Administrator/Source/Repos/aspnetcore-angular2-universal/node_modules/ng2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
Warning: Can't resolve all parameters for SignalR in C:/Users/Administrator/Source/Repos/aspnetcore-angular2-universal/node_modules/ng2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("
[WARNING ->]<template [ngIf]="!isClosed">
  <div [class]="'alert alert-' + type" role="alert" [ngClass]="classes""): ng:///C:/Users/Administrator/Source/Repos/aspnetcore-angular2-universal/node_modules/ngx-bootstrap/alert/alert.component.d.ts.AlertComponent.html@1:0
```

**Comment by isaac2004** [comment]
there is a pr #371 for this

**Comment by MarkPieszak** [comment]
Done! 👍 🍺  Thanks again @isaac2004

**Comment by isaac2004** [comment]
@MarkPieszak no worries, did you want a PR for JWT like we talked about?

**Comment by MarkPieszak** [comment]
One second, I'm about to push up the updated webpack stuff (that syncs us with JSServices)
