### ISSUE TITLE
I have some issues with tslint

### ISSUE THREAD

**Issue by nigul2009** [MarkPieszak/aspnetcore-angular2-universal#37]
Hi,

I have a some issues with tslint:

The Log after run lint script:

 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'lint' ]
2 info using npm@4.0.5
3 info using node@v7.4.0
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle aspnetcore-angular2-universal-starter@~prelint: aspnetcore-angular2-universal-starter@
6 silly lifecycle aspnetcore-angular2-universal-starter@~prelint: no script for prelint, continuing
7 info lifecycle aspnetcore-angular2-universal-starter@~lint: aspnetcore-angular2-universal-starter@
8 verbose lifecycle aspnetcore-angular2-universal-starter@~lint: unsafe-perm in lifecycle true
9 verbose lifecycle aspnetcore-angular2-universal-starter@~lint: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\PROJECTS\ARTYCO\CRM\Presentation\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\NativeBinaries\x86;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\;C:\NugetCLI\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\jgarcia.perez\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\jgarcia.perez\AppData\Roaming\npm
10 verbose lifecycle aspnetcore-angular2-universal-starter@~lint: CWD: C:\PROJECTS\ARTYCO\CRM\Presentation
11 silly lifecycle aspnetcore-angular2-universal-starter@~lint: Args: [ '/d /s /c', 'npm run tslint "Client/**/*.ts"' ]
12 silly lifecycle aspnetcore-angular2-universal-starter@~lint: Returned: code: 1  signal: null
13 info lifecycle aspnetcore-angular2-universal-starter@~lint: Failed to exec lint script
14 verbose stack Error: aspnetcore-angular2-universal-starter@ lint: `npm run tslint "Client/**/*.ts"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid aspnetcore-angular2-universal-starter@
16 verbose cwd C:\PROJECTS\ARTYCO\CRM\Presentation
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
19 error node v7.4.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error aspnetcore-angular2-universal-starter@ lint: `npm run tslint "Client/**/*.ts"`
22 error Exit status 1
23 error Failed at the aspnetcore-angular2-universal-starter@ lint script 'npm run tslint "Client/**/*.ts"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the aspnetcore-angular2-universal-starter package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run tslint "Client/**/*.ts"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs aspnetcore-angular2-universal-starter
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls aspnetcore-angular2-universal-starter
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MarkPieszak** [comment]
Were you able to get it working?

**Comment by nigul2009** [comment]
Yes, I were able!!

I had to fix some warnings about code quality(google style guide) that suggested tslint, that warnings came with the project initially.

tslint is very good.

Thanks Mark.
