### ISSUE TITLE
[question]: How best to get env variable?

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#375]
Hi,
So I am trying to implement json-server for use with my app because we will be calling an external WebAPI to get our data and not using WebAPI in this project. 

I set up an envionrment file that has my enviornments and the correct API endpoint for each.  devMocked enviornment will point to json-server(localhost).

I was trying to pass in a value to webpack but doesn't seem to work well. For example,

 "build:dev": "webpack --progress --color --define process.env.NODE_ENV='\"devMocked\"'",

```
import environment  from '../../environments/environment';
declare var process: any;
const url = environment[process.env.NODE_ENV];
```

Then like this in the method:

```
  getLeaderboard(): Observable<ILeaderboard> {
        return this.transferHttp.get(url+'/leaderboard');
    }
```

Do you have anything like this being done in the current template or played with this at all?

Thanks

**Comment by jrmcdona** [comment]
I should add, sometimes the above method works but other times (such as when I refresh the page) process.env.NODE_ENV is null.  So it is not a consistent solution!

**Comment by jrmcdona** [comment]
Looks like a better approach is with the Angular CLI.   http://morrisdev.com/2017/04/quick-webpack-environments-with-angular-cli/   

However, in this project template we are not using the Angular CLI.   Going to see if webpack will honor this setup.

**Comment by jrmcdona** [comment]
Think I have this figured out.  Will post what I did once done.

**Comment by jrmcdona** [comment]
Couldn't get it to work with WebpackMiddleware when running F5.   See github issue I posted at JavaScriptServices that describes it.

https://github.com/aspnet/JavaScriptServices/issues/1214

**Comment by isaac2004** [comment]
One thing you could do is have a simple API that gets you the url. That way you can use API configs to store urls

**Comment by jrmcdona** [comment]
This seems to work, if I create a webpack config just for what I need.

However HMR isn't working at the moment so I am not sure what I have done in that regard.

```
 app.UseWebpackDevMiddleware(new WebpackDevMiddlewareOptions {
          HotModuleReplacement = true,
          ConfigFile = "webpack.devMocked.config.js"
        });
```

**Comment by jrmcdona** [comment]
@isaac2004 which API configs are you referring to?  AppSettings.json or web.config?

**Comment by isaac2004** [comment]
This project uses appsettings.json. You can put contents of that in transfer in HomeController. As for HMR. Beside you have the environment variable set to Development
