### ISSUE TITLE
Asp.Net Core 2.0

### ISSUE THREAD

**Issue by vasyliv** [MarkPieszak/aspnetcore-angular2-universal#377]
After last changes I got errors
![image](https://user-images.githubusercontent.com/19407350/29493556-5afbdb5e-85a1-11e7-87c8-1247cf2f2656.png)

**Comment by isaac2004** [comment]
Run a dotnet restore from CMD in the folder of your web project. Also ensure you have the metapackage in your csproj

**Comment by MarkPieszak** [comment]
Also make sure you have 2.0 installed, `dotnet --version` in cmd-line to double check.

**Comment by isaac2004** [comment]
And while we are at it, you need VS2017 15.3

**Comment by vasyliv** [comment]
thanks a lot, all work fine.
