### ISSUE TITLE
How this repository still use Angular Universal?

### ISSUE THREAD

**Issue by m98** [MarkPieszak/aspnetcore-angular2-universal#379]
This is a question that is the result of a confusion I had the documentation, on the description of the repository we have:

> NEW* Angular 4.x Universal & ASP.NET Core 2.0 Advanced Starter
which sounds to me that you're using Angular version 4, but you're still using Universal (universal.angular.io)

> This repository is maintained by Angular Universal and is meant...

But when you go to the [universal](https://github.com/angular/universal) repository, you will see:

> Current Status: Universal platform API has been merged into Angular 4.0!
> https://github.com/angular/angular/tree/master/packages/platform-server

and I thought, from now we should use `platform-server` instead of Universal.

is Universal still available for Angular 4? Or you forgot/did not want to change the Universal to `platform-server` in your docs?

**Comment by pjmagee** [comment]
This template is using version 4 of Angular. The universal part has already been removed from this template.

**Comment by MarkPieszak** [comment]
Yeah it just has many names at this point, Universal/platform-server/pre-rendering/etc.
Universal has the best ring to it 👍 

I'll make sure to update those docs to reflect that we have the latest platform-server in here!

**Comment by m98** [comment]
Since there are a lot of confusions around `platform-server` and `universal`, it's better docs be clear about the used technology
Thanks:+1:
