### ISSUE TITLE
You need to include some adapter that implements __karma__.start method!

### ISSUE THREAD

**Issue by nigul2009** [MarkPieszak/aspnetcore-angular2-universal#38]
Hi,

I have some problems executing the comand npm “karma start”:
> karma start

npm : keywords if/then/else require v5 option

_[33m10 01 2017 18:11:06.625:WARN [karma]: _[39mNo captured browser, open http://localhost:9876/
_[32m10 01 2017 18:11:06.634:INFO [karma]: _[39mKarma v1.3.0 server started at http://localhost:9876/
_[32m10 01 2017 18:11:35.871:INFO [Chrome 55.0.2883 (Windows 10 0.0.0)]: _[39mConnected on socket /#-kYKd2-8muD341jcAAAA with id manual-7585

Chrome 55.0.2883 (Windows 10 0.0.0) ERROR
`You need to include some adapter that implements __karma__.start method!`

**Comment by MarkPieszak** [comment]
Let me take a look! Thanks for letting me know about it 
@nigul2009

**Comment by MarkPieszak** [comment]
Fixed, forgot I hadn't added the karma test file :)
Next up I'll add some real tests to get things going & fix up the tslint issues (coming from pretest)

**Comment by nigul2009** [comment]
Good news!!! Thanks Mark.
