### ISSUE TITLE
An unhandled exception occurred while processing the request.

### ISSUE THREAD

**Issue by mahavirjadhav** [MarkPieszak/aspnetcore-angular2-universal#381]
Hi, I am facing following issues. After building application from command line it is giving following errors. Also I modified nav component. In that I have added one image but its not working. detailed error is as following.

`  ERROR in G:/aspnetcore-angular2-universal-master/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
      Types of property 'lift' are incompatible.
        Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
          Type 'Observable<T>' is not assignable to type 'Observable<R>'.
            Type 'T' is not assignable to type 'R'.

    ERROR in G:/aspnetcore-angular2-universal-master/Client/app/shared/route.resolver.ts (7,14): Class 'ConnectionResolver' incorrectly implements interface 'Resolve<SignalRConnection>'.
      Types of property 'resolve' are incompatible.
        Type '() => Promise<ISignalRConnection>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => SignalRConnection | Observable<Sig...'.
          Type 'Promise<ISignalRConnection>' is not assignable to type 'SignalRConnection | Observable<SignalRConnection> | Promise<SignalRConnection>'.
            Type 'Promise<ISignalRConnection>' is not assignable to type 'Promise<SignalRConnection>'.
              Type 'ISignalRConnection' is not assignable to type 'SignalRConnection'.
                Property '_status' is missing in type 'ISignalRConnection'.

    ERROR in G:/aspnetcore-angular2-universal-master/Client/app/shared/route.resolver.ts (7,14): Class 'ConnectionResolver' incorrectly implements interface 'Resolve<SignalRConnection>'.
      Types of property 'resolve' are incompatible.
        Type '() => Promise<ISignalRConnection>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => SignalRConnection | Observable<Sig...'.
          Type 'Promise<ISignalRConnection>' is not assignable to type 'SignalRConnection | Observable<SignalRConnection> | Promise<SignalRConnection>'.
            Type 'Promise<ISignalRConnection>' is not assignable to type 'Promise<SignalRConnection>'.
              Type 'ISignalRConnection' is not assignable to type 'SignalRConnection'.
                Property '_status' is missing in type 'ISignalRConnection'.

    ERROR in ./Client/app/Content/Images/user2.jpg
    Module parse failed: G:\aspnetcore-angular2-universal-master\Client\app\Content\Images\user2.jpg Unexpected character '�' (1:0)
    You may need an appropriate loader to handle this file type.
    (Source code omitted for this binary file)
     @ ./Client/app/components/navmenu/navmenu.component.html 1:5263-5304 1:5997-6038 1:9885-9926 1:10240-10281
     @ ./Client/app/components/navmenu/navmenu.component.ts
     @ ./Client/app/app.module.ts
     @ ./Client/app/server-app.module.ts
     @ ./Client/main.server.ts`

**Comment by MarkPieszak** [comment]
Can you check out this commit & message here, think a few things might of changed in the 3rd part library. https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/a138974dfcf74ed723a4066231e6b808f112ec98

**Comment by mahavirjadhav** [comment]
Thank you MarkPieszak for reply. Please can you comment on following error.


`ERROR in ./Client/app/Content/Images/user2.jpg
Module parse failed: G:\aspnetcore-angular2-universal-master\Client\app\Content\Images\user2.jpg Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./Client/app/components/navmenu/navmenu.component.html 1:5263-5304 1:5997-6038 1:9885-9926 1:10240-10281
 @ ./Client/app/components/navmenu/navmenu.component.ts
 @ ./Client/app/app.module.ts
 @ ./Client/app/server-app.module.ts
 @ ./Client/main.server.ts``

**Comment by MarkPieszak** [comment]
That's because there's no loader to handle images by default (but in the latest PR #376, which I'm trying to merge real soon) it'll become default. 

In webpack.common.js add the following rule:
```
{ test: /\.(png|jpg|jpeg|gif|svg)$/, use: 'url-loader?limit=25000' },
```

Make sure url-loader is installed as well, `npm i --S url-loader`

Hope that helps!

**Comment by mahavirjadhav** [comment]
Thank you Mark for quick reply. I will try.

**Comment by mahavirjadhav** [comment]
Thank you Mark for your help. I have one question in mind. Can I start developing web application using Angular Universal Framework. As there are changes are going in the library. Are there any new versions coming. Or is current framework is  sufficient to start development.

**Comment by MarkPieszak** [comment]
You could get started, the changes coming are quite big(?) mainly the webpack build, and many file changes. Maybe ideally wait a day or two, subscribe to that PR so you know when it's merged?
