### ISSUE TITLE
Unable to open the project file.

### ISSUE THREAD

**Issue by markoj21** [MarkPieszak/aspnetcore-angular2-universal#386]
Hi Mark, 

With the latest code base i am unable to open the project (VS 15.3.2 and core sdk 2 32/64) this is happening on Win7 and Win 10 workstations. Does anything else need to be installed or modified?

![image](https://user-images.githubusercontent.com/3137101/29677980-c0ed95ac-88b1-11e7-82d9-3b9e3d1bfd4f.png)

**Comment by galkavorona** [comment]
Yep, it happened to me too.

**Comment by MarkPieszak** [comment]
One second let me take a look now! We just merged in a big PR, something must be missing from it. Thanks for letting me know!!

**Comment by MarkPieszak** [comment]
-Should- be fixed via: https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/265e9a791fbe1b9376d80a49d9a1a2894d620313

Can you give it a shot and let me know?? So sorry about that! Somehow it worked for me, then after wiping and getting latest again, I got the same issue you guys did. 👍

**Comment by markoj21** [comment]
It's working, thank you, closing the issue.
