### ISSUE TITLE
[question]:  Get .NET server data rendered in App.component.html

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#389]
I have a bit of a funky situation I am trying to solve for.

Do you all know if it possible to get server side data into to one of the Angular templates?

If I could get something like this into one of the Angular HTML files:
@Html.Raw(ViewData["SomeHTML"])

Specifically not the Layout.cshtml file, it needs to be in the Angular app to take advantage of Angular router.

Or even cache something on the server side during bootstrap of the app then pull it out in the Angular App.component and render the HTML.

Any thoughts on how I could possibly achieve this?

Thanks

**Comment by MarkPieszak** [comment]
Hey @jrmcdona, are you talking about this?
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Server/Controllers/HomeController.cs#L34

That data travels from HomeController -> [boot.server](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/ClientApp/boot.server.ts#L32)

From there, it's available via the window Object, and you're browser can even re-use it. If you need to use it within your Server render as well, you'll just have to use some Class / Service / D.I. to use it.

That should get you going 👍

**Comment by jrmcdona** [comment]
Oh booyah,  yeah this is what I am looking for.  I definitely need it on the initial server render view.  So I will have to see how that is done diffrently then the example you have showed here.

Really cool!
