### ISSUE TITLE
Request to add SignalR example

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#39]
I think adding signalR ( https://www.asp.net/signalr ) example is better than adding WebSocket example.

So, I think signalR can be added here

**Comment by MarkPieszak** [comment]
I think that's a good idea, at the time SignalR wasn't even in Alpha yet, but it's a much cleaner option than raw websockets. 

I'll close out #5 so we can add SignalR instead! Thanks :)

**Comment by abrarjahin** [comment]
Thanks for your interest :)

**Comment by abrarjahin** [comment]
I have done little works with signalR.

Initial setup is done in this project-

https://github.com/abrarjahin/signalR_BasicWorking

It is with signalR and ASP.Net Core
