### ISSUE TITLE
Use local copies of angularjs and bootstrap library files instead of remote files

### ISSUE THREAD

**Issue by mahavirjadhav** [MarkPieszak/aspnetcore-angular2-universal#391]
Hi,
I want to use local copies of angularjs and bootstrap libraries instead of remote files. I want maintain these files in lib folder and add this dependency in package.json file. 
Please can you help in this.

**Comment by MarkPieszak** [comment]
Hey there @mahavirjadhav 
We are using locally downloaded copies from npm, the only CDN being used is for signal-r jQuery (as it's just easier in this case).

Are you talking about using a personal Fork of Angular or bootstrap within your project? You'd want to import them into your project as normal, webpack would do the rest. Ideally you'd want to host these on npm either way though then save them into your package json. npm i --S your-angularfork-package-name.
