### ISSUE TITLE
Delete old webpack folder. It's misleading/confusing as its no longer used?

### ISSUE THREAD

**Issue by pjmagee** [MarkPieszak/aspnetcore-angular2-universal#393]

**Comment by MarkPieszak** [comment]
Yes! Wow sorry can't believe I forgot that 😳

**Comment by pjmagee** [comment]
Maybe also add in/comment out where people would add @angular/material and other third party js files like if they added a npm package like 'moment' (moment js datetime lib) where it would need to go for tree shaking/tree nonshaking. (I actually have very poor knowledge on this part).

**Comment by MarkPieszak** [comment]
fixed via: https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/85558da2b2a0573629b705548b3dad8e0938df94
