### ISSUE TITLE
Generator support?

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#395]
Hi Mark,
Did you add the ability to generate a project or still need to run a clone?

Thanks

**Comment by MarkPieszak** [comment]
Hey @jrmcdona, I'll be adding it to `dotnet new` soon after I updated just a few smaller things, but right now the easiest way is to yes just `git clone https://github.com/MarkPieszak/aspnetcore-angular2-universal`

**Comment by jrmcdona** [comment]
cool!
