### ISSUE TITLE
Request to update angular to 2.4

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#40]
I think update Angular to it's latest version will be more excited

**Comment by MarkPieszak** [comment]
Unfortunately (even with the workarounds) we're unable to update to higher than 2.2.1 where I have it now, until Universal core moves into Angular Core itself. (https://github.com/angular/angular/issues/13822)

We may be doing one final `angular2-universal` release (before it's `@angular/platform-server`) to fix a few other issues, and make it upgrade-able to 2.4. I'll add it in here as soon as it's possible :+1:

**Comment by abrarjahin** [comment]
Sure I understand.

NP, I am waiting till then :)

**Comment by MarkPieszak** [comment]
Managed to spend the time to get it working 🙈🎁

**Comment by ImkerAdam** [comment]
First day on this, but I think there are still some dep errors with 2.4.5,
with` npm install` I got dep errors.

npm WARN @angular/http@2.4.5 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@3.4.5 requires a peer of rxjs@^5.0.1 but none was installed. npm WARN @angular/core@2.4.5 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.5 requires a peer of zone.js@^0.7.2 but none was installed.

npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/compiler@~2.2.0 but none was installed.
npm WARN codelyzer@1.0.0-beta.4 requires a peer of @angular/core@~2.2.0 but none was installed.
npm WARN aspnetcore-angular2-universal-starter@1.0.0-beta.5 No license field.


Thanks for any hints on how to work around this.

**Comment by MarkPieszak** [comment]
@ImkerAdam Not to worry! npm Warnings come from sub node_modules, as long as you're not getting npm ERROR it's fine. It's just pointing out some inconsistencies between libraries, and peer Deps they might have etc.

For example codelyzer has this as it's peerDeps, although it still works with 2.4.5. 

```
 "peerDependencies": {
    "tslint": "^4.0.0",
    "@angular/compiler": "<=2.4 >=2.2.0",
    "@angular/core": "<=2.4 >=2.2.0"
  },
```

Thank you for reminding me though, I have been meaning to upgrade Zone.js & Rxjs dependencies within the repo. But don't mind the *new* Warnings that will come from Universal (ie: npm WARN angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.)  You just can't win ;) 

Either way you're all set!
