### ISSUE TITLE
Can't Run First asp.net core 2.0 with angular

### ISSUE THREAD

**Issue by Ashkan-rmk** [MarkPieszak/aspnetcore-angular2-universal#400]
I have made a new project with asp.net core 2.0 sdk :
>`dotnet new angular`

and it has done completely!
then enter:

>`npm restart`

ok too!
But when I type this command `dotnet run` I got this error message:

> newproject.csproj(34,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js" exited with code 1.
The build failed. Please fix the build errors and run again.

what should I do??!
Please help me!

**Comment by Flood** [comment]
Just clone this repo.

1. Run 'npm install'
2. Run 'npm run build:dev'
3. Run 'dotnet run'

There is no need to run 'dotnet new angular'

**Comment by MarkPieszak** [comment]
Yes as @Flood was saying, `dotnet new angular` would create some other repo - not this one :)

Let us know, his steps should get you going!
