### ISSUE TITLE
angular material 2 support in this template?

### ISSUE THREAD

**Issue by chencingyen** [MarkPieszak/aspnetcore-angular2-universal#402]
in the FAQ of the read me of this project you stated that
### How do I Material2 with this repo?
You'll either want to remove SSR for now, or wait as support should be coming to handle platform-server rendering.

https://github.com/MarkPieszak/aspnetcore-angular2-universal#how-do-i-material2-with-this-repo

and in this tweet you said that angular material now support angular universal....
![image](https://user-images.githubusercontent.com/17429259/30125274-17a8df5e-9362-11e7-85f9-952c40699c8a.png)

can i get more detail on this?

btw i am having difficulty for importing angular animation to use together wigh pre-rendering.... can you help also?
thank in advanced

**Comment by peterdobson** [comment]
I've been using material2  with this repo for months albeit with some workarounds that for the most part have been able to remove with the latest material  2.0.0-beta.10. 

Have you moved: 

import 'hammerjs'; 

from app.modeule.ts to boot.browser.ts?

**Comment by chencingyen** [comment]
not yet... let me try it @peterdobson  thanks :)

**Comment by peterdobson** [comment]
Moving hammer solved some console errors for me, but what browser animations are not working? Any specific errors?

**Comment by MarkPieszak** [comment]
Did you get it working? @chencingyen Apologies I'm escaping the hurricane at the moment 👍

**Comment by naveedahmed1** [comment]
@MarkPieszak can we have a simplified version of this template? with just angular, angular material, server side pre-rendering and seo.

**Comment by MarkPieszak** [comment]
It's in the works, it'll be a little bit simpler soon with PRs (or branches) that show the diff of adding a specific feature. Currently fleeing he hurricane so might be a week or two before I can get anything in there unfortunately. 😓

**Comment by naveedahmed1** [comment]
Thank you so much @MarkPieszak for quick reply. Stay safe :)

**Comment by tawsif93** [comment]
Material 2 works for this repo. @MarkPieszak

**Comment by chencingyen** [comment]
@MarkPieszak  thanks for you support :)
but right now I am using https://github.com/aspnet/JavaScriptServices i managed to work with angular material 2.  i think it will work with this repo the same way :)

anyway @MarkPieszak  stay safe

**Comment by MarkPieszak** [comment]
Yes they're meant to be fairly similar now, you should be able to transition around & take things from either easily! GL!

**Comment by odahcam** [comment]
What exactly you have done to use Material 2 with this repo? :)
