### ISSUE TITLE
Not including style in main-broswer.js

### ISSUE THREAD

**Issue by JustasKuizinas** [MarkPieszak/aspnetcore-angular2-universal#404]
Is it possible somehow not to include styles in final main-browser.js file? As I understand they get included directly in html file?

**Comment by MarkPieszak** [comment]
I'd have to try and play with it, but they might not be needed in their (at least for the ASPNET usecase here), good idea! Let me give it a shot.

**Comment by davidsekar** [comment]
#415

**Comment by davidsekar** [comment]
# #415

**Comment by isaac2004** [comment]
@JustasKuizinas have you taken a look after @davidsekar changes? If you still need help open a new issue.
