### ISSUE TITLE
[question] how is tslint integrated?

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#405]
Hello,
I am trying to figure out exactly how linting works here.   For example, I can add double quotes even though they are against the tslint rules and it compiles fine.

Is the linting not intergrated?
If I run "ng lint" doesn't look like that is integrated into Angular-cli either.

Just making sure I am not missing something here.
Thanks

**Comment by jrmcdona** [comment]
Nevermind, it seems to be working.

However, for others who may come across this, If you add lint section to angular-cli.json then "ng lint" command will work if you want to use this via command.
  "lint": [
    {
      "project": "ClientApp/tsconfig.app.json"
    }
  ]

**Comment by MarkPieszak** [comment]
Can you make a quick PR to get that into the project? It'd be great to have that by default, I must of missed that!

**Comment by MarkPieszak** [comment]
Also VSCode will show lint and codelyzer errors in real-time automatically, VS unfortunately can't 😔

**Comment by jrmcdona** [comment]
@MarkPieszak PR sent.

**Comment by MarkPieszak** [comment]
Merged! Thanks again 🤘🍻
