### ISSUE TITLE
[question] Is the general rule of thumb that all gets need transferHttp?

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#409]
Is the general rule of thumb that all gets need transferHttp?  Just trying to make a note for my team when to use it and when not to.  Thanks!

For example from the User service example:

```
getUsers(): Observable<IUser[]> {
        // ** TransferHttp example / concept **
        //    - Here we make an Http call on the server, save the result on the window object and pass it down with the SSR,
        //      The Client then re-uses this Http result instead of hitting the server again!

        //  NOTE : transferHttp also automatically does .map(res => res.json()) for you, so no need for these calls
        return this.transferHttp.get(`${this.baseUrl}/api/users`);
    }

    getUser(user: IUser): Observable<IUser> {
        return this.transferHttp.get(`${this.baseUrl}/api/users/` + user.id);
    }

    deleteUser(user: IUser): Observable<any> {
        return this.http.delete(`${this.baseUrl}/api/users/` + user.id);
    }

    updateUser(user: IUser): Observable<any> {
        return this.http.put(`${this.baseUrl}/api/users/` + user.id, user);
    }

    addUser(newUserName: string): Observable<any> {
        return this.http.post(`${this.baseUrl}/api/users`, { name: newUserName })
    }
}
```

**Comment by isaac2004** [comment]
what is the goal of your gets? to have then SSR? you truly don't need transfer at all

**Comment by jrmcdona** [comment]
I am just trying to not break the universal pattern that is in place in this project for SSR and SEO.   Didn't quite understand the implications of using transfer or not using it.

**Comment by isaac2004** [comment]
I personally don't use it in my own thing, but I also am using the new HttpClient

**Comment by jrmcdona** [comment]
that is what I want to use!  Part of the reason why I am asking.

**Comment by isaac2004** [comment]
take a peek at https://github.com/isaac2004/LevinBlog

**Comment by jrmcdona** [comment]
cool thanks!

**Comment by isaac2004** [comment]
@jrmcdona let me know if that poorly written code makes any sense ;)

**Comment by davidsekar** [comment]
When you use normal http request, it gets executed on servers for SSR and then again the same request will happen on client when it boots on browser. TransferHttp just avoids making the duplicate call on browser by persisting it to TransferCache. Look at the rendered HTML, you'll find window['TransferCache']

**Comment by isaac2004** [comment]
@davidsekar that's weird I don't get 2 http calls though. Even if I debug my controller only gets hit once. Hmmmmm

**Comment by jrmcdona** [comment]
Would be good to know for sure on this one!

**Comment by MarkPieszak** [comment]
Yes as David was saying the app gets re-rendered on the client again, usually that's not a big deal. Sometimes, let's say you have a list of products, you won't want that to happen, since the list will "flicker" in between those get's. This is an example of when you'd want to transfer it. Just be careful to use it everywhere, it essentially passes down json string to the browser, you don't want it to be too big 😀

Use wherever it's important to avoid that flicker, some places you won't need it.

I'll be adding an interceptor for it soon, when I get my life back in order! Also it'll be part of Angular core in 5.x, where it'll be an optional flag to set, making it even easier. 🎈 That's still in the works of course!

**Comment by jrmcdona** [comment]
@MarkPieszak cool I was hoping Angular 5 can help take care of it, easier.  It would be good if the framework managed this type of thing instead of the developers!

**Comment by MarkPieszak** [comment]
It will be part of 5.0 yes 👍
