### ISSUE TITLE
[proposal] Adding webRTC example

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#41]
I think adding WebRTC example will be helpful for enriching this template.

I am working on adding WebRTC ( https://webrtc.org/ ) to this library.

If you agree to add webRTC to this library, I proudly like to contribute here :)

**Comment by MarkPieszak** [comment]
It'd probably have to be separated out and not rendered / connected during the server-rendering, but if you used `import { isBrowser } from 'angular2-universal';` to set it up conditionally that could be nice!

Can you make a separate Route / page for it to showcase it?

Also I should be making a larger update today or tomorrow to update a few core things so I'm not sure if you want to wait until that's in there, get latest, then create it? @abrarjahin

**Comment by abrarjahin** [comment]
Sure, I am waiting for your next update.

After that, I like to add webRTC with it in a separate route.

And after doing that I will request you to add that, then if u agree, I like to contribute :)

**Comment by MarkPieszak** [comment]
This might be something better for a documentation markdown file as not everyone will need it, going to close it out for now!
