### ISSUE TITLE
HRM not working 

### ISSUE THREAD

**Issue by tawsif93** [MarkPieszak/aspnetcore-angular2-universal#411]
This version is working perfectly but HRM is not working. Any change in the files don't update in the browser.  Console showing HRM connected  but not updating any change 

I've also set `export $ASPNETCORE_ENVIRONMENT=Development`

**Comment by MarkPieszak** [comment]
Try it without the dollar before aspnetcore ? Let us know !

**Comment by tawsif93** [comment]
nah, It isn't working for me. I'm trying in Ubuntu 16.04. Don't know about others .

**Comment by tawsif93** [comment]
Thanks for your reply. It was due to less number of System inotify limits. This [comment](https://github.com/angular/angular-cli/issues/3273#issuecomment-320105187) in Angular-cli sloved the issue.

**HRM** is now working completely fine.
