### ISSUE TITLE
Question: Hows does AOT/JIT compilation work with the boot.browser.ts?

### ISSUE THREAD

**Issue by pjmagee** [MarkPieszak/aspnetcore-angular2-universal#414]
I've just been reading up a bit more on AoT/JiT compilation and it appears that for AoT compilation the bootstrapping code has to surely be different than if the bootstrapping was JiT based.

We have a few npm package tasks like build:dev and build:pro and I know they pass through the env.prod flag which will allow webpack to use the AoT plugin for production builds. But doesnt the same boot.browser.ts file fire up and essentially just try and run the application with the JIT compiler? 

Angular main-aot.ts looks like this:

```javascript
import { platformBrowser }    from '@angular/platform-browser';

import { AppModuleNgFactory } from '../aot/src/app/app.module.ngfactory';

platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);
```

And the JIT version looks like this (which is basically what our boot.browser.ts looks like):

```javascript
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';

platformBrowserDynamic().bootstrapModule(AppModule);
```

So what actually happens when you compile/build with env.prod. Does angular just know to bootrap the application knowing it was AoT compiled and just bypass JIT? I've also disabled SSR entirely. So It's almost like I am running this as an Angular CLI app. I even commented out the Server compilation code in webpack for now as it's just not something we can use at the moment.

[I've been reading the AoT compilation documentation](https://angular.io/guide/aot-compiler#ahead-of-time-compilation) on the Angular site but nothing explains like how we have it setup in this template.

**Comment by pjmagee** [comment]
I think i'll try and answer this myself by saying the AotPlugin checks for the platformBrowserDynamic code during compilation and changes this meaning we don't need to specify a seperate AOT bootstrap?

**Comment by MarkPieszak** [comment]
You are correct!

You don't have to separate and create your AoT files for browser or server as ngtools looks for and creates the correct one for you. Also server renders should always be AoT (or setup to auto compile to AoT) regardless as there is no benefit to doing JIT there.
