### ISSUE TITLE
Bootstrap CSS duplicated

### ISSUE THREAD

**Issue by davidsekar** [MarkPieszak/aspnetcore-angular2-universal#415]
There are two different ways in which bootstrap is included in this project.
1. It is added as an external CSS in vendor bundle. (outputs as `vendor.css`)
2. It is again imported in the app.component.scss file. so it is added to `main-client.js`

**Expected:**
Either it should be part of vendor bundle (Pros: Doesn't affect the dev. re-build timings. CSS are already vendor prefixed. Cons: No customization feasible.)
 
OR ELSE

Added as bootstrap SASS in app.component.scss (Pros:  **Allows customizing bootstrap**. Cons: Affects the dev. re-build timings. Requires postcss-loader for vendor prefixing)

I didn't raise a PR as I'm not sure which one is expected.

**Comment by isaac2004** [comment]
@davidsekarwhen you say no customization feasible, are you stating you would not be able to modify bootstrap includes? That doesn't seem like an issue

**Comment by davidsekar** [comment]
when bootstrap css comes as part of vendor module... Entire 210kb of CSS gets added to your vendor.css. You cann't customize what css should be included and what shouldn't be...
e.g., you may want to use just the tabs module and you just need the particular components CSS. such customization isn't feasible.  

But, If you uses bootstrap SASS, you can selectively comment out the section that you don't need.

**Comment by isaac2004** [comment]
@davidsekarsure I get that. It is an interesting choice. I wonder if you can set a flag in webpack to do either or

**Comment by MarkPieszak** [comment]
Well we definitely don't need two versions I hadn't noticed ! We only need the good bootstrap scss stuff. 

Sass should already be set up here: https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/ClientApp/app/app.component.scss#L7

Is it no longer working?

**Comment by davidsekar** [comment]
I have commented out bootstrap css from the vendor bundle, it is now part of reference pull request.
