### ISSUE TITLE
Can't resolve 'moment' 

### ISSUE THREAD

**Issue by casni14** [MarkPieszak/aspnetcore-angular2-universal#421]
After cloning the project and hitting F5 in VS as described I get 8 errors saying:
Can't resolve 'moment' in "C:\Users\...\ngx\bootstrap\datepicker
The other errors were similar with datepicker2\day - time - year etc.
Under file, it says module not found.
Any ideas?

**Comment by EvgenStudent** [comment]
I had this error too. But I don't know the reason.
Try 'npm install' through cmd admin. It helped me usually.

**Comment by digibum** [comment]
Same issue here :/

`    ERROR in ./~/ngx-bootstrap/datepicker/date-formatter.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker'
     @ ./~/ngx-bootstrap/datepicker/date-formatter.js 1:0-28
     @ ./~/ngx-bootstrap/datepicker/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor

    ERROR in ./~/ngx-bootstrap/datepicker2/custom-range/bs-custom-range-picker.component.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker2\custom-range'
     @ ./~/ngx-bootstrap/datepicker2/custom-range/bs-custom-range-picker.component.js 15:0-33
     @ ./~/ngx-bootstrap/datepicker2/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor

    ERROR in ./~/ngx-bootstrap/datepicker2/day/bs-day-picker.component.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker2\day'
     @ ./~/ngx-bootstrap/datepicker2/day/bs-day-picker.component.js 15:0-33
     @ ./~/ngx-bootstrap/datepicker2/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor

    ERROR in ./~/ngx-bootstrap/datepicker2/current-date/bs-current-date.component.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker2\current-date'
     @ ./~/ngx-bootstrap/datepicker2/current-date/bs-current-date.component.js 16:0-33
     @ ./~/ngx-bootstrap/datepicker2/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor

    ERROR in ./~/ngx-bootstrap/datepicker2/time/bs-date-time-picker.component.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker2\time'
     @ ./~/ngx-bootstrap/datepicker2/time/bs-date-time-picker.component.js 24:0-33
     @ ./~/ngx-bootstrap/datepicker2/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor

    ERROR in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-state.provider.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker2\common'
     @ ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-state.provider.js 12:0-33
     @ ./~/ngx-bootstrap/datepicker2/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor

    ERROR in ./~/ngx-bootstrap/datepicker2/year/bs-year-picker.component.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker2\year'
     @ ./~/ngx-bootstrap/datepicker2/year/bs-year-picker.component.js 15:0-33
     @ ./~/ngx-bootstrap/datepicker2/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor

    ERROR in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js
    Module not found: Error: Can't resolve 'moment' in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\node_modules\ngx-bootstrap\datepicker2\common'
     @ ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js 2:0-33
     @ ./~/ngx-bootstrap/datepicker2/custom-range/bs-custom-range-picker.component.js
     @ ./~/ngx-bootstrap/datepicker2/index.js
     @ ./~/ngx-bootstrap/index.js
     @ dll vendor
Child
    Hash: 280607aba66ba0f01778
    Time: 12558ms
                                   Asset     Size  Chunks                    Chunk Names
    89889688147bd7575d6327160d64e760.svg   109 kB          [emitted]
                               vendor.js  4.41 MB       0  [emitted]  [big]  vendor
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular4-aspnetcore-universal@1.0.0-rc3 build:vendor: `webpack --config webpack.config.vendor.js --progress --color`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular4-aspnetcore-universal@1.0.0-rc3 build:vendor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matej\AppData\Roaming\npm-cache\_logs\2017-09-25T12_39_51_419Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular4-aspnetcore-universal@1.0.0-rc3 build:dev: `npm run build:vendor && npm run build:webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the angular4-aspnetcore-universal@1.0.0-rc3 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matej\AppData\Roaming\npm-cache\_logs\2017-09-25T12_39_51_466Z-debug.log

C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2>`

**Comment by isaac2004** [comment]
The issue here is that moment is a devDependency of one of the dependencies and doesn't get resolved. Above "fixes" resolves issue
