### ISSUE TITLE
npm run build:prod doesn't produce AOT bundles for lazy loaded modules

### ISSUE THREAD

**Issue by KhalipskiSiarhei** [MarkPieszak/aspnetcore-angular2-universal#422]
If I run **npm run build:prod** it produces the following JS:
![aot1](https://user-images.githubusercontent.com/6203886/30809261-cfe46d1c-a209-11e7-83d3-3b6d5428aa4c.png)

So, there is not a lazy loaded JS module!  But when I run the project via F5 it adds 0.js because of DebugRunWebpack target which runs JIT compilation in advance:
![aot2](https://user-images.githubusercontent.com/6203886/30809406-4d869dda-a20a-11e7-976d-5c41b6efa827.png)

If I fix the mentioned above command to `<Exec Command="node node_modules/webpack/bin/webpack.js --end.prod" />` lazy loaded modules stop working during build process as well.

Could you clarify why **npm run build:prod doesn't produce AOT bundles for lazy loaded modules**, but it is created durnig solution building? Is lazy loaded module AOT bundle in 100%?

**Comment by naveedahmed1** [comment]
In your `webpack.config.js` file comment the line `resolve: { mainFields: ['main'] },` in `serverBundleConfig `

**Comment by KhalipskiSiarhei** [comment]
@naveedahmed1 Thanks, it fixed an issue. As soon as I commented the mentioned above line it started producing lazy bundles and they are AOT because there are NgFactory statements inside of the bundles. But what I am not understanding why all(!!!) bundles sizes are much bigger in comparison with JIT. As I can see in AOT we don't deliver Angular compiler but we deliver compiled code which is bugger than transpiled TS. But the differences JIT vs AOT in my bundles are 2-7 times. Is it ok or not?

![jitvsaot](https://user-images.githubusercontent.com/6203886/30844960-f60ea5ee-a299-11e7-9593-620d90770ccb.png)

**Comment by davidsekar** [comment]
@KhalipskiSiarhei
I'm guessing here.

Since angular can now reach your lazy modules, it can read all dependencies modules  within lazy loaded chunks and added those to the main-server bundle...

Im sure you can't see the angular compiler, if you did... Then please create an issue in angular/@ngtools/webpack repo,  because ngtools/webpack also powers the actual angular CLI

**Comment by davidsekar** [comment]
And according to current build system, ngx-bootstrap will be part of vendor bundle. But in production builds, it will be part of your code bundle....
And I think we are importing all modules of ngx-bootstrap, so expect approx. 500kb from that...

**Comment by davidsekar** [comment]
@KhalipskiSiarhei Check out this pull request that reduces the bundle size drastically
https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/410#issuecomment-332844437

**Comment by KhalipskiSiarhei** [comment]
@davidsekar I have applied the recommenced PR to my codebase and can confirm that it reduced bundles size up to 10 times. Thanks for your assistance with that!!!
