### ISSUE TITLE
Unable to locate 'moment' module

### ISSUE THREAD

**Issue by TylerBrinks** [MarkPieszak/aspnetcore-angular2-universal#423]
As of Sept. 25, pulling and running the project on Mac yields an error suggesting 'moment' cannot be found.

` Cannot find module "moment`

I've tried adding it via NPM, added it to nonTreeShakableModules, added a reference in markup to momentjs via a CDN, and tried adding like jquery

`new webpack.ProvidePlugin({ $: 'moment', moment: 'moment' })`

The error happens both client side and server side when pages are pre-rendered.  Any idea what needs to happen to eliminate the error?

**Comment by calhamdower** [comment]
I, too, have this issue. However, with windows.

**Comment by flauschi82** [comment]
Have you already tried to rebuild the vendor bundle?

`webpack --config webpack.config.vendor.js`

That did the trick for me.

**Comment by davidsekar** [comment]
moment-js is removed removed from ngx-bootstrap dependency list, due to its very huge size.

Now you can define your own locale translation.
https://github.com/valor-software/ngx-bootstrap/issues/1963#issuecomment-324002615

**Comment by MarkPieszak** [comment]
Should be ok now that I added moment to packagejson dependencies, but ideally we should come up with a better solution.

**Comment by MarkPieszak** [comment]
Closing for now, but if anyone has any better suggestions, I'm all ears! @davidsekar
