### ISSUE TITLE
Why _ngcontent-c* are always counting up?

### ISSUE THREAD

**Issue by doggy8088** [MarkPieszak/aspnetcore-angular2-universal#426]
Every tag in the SSR page are contains ` _ngcontent-c*` attributes in the HTML.  I know what is this for, but I'm really curious to know why this attributes are always counting up when I hit Refresh of the page.

**Comment by MarkPieszak** [comment]
This is just part of the compiler and how it handles everything. These are from ViewEncapsulation Emulation, we just want to make sure each request has different ones so that the browser doesn't some cache/display anything improperly! Hope that helps 👍 

Nothing to worry about it's all normal :)
