### ISSUE TITLE
Adding Guard to route fails with 'Prerendering timed out after'

### ISSUE THREAD

**Issue by digibum** [MarkPieszak/aspnetcore-angular2-universal#429]
`NodeInvocationException: Prerendering timed out after 30000ms because the boot function in 'C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2/ClientApp/dist/main-server' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper.`

This happens when I add simple guard to route. What am I dooing wrong?
`import { NgJwtModule, LoggedOutAuth, LoggedInAuth } from '../modules/ng-jwt';`
`{ path: 'alarm', component: AlarmComponent, canActivate: [LoggedInAuth] }`
`providers: [
        LoggedOutAuth, LoggedInAuth
    ]`

**Comment by digibum** [comment]
Problem was in localstorage not available to server...

**Comment by isaac2004** [comment]
@digibum take a look at the auth branch with an example of how to get around common auth storage issue.

**Comment by helloneoberg** [comment]
Hi, may i know is there a resolution to fix /workaround this issue?
Thank you
