### ISSUE TITLE
Vendor.css file is not generated

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#43]
Hi, I have cloned this repo and started with VS 2015 with Node.JS.

I think I am not getting the output it supposed to be.

I am getting-

    "./vendor/vendor.css" not found

![Error](https://cloud.githubusercontent.com/assets/4152843/22053192/4aec2cf8-dd79-11e6-8640-0a4d27b93220.jpeg)

Can anyone please help?

**Comment by MarkPieszak** [comment]
Let me take a look, what is `http://image.prntscr.com/image/a7b1f2c8ca3448d9a72e3310aba76528.jpeg` ?

**Comment by MarkPieszak** [comment]
Just removed the dist/vendor file in the _Layout page in Views, can you give that a shot and see if it fixes it? Just let me know or open it back up if something is still broken! Thanks again @AbrarJahin

**Comment by AbrarJahin** [comment]
It is partially solved.

As far as I know in current development, CDN is better, but if we need to use multiple CSS library, then using CDN is not a good way because it creates so many requests.

So, combining and compressing all CSS files and make only 1 file is a better solution which is done by webpack (gives vendor.css file).

So, I think, we should have solved the webpack issue to make it a good repo.

Isn't it @MarkPieszak ?

**Comment by MarkPieszak** [comment]
Re-opened it, you're right! For now I was just swamped so I took the easy way out, but you're correct we should let webpack handle everything instead of CDNs.

**Comment by AbrarJahin** [comment]
Thanks for your help.

:+1: 

And also, there is a way of combining all css and js together for angular2 and webpack.
In current webpack config, CSS are injected to HTML.

But I think, applying that will be a good approach so that page content got minimised and only 1 load for js is needed :).

So, page will be more performant :1st_place_medal:

**Comment by MarkPieszak** [comment]
Definitely, anything we can do to make everything more performant is :100: :+1:

**Comment by AbrarJahin** [comment]
Thanks for your understanding and help 👍

**Comment by MarkPieszak** [comment]
We're all set now, just added the dist/vendor.css file back in: 5321795.
:100: Thanks again!
