### ISSUE TITLE
@universal/ng-aspnetcore-engine usage in boot.server.ts

### ISSUE THREAD

**Issue by jrmcdona** [MarkPieszak/aspnetcore-angular2-universal#430]
Hello-

Any reason why boot.server.ts. doesn't use @universal/ng-aspnetcore-engine?
// Temporary * the engine will be on npm soon (`@universal/ng-aspnetcore-engine`)

I see it is installed in package.json.  

The documentation says to reference this app:
https://www.npmjs.com/package/@nguniversal/aspnetcore-engine

I assume just lack of time and/or nobody PR'd it.   But wanted to double check if it is stable.

Thanks

**Comment by MarkPieszak** [comment]
It'll be adding in the upcoming 5.0 release (as it's waiting to be merged in there, there were many updates for 5.0)

5.0 PR here:
#437 

Universal aspnetcore-engine PR here:
https://github.com/angular/universal/pull/825
