### ISSUE TITLE
Solution Not Building

### ISSUE THREAD

**Issue by shan75** [MarkPieszak/aspnetcore-angular2-universal#432]
Hi I donwloaded your repo and just openedin VS 2017.  It is not building. I comes up with lot of errors

Simple example as below.

Error	CS0518	Predefined type 'System.String' is not defined or imported	Asp2017	C:\Development\AngularDevelopment\aspnetcore-angular2-universal-master\Server\Controllers\HomeController.cs	48	Active

Can some one give me some idea how to make it to build and start working. Thanks
Shan

**Comment by davidsekar** [comment]
Did you install .net core 2.x SDK ? It doesn't come with VS2017.

https://www.microsoft.com/net/download/core

__Error reference:__
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0518

**Comment by MarkPieszak** [comment]
Thank you again David! 👍
Closing out as it seems like that's most likely the culprit, let us know if you're all set Shan

**Comment by shan75** [comment]
Hi


I have made it to work. It is is actually a different issue not .net core issue.


I read some where else in the forum to install sass using npm and after that it worked like Charm.


I guess it is worth mentioning that in your steps


Regards

Shan

________________________________

**Comment by MarkPieszak** [comment]
Ah did you have to do an npm rebuild node-sass? That happens if you changed your Node version from a previously time you did npm install. Let us know!
