### ISSUE TITLE
Slow HMR speed

### ISSUE THREAD

**Issue by EricBichara** [MarkPieszak/aspnetcore-angular2-universal#435]
Hot reload takes about 5-6 seconds after any change in the code. Is there anything that can be done to speed this up? This project contains a lot of features, maybe a cleaner project with fewer features would help? By comparison, a clean cli project takes about 1-2 seconds to reload.

**Comment by peterdobson** [comment]
The following tweaks to webpack.config.js: made my HMR much faster in development. See the lines with the "//PD added this" comment

const clientBundleConfig = merge(sharedConfig, {
        entry: { 'main-client': './ClientApp/boot.browser.ts' },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Plugins that apply in development builds only
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // Plugins that apply in production builds only
            new webpack.optimize.UglifyJsPlugin(),
            new AotPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.browser#AppModule'),
                exclude: ['./**/*.server.ts']
            })
                ])
        ,
        devtool: isDevBuild ? 'cheap-eval-source-map' : ''  //PD added this
    });

    const serverBundleConfig = merge(sharedConfig, {
        resolve: { mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot.server.ts' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ].concat(isDevBuild ? [] : [
            new AotPlugin({
                tsConfigPath: './tsconfig.json',
                entryModule: path.join(__dirname, 'ClientApp/app/app.module.server#AppModule'),
                exclude: ['./**/*.browser.ts']
            })
        ]),
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },
        target: 'node',
        devtool: isDevBuild ? 'cheap-eval-source-map' :  'inline-source-map' //PD added this
    });

**Comment by EricBichara** [comment]
That made a huge difference thanks!!!

**Comment by Flood** [comment]
@peterdobson 

The last line:
```
devtool: isDevBuild ? 'cheap-eval-source-map' :  'inline-source-map' //PD added this
```

Shoudn't that be:
```
devtool: isDevBuild ? 'cheap-eval-source-map' : false //PD added this
```

Since it was like this before:
```
devtool: isDevBuild ? 'inline-source-map': false
```

Otherwise we are adding source maps for production build.

**Comment by peterdobson** [comment]
yeah thanks @Flood I think you are right

**Comment by davidsekar** [comment]
If you need to debug the Typescript that runs on the Server side (i.e., while Server Side Rendering initial HTML). Then 'inline-source-map' is the best as it maps to the **exact source line** of .ts file & shows that in the dev toolbar....

But if SSR debugging is not required, then devtool can be false ( as cheap-eval-source-map will map some things to the transpiled JS, so not that useful)

@peterdobson Thanks for your pointer on how to improve HMR build speed.

**Comment by MarkPieszak** [comment]
Added this in the #437 upcoming 5.0 release, thank you Peter! I left it as inline as default figuring people would want that TS SSR debugging, but instead I put a note in there.

Overall I'm sure people won't need it, and would prefer faster rebuilds :)

Thanks again! 🍺

**Comment by sebrojas14** [comment]
Hey, I'm facing slow speeds with angular 7, please help me
