### ISSUE TITLE
Conversion?

### ISSUE THREAD

**Issue by Ox29A** [MarkPieszak/aspnetcore-angular2-universal#436]
Sorry, this is more of a question than an issue,

i have a really large project using the old ng2 template, and i am just curious how i would go about upgrading to angular 4, what do you think would be the best place to start?

Kind Regards

**Comment by MarkPieszak** [comment]
There aren't that many changes between versions 2 & 4 so it should be relatively smooth ?
If you start porting over your App, while its running, you'll at least be able to spot & fix little issues here and there as they crop up.  Shouldn't be that bad! GL 🍺
