### ISSUE TITLE
Use of a component which needs 'core-js'

### ISSUE THREAD

**Issue by Moalpima** [MarkPieszak/aspnetcore-angular2-universal#44]
Hi,

I added the "angular2-tree-component" component via npm and got the error "TS2688: Cannot find type definition file for 'core-js'.

After installing "@types\core-js" I got "TS2300: Duplicate identifier 'PropertyKey'" (lib.es2015.core.d.ts).

Has anyone an idea how I can fix that problem?

**Comment by MarkPieszak** [comment]
Within the `tsconfig` you'll see: `"lib": [ "es6", "dom" ],`

The duplicate identifiers are coming from the `es6` part there.

I also forgot this template still has the older es6-shim as a devDependency as opposed to core-js there. Having that instead of es6-shim, you won't need the `@types/core-js` since you'll have core-js included anyway. This should also help polyfill older browsers as well.

```
// remove es6-shim here
"devDependencies": {
    "core-js": "^2.4.1",
```

**Comment by MarkPieszak** [comment]
Can you give that a shot and see if it takes care of everything? Just checked in the replacement for es6-shim with core-js as a devDependency (a few other small fixes in there as well)

**Comment by Moalpima** [comment]
I changed it but still got following error:

An unhandled exception occurred while processing the request.

Exception: Call to Node module failed with error: Error: Webpack compilation reported errors. Compiler output follows: Hash: ed1cadf089d8ea299d97
Version: webpack 2.1.0-beta.25
Time: 4516ms
Asset Size Chunks Chunk Names
0.webpack-output.js 3.75 kB 0 [emitted] 
webpack-output.js 81.6 kB 1 [emitted] main
0.webpack-output.js.map 2.57 kB 0 [emitted] 
webpack-output.js.map 101 kB 1 [emitted] main

ERROR in [default] G:\GitRep\aspnetcore-angular2-universal\src\aspnetcore-angular2-universal\node_modules\angular2-tree-component\dist\models\tree-node.model.d.ts:1:0 
Cannot find type definition file for 'core-js'.

**Comment by MarkPieszak** [comment]
Let me try adding `angular2-tree-component` and see if I can get it working.

**Comment by Moalpima** [comment]
Hi Mark,

first thank you for your help. Have you found out anything yet? Let me know, if you need any further information.

**Comment by MarkPieszak** [comment]
Apologies was swamped today, let me give it a shot either tonight or right in the morning and I'll get back to you! @Moalpima

**Comment by MarkPieszak** [comment]
Did you try removing es6 from lib and keeping core-js types?

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/11700
Was just looking at others having a similar problem ^

**Comment by MarkPieszak** [comment]
So I emptied node_modules, `npm i --save angular2-tree-component` and added it to the webpack.vendor array (at the bottom), and re-ran `npm run postinstall` (it just re-runs the webpack vendor bundle) and tried running, and it didn't have any problems.

Do I need to try to use it for that error to be triggered?

When is that coming up for you? Try it with the latest repo and let me know if it still happens (maybe even try closing and re-opening VSCode)

**Comment by MarkPieszak** [comment]
So I got rid of the duplicate identifiers by adding `core-js` to the `types` section of the tsconfig, and changing lib to `"lib": [ "es5", "dom" ],`

But it looks like now it's coming up with errors since it hasn't been designed to be ran w/ Universal.

> Exception: Call to Node module failed with error: ReferenceError: Element is not defined

So the library itself is doing things 

Can you also try logging a bug with the angular2-tree-component library and see if they can help guide us with this one?

**Comment by MarkPieszak** [comment]
I'll close this out for now as we have the issue with the library creator to look out for changes!

One thing you could do if it's very important for you at the moment is disabling Universal (by removing that asp-prerender-module tag from the Views/index.cshtml page. That way you can at least use it any other non-Universal component for a while until things get cleared up.

Sorry I couldn't be of any more assistance!
