### ISSUE TITLE
HMR stops working

### ISSUE THREAD

**Issue by EricBichara** [MarkPieszak/aspnetcore-angular2-universal#440]
I'm running from the command line on a Mac (OSX 10.12.6). The service watching for changes usually stops working after a few code changes. When i change a file i get the following message:

 Node will restart because file changed: /Users/myproject/ClientApp/app/pages/m-pagye/my-page.component.html___jb_tmp___

But the browser wont reload. Reloading it manual does't seem too help, still see old cold.

**Comment by MarkPieszak** [comment]
If you're running from command line, you're probably going to have to set things manually, try `set ASPNETCORE_ENVIRONMENT=Development` on Mac, `export` (instead of set) for windows.

Then give `dotnet run` a shot. Hope that helps!

**Comment by EricBichara** [comment]
@MarkPieszak I've been doing that but for some reason it sometimes stops rebuilding and i have to build manually. I'll try to identify a pattern to reproduce. Thanks

**Comment by EricBichara** [comment]
Things are working better now that i added the environment variable to my bash_profile to make it permanent, so ill close this issue
