### ISSUE TITLE
The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2

### ISSUE THREAD

**Issue by digibum** [MarkPieszak/aspnetcore-angular2-universal#442]
When tryng to publish my solution I get this error.

`C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2>dotnet publish
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Server\RestAPI\DemoController.cs(19,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\DemoController.cs(25,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\DemoController.cs(31,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\DemoController.cs(37,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\DemoController.cs(43,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\User\userController.cs(42,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\Components\NgJwt\jwtController.cs(46,29): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\Components\NgJwt\jwtController.cs(50,26): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\Controllers\HomeController.cs(67,38): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\Alarm\alarmController.cs(49,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\Alarm\alarmController.cs(81,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\DefaultController.cs(42,28): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\PasswordReset\PasswordResetController.cs(63,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\Alarm\alarmController.cs(115,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\Alarm\alarmDetailsController.cs(99,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\Alarm\alarmController.cs(150,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\Alarm\alarmDetailsController.cs(267,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
Server\RestAPI\Alarm\alarmDetailsController.cs(308,24): warning CS0168: The variable 'e' is declared but never used [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
  Asp2017 -> C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\bin\Debug\netcoreapp2.0\Asp2017.dll
  npm WARN bootstrap@4.0.0-beta requires a peer of jquery@>=3.0.0 but none is installed. You must install peer dependencies yourself.
  npm WARN bootstrap@4.0.0-beta requires a peer of popper.js@^1.11.0 but none is installed. You must install peer dependencies yourself.
  npm WARN ngx-bootstrap@2.0.0-beta.6 requires a peer of typescript@>=2.4.2 but none is installed. You must install peer dependencies yourself.
  npm WARN angular4-aspnetcore-universal@1.0.0-rc3 No repository field.
  npm WARN angular4-aspnetcore-universal@1.0.0-rc3 No license field.
  npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
  npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

  added 114 packages in 25.761s
  env = {"prod":true}
  Hash: 21f92c3f610ebf4a93ed231b55dd03dd4cdd7cd7
  Version: webpack 2.7.0
  Child
      Hash: 21f92c3f610ebf4a93ed
      Time: 23520ms
           Asset    Size  Chunks             Chunk Names
       vendor.js  143 kB       0  [emitted]  vendor
      vendor.css  122 kB       0  [emitted]  vendor
  Child
      Hash: 231b55dd03dd4cdd7cd7
      Time: 23496ms
          Asset     Size  Chunks                    Chunk Names
      vendor.js  3.92 MB       0  [emitted]  [big]  vendor
EXEC : warning : Can't resolve all parameters for SignalR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/node_modules/ng2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
EXEC : warning : Can't resolve all parameters for SignalR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/node_modules/ng2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
EXEC : warning : Can't resolve all parameters for SignalR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/node_modules/ng2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
EXEC : warning : Can't resolve all parameters for SignalR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/node_modules/ng2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x [C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj]
  Hash: 8160eff531ee07d88763880e0d18f8384fc2761a
  Version: webpack 2.7.0
  Child
      Hash: 8160eff531ee07d88763
      Time: 35700ms
                                       Asset       Size  Chunks                    Chunk Names
        674f50d287a8c48dc19ba404d20fe713.eot     166 kB          [emitted]
        b06871f281fee6b241d60582ae9369b9.ttf     166 kB          [emitted]
      af7ae505a9eed503f8b8e6982036873e.woff2    77.2 kB          [emitted]
       fee66e712a8a08eef5805a46892932ad.woff      98 kB          [emitted]
        912ec66d7572ff821749319396470bde.svg     444 kB          [emitted]  [big]
                              main-client.js  510 bytes       0  [emitted]         main-client

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (164,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (166,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (168,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (169,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.
      Child ClientApp\app\app.component.scss:
                                           Asset     Size  Chunks                    Chunk Names
            674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
            b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
          af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
           fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
            912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
  Child
      Hash: 880e0d18f8384fc2761a
      Time: 35681ms
                                       Asset     Size  Chunks                    Chunk Names
        674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
        b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
      af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
       fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
        912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
                              main-server.js  6.28 kB       0  [emitted]         main-server

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (164,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (166,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (168,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.

      ERROR in C:/Users/Matej/Documents/Visual Studio 2017/Projects/eAlarm Angular2 .NetCore2/ClientApp/app/containers/alarm/detailComponent/alarmDetail.component.ts (169,30): Property 'nativeElement' does not exist on type 'TabsetComponent'.
      Child ClientApp\app\app.component.scss:
                                           Asset     Size  Chunks                    Chunk Names
            674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
            b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
          af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
           fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
            912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2\Asp2017.csproj(50,5): error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.

C:\Users\Matej\Documents\Visual Studio 2017\Projects\eAlarm Angular2 .NetCore2>`

And this is the problem:
`if (command == 'play')
            this.videoplayer.nativeElement.play();
        else if (command == 'pause')
            this.videoplayer.nativeElement.pause();
        else {
            this.videoplayer.nativeElement.pause();
            this.videoplayer.nativeElement.currentTime = 0;
        }`

How to use Renderer2 to control native videoplayer?

**Comment by digibum** [comment]
Solved, using wrong type of @ViewChild :/

**Comment by s-leonard** [comment]
Hi

I'm getting the same issue. What exactly did you have to change?

**Comment by garthtee** [comment]
I too am getting this error. Can anyone explain how the resolution?

**Comment by klgunarathne** [comment]
i have the same error.
error MSB3073: The command "node node_modules/webpack/bin/webpack.js --env.prod" exited with code 2.
is anyone know the solution.

**Comment by xVishera** [comment]
@klgunarathne 

Visual Studio > Tools > Options > Projects and Solutions > Web Package Management > External Web Tools

Check if here have a ref to nodejs install folder (like "C:\Program Files\nodejs")

This solved the problem for me.

**Comment by chinna510** [comment]
I have added node js path but i am facing same issue. can any one suggest me how to resolve this issue?

**Comment by nakinnubis** [comment]
I have mine resolved by re-installing nodejs and at the installation point i added entire feature to path. this resolve the issue for me.
