### ISSUE TITLE
Elements size issue

### ISSUE THREAD

**Issue by Karine-GitHub** [MarkPieszak/aspnetcore-angular2-universal#443]
Hi,

By including Echarts js library in your latest template (commit 73da5694435cf014218e57194aad0c718dffd168), I found an issue with elements size.
Echarts needs to know its parent size for drawing itself. I include it in my html like this:
`<div echarts [options]="opt" style="width: 100%; height: 400px;"></div>`

I fork your project and include my modifications here: [https://github.com/Karine-GitHub/aspnetcore-angular2-universal](url) for easier testing.
If you need more informations on Echarts:
- js library [https://github.com/ecomfe/echarts](url)
- my directive is based on [https://github.com/xieziyu/ngx-echarts](url) 

## **Initially loaded module**: (test with HomeComponent)
- in _**home.component.ts**_

      ngOnInit() {
          let tab = document.getElementById("myblock");
          console.error(tab.offsetWidth + '/' + tab.offsetHeight);
       }
- In _**home.component.html**_
`<blockquote id="myblock">`

Results: 0/0
When I inspect the element in developer tools, myblock has a size. The results is the same if I press F5 for refreshing the page. If I navigate to another page and come back to home, myblock has a size.

## **Lazy loaded module**: (test with _**lazy.component.ts**_)
  ` <blockquote id="myblock">`
 ...

      ngOnInit() {
          let tab = document.getElementById("myblock");
          console.error(tab.offsetWidth + '/' + tab.offsetHeight);
       }
Results: 1390/38
If I press F5, the result is 0/0. If I navigate to another page and come back to home, myblock has a size.

I have an old zipped version of your project. I think it's based on commit b3fcacd62b0272051eb213912633c8e37b5208f4. 
It's works fine with this version : the size is always correct (but Echarts does not work :./ that's why I try your latest version)

I know there a lot of changes between the two commits. I have already begun to look for the problem but I'm not really comfortable with HMR, webpack and co

If I set a fixed width to the chart, it works but I loose responsive design. I absolutely need to work with percentage.

I hope my explanations are enough clear. Thanks in advance for your help

**Comment by isaac2004** [comment]
Is this possibly a CSS issue? Like a new version of bootstrap changed a class name?

**Comment by Karine-GitHub** [comment]
It's not a bootstrap issue. I downgrade to Bootstrap 3 and the result is the same.

**Comment by MarkPieszak** [comment]
This is because things like `document` don't exist on the server, so it won't render anything there. You should have all things like that conditionally wrapped with isPlatformBrowser() and only run it then. You'll have to either set some sane defaults you could use for server render, or ignore the component entirely during SSRendering.

Hope that helps!
