### ISSUE TITLE
Problem in IIS 10 with translate of tokens

### ISSUE THREAD

**Issue by GetTaxSolutions** [MarkPieszak/aspnetcore-angular2-universal#444]
Not sure is it only for our IIS10 but when publish the project I can see the whole page without tokens. All places which contains token are empty in the page. Is it the same for you?

**Comment by MarkPieszak** [comment]
Which Tokens are missing?

**Comment by GetTaxSolutions** [comment]
Forgot it. I switched to classic application pool and all is working. Thanks
