### ISSUE TITLE
Not a bug, not a request, just a question on unit testing

### ISSUE THREAD

**Issue by mdelgadov** [MarkPieszak/aspnetcore-angular2-universal#446]
Hi, this is just a question about unit testing.
I'm trying to test the app.component that contains an injected constant @inject(REQUEST)J

Karma is raising the error: Failed: No provider for InjectionToken REQUEST!

I tried several things, like: 

providers: [REQUEST]
 in the test bed configure testing module but got:

Failed: Invalid provider for the NgModule 'DynamicTestModule' - only instances of Provider and Type are allowed, got: [?InjectionToken REQUEST?, ...]

I'm kinda new in this unit testing, so I'm out of sorts... thanks in advance.

Miguel Delgado

**Comment by isaac2004** [comment]
Have you tried since the Angular 5 merge

**Comment by MarkPieszak** [comment]
REQUEST comes from nguniversal/aspnetcore-engine are you making sure that's all provided to your TestBed?
