### ISSUE TITLE
Run as Windows Service

### ISSUE THREAD

**Issue by digibum** [MarkPieszak/aspnetcore-angular2-universal#447]
Is there any esy way to accoplish this?
TopShelf does not support .NET core.

**Comment by Crazyht** [comment]
Windows service can be made with Net Core (which is cross platform). 
I think best way to achieve this is used NSSM (https://nssm.cc/) or other product like this.

**Comment by MarkPieszak** [comment]
I'm not sure about this one, but I'd say @Crazyht might have a good suggestion there!
