### ISSUE TITLE
Lazy Loading, cannot find module? 

### ISSUE THREAD

**Issue by Defmetalhead** [MarkPieszak/aspnetcore-angular2-universal#449]
`{
        path: 'venue/:name/:id',
        loadChildren: './containers/activity-detail/activity-detail.module#ActivityDetailModule'
    },`

I keep getting the error "cannot find module" 

I used the example for Lazy module, but cannot seem to lazy load the module.

**Comment by MarkPieszak** [comment]
Is this in the middle of development? Sometimes when creating new NgModules, you might need to stop the process and re-do webpack/etc.

Also is it definitely named `ActivityDetailModule` and at that location, etc?

**Comment by Defmetalhead** [comment]
I did reload everything in Visual Studio several times. The path is 100% correct. I did end up getting the module to load but I had to use the following code. 


`{
        path: 'venue/:name/:id',
        loadChildren: () => System.import('../containers/activity-detail/activity-detail.module').then((file: any) => {
            return file.default;
        }),
        data: {
            shouldDetach: false,
            title: null
        }
    },`

Not sure why I could not find the module using the example listed within the project.

**Comment by MarkPieszak** [comment]
Is it an older version of the repo? That’s strange it should work like previously shown. The only other thing I can think of is that something in the webpack must be off(?)

**Comment by Defmetalhead** [comment]
I have an updated version of the repo, but I believe you are right about the webpack issue. Going to look at the config there. Thanks you.
