### ISSUE TITLE
Some examples of Unit Testing would be necessary.

### ISSUE THREAD

**Issue by nigul2009** [MarkPieszak/aspnetcore-angular2-universal#45]
Hi,

Maybe it's something I'm doing wrong with my tests, but when I run "karma" I get errors with the use of JavaScript ES6 +: let.

Log of some errors:

1. JavaScript ES6 +: let

```

> [default] Checking started in a separate process...
> Chrome 55.0.2883 (Windows 10 0.0.0) ERROR
>   Uncaught Error: Module parse failed: C:\PROJECTS\ARTYCO\CRM\Presentation\Client\containers\customers\customer-list.component.spec.ts Unexpected token (24:13)
>   You may need an appropriate loader to handle this file type.
>   |    describe('CustomerListComponent:', () => {
>   |       
>   |      let comp: BannerComponent;
>   |      let fixture: ComponentFixture<BannerComponent>;
>   |      let de: DebugElement;
>   at Client/karma-tests.ts:2234
> [default] Ok, 1.105 sec._

```

2. When mock Http
```

> [default] Checking started in a separate process...
> Chrome 55.0.2883 (Windows 10 0.0.0) ERROR
>   Uncaught Error: Module parse failed: C:\PROJECTS\ARTYCO\CRM\Presentation\Client\containers\customers\customer-list.component.spec.ts Unexpected token (32:39)
>   You may need an appropriate loader to handle this file type.
>   |               {
>   |                   provide: Http,
>   |                   useFactory: (pBackend: MockBackend, pOptions: BaseRequestOptions) => {
>   |                       return new Http(pBackend, pOptions);
>   |                   },
>   at Client/karma-tests.ts:2234
> [default] Ok, 0.985 sec.

```

Also, It will help an example of unit test for "rest-test.component" and some edit form.

If the component has depencies with some service, http, rxjs and use mocks, it will be perfect.

Regards!

**Comment by MarkPieszak** [comment]
You're right some real-life unit test examples would be great, it's on my timeline, but if anyone wants to beat me too it, PRs are always welcome ! :)

Karma runs the tests in the browser, so it looks like we need to make sure the correct *polyfills* are there as well (since it doesn't know what let/const etc are).  Making a note of everything.

Thanks for giving great feedback on everything! @nigul2009 Always appreciated.

**Comment by nigul2009** [comment]
Thank to you @MarkPieszak.

**Comment by MarkPieszak** [comment]
Fixed it up, updated the webpack.test file, basically it was `exclude: [/\.(spec|e2e)\.ts$/])` that was causing it not to transpile TS files, that was my mistake!

Added an example Home test to test everything out and looks like it's working now.

Now I just need to take the time to re-organize & clean up all these configs!

**Comment by nigul2009** [comment]
**Excellent News!!!**
I saw it very strange that spec files were excluded.
Thank you very much @MarkPieszak.
