### ISSUE TITLE
Autoprefixer

### ISSUE THREAD

**Issue by EricBichara** [MarkPieszak/aspnetcore-angular2-universal#450]
Would it be a good idea to add autoprefixer to this project?

**Comment by isaac2004** [comment]
@MarkPieszak this seems pretty straightforward. Any concerns?

**Comment by MarkPieszak** [comment]
Not really, is it something most/all people would want or need?

**Comment by isaac2004** [comment]
@MarkPieszak not sure on that, maybe it goes in a feature branch/PR
@EricBichara you are more than welcome to plug this in if you want
