### ISSUE TITLE
Slow server render due to long Http API call

### ISSUE THREAD

**Issue by mleader1** [MarkPieszak/aspnetcore-angular2-universal#452]
Hi,

I created a website using this repo however the performance is really poor - I'm experienced developer but with limited knowledge in angular, can anyone take a look at the load screenshot and point me to the right direction please?....

Thanks.

The website is  http://www.bellabags.co.uk/

It showed the root document load took 9.36 seconds to load 74.8k which is rendered by the nodejs on server. the server spec is pretty high. 

The load screenshot (Chrome)

![image](https://user-images.githubusercontent.com/5477158/32273354-07f3fce2-befa-11e7-9454-8fc784ac9245.png)

**Comment by hakonamatata** [comment]
Angular loads quite fast when I tested it. 

But the API in the background is really slow, taking 5 seconds to just do one simple GET call. So you need to fix the back-end API first of all. 

![image](https://user-images.githubusercontent.com/4003969/32274141-cc4ecd46-bf05-11e7-98b2-5859ef2c6b33.png)

**Comment by MarkPieszak** [comment]
Yes, renders are extremely quick, but just keep in mind that the render waits until all API calls & setTimeouts (or anything else Async) finishes, before rendering.

The two options you have, are either using `isPlatformServer()` and simply -not- making that big API call during server-renders, and having them only run on the Browser, or fixing the backend code to improve that APIs performance (either splitting it into multiple smaller API calls run in unison, or seeing whatever other performance bottleneck you're experiencing in SQL/whatever DB you're using.

Hope that helps!
