### ISSUE TITLE
Angular 5 - Merge or PR?

### ISSUE THREAD

**Issue by BillSheldon-HunterIndustries** [MarkPieszak/aspnetcore-angular2-universal#454]
With the launch of Angular 5, is the plan to update the main branch via a new PR or merge the existing Angular 5 branch into the master (with appropriate updates from RC)?

**Comment by MarkPieszak** [comment]
Yes I'll definitely merge it in there! Let me just make sure things are working and I'll get it in tomorrow morning 👍 Apologies on the delay.

I'll try to get HttpTransferCacheModule in there, if not I can get that in, in a later PR.

**Comment by naveedahmed1** [comment]
Sounds great! HttpTransferCacheModule is much needed :)

**Comment by MarkPieszak** [comment]
Merged ✨ 
but unfortunately couldn't fix ServerTransfer quickly enough, for the time being you could keep the existing Transfer technique we had already built-in to the project!

Hopefully we can figure out the root cause of why ServerTransfer is breaking server renders with ASPNET.

**Comment by naveedahmed1** [comment]
Thank you so much, but I think even the old Transfer technique is broken.
