### ISSUE TITLE
Lazyloading - Use of @nguniversal/module-map-ngfactory-loader

### ISSUE THREAD

**Issue by naveedahmed1** [MarkPieszak/aspnetcore-angular2-universal#456]
Shouldn't we use `@nguniversal/module-map-ngfactory-loader` for Lazy Loading.

**Comment by MarkPieszak** [comment]
That's for the Angular-CLI to generate the Map of lazy routes, not needed here :)

**Comment by maxisam** [comment]
@MarkPieszak But if we want to make cli work with asp.core universal. Is there any way I can add LAZY_MODULE_MAP main.server.ts?
