### ISSUE TITLE
How to include font-awesome

### ISSUE THREAD

**Issue by juliocgm83** [MarkPieszak/aspnetcore-angular2-universal#457]
Hello Team
I am having hard time trying to include font-awesome in the project, can you guys to provide an example that show how to do that? and what is the way to include a css file that an external  component required ?
Thanks

**Comment by ebeeb** [comment]
You add font-awesome to your package.json

In your app.component.scss file you then have to import it 
```
/* Import FontAwesome */
$fa-font-path: '~font-awesome/fonts';
@import "~font-awesome/scss/font-awesome";
```

I guess you'd have to import additional css files there as well.

**Comment by MaklaCof** [comment]
[Duplicate](https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/234).

**Comment by juliocgm83** [comment]
Thanks you guays

**Comment by bigWebApps** [comment]
hi all
I got issue
$fa-font-path: '~font-awesome/fonts' is not found
 and  font-awesome module is missing
but i added it to package.json
on azure build I got error
but on local everithyng good
how to refresh npm on azure?

**Comment by isaac2004** [comment]
@bigWebApps what is the folder structure in Azure? Maybe the mom folder isn't updating.
