### ISSUE TITLE
Best way to get this running in Visual Studio 2015? 

### ISSUE THREAD

**Issue by Defmetalhead** [MarkPieszak/aspnetcore-angular2-universal#466]
What is the best way to get this project running in VS2015? I can run the console commands to build and run, but I am not sure how to get this thing running with F5 in VS 2015. Any help would be appreciated.

**Comment by daveo1001** [comment]
I think you're out of luck :(
https://stackoverflow.com/questions/42337211/asp-net-core-support-in-visual-studio-2015

**Comment by MarkPieszak** [comment]
Yeah unfortunately Dave is right, you either need VS2017, or just make sure you have the Dotnet Core SDK 2.0 installed, and use VSCode instead :)

It's better than VS especially when it comes to front-end dev!
Hope that helps, cheers.
