### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by weskhaled** [MarkPieszak/aspnetcore-angular2-universal#467]
Hello
I am having hard time trying to include JWT in the project, can you guys to provide an example that show how to do that?
Thanks

**Comment by peterdobson** [comment]
@weskhaled  I've been using openiddict. Samples are here:

https://github.com/openiddict/openiddict-samples

**Comment by isaac2004** [comment]
There is an auth branch that uses JWT. It needs to be updated to Angular 5 however

**Comment by isaac2004** [comment]
closing and setting note to update JWT after 5.0 updates are done
