### ISSUE TITLE
asp-append-version="true" not appending version

### ISSUE THREAD

**Issue by consigliory** [MarkPieszak/aspnetcore-angular2-universal#471]
I pretty sure it is not related to this repo but not sure where to ask.  I upgrading existing project which was based on this template to latest. With .net 1.1.* asp-append-version="true" worked as it suppose but as it is now it does not append version. and it looks like all asp-* tags are ignored and sent to the browser as is. There is also in viewImports @using AspCoreServer cannot be resolved.
Any suggestion would be very helpful. Thanks in advance

**Comment by Flood** [comment]
See https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/465 and https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/470

**Comment by MaqSaid** [comment]
How would you do for angular .less files?
