### ISSUE TITLE
Support for Build Optimizer

### ISSUE THREAD

**Issue by naveedahmed1** [MarkPieszak/aspnetcore-angular2-universal#474]
Can you please also add the Build Optimizer ? https://www.npmjs.com/package/@angular-devkit/build-optimizer ?

Its the first thing highlighted in official release blog post of Angular 5 https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced , I am sure it would be a valuable addition :)

**Comment by isaac2004** [comment]
@naveedahmed1 feel free to open a PR, I bet alot of people would appreciate it.

**Comment by MarkPieszak** [comment]
This will come with #539 when we transition to the CLI based template. I don't have the bandwidth to have all this in now =/
