### ISSUE TITLE
Route CanActivate

### ISSUE THREAD

**Issue by juliocgm83** [MarkPieszak/aspnetcore-angular2-universal#477]
Hi Team

I am having issues trying to implement a Route CanActivate,  the error is:   
"NodeInvocationException: Can't resolve all parameters for AuthGuard: (?, [object Object], ?, [object Object]).
Error: Can't resolve all parameters for AuthGuard: (?, [object Object], ?, [object Object])."
Look like it is in the server side but I a not sure what I need to do.
does anyone know what is going on ? any example of an implementation ?
thanks

**Comment by isaac2004** [comment]
The auth branch has a Guard in it, but uses the old HttpModule. I plan on updating to HttpClient when I have time

**Comment by etatuev** [comment]
@juliocgm83 

I'm using `CanActivate` router hooks without any troubles at my project, which based on this repo. Try to check things that you're injecting into `AuthGuard`, looks like you have some circle dependency.

Some sample codes:

1) Some guard itself:
```
export abstract class AuthActivateGuard {
    constructor(protected router: Router, protected _auth: AuthService) { }

    guardIt(canFn: () => boolean, state: RouterStateSnapshot, redirect404: boolean = false): Observable<boolean> {
        return this._auth.userUpdated$.map(a => {
            const can = canFn();
            if (can) return can;

            if (redirect404) {
                this._auth.redirectToLogin([decodeURIComponent(state.url)]);
            } else {
                this.router.navigateByUrl('/not-found');
            }
        });
    }
}

@Injectable()
export class AnyUserExceptGuestGuard extends AuthActivateGuard implements CanActivate {
    constructor(router: Router, _auth: AuthService) {
        super(router, _auth);
    }

    canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
        return this.guardIt(() => this._auth.authorized && !this._auth.isGuest, state);
    }
}
```

2) Don't forget to add your Guard to providers section of ngModule
3) And at router configuration:

```
export const appRoutes: Routes = [
...
{ path: 'account', component: AccountComponent, children: accountRoutes, canActivate: [AnyUserExceptGuestGuard] },
...
]
```

**Comment by isaac2004** [comment]
@juliocgm83 let me know if you are still having this issue
