### ISSUE TITLE
[feature] Request to add CSRF token protection in AJAX calls

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#48]
I think, CSRF token protection is better than using a plain AJAX request.

It is a config and should be configured with this template, because it should be a default configuration.
More can be found here-

https://timdows.com/projects/preventing-csrf-in-asp-net-core-combined-with-angularjs/

I am requesting you to have a look at this link and let me know if this is a good idea or not :)

**Comment by AbrarJahin** [comment]
And also adding an example to pass data with rxjs AJAX will be more helpful 👍 if possible :)

**Comment by MarkPieszak** [comment]
Great idea!

Yes I think it would be nice to have the Login be a POST (even if fake login), and get the xsrf token setup on the .NET side. Angular sends it by default, but the backend needs to set it up for it to work.

**Comment by AbrarJahin** [comment]
Sure, thanks.

Currently, I am working on adding SignalR.

If it is added, then I will work on this.

Thanks 👍
