### ISSUE TITLE
Issue when prerendering a component with Observable.timer()

### ISSUE THREAD

**Issue by vyliniem** [MarkPieszak/aspnetcore-angular2-universal#483]
I have been struggling with this weird issue where a view with Observable.timer() works fine if it is navigated to from another route, but breaks when served as prerendered.

The view has a component that loads an item from backend, then displays a countdown timer and then reloads the item when countdown reaches zero. This is repeated until user either selects current item or navigates away.

I prepared a minimal case that demonstrates the issue:
[https://github.com/vyliniem/aspnetcore-angular2-universal/blob/timer-issue/ClientApp/app/containers/counter/counter.component.ts](https://github.com/vyliniem/aspnetcore-angular2-universal/blob/timer-issue/ClientApp/app/containers/counter/counter.component.ts)

The counter-component has a timer that increments the counter every 10 seconds. When opening the home-page and navigating to the counter-page it works as intended. But if you hit F5 while on the counter-page and when the view is loaded (as prerendered) nothing on the page updates and the increment-button does not work. However in console you can see the timer running, but no errors there or during the backend prerender.

**Comment by parys** [comment]
Because timer is endless function. And for SSR you are getting timeout error, because prerendering engine waits for end of this function. You should wrap all timers into this:
      if (isPlatformBrowser(this.platformId)) {
           call your timer function
        }

**Comment by vyliniem** [comment]
The function-call starting the timer is wrapped into platform-check and there are no prerender engine errors. Without the platform-check a timeout-error happens but that is not the case in here, something else goes wrong.

**Comment by vyliniem** [comment]
I was able to make the timer work with prerendered view using the method suggested in issue #489 (starting timer "outside of angular").

In addition to that I had to wrap the component state changing code into this.zone.run(() => { ... }) callback to make the view update.
