### ISSUE TITLE
Disable SSR for parts of site?

### ISSUE THREAD

**Issue by Pricelsss5386** [MarkPieszak/aspnetcore-angular2-universal#484]
I am using WOW.js to trigger some animations for some of the content on my site.  The issue i am having is  on load of the page,  the pre rendered page shows with the content.  Then when the page loads, that same content animates in.
An example might be i have a div:
<div class="wow fadeInLeft">Hello World</div>
So when the user goes to the page the pre render shows and it says Hello World, then when the actual page load the Hello World suddenly disappears and then animates back in like expected.
It just looks kind of bad.  I would like to disable this content so it doesn't show on the server rendered page.  Any idea how to do this?

**Comment by etatuev** [comment]
First way is to disable SSR for this route completely (as it states in topic header, but seems like it's not the correct solution for given problem). 
Second - add platform check on the front-end side, to skip loading of unwanted content on the server side. Looks like second way is more correct in that case, however, for reference I described both solutions below:

## First way, complete SSR disabling for parts of site
In this case you can add some condition into Index controller, where Prerendering starts. As far as we have request url at the back-end side, we can decide to use or to not use Prerender engine for this particular request.

_**Index action of HomeController:**_
```
if (Request.GetDisplayUrl().Contains("/some/route/you/want/to/do/without/SSR"))
{
     ViewData["ServerSideRenderingEnabled"] = false;
}
else
{
      ViewData["ServerSideRenderingEnabled"] = true;
      var prerenderResult = await Prerenderer.RenderToString(
         ...
}
```
_**Index.cshtml**_
```
@if ((bool)ViewData["ServerSideRenderingEnabled"])
{
    @Html.Raw(ViewData["SpaHtml"])
}
else
{
    <your-app-selector>Loading...</your-app-selector>
}

```

In case if `ServerSideRenderingEnabled` key of `ViewData` will have `false`, then prerendering will be skipped, and Angular app will be loaded as usual.

## Second way, front-end check

In this way you can check current platform, and disable unwanted component or child div with content using ngIf directive:

**_hello-world.component.ts_**
```
import { isPlatformServer } from '@angular/common';
import { PLATFORM_ID} from '@angular/core';
...
isServer = isPlatformServer(this.platformId);
constructor( @Inject(PLATFORM_ID) private platformId: Object) { }
...
```
**_hello-world.view.html_**
```
...
<child-component-with-awesome-animation *ngIf="!isServer">
</child-component-with-awesome-animation>
...
```

**Comment by Pricelsss5386** [comment]
Thank you, I will give this a shot!

**Comment by MarkPieszak** [comment]
Thank for for the excellent write-up there @etatuev !! 🍻

**Comment by etatuev** [comment]
Thanks :) I'm using your codes in production right now, and will try to help if I've got something to say.
@MarkPieszak

**Comment by MarkPieszak** [comment]
Another option here is wrapping the -entire- component with ng-container and conditionally checking. Sometimes this helps even more, as the component isn't touched at all.

```html
<ng-container *ngIf="!isServer">
  <child-component-with-awesome-animation>
  </child-component-with-awesome-animation>
</ng-container>
```

**Comment by filiptrivan** [comment]
> ## Second way, front-end check
> In this way you can check current platform, and disable unwanted component or child div with content using ngIf directive:
> 
> **_hello-world.component.ts_**
> 
> ```
> import { isPlatformServer } from '@angular/common';
> import { PLATFORM_ID} from '@angular/core';
> ...
> isServer = isPlatformServer(this.platformId);
> constructor( @Inject(PLATFORM_ID) private platformId: Object) { }
> ...
> ```
> 
> **_hello-world.view.html_**
> 
> ```
> ...
> <child-component-with-awesome-animation *ngIf="!isServer">
> </child-component-with-awesome-animation>
> ...
> ```
for this implementation I get this error: Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: 'false'.
