### ISSUE TITLE
Add an Auth Guard to Router

### ISSUE THREAD

**Issue by AndyTang0123** [MarkPieszak/aspnetcore-angular2-universal#485]
When I add  canActivate to the route. it return an internal server error:

> NodeInvocationException: Prerendering timed out after 30000ms because the boot function in '.../ClientApp/dist/main-server' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper.

Is that not supported on SSR?

**Comment by Crazyht** [comment]
Hi, 

I have routerguard too for authentication (Cookie) and it work correctly, I support you make something wrong in you guard. Could you provide guard ?

**Comment by AndyTang0123** [comment]
Thank you, I fixed the guard.
