### ISSUE TITLE
Webkit has stopped functioning correctly; Visual Studio will not be able to debug your app any further.

### ISSUE THREAD

**Issue by helloneoberg** [MarkPieszak/aspnetcore-angular2-universal#487]
Hi,
   I can compile the project successfully and i am using Chrome debugger.
   Everytime when the debugger is trigger, i will get a pop up stating "Webkit has stopped functioning correctly; Visual Studio will not be able to debug your app any further.".
   Visual Studio will show a tab" mdha:unknowncode"

   May i know how to solve this issue? Can anyone help?
   Thank you in advance

**Comment by Crazyht** [comment]
As workaround, you can disable "Enable Javascript debugging for ASP.NET (Chrome and IE)" option in VS Option (Debugging>General).

**Comment by helloneoberg** [comment]
Hi @Crazyht, noted. Thanks for the workaround.
