### ISSUE TITLE
How to link javascript to the template

### ISSUE THREAD

**Issue by helloneoberg** [MarkPieszak/aspnetcore-angular2-universal#488]
Hi,
   I found that the template had zoom issue on IOS "Add to Home Screen".
   Found a solution: https://github.com/sergiolopes/ios-zoom-bug-fix and it required to link javascript <script src="ios-zoom-bug-fix.min.js"></script>, can i know how to achieve in this template?
   Thank you

**Comment by Crazyht** [comment]
Quick answer is add your link to /Views/Shared/_Layout.cshtml.
More sophisticated is to handle this script by vendor file.

**Comment by helloneoberg** [comment]
Hi @Crazyht, thanks for the Quick Answer, i will try it out.
Can you give example of how to handle using vendor file?
Thank you so much

**Comment by Adondriel** [comment]
ok, so if you look at my branch, where i'm updating to bootstrap 4, you can add your JS to the rx-imports.ts file, and it seems to grab it and put it in the vendor file fairly well, from what I can tell... https://github.com/Adondriel/aspnetcore-angular2-universal/blob/c3962775d09b83678ab6ce3882db02a3d7f9989f/ClientApp/polyfills/rx-imports.ts

**Comment by helloneoberg** [comment]
Hi, @Adondriel, thanks for sharing to help.
i saw rx-imports.ts and you are tring to add 
//popper
import 'popper.js';

May i know which folder did you put your popper.js file?

For sharing purpose, i actually referenced my javascript file in Index.cshtml

<script src="~/dist/vendor.js" asp-append-version="true"></script>
@section scripts {
  
  <script src="~/dist/main-client.js" asp-append-version="true"></script>
  **<script src="~/scripts/ios/Cache/ios-clearcache_V0_0_4.js"></script>**
}

I created a folder "scripts/ios/Cache" under wwwroot and put the "ios-clearcache_V0_0_4.js" file in there.
The project is compiling and running well, but i am not sure if it is a good practice as well.

**Comment by Adondriel** [comment]
The popper.js is installed via npm, in the nodemodules folder.
