### ISSUE TITLE
Interval on ngOnInit

### ISSUE THREAD

**Issue by AndyTang0123** [MarkPieszak/aspnetcore-angular2-universal#489]
I tried to set an interval on the app component's ngOnInit,  I have checked isPlatformBrowser. It can redner the first login screen and the interval is working, but all the script seem not working.

I also tried to disable SSR, I can see that the interval is running but the app can not be rendered and stay on "loading..." screen.

**Comment by rtozati** [comment]
@AndyTang0123 

I have had this issue when trying to use setInterval and to solve the problem I needed to tell angular to ignore setInterval as the code example below:

`code:
import { isPlatformBrowser } from '@angular/common';
import { PLATFORM_ID, NgZone } from '@angular/core';
...
constructor(@Inject(PLATFORM_ID) private platformId, private zone: NgZone) {
    this.isBrowser = isPlatformBrowser(platformId);
}
...
ngOnInit() {
    if (this.isBrowser) {
        this.zone.runOutsideAngular(() => {
          NgZone.assertNotInAngularZone();
          setInterval(() =>  {
           ...
          }, interval);
        });
    }
}
...
`

I hope this helps.

**Comment by AndyTang0123** [comment]
Thank you!
