### ISSUE TITLE
[feature] Request to add REST API example with Entity Framework

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#49]
I like to add a simple CRUD REST API with Entity framework in this template.

I like to use SQLite as DB because it is portable and no configuration issue is needed to be faced.

Add after doing that, I like to make a PR.

Will you appreciate to add a REST API with entity framework here and merge that?

Thanks

**Comment by MarkPieszak** [comment]
Hey @AbrarJahin I'm sure a relatively simple example would be nice, we could even use it for the Login etc. Might get others going in the right direction!

**Comment by AbrarJahin** [comment]
Sure, thanks 🥇

**Comment by AbrarJahin** [comment]
PR made-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/55

**Comment by AbrarJahin** [comment]
Thanks 👍
