### ISSUE TITLE
Don't apply bootstrap over ngx-formly

### ISSUE THREAD

**Issue by GetTaxSolutions** [MarkPieszak/aspnetcore-angular2-universal#493]
I'm trying to add form in the project using ngx-formly:
[github.com/formly-js/ng-formly](url)
I added the packages and add the proper modules. It looks like that start to work but bootstrap doesn't apply the validation styles over the form. Form example when the field is required it have to go in red state but it didn't. My changes are in fork of your repository:
[https://github.com/GetTaxSolutions/aspnetcore-angular2-universal/commits/master](url)

Can you check why the styles are not applied when the form is invalid and required fields are empty?

**Comment by GetTaxSolutions** [comment]
After some fixes in ngx-formly it started to work with bootstrap version 3.3.7. Here is the example [https://stackblitz.com/edit/angular-hvklvh?file=index.html](url)
But it's not show validation red color in this project. May be some of the styles are not fully loaded here. The red color comes from forms.less in example. These styles are missed here. Do you now why?

**Comment by Adondriel** [comment]
ng-formly looks to have updated to bootstrap 4, so I don't think this is an issue on our end.
