### ISSUE TITLE
[Question] Removing Server Side Pre-rendering and enabling AOT

### ISSUE THREAD

**Issue by EmaGht** [MarkPieszak/aspnetcore-angular2-universal#494]
Hi Mark, I've been following this project since the very beginning but now i've been having problems catching up.

When making my project based on this I basically stripped out all the server side prerendering stuff, leaving me only with the clientBundle in Webpack.
Now, after months of development i tried to enable the then-broken AOT and it looks like everything's dandy, with the only exception that lazy modules are not being emitted.

I took a look at this:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/422

And that's exactly what I'm experienceing with my app... with the difference I can't comment any magical line in serverBundleConfig cause I don't have one.

So, is there some guideline I've been missing in making this project Client-Side only + AOT or by just keeping the client bundle it's expected to work with AOT without problems?

Thanks for your time,
Cheers

**Comment by amamh** [comment]
Hey, how did you get rid of server rendering? it's causing me a lot of pain when injecting services and I don't want to waste time on it. The guide on disabling server rendering is outdated and doesn't give much details beyond "SIMPLY remove X line" except X line doesn't exist.

**Comment by EmaGht** [comment]
I'm sorry, i did this a long time ago so i wouldn't know if it's easily doable with the current state of this starter...
The only things i remember are:
-Removing serverside bundle from webpack
-Everything moved to app.browser.module
-Also removal of HMR because it's just a pain. (Oh, i saved a wrong variable! Wait let me edit and save again... aaaaand let's wait 2 compilations run... <.<)

**Comment by EmaGht** [comment]
@amamh Yup, forgot about that, thanks for reminding me about it!

**Comment by Adondriel** [comment]
The repo has a tutorial, in the "gotchas" section, on how to disable SSR, I believe... it's a bit vague though, could probably use a little bit of work, since last I checked it.
