### ISSUE TITLE
Adding root styles.scss not working?

### ISSUE THREAD

**Issue by jfpicard123** [MarkPieszak/aspnetcore-angular2-universal#495]
Hi! I added a styles.scss under ClientApp and added the styles: ["styles.scss"] line to the .angular-cli.json file and the scss doesn't seem to make it into the bundle. What am I missing?

**Comment by davidsekar** [comment]
This project is not yet using Angular CLI to do the actual builds... CLI is presented to generate or scaffold the Angular components.

It currently builds based on the custom webpack config.

So If you want your global SCSS to be built... , then import it into the app.component.ts like below
import './assets/scss/style.scss';

But this will add all generated CSS within the JS bundle. (use **extract-text-webpack-plugin** to create a separate CSS file )
