### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by LiverpoolOwen** [MarkPieszak/aspnetcore-angular2-universal#496]
I have a question regarding the tree shareable modules. I am wondering which libraries we can apply this too? 

Also is there any other performance gains we can get in our apps? I have build a simple website for a client using the javascript services template and have made use of some of the features from this template. I get getting an initial 4mb of downloads. I appreciate how much the pre rending is helping this to seem like less but I am still in Google dev tools getting a really bad initial first render speed for my site. I think it is about 6 seconds(chrome simulates a 3g speed).

Thanks

**Comment by rtozati** [comment]
Hi @LiverpoolOwen ,

Are you using a release version to do these tests?

My main-client.js has about 260 kb and the vendor.js has 40 kb on the production environment.

**Comment by Adondriel** [comment]
Yea, make sure you are doing a production build, before testing this.
