### ISSUE TITLE
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: No NgModule metadata found for 'AppModule'

### ISSUE THREAD

**Issue by kislasi** [MarkPieszak/aspnetcore-angular2-universal#498]
hi guys,
when i building the project: `npm run build:prod` or `npm run build:vendor`
and then try to run the project: `dotnet run`
im getting this error (in run time):
**Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: No NgModule metadata found for 'AppModule'.
Error: No NgModule metadata found for 'AppModule'.**

any ideas?

**Comment by stephenlautier** [comment]
Its still not working since there are other issues, but, you shouldnt use `npm run build:vendor` after `npm run build:prod` as you are rebuilding vendors again without prod mode

this is what you should use
```bash
npm run build:prod
dotnet run
```
