### ISSUE TITLE
$fa-font-path: '~font-awesome/fonts' is not found on Azure build

### ISSUE THREAD

**Issue by bigWebApps** [MarkPieszak/aspnetcore-angular2-universal#499]
hi all
I got issue
$fa-font-path: '~font-awesome/fonts' is not found
and font-awesome module is missing
but i added it to package.json
on azure build I got error
but on local everithyng good
how to refresh npm on azure?

**Comment by peterdobson** [comment]
Do you have:

const nonTreeShakableModules = [
  'font-awesome/css/font-awesome.min.css',
];

in webpack.config.vendor.js?

**Comment by evgeniynet** [comment]
hi, yea I have,
but on azure deploy path not found

**Comment by Adondriel** [comment]
I think the variable is supposed to be:
`$icon-font-path: '~font-awesome/fonts/';`
This is what I have been using in my projects for awhile.
