### ISSUE TITLE
Question how to proceed with modules related to jQuery (ngx-owl-carousel)

### ISSUE THREAD

**Issue by GetTaxSolutions** [MarkPieszak/aspnetcore-angular2-universal#500]
Hello,

We want to add ngx-owl-carousel (https://github.com/mujtaba01/ngx-owl-carousel) in the project. This module require jQuery and I started to implement in with follow steps:
1. webpack.config.vendor.js - add jquery module in nonTreeShakableModules and turn on ProvidePlugin `new webpack.ProvidePlugin({ $: 'jquery', jQuery: 'jquery' })`
2. Install carousel modules `npm install owl.carousel "ngx-owl-carousel --save` 
3. Load CSS files - add them into app.component.scss `@import "~owl.carousel/dist/assets/owl.carousel.css";
@import "~owl.carousel/dist/assets/owl.theme.default.css";`
4. Register the module in app.module.ts file: 
`import { OwlModule } from 'ngx-owl-carousel';
.....
@NgModule({
  imports: [
    ........ ,
    OwlModule
]);`
5. Add owl-carousel component in some of our components to use it: 
        `<owl-carousel [options]="{items: 3, dots: false, navigation: false}">
              <div class="item"><img alt="" src="../../../content/images/aboutus-1.jpg"></div>
              <div class="item"><img alt="" src="../../../content/images/aboutus-2.jpg"></div>
              <div class="item"><img alt="" src="../../../content/images/aboutus-3.jpg"></div>
           </owl-carousel>`

We expect to see carousel module but the result is 

> OwlCarousel.html:1 ERROR ReferenceError: $ is not defined
    at new OwlChild (owl-child.component.js?bfe4:18)
    at createClass (vendor.js:12486)
    at createDirectiveInstance (vendor.js:12331)
    at createViewNodes (vendor.js:13769)
    at createEmbeddedView (vendor.js:13647)
    at callWithDebugContext (vendor.js:15060)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (vendor.js:14390)
    at TemplateRef_.createEmbeddedView (vendor.js:11734)
    at ViewContainerRef_.createEmbeddedView (vendor.js:11450)
    at NgIf._updateView (vendor.js:20125)

Obviously it doesn't find the jQuery. But when I'm trying to use in some of our components `@import * as $ from 'jQuery'` and invoke $(selector), it's there. Why  OwlModule doen't find it? Is my implementation correct or doing something wrong? 

We want to use exact owl-carousel because migrating old product from angular 1.0 to 5.0 using your universal project. I know that adding of jQuery is not good practice but have to migrate old code faster. If you can give me better advise how to do it most intelligent I will be very happy, I'm beginner with angular 5 and have some confusions yet which can't cleanup reading the project documentation. will appreciate if you extend it with details of all ways how to add external vendors and modules into the project. Will wait for your help and advises.

Thank you very much,
GetTaxSolutions team.

**Comment by MarkPieszak** [comment]
Take a look at some of the FAQ labels, this one on jQuery should have all the info you need!

https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/273

You need webpack to DefinePlugin for `$` in your case.

Hope that helps 👍
