### ISSUE TITLE
XMLHttpRequest not defined.

### ISSUE THREAD

**Issue by aneogiarcadix** [MarkPieszak/aspnetcore-angular2-universal#501]
I keep getting this error when pre-rendering is attempted-

> An unhandled exception occurred while processing the request.
> 
> Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: XMLHttpRequest is not defined
> at patchXHR 

this error accurs when `return await Prerenderer.RenderToString()` is called
I have followed the repo to make necessary changes to my application. What could be the possible reason for this error?

**Comment by MarkPieszak** [comment]
Are you using d3 or something that's using XMLHttpRequest behind the scenes? That's a browser-only API, so it's throwing errors during SSR.

You should wrap logic/code that's doing those things in the isPlatformBrowser() code, so it doesn't try to run those calls during SSR, that should fix it!

Hope that helps 👍
