### ISSUE TITLE
Polyfill.ts and Angular Animations  

### ISSUE THREAD

**Issue by Pricelsss5386** [MarkPieszak/aspnetcore-angular2-universal#502]
I want my angular animations to work in IE10 and IE11.  I uncommented the line:
import 'web-animations-js';
and did the npm install:
npm install --save web-animations-js
I now get this error:
NodeInvocationException: Prerendering failed because of error: ReferenceError: document is not defined

Any help would be appreciated!

EDIT:  I have made a lot of changes to this project, so for my sanity, i downloaded a clean version of this project and did the above steps and I still get the error.

**Comment by MarkPieszak** [comment]
I see the problem!
So can you move those, and put them inside of browser.polyfills instead?

The server has no concept of animations, so when those file get populated in Node, it throws those errors.

Give that a shot, that should fix it! 👍

**Comment by nfdevil** [comment]
I can confirm that this is the solution. Had the same error and moved the line
```
import 'web-animations-js'; // Run `npm install --save web-animations-js`.
```
to the browser.polyfills.ts.

I guess this can be closed.
