### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by punkouter** [MarkPieszak/aspnetcore-angular2-universal#503]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Missing binding C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor\win32-x64-57\binding.node	Asp2017	C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\Module build failed	1	
Error		Missing binding C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor\win32-x64-57\binding.node	Asp2017	C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\Module build failed	1	
Error	MSB3073	The command "node node_modules/webpack/bin/webpack.js" exited with code 2.	Asp2017	C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\Asp2017.csproj	38

**Comment by svoychik** [comment]
I had the similar problem yesterday after updating nodeJs to the latest version (I had installed all packages using nodeJs 6.x.x version). 
I deleted node_modules, package-lock.json and executed `npm i `

**Comment by punkouter** [comment]
Still cant get it to work :(

An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: Error: Module build failed: Error: Missing binding C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor\win32-x64-57\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 8.x

Found bindings for the following environments:
- Windows 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
at module.exports (C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\binding.js:15:13)
at Object.<anonymous> (C:\Users\Matt_Herb\Downloads\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\index.js:14:35)
at Module._compile (module.js:635:30)

**Comment by peterdobson** [comment]
Did you run:

npm rebuild node-sass --force

?

**Comment by Sosunov93** [comment]
Keep in mind that if you are working with visual studio - it will use built-in nodejs instead of installed. I'd recommend you to do the following:
[https://stackoverflow.com/a/43850262/5767872](https://stackoverflow.com/a/43850262/5767872)
Dont forget to reinstall the packages after that.

**Comment by MarkPieszak** [comment]
Yes as @Sosunov93 recommended, make sure VS is using your $PATH variable'd Node, not the (really old) version that comes built-in. I hope they fix this bug soon, it should always use $PATH first.

Make sure you do a `node --version` to see that you're actually using a newer version, I'd suggest installing everything from command-line regardless.

If you're using `nvm` or some other node version manager, the versions are all sandboxed, so you may of closed/re-opened that terminal, which could be causing the node-sass issue as well. In that case, a little `npm rebuild node-sass --force` will fix it right up.

Hope that helps!
