### ISSUE TITLE
What is the meaning of Scripts object in package.json file

### ISSUE THREAD

**Issue by MaklaCof** [MarkPieszak/aspnetcore-angular2-universal#505]
I need to tweak build system, but before I do that I need to understand why is this in `package.json`:
```
  "scripts": {
    "lint": "tslint -p tsconfig.json",
    "test": "npm run build:vendor && karma start ClientApp/test/karma.conf.js",
    "test:watch": "npm run test -- --auto-watch --no-single-run",
    "test:ci": "npm run test -- --browsers PhantomJS_custom",
    "test:ci:watch": "npm run test:ci -- --auto-watch --no-single-run",
    "test:coverage": "npm run test -- --coverage",
    "build:dev": "npm run build:vendor && npm run build:webpack",
    "build:webpack": "webpack --progress --color",
    "build:prod": "npm run clean && npm run build:vendor -- --env.prod && npm run build:webpack -- --env.prod",
    "build:vendor": "webpack --config webpack.config.vendor.js --progress --color",
    "clean": "rimraf wwwroot/dist clientapp/dist"
  },

```
I thought it has to do something with publishing application (to perform AOT build), but nothing indicates  in `Asp2017.csproj`: `<Target Name="DebugRunWebpack" BeforeTargets="Build" ...` that anything is used from `package.json`.

**Comment by MarkPieszak** [comment]
These are there just for when you're doing local development, you can build packages, run tests, lint, or even package a prod build (if you set your `set ASPNETCORE_ENVIRONMENT=Production` (or Development) as well.

Hope that helps!

The csproj just manually calls node_modules/webpack configs.
