### ISSUE TITLE
Update angular/material support status

### ISSUE THREAD

**Issue by odahcam** [MarkPieszak/aspnetcore-angular2-universal#508]
With Angular 5 and Material 2 a lot of things have changed, specially with Material 5, which is in its third release candidate `5.0.0-rc.2` (at the time of writing).

People are saying that Material 2 works fine now, also maybe 5 works like a charm, you can see that #20, #402 or https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/202#issuecomment-295860289.

I'm creating the issue because README says that SSR is not possible with NgMaterial, but people say it's possible, I wanna clear the things up. 😄 

Can we validate #510?

**Comment by MarkPieszak** [comment]
Will do, I'll take a look soon - as far as I know now, Material works (for the most part) I think there are still a few bumps for some of the components.

**Comment by Adondriel** [comment]
I believe you should be able to add Material design now. I believe they finally updated NgMaterial to allow for SSR, from what I read recently. So, yea, it SHOULD be possible. Personally, I think their class names are too damn long, which is the biggest thing preventing me from using it, lol.

**Comment by odahcam** [comment]
I'm rendering @angular/material2 in server side.

**Comment by Adondriel** [comment]
Awesome!

**Comment by odahcam** [comment]
Sure! I'm trying to create a boilerplate like project, but I gotta finish some tasks first. I'll certanty share the link to the project when published and try to share some code ASAP.

For now I leave this print: 
![image](https://user-images.githubusercontent.com/3942006/34277362-87679182-e68c-11e7-949c-d28847b25b51.png)

**Comment by Adondriel** [comment]
Awesome! thanks for helping out! :D I like the look of material, in some cases. They have some nice ideas, in terms of design, but god I HATE it on mobile, having to reach alllll the way to the top left to get to the menu on mobile is stupid, and annoying. I really do miss the android menu button. :(

**Comment by odahcam** [comment]
One of the cool features of material design implementations is the drawer, which allows you to drag from the left edge of the screen to the right side, openning a sidebar (the menu in this case). Unfortunatelly, the material2 project stills not have this feature. *laughts*

I was thinking here if we could implement a generatorwith **Yeoman** like this project: https://github.com/tycomo/generator-pwa-angular-core

**Comment by ruant** [comment]
Is there a HOW TO - Guide available since this issue has been closed?

From the README.md it says:
`We do not have a tutorial available for this yet.`

**Comment by ElderJames** [comment]
Hi there,
I'm building a project contains features like asp.net core,angular 6,material2,ssr in https://github.com/ElderJames/aspnetcore-material-universal.
Welcome to  contribute  😄
