### ISSUE TITLE
How to add new JS files in vendor

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#51]
Hi @MarkPieszak ,
I want to add new CSS and JS files in vendor.js and vendor.css

As for example I want to add this - https://www.npmjs.com/package/signalr-no-jquery

As a JS for vendor.js

What do I need to do for that?

Will I need to add the new library here-
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L45

Or need to do anything else.

Thanks in advance for helping

**Comment by AbrarJahin** [comment]
And also, is this 3 lines is OK-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L46
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L47
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L48

**Comment by MarkPieszak** [comment]
At the moment yes, but if you add them there it will be accessible by client and server code. But looks like it doesn't have jQuery so it should work! 

I'll review the latest SignalR stuff soon as well, thanks again.

Eventually I might clear up that vendor webpack and just use a vendor.ts file bundle and pack it like normal.

Let me know if that clears it up!

**Comment by AbrarJahin** [comment]
SignalR client side is not implemented.

So, I am implementing it.

To do that, I need to add jQuery with Angular2.

I am a little kind of stuck here.

Can u please help to add jQuery here?

Providing procedure or link would be enough.

Thanks

**Comment by MarkPieszak** [comment]
Sure let me take a look, is that the piece missing for the SignalR implementation?

**Comment by AbrarJahin** [comment]
Yes.

But before that, please resolve the PR, because I have made an experiment and it failed, so need to fix that.

That is why I have made the PR.

Thanks
