### ISSUE TITLE
Can't make sample repo to run

### ISSUE THREAD

**Issue by asfaya** [MarkPieszak/aspnetcore-angular2-universal#514]
Hi there,
Thanks for all the hard work you put here.
I downloaded a ZIP of the repo, unzipped in a local folder
Tried running with F5 and got errors of "module not found"
I manually ran a: npm install && npm run build:dev && dotnet restore

Now I'm getting a different error:

An unhandled exception occurred while processing the request.
NodeInvocationException: ENOENT: no such file or directory, open 'C:\Projects\MyApp\app.component.html'
Error: ENOENT: no such file or directory, open 'C:\Projects\MyApp\app.component.html'

Seems that prerrendering is not being able to locate the right root for the ClientApp.
Any clues on what I could be missing?
Thanks!

**Comment by isaac2004** [comment]
What gets into your wwwroot folder after webpack?

**Comment by asfaya** [comment]
Hi Issac: 
The content is: 

+assets
+dist
-favicon.ico

Then, inside dist:
-main-client.js
-main-client.js.map
-vendor.js
-vendor.js.map

**Comment by isaac2004** [comment]
I am a bit confused since there is no appcomponent.html at root. You have made no changes to the directory? I just downloaded a zip of the repo and ran

````
npm install
dotnet restore
 npm run build:dev
dotnet run
````

And it works just fine

**Comment by asfaya** [comment]
But is it ok that the app tries to find the files in the root folder?
Seems that copying files to the root manually makes it work, but doesn't feel good that the files are copied there

**Comment by isaac2004** [comment]
You should not need to alter the directory structure at all. Package.json and csproj is expecting a certain structure.

**Comment by asfaya** [comment]
I know that, but just curious on why is dotnet trying to serve files from root and not from wwwroot

**Comment by isaac2004** [comment]
I would need to see this as it is not my experience.

**Comment by asfaya** [comment]
I started all over again and second time is working.
Later I'll se if I can compare them to see what I can find that is different
