### ISSUE TITLE
Lazy Loaded demo not really lazy.

### ISSUE THREAD

**Issue by electricessence** [MarkPieszak/aspnetcore-angular2-universal#523]
As suggested by the resultant text, I viewed my network monitor:

The ```0.js``` is "late" loaded after the initial scripts but happens before I click on the tab to display it.

**Comment by Rogerio-Soares** [comment]
Hi,
It is probably du to the [preloadingStrategy: PreloadAllModules](https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/ClientApp/app/app.module.ts#L141).
Regards

**Comment by MarkPieszak** [comment]
@Rogerio-Soares is correct, that's used also to help prevent some flicker (that can occur from time to time), try removing that to see if everything works for you as expected!

Hope that helps.
