### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by tishansoft** [MarkPieszak/aspnetcore-angular2-universal#530]
Hi 

I downloaded your repository, and I end up with this error.

can some one help how to fix this? I haven't changed anything.

Thanks
Shan

An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: Error: Module build failed: Error: Missing binding C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor\win32-x64-59\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 9.x

Found bindings for the following environments:
- Windows 64-bit with Node.js 5.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
at module.exports (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\binding.js:15:13)
at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\index.js:14:35)
at Module._compile (module.js:660:30)
at Object.Module._extensions..js (module.js:671:10)
at Module.load (module.js:573:32)
at tryModuleLoad (module.js:513:12)
at Function.Module._load (module.js:505:3)
at Module.require (module.js:604:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\sass-loader\lib\loader.js:3:14)
at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:121441:7)
at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30)
at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:121428:22)
at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30)
at C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:110064:22
at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:110076:2)
at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30)
at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:119516:73)
at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30)
at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:114618:70)
Current directory is: C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

Stack Query Cookies Headers
NodeInvocationException: Prerendering failed because of error: Error: Module build failed: Error: Missing binding C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\node-sass\vendor\win32-x64-59\binding.node Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 9.x Found bindings for the following environments: - Windows 64-bit with Node.js 5.x This usually happens because your environment has changed since running `npm install`. Run `npm rebuild node-sass --force` to build the binding for your current environment. at module.exports (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\binding.js:15:13) at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\node-sass\lib\index.js:14:35) at Module._compile (module.js:660:30) at Object.Module._extensions..js (module.js:671:10) at Module.load (module.js:573:32) at tryModuleLoad (module.js:513:12) at Function.Module._load (module.js:505:3) at Module.require (module.js:604:17) at require (internal/module.js:11:18) at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\node_modules\sass-loader\lib\loader.js:3:14) at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:121441:7) at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30) at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:121428:22) at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30) at C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:110064:22 at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:110076:2) at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30) at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:119516:73) at __webpack_require__ (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:26:30) at Object.<anonymous> (C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master\ClientApp\dist\main-server.js:114618:70) Current directory is: C:\Training\ASP.NETANGULAR\SuperCoolApp\aspnetcore-angular2-universal-master
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance+<InvokeExportAsync>d__13.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.NodeServices.NodeServicesImpl+<InvokeExportWithPossibleRetryAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Asp2017.Server.Helpers.HttpRequestExtensions+<BuildPrerender>d__1.MoveNext() in HttpRequestExtensions.cs
+
      return await Prerenderer.RenderToString(
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
AspCoreServer.Controllers.HomeController+<Index>d__0.MoveNext() in HomeController.cs
+
      var prerenderResult = await Request.BuildPrerender();
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.GetResult()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware+<Invoke>d__3.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware+<Invoke>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

Show raw exception details

**Comment by mcgri** [comment]
I checkout version ng4 this morning and everything works for me...

Did you follow error instructions?

```
This usually happens because your environment has changed since running npm install.
Run npm rebuild node-sass --force to build the binding for your current environment.
```
have you run dotnet restore?

**Comment by jecourtney** [comment]
Make sure you have at least Node 6.x or higher

**Comment by MarkPieszak** [comment]
Yes, make sure you have Node 6+ installed, ideally the latest & greatest.

When you install that, run the script like it says in the error,  to build the binding for your current environment. (It's from node-sass)

```
npm rebuild node-sass --force
```

Thank you @mcgri @jecourtney  👋
