### ISSUE TITLE
opening Asp2017.csproj in VS 2015

### ISSUE THREAD

**Issue by jaroberts-krittermedia-com** [MarkPieszak/aspnetcore-angular2-universal#533]
I'm trying to open the repo in vs 2015 and getting an error XML namespace of project must be the MSBuild. pelase add xmls="htt//:schemas.microsoft.com.......to project element

forgive me, but new to vs 2015, how to do this and why is this happening.

**Comment by mcgri** [comment]
@jaroberts-krittermedia-com  It could be related to https://github.com/dotnet/core/issues/685

**Comment by isaac2004** [comment]
closing as there is no VS2015 support with this repo
