### ISSUE TITLE
Server side rendering is not working

### ISSUE THREAD

**Issue by jwdelgado** [MarkPieszak/aspnetcore-angular2-universal#535]
I ran the Angular 5.0 Universal & ASP.NET Core advanced starter-kit example, but it only runs the browser version. The Server version that is supposed to be having the server side rendering is not working for me.

Could you please specify how to turn it on as it is not yet turned on. 

Also, the working example : http://aspnetcore-angular2-universal.azurewebsites.net/home
has the SSR. If I check on the view source, I could see the rendered html tags in the app-root. The example for Angular 5 does not seem to work.

**Comment by tenderloin420** [comment]
I'm also keen to use SSR with ng5, but it looks like it's still a work in progress.

From the Angular 5 branch readme: "NOTE Currently issues with SSR and 5.x - SSR temporarily removed"

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/angular-5.0-WIP/README.md

**Comment by MarkPieszak** [comment]
5.0 template now merged into Master via #538 
Angular-CLI template will be the next great upgrade to improve everything. #539 to track that

**Comment by MMilan19** [comment]
@MarkPieszak , I have built application using Asp.Net core 2.0 with  Angular Template in VS2017 with AspNetCoreSPA. After publish site, Everything is working fine except Server side rendering when I access website with domain name or Server IP address. Although, when I accessing using local host on server, server side is working. I am not able to figure out why it is behaving like this. please help me to get rid of  it. 
Waiting for your prompt replay,
Thanks,
Milan
