### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by simplymequeeny** [MarkPieszak/aspnetcore-angular2-universal#536]
HI I do not want to use bootstrap (ngx-bootstrap) so i removed it in the places it is used.  I was able to build the project successfully but I got a warning.

D:\\aspnetcore-angular2-universal>npm install && npm run build:dev && dotnet restore
npm WARN aspnet-webpack@2.0.1 requires a peer of webpack@^1.13.2 || ^2.1.0-beta but none is installed. You must install peer dependenci
es yourself.
npm WARN angular4-aspnetcore-universal@1.0.0-rc3 No repository field.
npm WARN angular4-aspnetcore-universal@1.0.0-rc3 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"
os":"win32","arch":"x64"})

up to date in 16.941s

> angular4-aspnetcore-universal@1.0.0-rc3 build:dev D:\aspnetcore-angular2-universal
> npm run build:vendor && npm run build:webpack

> angular4-aspnetcore-universal@1.0.0-rc3 build:vendor D:\aspnetcore-angular2-universal
> webpack --config webpack.config.vendor.js --progress --color

env = undefined
[1] Hash: dfcb7b73d0e16d1637d436f7efe08789cbdc4e8d
Version: webpack 3.10.0
Child
    Hash: dfcb7b73d0e16d1637d4
    Time: 5635ms
        Asset     Size  Chunks                    Chunk Names
    vendor.js  3.09 MB       0  [emitted]  [big]  vendor
Child
    Hash: 36f7efe08789cbdc4e8d
    Time: 5605ms
        Asset     Size  Chunks                    Chunk Names
    vendor.js  2.97 MB       0  [emitted]  [big]  vendor

> angular4-aspnetcore-universal@1.0.0-rc3 build:webpack D:\aspnetcore-angular2-universal
> webpack --progress --color

[1] Hash: b5c90ae164a33ab9a49224873658318dd557f0be
Version: webpack 3.10.0
Child
    Hash: b5c90ae164a33ab9a492
    Time: 11036ms
                 Asset    Size  Chunks                    Chunk Names
        main-client.js  560 kB       0  [emitted]  [big]  main-client
    main-client.js.map  688 kB       0  [emitted]         main-client
Child
    Hash: 24873658318dd557f0be
    Time: 16605ms
             Asset     Size  Chunks                    Chunk Names
    main-server.js  9.29 MB       0  [emitted]  [big]  main-server

    **WARNING in ./node_modules/@angular/core/@angular/core.es5.js
    5659:15-36 Critical dependency: the request of a dependency is an expression
     @ ./node_modules/@angular/core/@angular/core.es5.js
     @ ./ClientApp/boot.server.ts

    WARNING in ./node_modules/@angular/core/@angular/core.es5.js
    5675:15-102 Critical dependency: the request of a dependency is an expression
     @ ./node_modules/@angular/core/@angular/core.es5.js
     @ ./ClientApp/boot.server.ts**
  Restore completed in 43.98 ms for D:\aspnetcore-angular2-universal\Asp2017.csproj.
  Restore completed in 112.68 ms for D:\aspnetcore-angular2-universal\Asp2017.csproj.
How can i fix this?

Note:  the project still runs even with this warning (able to access the web app via localhost:5000/home).

Is it possible to use material design instead of bootstrap?

**Comment by MarkPieszak** [comment]
Glad to hear you're all set!
