### ISSUE TITLE
Error when create build for version 5.0.0

### ISSUE THREAD

**Issue by GetTaxSolutions** [MarkPieszak/aspnetcore-angular2-universal#540]
Hello,

I applied your changes to version 5.0.0. The project continue to work fine in develop mode, but when webpack start to create files for PROD it give me follow error:

> Version: webpack 3.10.0
> Child
>     Hash: 038d75b6a3d922f8aad5
>     Time: 6692ms
>              Asset     Size  Chunks             Chunk Names
>     main-client.js  2.48 kB       0  [emitted]  main-client
> 
>     ERROR in Error during template compile of 'AppModuleShared'
>       Function expressions are not supported in decorators in 'ɵ0'
>         'ɵ0' contains the error at ClientApp\app\app.module.ts(190,39)
>           Consider changing the function expression into an exported function.

The row 390 in the code is in bold:
FormlyModule.forRoot({
      validationMessages: [
        { name: 'required', message: 'This field is required' },
        **{ name: 'maxlength', message: (error, field: FormlyFieldConfig) => 'The limit of ' + `${field.templateOptions.maxLength} characters is reached` }**
      ],

**Comment by MarkPieszak** [comment]
That's just an AoT error.
AoT can't statically analyze inline functions like that, you need to make sure you move that up above somewhere, and `export` it.

Similar to how we handle createTranslateLoader in app.main.

```ts
export function maxLengthMessage(error, field: FormlyFieldConfig) {
  return `The limit of ${field.templateOptions.maxLength} characters is reached`;
}

{ name: 'maxlength', message: maxLengthMessage }
```

Hope that helps!

**Comment by GetTaxSolutions** [comment]
It was helpful for us. thank you
