### ISSUE TITLE
Create gitter chat

### ISSUE THREAD

**Issue by odahcam** [MarkPieszak/aspnetcore-angular2-universal#553]
Gitter would be great for devs to get help, contribute and dicuss about new features without making noise at the issue tracker.

**Comment by RZeni** [comment]
@MarkPieszak Can you set this up? I would do it and transfer ownership to you once you joined but I can only link to a repo during creation and not afterwards. Since you are the owner it would be best if you could set up the gitter linked to the repo. Thanks!

**Comment by MarkPieszak** [comment]
Gitter chat added here: https://gitter.im/aspnetcore-angular2-universal/

Added badge on homepage as well! :+1:
@RZeni 

@odahcam @Flood @BillSheldon-HunterIndustries
