### ISSUE TITLE
State Rehydration with TransferState

### ISSUE THREAD

**Issue by Flood** [MarkPieszak/aspnetcore-angular2-universal#555]
Since we upgraded to the latest version of this repo our state rehydration fails. 

Found this in app.module.server

```
// HttpTransferCacheModule still needs fixes for 5.0
    //   Leave this commented out for now, as it breaks Server-renders
    //   Looking into fixes for this! - @MarkPieszak
    //ServerTransferStateModule
```

Any ideas when this will be fixed? Can you @MarkPieszak  point me in the right direction and then I can investigate as well.

**Comment by stephenlautier** [comment]
I'm trying to look into this as well, any help would be appreciated.

What i've discovered so far:
 - when adding `ServerTransferStateModule` - no html is outputted, i was debugging to understand why its returning `""` , what i've noticed is that within angular https://github.com/angular/angular/blob/master/packages/platform-server/src/utils.ts#L63 its actually outputted.
 - I was experimenting to add my own service (or register `TransferState`) alone, however the `moduleRef` is not exposed if it was i could fix it. As i managed to hack it however without using the new module [renderModuleFactory](https://github.com/angular/angular/blob/master/packages/platform-server/src/utils.ts#L98) and `@nguniversal/aspnetcore-engine` (which im not happy to do)

**Comment by stephenlautier** [comment]
update: what i noticed is when registering `ServerTransferStateModule ` the universal [beforeAppSerialized](https://github.com/angular/universal/blob/master/modules/aspnetcore-engine/src/main.ts#L107) is not being triggered.. cant understand why because both uses `multi: true`

**Comment by stephenlautier** [comment]
update#2

So pretty much I have a working solution and got it working on our project, but it requires some changes, ideally in both angular and universal
 - Submitted an issue on angular https://github.com/angular/angular/issues/22049 - its a very simple change but its breaking, not sure if they agree to do so
 - Requires some changes in universal `aspnetcore-engine` tomorrow I will try to submit a PR to it, and move the breaking change temp in it gets accepted `TransferState` will work for aspnet 🎆

**Comment by MarkPieszak** [comment]
@stephenlautier You rock!
Let me talk to the team and see if we can push in those changes asap so we can publish a new version of the engine etc out!

**Comment by Flood** [comment]
@MarkPieszak Any updates?

**Comment by Flood** [comment]
It seems to work! State rehydration works on my project but SSR does not. It breaks on

ERROR ReferenceError: Event is not defined (see https://github.com/angular/universal/issues/844)

However, SSR works on this repo. I guess it will work on my project when the Event issue is solved.

**Comment by MarkPieszak** [comment]
Excellent 👍 
That might be coming from a third party library you have (?)

Just add `global['Event'] = null;` to your `boot.server.ts` file, and that should help the issue.

A lot of times you need to mock/stub things in Node to handle crazy global (typically browser-only items). Unfortunately a lot of people forget you should always check for the existence of global variables :(

Closing as TransferState works now 💃
