### ISSUE TITLE
Deploying template based app to Service Fabric

### ISSUE THREAD

**Issue by johnkattenhorn** [MarkPieszak/aspnetcore-angular2-universal#56]
Debugging and Running the template locally works great on my local machine, however when I deploy the same app into a Service Fabric cluster is fails with the following error

`Exception: Call to Node module failed with error: If you use aspnet-prerendering >= 2.0.0, you must update your server-side boot module to call createServerRenderer. Either update your boot module code, or revert to aspnet-prerendering version 1.x`

I suspect this is because it's looking for a node_module which I'm not shipping as part of the SF packaging process but I would have though any files that were needed would be bundled and be present under the `dist` folder. 

Can anyone recommend what I could do to track down what I'm missing, seems like shipping the node_modules folder into the cluster is a bad idea.

**Comment by johnkattenhorn** [comment]
If I disable the Server Side rendering then it works well both inside and outside SF. I'm going to see if I can monitor the file system and look for files it asks for but cannot find.

**Comment by MarkPieszak** [comment]
Is it setup to be using Node 4+? Wondering if that might be playing a part in this as well.

Interesting the app works otherwise though, since that is a dependency and it seems like everything else installed. Let me know! Looking into it on my end as well.

**Comment by johnkattenhorn** [comment]
Ah good, question, I'm going to sound dumb now but to use SSR I would need to the SF cluster machines to have Node installed right ?

This might not be an option for us.

**Comment by MarkPieszak** [comment]
Not dumb at all! Yes so what it does is creates a small node process to run Universal (which ends up serializing the app).

I believe it's possible on SF isn't it? 

At worst case for now, you can simply disable SSR for now, I'll see if I can get some more information on this issue.

**Comment by johnkattenhorn** [comment]
Oh yes, I forgot about this capability, thanks for pointing this out and being so responsive :-)

We are early days in this project so I'll disable for now and move this into the backlog. 

Loving the template, looking forward to showing some of my web developers some of the pain this removes for us.

**Comment by MarkPieszak** [comment]
@johnkattenhorn Did you update the `aspnet-prerendering` by any chance in your package.json? What version do you have in there?

**Comment by johnkattenhorn** [comment]
I didn't as I was trying to be careful about mimicking exactly the same versions from the repo. My npm reports 1.0.7.

**Comment by johnkattenhorn** [comment]
I'm lucky it's didn't work on my developer workstation as I have node installed otherwise I would have pushed the code and would have failed inside the cluster right now :-)

**Comment by MarkPieszak** [comment]
Strange!  That error comes from the 2.x *warning*, but the repo is still calling the 1.x signature. Not sure how that error is appearing. Interesting

**Comment by johnkattenhorn** [comment]
![image](https://cloud.githubusercontent.com/assets/616249/22340022/e6540556-e3e3-11e6-8921-dd89186e61f3.png)

What's a good way to double check I've not made a mistake ?

**Comment by MarkPieszak** [comment]
That looks fine there!
Hmm

Also someone told me this about SF & Node: "when we had a node service on SF, we simply embedded the node.exe." I'm not sure if that helps you any? I'm not familiar with SF unfortunately, haven't gotten around to using/experimenting with it yet.

**Comment by johnkattenhorn** [comment]
I think embedding would be the best way going forward. I've added an item to our backlog but server-side rendering is not high on our project list right now (it will be though for something else).
