### ISSUE TITLE
Testing - Karma unable to find spec files located under containers sub folders

### ISSUE THREAD

**Issue by simplymequeeny** [MarkPieszak/aspnetcore-angular2-universal#561]
Hi,
I was able to run a test on app.component.spec.ts (as a sample), but when I created another spec file under containers folder (ClientApp/app/containers).  Karma unable to find the spec file.  
I am not that familiar with karma test runner.  Is there anything I should do to run the spec files in any subfolders?
Thanks

**Comment by MarkPieszak** [comment]
That's strange, it should work for anything under `/ClientApp/`.
Does your new unit test file end with `.spec.ts`?

**Comment by simplymequeeny** [comment]
yes. i didnt modify on the test config files but here's what i have.

**boot-tests.js**
Error.stackTraceLimit = Infinity;
// Load required polyfills and testing libraries
require('core-js'); // Added for Phantomjs
require('zone.js');
require('zone.js/dist/long-stack-trace-zone');
require('zone.js/dist/proxy.js');
require('zone.js/dist/sync-test');
require('zone.js/dist/jasmine-patch');
require('zone.js/dist/async-test');
require('zone.js/dist/fake-async-test');
const testing = require('@angular/core/testing');
const testingBrowser = require('@angular/platform-browser-dynamic/testing');

// Prevent Karma from running prematurely
__karma__.loaded = function () {};

// First, initialize the Angular testing environment
testing.getTestBed().initTestEnvironment(
    testingBrowser.BrowserDynamicTestingModule,
    testingBrowser.platformBrowserDynamicTesting()
);

// Then we find all the tests
const context = require.context('../', true, /\.spec\.ts$/);

// And load the modules
context.keys().map(context);

// Finally, start Karma to run the tests
__karma__.start();

**karma.conf.js**

module.exports = function (config) {
  config.set({
    basePath: '.',
    frameworks: ['jasmine'],
    exclude: [],
    files: [
      '../../wwwroot/dist/vendor.js',
      './boot-tests.js'
    ],
    preprocessors: {
      './boot-tests.js': ['coverage', 'webpack', 'sourcemap']
    },
    client: {
      captureConsole: false
    },
    coverageReporter: {
      type: 'in-memory'
    },
    remapCoverageReporter: {
      'text-summary': null,
      json: './coverage/coverage.json',
      html: './coverage/html'
    },
    reporters: ['mocha', 'coverage', 'remap-coverage'],
    port: 9876,
    colors: true,
    logLevel: config.LOG_WARN,
    autoWatch: false,
    browsers: ['Chrome'],
    mime: {
      'application/javascript': ['ts', 'tsx']
    },
    singleRun: true,
    webpack: require('./webpack.config.test.js')({
      env: 'test'
    }),
    webpackMiddleware: {
      noInfo: true,
      stats: {
        chunks: false
      }
    },
    // you can define custom flags
    customLaunchers: {
      'PhantomJS_custom': {
        base: 'PhantomJS',
        options: {
          windowName: 'test-window',
          settings: {
            webSecurityEnabled: false
          }
        },
        flags: ['--load-images=true'],
        // debug: true
      }
    },
    phantomjsLauncher: {
      // Have phantomjs exit if a ResourceError is encountered (useful if karma exits without killing phantom)
      exitOnResourceError: true
    }
  });
};

**webpack.config.test.js**
const ContextReplacementPlugin = require('webpack/lib/ContextReplacementPlugin');
const LoaderOptionsPlugin = require('webpack/lib/LoaderOptionsPlugin');

const webpack = require('webpack');
var path = require('path');
var rootPath = path.join.bind(path, path.resolve(__dirname, '../../'));

module.exports = function (options) {
  return {
    devtool: 'inline-source-map',
    resolve: {
      extensions: ['.ts', '.js'],
      modules: [rootPath('ClientApp'), 'node_modules']
    },
    module: {
      rules: [{
          enforce: 'pre',
          test: /\.js$/,
          loader: 'source-map-loader',
          exclude: [
            rootPath('node_modules/rxjs'),
            rootPath('node_modules/@angular')
          ]
        },
        {
          test: /\.ts$/,
          use: [{
              loader: 'awesome-typescript-loader',
              query: {
                sourceMap: false,
                inlineSourceMap: true,
                compilerOptions: {
                  removeComments: true
                }
              },
            },
            'angular2-template-loader'
          ],
          exclude: [/\.e2e\.ts$/]
        },
        {
          test: /\.css$/,
          loader: ['to-string-loader', 'css-loader']
        },
        {
          test: /\.scss$/,
          loader: ['raw-loader', 'sass-loader']
        },
        {
          test: /\.html$/,
          loader: 'raw-loader'
        },
        {
          enforce: 'post',
          test: /\.(js|ts)$/,
          loader: 'istanbul-instrumenter-loader',
          options: {
            esModules: true
          },
          include: rootPath('ClientApp'),
          exclude: [
            /ClientApp\\test/,
            /\.(e2e|spec)\.ts$/,
            /node_modules/
          ]
        }

      ]
    },
    plugins: [
      new webpack.DllReferencePlugin({
        context: __dirname,
        manifest: require(rootPath('wwwroot', 'dist', 'vendor-manifest.json'))
      }),
      new ContextReplacementPlugin(
        /**
         * The (\\|\/) piece accounts for path separators in *nix and Windows
         */
        /angular(\\|\/)core(\\|\/)@angular/,
        rootPath('ClientApp'), // location of your src
        {
          /**
           * your Angular Async Route paths relative to this root directory
           */
        }
      ),
      new LoaderOptionsPlugin({
        debug: false,
        options: {
          /**
           * legacy options go here
           */
        }
      }),

    ],
    performance: {
      hints: false
    },

    /**
     * Include polyfills or mocks for various node stuff
     * Description: Node configuration
     *
     * See: https://webpack.github.io/docs/configuration.html#node
     */
    node: {
      fs: 'empty',
      global: true,
      process: false,
      crypto: 'empty',
      module: false,
      clearImmediate: false,
      setImmediate: false
    }
  };
}

**Comment by simplymequeeny** [comment]
Please close this issue.  I am not sure if this is the right fix.
I installed source-map-loader before I created the tests because the first time I ran the test I got an error about source-map-loader cannot be found (something like that), so what I did I installed it.  But I just found out earlier that karma has its own source map loader.  So I uninstalled the source-map-loader, and then just comment this line
```loader: 'source-map-loader',``` 
in **webpack.config.test.js**.

All tests files are now being executed.

Thanks for taking time looking at this issue.  Very much appreciated.

**Comment by MarkPieszak** [comment]
Oh great that might be what was doing it!
Glad you figured it out though :+1:

Cheers

**Comment by manishkumar1689** [comment]
That happens with my unit-tests , actually one of the unit tests I had

import { NO_ERRORS_SCHEMA } from '@angular/compiler/src/core';

which I replaced with

import { NO_ERRORS_SCHEMA } from '@angular/core';
