### ISSUE TITLE
Google Search Console thinks sitemap.xml is HTML

### ISSUE THREAD

**Issue by peterdobson** [MarkPieszak/aspnetcore-angular2-universal#562]
In Google Search Console the sitemap.xml generated in HomeController fails to be read with the following error:
![image](https://user-images.githubusercontent.com/16025228/36762956-144292d2-1c7a-11e8-94ce-8ce5707284f5.png)

**Comment by peterdobson** [comment]
UPDATE: After renaming the <sitemapindex> & <sitemap> tags to <urlset> & <url> in HomeController.cs has fixed it

![image](https://user-images.githubusercontent.com/16025228/36768360-ee1a717e-1c92-11e8-8321-c38213963ece.png)

**Comment by MarkPieszak** [comment]
Great find! 👍 💯 
Can you make a PR so we can get these changes updated for others?

**Comment by peterdobson** [comment]
PR: #565
