### ISSUE TITLE
Setting APP_BASE_HREF in _layout.cshtml fails

### ISSUE THREAD

**Issue by heavyflames** [MarkPieszak/aspnetcore-angular2-universal#568]
Using  <base href="@(Url.Content("~/en"))" /> in _layout.cshtml results in the url to be correct, but angular initialy hits the "Not found page", and after a second or two, loads the correct page.

For example, http://localhost:53545/en/home

Later I need to use this in app.browser.module.ts :
```
 {
        provide: APP_BASE_HREF,
        useFactory:(getBaseUrl)
      }
```

```
export function getBaseUrl() {
  return '/' + (window.location.pathname.split('/')[1] || 'en');
}
```

This because I later on need to check what language the user wants to load.
For example if the users needs danish : http://localhost:53545/dk/home

But how do I set this up, so that the router doesnt load the 404 page first?

**Comment by heavyflames** [comment]
Anyone have any idea on how to do this?

**Comment by MarkPieszak** [comment]
> Data from your <base> tag is not available during server-side prerendering. It never has been - we don't try to parse things out of your Razor pages like that.
> 
> Instead, params.baseUrl comes from ASP.NET's PathBase context property. This should match whatever virtual directory your app is being served from.

Try this above to see if that works! During SSR, we don't have access to anything in the Razor/ASP.NET world unless it's passed down. We aren't able to pass the entire HTML, but only the `<app-root>` to Universal, since dotnet handles everything else.

Hope that helps!
