### ISSUE TITLE
how to run locally?

### ISSUE THREAD

**Issue by cissecedric** [MarkPieszak/aspnetcore-angular2-universal#569]
Hello,
This is not an issue but a request for an How To, a quickstart to run the app..
I'm new to aspnet/angular/azure, I would like to know how to run this app on my desktop just to to see it working locally, and then how to deploy it to azure ?
I tried to run ngserve from different folders but it failed (no index.html file in ClientApp directory...)
Could someone give me some clues ?

Regards,

**Comment by peterdobson** [comment]
If you are using Visual Studio 2017 you can run locally by pressing f5 which will launch a browser and IIS Express.
To publish to Azure, just right-click on the project  in Solution Explorer click Publish and follow the wizard steps.

**Comment by Adondriel** [comment]
You can even use F5 in VSCode as well. Deploying is a bit harder, and I don't know how to deploy to Azure, since I only deploy to local/dedicated IIS.
