### ISSUE TITLE
Catch error while SSR

### ISSUE THREAD

**Issue by Sharique-Hasan** [MarkPieszak/aspnetcore-angular2-universal#570]
How do I catch errors occuring while server side rendering which breaks SSR and just deliver the basic html to browser which after that Application runs entirely on browser. Due to this Application can't have metadata for SEO purpose.

**Comment by MarkPieszak** [comment]
In the `boot.server.ts` file, you should be able to use `.catch()` within that Promise, and simply return your app-root component, instead of the serialized HTML outputted from Universal.

```ts
return ngAspnetCoreEngine(setupOptions).then(response => {

    // Apply your transferData to response.globals
    response.globals.transferData = createTransferScript({
      someData: 'Transfer this to the client on the window.TRANSFER_CACHE {} object',
      fromDotnet: params.data.thisCameFromDotNET // example of data coming from dotnet, in HomeController
    });

    return ({
      html: response.html, // our <app-root> serialized
      globals: response.globals // all of our styles/scripts/meta-tags/link-tags for aspnet to serve up
    });
  }).catch(e => {
    return ({
      html: `<app-root></app-root>`
    });
  });
```

I hope that helps! Let us know
