### ISSUE TITLE
ERROR ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by marcelcandidoferreira** [MarkPieszak/aspnetcore-angular2-universal#571]
Hi, 

I'm trying to use the branch howto/auth to check how the localstorage is used in client and server. Everything works fine, but I realized that the method getUsers() in user.service.ts do not use the JWT method. 

I'm getting the error  "localStorage is not defined" when I use the jwt method as a parameter of transferHttp.get(url, this.jwt())

Just downloaded the branch, then modify the user.service.ts to:
return this.transferHttp.get(`${this.baseUrl}/api/users`, this.jwt());

So, can someone help me?

Thank you,

![screen shot 2018-03-13 at 8 19 31 pm](https://user-images.githubusercontent.com/15752746/37376696-f53e759a-26fb-11e8-8437-53e77b601a70.png)

**Comment by isaac2004** [comment]
Local storage is not available on the server, you need to wrap that call to local storage with isPlatformBrowser()

**Comment by marcelcandidoferreira** [comment]
Hi @isaac2004 thanks for answering!

**Comment by MarkPieszak** [comment]
Yes, you can either wrap it - or use D.I. to have an abstract class that you provide a Browser & Server implementation for. Browser implementation using actual localStorage, Server implementation using either a JS Object, or maybe even Redis or something (if you really need it persisted like that).

Hope that helps! :+1:
