### ISSUE TITLE
SSR problem with paypal checkout

### ISSUE THREAD

**Issue by GetTaxSolutions** [MarkPieszak/aspnetcore-angular2-universal#572]
Hello,

I'm trying to create paypal component in my project. I added 'paypal': 'paypal-checkout/dist/checkout.lib.js' in ProvidePlugin in webpack.config. So the paypal object is available on global level. I have added follow code in the paypal component which have to invoke script to render the button and attach its functionality:
```
ngAfterContentInit() {
    paypal.Button.render(paypalBtnOptions, self.ppButton.nativeElement);
}
```
The component was added into another component which is hit from the route entry.

My commit is here: https://github.com/GetTaxSolutionsLtd/aspnetcore-angular2-universal/commit/12b3f0ca8522072b5b767d6b15944b529ae35d86

If you switch to the commit when open the page and click on Payment navigation button - Paypal is correctly rendered on the page and is working. But if you type directly URL to the route (http://localhost:46653/test) into the browser it open the page but without the button. No errors but button is not rendered. It looks like it show SSR result but does not start browser scripts which are responsible to render the button. If I change something into the script and HMR refresh the page and the button is there and working properly. If I disable SSR everything is fine as well. 

What is wrong in my implementation which is in conflict with SSR? How have to do similar implementation which have similar rendering using javascript which is not supported by SSR? Is there some design pattern for this? 

Thank you
GetTaxSolutions
#571

**Comment by MarkPieszak** [comment]
Try only importing the paypal file in your `main.ts`, that way it's not even part of your Server bundle, and then wrapping that code conditionally with `isPlatformBrowser()` checks so it doesn't touch any SSR code.

Hope that helps!

**Comment by GetTaxSolutions** [comment]
It didn't help me. I removed checkout.lib.js from webpack.config and import paypal only into the paypal component and check for browser rendering. But result is the same. When hit direct URL in browser it show only the part which is rendered by SSR and don't start the scripts which are browser related. I added additional commit with this changes: [Last changes commit](https://github.com/GetTaxSolutionsLtd/aspnetcore-angular2-universal/commit/0c97f742054625100cc4d8af72b0f675bd0827cb)

Actually I have no problem and errors in SSR rendering. The problem is that hit the url in browser the scripts for browser part are not executed. If I open some other route (for example /Home) and switch to this page using button Payment in navigation (which I have added) then everything is ok.

Can you help me how to avoid this script execution problem. It's very important for me. 

Thank you
GetTaxSolutions

**Comment by GetTaxSolutions** [comment]
I lost 2 days and have no resolution of this problem. When I open /test route using browser URL I added breakpoint to this row which create paypal button:
paypal.Button.render(paypalBtn, self.ppButton.nativeElement);
It stop here and all objects are handled and are not undefined but the button is not render. I have same problem and with other external libraries which have some javascript DOM modification and hit directly the route. Can you take a look into this one please. It stopped my work and can't resolve why is that.

**Comment by MarkPieszak** [comment]
Sorry I'm unfortunately unable to really help, try removing it from the Component itself and have it simply within the normal `main.browser.ts` file and import it there. You shouldn't need to import it within the file.

```ts
import * as paypal from 'paypal-checkout/dist/checkout.lib.js';
```

Maybe even a window addition for it might help. (in that main.browser file)
`window.paypal = paypal`

First shut off SSR, and just get it working normally, it sounds like it's not setup correct to work regularly, so SSR isn't the issue.

Hope that helps, sorry I can't help more! Super busy :(

**Comment by GetTaxSolutions** [comment]
Have already tried. If SSR is turned off it's working without any errors. But it stopped in moment when I turn it on back. /also can't see any errors but not working properly/. Don't know where is main.browser.ts but I moved loading of library in app.module.browser. The result is the same.

I'm trying to debug and the debugger stopped in point which invoke paypal button creation and all objects looks good. But when try to change some style into the console it doesn't apply the changes into the page. It's very strange. May be hit some different references of objects. But I just manipulate the object which is get using @ViewChild angular directive. It have to apply the style changes. And why this is not happens when you comes from RouterLink which point to this page. Then everything is OK and whenc change some style in the console it applies in page as well. 
![debug](https://user-images.githubusercontent.com/32810729/37660327-d2447396-2c5a-11e8-858d-aa94f4ae5537.png)

I have no any additional settings. Just get your last version from master and added this payment component. I think it is some common problem and many other people also will have it. 

If you have no time to see it, Do you know someone who can help to resolve this? 

The last changes: [Last changes link to commit](https://github.com/GetTaxSolutionsLtd/aspnetcore-angular2-universal/commit/c9063d23b3524556ffcd42aba830efe38e8d3da5)

Thank you
GetTaxSolutions Team

**Comment by Adondriel** [comment]
The fact you have been making tickets here for fairly simple angular issues, that have documentation, for a very long time/at least half of 2017 is troubling. How much stuff have you actually gotten done? Like, since your first ticket you haven't change the layout, or anything from this project, but yet you are working on a payment system? 

SSR issues are well documented on our page. You cannot use SSR if you have things that use Window/browser specific things. Please. Read the docs before posting more tickets. We don't mind helping, but you are obviously not trying to figure it out by yourself.

**Comment by GetTaxSolutions** [comment]
Hello @Adondriel 

Our project is currently written on Anuglar 1.x and we want to migrate it to version 5.x. We admit that we do not have much experience with SSR. Because we could not get resolution of this problem, that was the reason I asked so urgently. In fact, most of the issues which we have reported are related to the addition of external libraries that use window and document objects. But the answer I received was to make sure I called up the code only when checking that the code was running only in the browser - not on the server. We comply with this condition, and in action anywhere in consoles there are no errors. Nowhere in the documentation did we see that it is not possible to run such a library only on the client side, as the implementation of the specific code was omitted by SSR. In fact, we do not want these libraries to be used on the server side - they have to be used only in the browser. It works, but only if you do not get direct URL. In fact, we have written almost everything needed on the system including payments and it works without SSR /because of the direct use of the URL/. My insistent questions are because we want to take advantage of the benefits it provides. We apologize if we offend you, but we did not know who else could give more information for your project than you. If I had received one specific and comprehensive answer, we would not have created so many similar issues. The simple questions for you are more complex for us. Our work is mainly focused on component develop and design, and this was basically the idea of ​​using your really good project with great activity and incredible start-up. We wanted to move faster and easier with migration. Applause for the incredible work you've done! We are understanding that you are very busy and thank you for attention to us.

We are very happy that have branch which will support window/document objects. That's really great.

If questioning in the form of issues is not correct as a way of correspondence, please let we know what is the other more optimal option.

**Comment by isaac2004** [comment]
How badly do you need SSR? What is the kind of app you are building? If you are having tons of issues with SSR, maybe your technology decisions need to thought about more. I am not trying to be rude, but there are solutions to include performance of a web app without SSR. Please give us some background on what you are trying to do, at a high level.

**Comment by GetTaxSolutions** [comment]
Hello @isaac2004 

The main problem with Angular 1.x is that the page is empty when disable all Javascripts into the browser. Here the problem is the same but is good with SSR. Actually we have no many issues with SSR. We have only one - when type some route into the browser and hit enter. Then all external libraries are not working properly and no have errors in the consoles. If you continue to navigate on the site using links which point to any route (including this which you try with direct access) then everything working fine without any problems. 

Trying to debug and saw that when invoke direct access to URL and debugger stop in our component in method ngAfterContentInit from lifecycle - all DOM objects are not accessible. We trying to access it using standard Angular object reference to native element into debugger - using #ppButton reference and ppButton.nativeElement.style.backgroundColor = "red". The result is that it changed something else not the elements on the screen. I had attached screens in previous posts.

We want to use SSR not just for performance but want to have good SEO optimization from all search engines. But I think that our observations is not in focus to reported issue.
