### ISSUE TITLE
Create a template pack for Visual Studio

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#58]
Hi @MarkPieszak,
I think creating a template pack would be a better option for reaching people in an easy way.

There is already one template pack like this-

https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ASPNETCoreTemplatePack

In the template pack, we can put a multiple version of this project like-

 1. Only ASP.Net Core and Angular2
 2. ASP.Net Core and Angular2 with REST example
 3. ASP.Net Core and Angular2 with server-side rendering with webpack
 4. ASP.Net Core and Angular2 with testing facility
 5. ASP.Net Core and Angular2 Advanced pack

Or other things can be added so that more people can use this template easily and they can simply search in visual studio template and get it from visual studio

**Comment by MarkPieszak** [comment]
I love the idea! But with upcoming things we are adding and the overall universal API change that will be coming wi ng4 I'm wondering if it's better to wait? Or should it be up there once a few other additions are made. 

How easy is it to update a .NET template ?

**Comment by AbrarJahin** [comment]
Frankly speaking, I have no idea.

I will let you know by checking.

Thanks

**Comment by isaac2004** [comment]
closing this as we are looking into making this template more accessible using dotnet cli
