### ISSUE TITLE
Angular Material support

### ISSUE THREAD

**Issue by vmachacek** [MarkPieszak/aspnetcore-angular2-universal#586]
Hello, 

I forked the repo and tried to add Angular Material into the mix but I got he exception about window is not defined. Has anyone here already been there?

Any tip appreciated.

**Comment by ruant** [comment]
I'm in the process of using this with Angular Material
Haven't had any exceptions about `window` (yet).

What Angular Components are you trying to use?

**Comment by vmachacek** [comment]
This is my fork - there is only one commit in master 

https://github.com/vmachacek/aspnetcore-angular2-universal

You can see I added checkbox to the shared module (client and server), and than it blew up.

**Comment by ruant** [comment]
I would try to remove what you added to the `ClientApp/boot.server.ts`

**Comment by vmachacek** [comment]
yeah, it works now, but it's strange to me, because I added it there because it was not working in a first place. But It was probably not synced or something was cached or whatever. I will try to migrate my whole app and see how far I can get.

**Comment by MarkPieszak** [comment]
Glad you got it working! I'll close this out for now :+1:

**Comment by vmachacek** [comment]
yes, It was my own stupidity, it turned out to be xcomponent part of the paypal-checkout npm package. Once I removed that and shuffled some modules around I made it work.
