### ISSUE TITLE
Http 404 error while giving url like .vpf and refereshing the page

### ISSUE THREAD

**Issue by kamalakkanni** [MarkPieszak/aspnetcore-angular2-universal#590]
Hi,

I am using angular 5 universal with asp.net core.I am getting "Http 404 error while giving url like .vpf and refereshing the page" error.pls help me to fix it

Thanks

**Comment by kamalakkanni** [comment]
I changed routing in asp.net core startup file.its working fine

**Comment by Flood** [comment]
@kamalakkanni What did you change?
