### ISSUE TITLE
Browser caching - refresh after a publish?

### ISSUE THREAD

**Issue by peterdobson** [MarkPieszak/aspnetcore-angular2-universal#592]
Can anyone suggest a way to force the browser to get the latest version of vendor.js and main-client.js after a new build has been published? I appreciate that a timespan can be set in startup.cs, 

i.e. MaxAge = TimeSpan.FromDays(30)

but within that timespan if the cached javascript gets out of sync with the server api, there will be errors. For development we can ctrl-f5. but can't expect users to do the same. 

Any ideas? Thanks in advance

**Comment by Flood** [comment]
Hi @peterdobson 

See this PR: https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/593

**Comment by peterdobson** [comment]
Awesome @Flood ! that did the trick! I'd noticed those asp-append-version="true" tags , but had no idea that the TagHelpers imports were required also. Thanks so much!
