### ISSUE TITLE
Create a Entry showcase with Angular Service

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#60]
Hi, in the current system, there is showing a REST page which is showing random data.

We can replace that with a real data showing a page with CRUD option in 1 page for users so the data can be added to pop up and can be shown on the page.

Now we have REST API, a database and CSRF protection.

So, I think this kind of showcase should be added in replace of current REST page.

**Comment by MarkPieszak** [comment]
Definitely, I'll add something in there to replace it!

**Comment by AbrarJahin** [comment]
Thanks @MarkPieszak 👍

**Comment by LiverpoolOwen** [comment]
Do we want the User API back? I have readded it locally and seems to be working

**Comment by MarkPieszak** [comment]
Yeah why not! It'd be nice if it aphasia all the contributors in it too 👍🎈
