### ISSUE TITLE
Error on ng serve

### ISSUE THREAD

**Issue by ch-hristov** [MarkPieszak/aspnetcore-angular2-universal#605]
I get this error if I run ng serve, removed node_modules and rebuild node-sass

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve 'C:\github\unikyte\unikyte_v2\aspnetcore-angular2-universal\ClientApp\ind  ex.html' in 'C:\github\unikyte\unikyte_v2\aspnetcore-angular2-universal':
  Error: Can't resolve 'C:\github\unikyte\unikyte_v2\aspnetcore-angular2-universal\ClientApp\index.html' in 'C:\github\u  nikyte\unikyte_v2\aspnetcore-angular2-universal'

  - compiler.js:76
    [aspnetcore-angular2-universal]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:300 compile
    [aspnetcore-angular2-universal]/[webpack]/lib/Compiler.js:300:11

  - Compiler.js:510 applyPluginsAsync.err
    [aspnetcore-angular2-universal]/[webpack]/lib/Compiler.js:510:14

  - Tapable.js:202 next
    [aspnetcore-angular2-universal]/[tapable]/lib/Tapable.js:202:11

  - CachePlugin.js:78 Compiler.<anonymous>
    [aspnetcore-angular2-universal]/[webpack]/lib/CachePlugin.js:78:5

  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [aspnetcore-angular2-universal]/[tapable]/lib/Tapable.js:206:13

  - Compiler.js:507 compilation.seal.err
    [aspnetcore-angular2-universal]/[webpack]/lib/Compiler.js:507:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [aspnetcore-angular2-universal]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:677 applyPluginsAsync.err
    [aspnetcore-angular2-universal]/[webpack]/lib/Compilation.js:677:19

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [aspnetcore-angular2-universal]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:668 applyPluginsAsync.err
    [aspnetcore-angular2-universal]/[webpack]/lib/Compilation.js:668:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [aspnetcore-angular2-universal]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:663 applyPluginsAsync.err
    [aspnetcore-angular2-universal]/[webpack]/lib/Compilation.js:663:10

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [aspnetcore-angular2-universal]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:659 applyPluginsAsyncSeries
    [aspnetcore-angular2-universal]/[webpack]/lib/Compilation.js:659:9

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [aspnetcore-angular2-universal]/[tapable]/lib/Tapable.js:195:46

webpack: Failed to compile.

**Comment by MarkPieszak** [comment]
The CLI is only here for the generator actually, so you can’t run ng serve.
Use dotnet run to fire everything up 👍

**Comment by ch-hristov** [comment]
Awesome thanks
