### ISSUE TITLE
Unverified breakpoint in VS Code

### ISSUE THREAD

**Issue by seanhs22** [MarkPieszak/aspnetcore-angular2-universal#606]
Repro steps:
1. Install Debugger for Chrome (4.3.0) in Visual Studio Code
2. Debug [Development] Launch Server (no browser)
3. Debug [Development] Debug TypeScript
4. Navigate to http://localhost:5000/users in the Chrome instance that was launched

Observed: Unverified breakpoint in Visual Studio code
![image](https://user-images.githubusercontent.com/2790605/38839971-c4395138-41a2-11e8-833d-c102d36b5461.png)

I can debug in the Chrome dev tools, but debugging right in VS Code would be superb :D
![image](https://user-images.githubusercontent.com/2790605/38840021-1146b4f2-41a3-11e8-8170-e66166d705d6.png)

**Comment by aaronwJordan** [comment]
I'm seeing this issue as well.

`VSCode 1.22.2`
`TS 2.5.3`
`Webpack 3.11.0`
`Debugger for Chrome 4.3.0`

**Comment by seanhs22** [comment]
For me, the fix was simply changing `cheap-eval-source-map` to `eval-source-map` in webpack.config.js. I can open a PR for it, but eval-source-map is slower and everyone may not want it.

**Comment by coloradocolby** [comment]
AFAICT this is still for Macs on VSCode

My environment:
`VSCode 1.32.0`
`TS 2.9.2`
`Webpack 3.12.0`
`Debugger for Chrome 4.11.3`
