### ISSUE TITLE
Slow performance when accessing the webservice

### ISSUE THREAD

**Issue by wilson0506** [MarkPieszak/aspnetcore-angular2-universal#608]
Hi, i experience an slow performance when loading data from the api. May I know how to do performance tuning for .net core ef part?

**Comment by MarkPieszak** [comment]
If you're using Visual Studio (not VSCode) there are many good tools for checking out timing of your API calls / etc.

There's plenty of good articles out there:

https://www.thereformedprogrammer.net/entity-framework-core-performance-tuning-a-worked-example/

http://sikorsky.pro/en/blog/aspnet-core-performance-tuning

https://www.carlrippon.com/scalable-and-performant-asp-net-core-web-apis-profiling-and-monitoring/

Hope that helps! :+1:
(Just closing as not related to the project itself)

**Comment by kamalakkanni** [comment]
Hi can you pls guide me to improve the performance of asp.net core with angular  universal application.It is slow while reloading.(due to preboot)
