### ISSUE TITLE
Bootstrap Collapsible nav bar

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#61]
In the current system, nav bar is not collapsible and the page is not responsive.

I think, if we can use this kind of nav bar in our system, that would be nice-

https://getbootstrap.com/examples/navbar-fixed-top/

What do u suggest @MarkPieszak ?

**Comment by MarkPieszak** [comment]
Sounds like a great idea to me! I've been meaning to fix some of the smaller css/design things!

**Comment by AbrarJahin** [comment]
Working on this issue.

From this answer-

http://stackoverflow.com/questions/37438683/is-there-a-way-to-build-the-mobile-nav-bar-in-ng2-bootsrap

Will make a PR ASAP

**Comment by LiverpoolOwen** [comment]
Did this get done?

**Comment by MarkPieszak** [comment]
This is already done, but the styles aren't shining through, think that's based on another issue.
