### ISSUE TITLE
 Module not found: Error: Can't resolve *.ngfactory.js

### ISSUE THREAD

**Issue by isaac2004** [MarkPieszak/aspnetcore-angular2-universal#610]
I have an app that is an extension of this repo and I am running into an issue running `npm run build:prod` and getting the below error

>  ERROR in ./ClientApp/boot.server.PRODUCTION.ts
    Module not found: Error: Can't resolve 'app/admin/admin.module.ngfactory.js' in 'C:\Development\LevinBlog\src\LevinBlog.Web\ClientApp'
     @ ./ClientApp/boot.server.PRODUCTION.ts 1:0-66

In a nutshell, I have a lazy loaded module (admin.module) that has a handful of components added to it. Here is the module

````
import { NgModule } from '@angular/core';
import { CoreModule } from '../core/core.module';
import { AdminHomeComponent } from './adminhome/adminhome.component';
import { AdminPostComponent } from './adminpost/adminpost.component';
import { AdminTagComponent } from './admintag/admintag.component';
import { AdminCategoryComponent } from './admincategory/admincategory.component';
import { AdminRoutingModule } from './admin-routing.module';
import { AdminComponent } from './admin.component';
import { CollapseModule, ModalModule } from 'ngx-bootstrap';
import { AdminMenuComponent } from './adminmenu/adminmenu.component';
import { AuthGuard } from './auth.guard';
import { SharedModule } from '../shared/shared.module';

@NgModule({
  imports: [
    CoreModule,
    AdminRoutingModule,
    SharedModule
  ],
  declarations: [
    AdminComponent,
    AdminMenuComponent,
    AdminHomeComponent,
    AdminPostComponent,
    AdminCategoryComponent,
    AdminTagComponent
  ],
  providers: [
    AuthGuard
  ]
})
export class AdminModule { }

````

Nothing fancy, just some routes and a guard. However if I do not include this module in my app.module route (aka not include it in the routing), the npm script runs fine. Is there a way to debug what in that module is causing ngfactory from getting built

**Comment by MarkPieszak** [comment]
This could be related to something else within that module that's broken, thread on basically the same issue here:
https://github.com/angular/angular-cli/issues/4551#issuecomment-280376180

Make sure all the files and references within that module are there and working, with VSCode and Angular Language Service you can try and comb through and see if there's some private property being accessed in a template, etc.

In the guys case above, he was missing some scss file was referencing.

It's probably the most minor annoying thing, but it's causing the AoT build not to complete, so you're getting the error above :(

Hope that helps man! 👍

**Comment by isaac2004** [comment]
Oddly enough, if I run ngc (I know this repo doesn't work with ngc) I get a message about importing bootstrap in a scss

> : Couldn't resolve resource ~bootstrap/scss/bootstrap.scss from C:/Development/Web/ClientApp/app/app.component.scss

And at the top of my scss

````
@import "~bootstrap/scss/bootstrap.scss";
@import '~font-awesome/scss/_variables.scss';
$fa-font-path: "~font-awesome/fonts";
@import '~font-awesome/scss/font-awesome.scss';
````

If I comment out the reference to app.component.scss, ngc works fine, yet build:prod does not.

Not sure what is going on here. Is there way to get the full AoT log?

**Comment by hatemalhassani** [comment]
there are some issues break aot compiler almost of them are incorrect imports files such as

1. import from src files, for example: 
incorrect: 
` import { OnChanges } from '@angular/core/src/metadata/lifecycle_hooks';`
correct:
` import { OnChanges } from '@angular/core';`
 
2. import wrong file
incorrect:
```
import { moment } from 'ngx-bootstrap/chronos/test/chain';
import { StringLiteral } from 'typescript';
```
correct:
```
import * as  moment from 'moment';
```

i recommend you to use vs code extension called "typescript hero" that help you to sort and remove unused imported files.

**Comment by isaac2004** [comment]
Going through a ton of components and modules isn't an ideal solution. Why can't I just get a more verbose log of the AOT run?

**Comment by MarkPieszak** [comment]
Sometimes it is tough for the static analyzer to really give a perfect error stack trace. These things will be vastly improved once `Ivy` is fully available and ready.

@hatemalhassani is definitely right, it's probably some strange deep import that's causing this.

It is definitely something within that NgModule, so just do some global searches for stuff like `/src/` etc, and manually just peak around at the imports.

I've noticed VSCode a lot of times imports the incorrect thing for Router and such, it grabs the deep import (which isn't allowed). 

Sometimes you'll see things like `import { OnDestroy } from '@angular/core/src/metadata/lifecycle_hooks';` which aren't allowed as well.

**Comment by isaac2004** [comment]
I figured this out. I had a member in one of my TS classes that didn't match the class on the server. The template was throwing an error only on AOT.

**Comment by MarkPieszak** [comment]
What was the exact error and how did you fix it? (Just incase others find this issue)

That's awesome man, glad you got it!! 👍

**Comment by isaac2004** [comment]
AOT never gave me the actual error. I was checking to make sure all my templates and components were correct. I noticed that one of my models was small and there were properties the template was using that were not there (but were there in my service model). In non-prod, everything worked because of weak typing. When AOT runs the check of the template vs the model fails. That was it

**Comment by hatemalhassani** [comment]
@isaac2004 try angular-service extension which check for template errors and do a good staff.

**Comment by isaac2004** [comment]
@hatemalhassani that is what helped me!!!
