### ISSUE TITLE
appId // make sure this matches with your Server NgModule 

### ISSUE THREAD

**Issue by ruant** [MarkPieszak/aspnetcore-angular2-universal#616]
Don't quite get this.
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/82afbb5781165081e6167e4679a89ed1caeba8b6/ClientApp/app/app.module.ts#L52

What should it match?
The selector of the Server NgModule bootstrapped component?

**Comment by MarkPieszak** [comment]
This is just used to match up the IDs created during the server-render with the client-rendered version so that styles get reused/etc, otherwise you'd get a flicker from it.

**Comment by ruant** [comment]
But where in the Server NgModule is this set? Can't find it anywhere 😕 

Is it this one?
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/82afbb5781165081e6167e4679a89ed1caeba8b6/ClientApp/app/app.module.server.ts#L19
