### ISSUE TITLE
Latest commit does not publish

### ISSUE THREAD

**Issue by GRIMMR3AP3R** [MarkPieszak/aspnetcore-angular2-universal#632]
Even if you add the UglifyJsPlugin to webpack so it will quit barking about the missing reference it only then fails with "node_modules\rxjs\_esm5\internal\Subscription.js has no id. This should not happen."

**Comment by MarkPieszak** [comment]
Let me take a look! Thanks for the heads up!

**Comment by MarkPieszak** [comment]
@GRIMMR3AP3R Take a look at the latest commit here: https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/eff67f28a986be7fb36b16d002649e6ea37622e2

I fixed the dotnet version to 2.1 and added the uglify JS stuff from the new webpack plugin.

Prod builds seem to be working fine now, no errors thrown!
Let me know :+1:

I'll leave this open for now incase others run into this as well.

**Comment by GRIMMR3AP3R** [comment]
Looks good.

**Comment by MarkPieszak** [comment]
Excellent! 👍
