### ISSUE TITLE
Can't deploy on IIS

### ISSUE THREAD

**Issue by GonzaloAndrade** [MarkPieszak/aspnetcore-angular2-universal#635]
Hi, I deployed this application from VS2017 to my Windows Virtual Machine with IIS.

![image](https://user-images.githubusercontent.com/1771862/40863207-9965933c-65b4-11e8-9aea-50d2fe309db2.png)

The app runs but then I try to open localhost:5000 on my browser I get the following error:
![image](https://user-images.githubusercontent.com/1771862/40863258-b572ca5e-65b4-11e8-9d80-87916fe17507.png)

Any help would be appreciated.

Update: I was able to run the project by cloning, running the scripts and then dotnet run.

Still can't get the project working with VS2017 publish option.

**Comment by MarkPieszak** [comment]
Can you take a look at some of the other issues about IIS, I'm not sure if there's something else that you might be missing. I have only deployed to AWS and Azure myself. Possibly Node is missing, or there is some kind of folder/base-path issue going on.

https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/412

IIS issues to look through here
https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues?utf8=%E2%9C%93&q=is%3Aissue+IIS

**Comment by RZeni** [comment]
this seems related to #633

**Comment by GRIMMR3AP3R** [comment]
Known issue for SSR, https://github.com/angular/angular-cli/issues/8616. #639 fixes this problem.

**Comment by MarkPieszak** [comment]
#639 merged https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/639
@GonzaloAndrade take a look and see if updating your webpack code like shown there fixes it for you as well! 

@GRIMMR3AP3R 💯 💯

**Comment by GonzaloAndrade** [comment]
Everything works now 👍 
Thanks!!
