### ISSUE TITLE
Production mode error

### ISSUE THREAD

**Issue by LiverpoolOwen** [MarkPieszak/aspnetcore-angular2-universal#637]
Production mode error since recent changes

NodeInvocationException: StaticInjectorError(n)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object
TypeError: StaticInjectorError(n)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
StaticInjectorError(Platform: core)[InjectionToken Application Initializer -> InjectionToken DocumentToken]: 
Right-hand side of 'instanceof' is not an object

**Comment by vasyliv** [comment]
@LiverpoolOwen  please check this issue 
https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/633

**Comment by GRIMMR3AP3R** [comment]
Setting preserve  class names fixes this issue. #639

**Comment by MarkPieszak** [comment]
Merged in @GRIMMR3AP3R's 🙏  PR: https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/639
@LiverpoolOwen Can you see if updating that fixes it for you as well?

**Comment by peterdobson** [comment]
FYI, PR: #639 fixes it for me

**Comment by MarkPieszak** [comment]
Great! Closing as fixed thanks to Grimm 👍
