### ISSUE TITLE
tslint fails

### ISSUE THREAD

**Issue by Ketrex** [MarkPieszak/aspnetcore-angular2-universal#64]
When running `npm run lint` the command fails due to several code rule violations:

`Client/app/index.ts[23, 52]: file should end with a newline
Client/containers/chat/chat.component.ts[9, 1]: misplaced opening brace
Client/containers/chat/chat.component.ts[18, 5]: misplaced opening brace
Client/containers/not-found/not-found.component.ts[5, 15]: The selector of the component "NotFoundComponent" should be named kebab-case (https://goo.gl/mBg67Z)
Client/containers/not-found/not-found.component.ts[10, 1]: misplaced opening brace
Client/containers/not-found/not-found.component.ts[19, 5]: misplaced opening brace
Client/shared/cache/storage/index.ts[4, 35]: file should end with a newline
Client/shared/cache/storage/storage.browser.ts[29, 2]: file should end with a newline
Client/shared/cache/storage/storage.node.ts[23, 2]: file should end with a newline
Client/shared/meta/meta.store.ts[16, 2]: file should end with a newline
Client/shared/meta/meta.store.ts[16, 2]: Missing semicolon`

I will submit a PR to fix unless that is not advised.

**Comment by MarkPieszak** [comment]
Sure PR's are more than welcome!
Must of missed that one 👍
