### ISSUE TITLE
Error deploying to Azure

### ISSUE THREAD

**Issue by ima18h** [MarkPieszak/aspnetcore-angular2-universal#644]
Can someone explain to me how to deploy to Azure please? 
**I have been trying to make this project work on Azure, but it keeps failing. 
The app works when i run it on my machine. 
I cloned the repo, then tried to follow the Azure deployment section:**

> git remote add azure https://your-user-name@my-angular2-site.scm.azurewebsites.net:443/my-angular2-site.git
>                      // ^ get this from Azure (Web App Overview section - Git clone url)
> 
> git push --set-upstream azure master

**But, I get:**
remote:   Version: webpack 4.11.1
remote:   Child
remote:       Hash: 7baa171d65663214aaf2
remote:       Time: 12672ms
remote:       Built at: 06/07/2018 7:53:49 PM
remote:           Asset     Size  Chunks             Chunk Names
remote:       vendor.js  103 KiB       0  [emitted]  vendor
remote:   Child
remote:       Hash: 7d44053e681937d45461
remote:       Time: 75063ms
remote:       Built at: 06/07/2018 7:54:51 PM
remote:           Asset      Size  Chunks             Chunk Names
remote:       vendor.js  1.81 MiB       0  [emitted]  vendor
remote:
remote:       WARNING in ./node_modules/@angular/core/bundles/core.umd.js 4910:15-36
remote:       System.import() is deprecated and will be removed soon. Use import() instead.
remote:       For more info visit https://webpack.js.org/guides/code-splitting/
remote:        @ dll vendor
remote:
remote:       WARNING in ./node_modules/@angular/core/bundles/core.umd.js 4922:15-102
remote:       System.import() is deprecated and will be removed soon. Use import() instead.
remote:       For more info visit https://webpack.js.org/guides/code-splitting/
remote:        @ dll vendor
fatal: The remote end hung up unexpectedly
error: error in sideband demultiplexer
To https://firstapp54637869.scm.azurewebsites.net/firstApp54637869.git
 * [new branch]      master -> master
Branch 'master' set up to track remote branch 'master' from 'azure'.

**Help resolving this appreciated!**

**I tried again, and got this:**
remote:   Installing System.Reflection 4.1.0.
remote: D:\Program Files (x86)\dotnet\sdk\2.1.300\NuGet.targets(114,5): error : There is not enough space on the disk : 'D:\home\.nuget\microsoft.aspnetcore.razor.design\2.1.0\mvnevfbz.ykt' [D:\home\site\repository\Asp2017.sln]
remote: D:\Program Files (x86)\dotnet\sdk\2.1.300\NuGet.targets(114,5): error : There is not enough space on the disk : 'D:\home\.nuget\microsoft.aspnetcore.razor.design\2.1.0\mvnevfbz.ykt' [D:\home\site\repository\Asp2017.sln]
remote:
remote: Error - Changes committed to remote repository but deployment to website failed.
error: failed to push some refs to 'https://******@simple.scm.azurewebsites.net:443/simple.git'

**Comment by GRIMMR3AP3R** [comment]
Pretty sure these are explaining it There is not enough space on the disk : 'D:\home.nuget\microsoft.aspnetcore.razor.design\2.1.0\mvnevfbz.ykt' . 
Where ever you are trying to build at is running out of space.

**Comment by ima18h** [comment]
Thanks for the reply! 
I want to use this starter to learn and use as a personal website. Can anyone suggest the best/cheapest way to have something like that on Azure?
