### ISSUE TITLE
HOW TO DISABLE BROWSER CHACHE?

### ISSUE THREAD

**Issue by hartov** [MarkPieszak/aspnetcore-angular2-universal#661]
How could i disable this browser cache? New version of angular build did not load! 
So, because of this HMR not working as expect ! I need full prevent this

**Comment by GRIMMR3AP3R** [comment]
If you are developing in chrome then disable cache while debugger tool is open should work. However, you can disable PWA in development and that should do it as well.

**Comment by gerasymchuk25** [comment]
Maybe that will help you  #[287]

**Comment by hartov** [comment]
eah, i understand that serviceworker cache project data. thanks!

**Comment by hartov** [comment]
BUT better to use serviceworker ONLU in PRODUCTION
