### ISSUE TITLE
Errors were found in your package-lock.json, run  npm install  to fix them.

### ISSUE THREAD

**Issue by Daeamon** [MarkPieszak/aspnetcore-angular2-universal#664]
```0 info it worked if it ends with ok
1 verbose cli [ 'G:\\nodejs\\node.exe',
1 verbose cli   'G:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'audit' ]
2 info using npm@6.1.0
3 info using node@v10.6.0
4 verbose npm-session 3cbf1855d9d3c78d
5 verbose stack Error: Errors were found in your package-lock.json, run  npm install  to fix them.
5 verbose stack     Missing: karma-phantomjs-launcher@^1.0.4
5 verbose stack     at lockVerify.then.result (G:\nodejs\node_modules\npm\lib\audit.js:159:19)
6 verbose cwd D:\git\aspnetcore-angular2-universal-master
7 verbose Windows_NT 10.0.17134
8 verbose argv "G:\\nodejs\\node.exe" "G:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "audit"
9 verbose node v10.6.0
10 verbose npm  v6.1.0
11 error code ELOCKVERIFY
12 error Errors were found in your package-lock.json, run  npm install  to fix them.
12 error     Missing: karma-phantomjs-launcher@^1.0.4
13 verbose exit [ 1, true ]
```

**Comment by GRIMMR3AP3R** [comment]
You may need to rebuild phatomjs.

**Comment by Daeamon** [comment]
Ty))) my problem solved!!)

**Comment by gdm-1718-brundeco** [comment]
Hey i'm having a similar error after installing the parallax via npm
I'm using a mern template

Is there a quick way to solve this?

```
npm ERR! code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Missing: @babel/register@^7.4.0
npm ERR!     Missing: body-parser@^1.18.3
npm ERR!     Missing: chalk@^2.4.2
npm ERR!     Missing: jsonwebtoken@^8.5.1

npm ERR! A complete log of this run can be found in:

```

Thanks in advance!

**Comment by GRIMMR3AP3R** [comment]
delete the package-lock.json file. Then run the npm build. That will rebuild the package-lock.

**Comment by gdm-1718-brundeco** [comment]
Was indeed the problem, thanks for your response! Cheers

**Comment by andreihamalainen** [comment]
ok, the problem is solved for one time. but when I try to install it again, then I HAVE THE SAME ISSUE - the package-lock file is broken always. Is there a way to create non-broken package-lock?

**Comment by janupan** [comment]
code ELOCKVERIFY
npm ERR! Errors were found in your package-lock.json, run  npm install  to fix them.
npm ERR!     Missing: mocha@^7.0.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/janupan/.npm/_logs/2020-02-21T09_54_42_239Z-debug.log
bciasia@januari sdet_test % npm install --save-dev mochawesome
npm WARN mocha-parallel-tests@1.2.10 requires a peer of mocha@^3 but none is installed. You must install peer dependencies yourself.
npm WARN mocha-testrail-reporter@1.0.12 requires a peer of mocha@^3 || ^2.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN mochawesome@4.1.0 requires a peer of mocha@>=5 but none is installed. You must install peer dependencies yourself.
npm WARN sdet_test@1.0.0 No repository field.

+ mochawesome@4.1.0
added 39 packages from 24 contributors, removed 57 packages, updated 16 packages and audited 913 packages in 8.167s

1 package is looking for funding
  run `npm fund` for details

found 15 vulnerabilities (1 low, 7 moderate, 6 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details


How about like this, anyone can help me. thank you
