### ISSUE TITLE
Core JS 'Math' polyfill not working in IE - Webpack doesn't target es 5

### ISSUE THREAD

**Issue by nfdevil** [MarkPieszak/aspnetcore-angular2-universal#666]
In my tsconfig the target is set to ES5. However, when I run the application or publish it, I get an error in IE 11:
![image](https://user-images.githubusercontent.com/7434048/43122551-c4256e08-8f21-11e8-965d-4d74fe62095d.png)
It's in dutch, but saying ':' is expected.
When diving in the source code, the following line gives the error:
![image](https://user-images.githubusercontent.com/7434048/43122600-f10b7728-8f21-11e8-8add-9786b5c3e531.png)
Because IE11 does not support ES2015 Enhanced Object literals (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Grammar_and_types#Object_literals)

This code is from the Core JS, specifically from the polyfill 'core-js/es6/math'.
When I comment this line in my polyfills.ts, the error is gone.

How can I get this file to be compiled as ES5?

**Comment by gerasymchuk25** [comment]
In webpack.config and webpack.config.vendor change option of UglifyJsPlugin **ecma: 6** to **ecma: 5**.

**Comment by nfdevil** [comment]
Indeed, this worked! I thought that it only applied to production builds, because the UglifyJsPlugin is added if isDevBuild = false.

**Comment by rcanpahali** [comment]
It solved my problem too, thank you so much!
