### ISSUE TITLE
User is unable to get the updated version in the server

### ISSUE THREAD

**Issue by helloneoberg** [MarkPieszak/aspnetcore-angular2-universal#668]
Hi,
I am using angular 4 version of this project. I compile and publish it to a Azure VM which is my web server. I notice that my user will not automatically see the latest version. Only way for user to get the new version is to manually clear cache in chrome and open the URL again.
  

Please enlighten me. Thank you.

**Comment by peterdobson** [comment]
See commit 82afbb5781165081e6167e4679a89ed1caeba8b6

**Comment by MarkPieszak** [comment]
Closing as fixed via 82afbb5, hope that helps fix your issue @helloneoberg !
