### ISSUE TITLE
NodeInvocationException: Can't resolve all parameters for HomeComponent

### ISSUE THREAD

**Issue by Hiroki-Honda** [MarkPieszak/aspnetcore-angular2-universal#680]
When compiling in Dev mode, IIS Express becomes Internal Server Error (500).
in boot.server.ts
Add below to the first line
 import 'reflect-metadata';
or
import './polyfills/server.polyfills';
To
import {AppModule} from './app/app.module.server';
Move before

I was able to avoid the error.
---------------------------------------------------------------------------
A similar error also occurs in the browser.
I get Uncaught Error: Can't resolve all parameters for HomeComponent ...
in boot.browser.ts
Add below to the first line
 import 'reflect-metadata';
or
import './polyfills/browser.polyfills';
To
import { AppModule } from './app/app.module.browser';
Move before

I was able to avoid the error.
If there are other methods, please teach me. 
Thanks.

**Comment by wilson0506** [comment]
it avoid the error, but all other javascript function failed

**Comment by Hiroki-Honda** [comment]
In my environment, 

> npm run build:dev
> npm run build:prod

all javascript works normally, and HMR is OK.

**Comment by CybrZr00** [comment]
I had the same issue a while back, and just moved the polyfills imports to the top of the list, as suggested. This fixed it for me.

**Comment by Jason9199** [comment]
Pulling this repo down fresh, then running the commands given in the repo for VSCode `npm install && npm run build:dev && dotnet restore App2017.csproj` I get this same error when I run the app `Uncaught Error: Can't resolve all parameters for HomeComponent: (?).`

Don't know if it's related but I also get `Uncaught ReferenceError: prebootInitFn is not defined
    at (index):12442` before the HomeComponent error. 

I have tried moving `import './polyfills/server.polyfills';` and `import './polyfills/browser.polyfills';` to the very top in both boot.server.ts and boot.browser.ts respectively and it had no effect.

**Comment by wilson0506** [comment]
changed 
import { enableProdMode } from '@angular/core';
import { createTransferScript, IEngineOptions, ngAspnetCoreEngine } from '@nguniversal/aspnetcore-engine';
import { createServerRenderer } from 'aspnet-prerendering';
import 'zone.js/dist/zone-node';
// Grab the (Node) server-specific NgModule
import './polyfills/server.polyfills';
import { AppModule } from './app/app.module.server';

UI fixed
but still have js error
compiler.js:11359 Uncaught Error: Can't resolve all parameters for HomeComponent: (?).
    at syntaxError (compiler.js:1270)
    at CompileMetadataResolver._getDependenciesMetadata (compiler.js:11171)
    at CompileMetadataResolver._getTypeMetadata (compiler.js:11064)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (compiler.js:10683)
    at CompileMetadataResolver._getEntryComponentMetadata (compiler.js:11267)
    at eval (compiler.js:11258)
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getEntryComponentsFromProvider (compiler.js:11257)
    at eval (compiler.js:11230)
    at Array.forEach (<anonymous>)

**Comment by MarkPieszak** [comment]
Let me try to dig into this one, I'm not sure where this one popped up from... potentially something from NodeServices ?

**Comment by MarkPieszak** [comment]
This should be fixed now in the latest commit, Hiroki is correct - there was a PR that went in that formatted all the documents (automatically) and I didn't catch it moved some of those important files where things need to be in a specific order.

Sorry about the delay there guys, hope it's working ok now!

@CybrZr00 
@wilson0506 
@stephenlautier 
@Jason9199
