### ISSUE TITLE
error TS2304: Cannot find name 'module'.

### ISSUE THREAD

**Issue by rodolfoortiz** [MarkPieszak/aspnetcore-angular2-universal#685]
Hi, I download the latest template from the master branch and when I run
```
npm run build:prod
```
I get
```
> angular6-aspnetcore-universal@1.0.0-rc4 build:webpack C:\Users\rodolfo.ortiz\Documents\blitz-registration\tmp\aspnetcore-angular2-universal-master
> webpack --progress --color "--env.prod"

[0] Hash: db0ea034fb8a47ea29fa
Version: webpack 4.20.2
Child
    Hash: db0ea034fb8a47ea29fa
    Time: 6336ms
    Built at: 2018-09-27 08:38:33
     1 asset
    Entrypoint main-client = main-client.js

    ERROR in ClientApp/boot.browser.ts(8,5): error TS2304: Cannot find name 'module'.
    ClientApp/boot.browser.ts(9,3): error TS2304: Cannot find name 'module'.
    ClientApp/boot.browser.ts(10,3): error TS2304: Cannot find name 'module'.
```

npm run build:prod works fine. I've tried several different ways to fix this but none seem to work.

**Comment by rodolfoortiz** [comment]
I forgot to add, one thing I did do was updating `webpack-cli` to 3.1.1 because I was getting an error `cannot read property 'properties' of undefined`. Upgrading to 3.1.1 got rid of the `undefined` error.

**Comment by MarkPieszak** [comment]
Can you take a look and see if 
https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/686
fixes this issue for you?

**Comment by rodolfoortiz** [comment]
That fixed, it, thank you so much.
