### ISSUE TITLE
Cannot even restore

### ISSUE THREAD

**Issue by montella1507** [MarkPieszak/aspnetcore-angular2-universal#694]
While trying to restore packages:

Error	NU1605	Detected package downgrade: Microsoft.EntityFrameworkCore from 2.1.1 to 2.1.0. Reference the package directly from the project to select a different version. 
 Asp2017 -> Microsoft.AspNetCore.All 2.1.1 -> Microsoft.EntityFrameworkCore (>= 2.1.1) 
 Asp2017 -> Microsoft.EntityFrameworkCore (>= 2.1.0)	Asp2017	

Fix in .csproj:

` <PackageReference Include="Microsoft.EntityFrameworkCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="2.1.1" />`

**Comment by MarkPieszak** [comment]
Upgrading to 2.1.1 fixed this? I can make sure that's in the latest master branch

**Comment by montella1507** [comment]
@MarkPieszak  Wait, did u rly react in 2 mins? WOW :-) you are my new Angular-team hero :-)   

1) it fixed problem with EF
2) Problem in documentation - dotnet restore is not enough - you have to specify Asp2017.sln because multiple .csproj/.sln files in folder (i suggest different project structure) - do you accept MRs?
3) Still  problem with npm build.. (Visual studio NPM install - warning it could not install optional dependency - not supported LOL )
   
```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (XXXXYYYYY\node_modules\webpack-cli\bin\config-yargs.js:89:48)
```
