### ISSUE TITLE
Webpack compilation reported errors on running project

### ISSUE THREAD

**Issue by ImkerAdam** [MarkPieszak/aspnetcore-angular2-universal#72]
- cloned the repo
- nuget/dotnet restore
- npm install
- starting the project inside Visual Studio 2015.

Got this in the browser:  

Thanks.
> An unhandled exception occurred while processing the request.
> 
> Exception: Call to Node module failed with error: Error: Webpack compilation reported errors. Compiler output follows: Hash: 9d0a8bbc8efdeb386297
> Version: webpack 2.2.0
> Time: 5867ms
> Asset Size Chunks Chunk Names
> 0.webpack-output.js 3.73 kB 0 [emitted] 
> webpack-output.js 87.4 kB 1 [emitted] main
> 0.webpack-output.js.map 2.48 kB 0 [emitted] 
> webpack-output.js.map 106 kB 1 [emitted] main
> 
> ERROR in [default] C:\temp\aspnetcore-angular2-universal\node_modules\@types\protractor\index.d.ts:11:33 
> Cannot find name 'webdriver'.
> 
> ERROR in [default] C:\temp\aspnetcore-angular2-universal\node_modules\@types\protractor\index.d.ts:12:26 
> Cannot find name 'webdriver'.
> 
> ERROR in [default] C:\temp\aspnetcore-angular2-universal\node_modules\@types\protractor\index.d.ts:13:31 
> Cannot find name 'webdriver'.
>

**Comment by MarkPieszak** [comment]
Looking at this right now, might have something to do with the PR https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/71. 

One sec let me check!

**Comment by ImkerAdam** [comment]
@MarkPieszak I can not belive your speed, so glad I chose this template! 

Greetings from Switzerland.

**Comment by MarkPieszak** [comment]
Glad to hear it ! 🎉 
Just trying to get everything more stable :)

As for the bug, yup that was it! I'm checking in the fix now, but you can just go to your `tsconfig.json` and remove the protractor string in the Array. That should do it!

    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "protractor", // <-- remove this line
      "source-map",
      "selenium-webdriver",
      "uglify-js",
      "webpack"
    ],

**Comment by ImkerAdam** [comment]
This worked! Thanks.
