### ISSUE TITLE
How to use jQuery with Angular2 in this project

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#73]
Hi, I want to add a chat client example in this template.

For that, I need to make a demo of **signalR** client with javascript.

For that, I need to add signalR javascript client.

For that, I need to add this 2 library to run this-

1. http://ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js
2. https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js

It can be found here-
https://www.npmjs.com/package/ms-signalr-client

So, I need to have jQuery to make a signalR example.

So, can u please help, @MarkPieszak ?

Thanks

**Comment by MarkPieszak** [comment]
The jQuery part and the signalr library part would be setup like in the FAQ here (https://github.com/MarkPieszak/aspnetcore-angular2-universal#how-can-i-use-jquery-andor-some-jquery-plugins-with-angular-universal).

I know they're working on a non-jquery version of the signalR client (https://github.com/aspnet/SignalR/issues/3), I'm not sure if that's part of the problem you're having?

Let me see how bad it is to add those necessary files.

Were you getting any specific errors?

**Comment by AbrarJahin** [comment]
Actually, I was having issue with webpack and jQuery.

I think it will be solved now :)

By the way, I have got a better library than jQuery plugin.

I am looking in this-

https://www.npmjs.com/package/@types/signalr

To add signalR

**Comment by MarkPieszak** [comment]
Since we'll hopefully be able to add SignalR with that other project, i think we can close this one out.

I'll try and add some more details (https://github.com/MarkPieszak/aspnetcore-angular2-universal#how-can-i-use-jquery-andor-some-jquery-plugins-with-angular-universal) there just in case for people as well.

**Comment by AbrarJahin** [comment]
Sure, that will be great :)
