### ISSUE TITLE
HttpCacheService saves client's requests to cache

### ISSUE THREAD

**Issue by nalex095** [MarkPieszak/aspnetcore-angular2-universal#74]
As far as I understand HttpCacheService is supposed to cache requests on the server and pass them to the client. But now it saves clients requests too. So even if you auto clean up the cache on client after first read, any subsequent request on the client pushes its result to the cache. And on the next request it is being read from there.

I believe there should be a way to avoid caching on client. Probably isNode check should be added there like:
```
        return this._http.get(url, options)
            .map(res => res.json())
            .do(json => { if (isNode) { this._cache.set(key, json); } })
            .share();
```

**Comment by MarkPieszak** [comment]
Thanks for noticing that! I actually think I noticed the same thing this afternoon! IsNode would be perfect. I can fix it up unless you'd like to put in a PR for it?

**Comment by nalex095** [comment]
I will be happy to contribute a little bit. Please see #75. Thanks!
