### ISSUE TITLE
Suggest instance on Heroku as Demo example

### ISSUE THREAD

**Issue by ORuban** [MarkPieszak/aspnetcore-angular2-universal#80]
I have successfully deployed this starter on Heroku and you can use this link as demo example: https://aspnetcore-angular2-universal.herokuapp.com

I am using free instance, to startup time for may be slow, as Heroku use sleep mode for such type of instances.

I am using a fork, as needed to have `app.json` config in repo and updated readme for "Deploy on Heroku" button + this allows to prevent possible deploying errors after changes in your master.

This buildpack has been used for deploy: [dotnet-core-buildpack](https://github.com/ORuban/dotnet-core-buildpack). And you are free to create your own instance if needed.

**Comment by MarkPieszak** [comment]
Great!
Would you like to make a PR to include the app.json etc so people can try deploying to Heroku as well?

I was attempting to have an example on Azure this weekend but was running into a random issue, hoping to have that available as well.

**Comment by AbrarJahin** [comment]
Prerender is not working in heroku.

Please have a look in here-

view-source:https://aspnetcore-angular2-universal.herokuapp.com/rest-test
