### ISSUE TITLE
UI-Router-ng2 Question

### ISSUE THREAD

**Issue by NelsonLamprecht** [MarkPieszak/aspnetcore-angular2-universal#86]
New to the angular 2 world:
Has anyone used universal successfully with ui-router-ng2?
Atttempting to add it in place of the built in router but I get this exception:
TypeError: this._rootRenderer.document.querySelector is not a function
at DomRenderer.selectRootElement
at selectOrCreateRenderHostElement 
..

**Comment by MarkPieszak** [comment]
I haven't played with the UI-Router with Universal specifically but I just spoke with the author he said he believes it should work though?

Do you have it within a fork/repo so I can try and take a look?

**Comment by NelsonLamprecht** [comment]
Let me see what I can put together...
Found this as well which seems to be the same stack trace:
https://github.com/devCrossNet/universal-cli/issues/54

**Comment by NelsonLamprecht** [comment]
I forked your solution and tried to introduce ui-router-ng2 but now I am getting something different so its obvious I am missing something. Any help would be appreciated...

**Comment by NelsonLamprecht** [comment]
https://github.com/TalaveraTechnologySolutions/aspnetcore-angular2-universal

**Comment by MarkPieszak** [comment]
Looks like UI-Router should work with it :)
https://github.com/ui-router/ng2/issues/18
