### ISSUE TITLE
vendor.css creation and file optimization is not working with webpack2

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#87]
If we uncomment this 2 line-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/src/Angular2Spa/webpack.config.vendor.js#L50-L51

Then vendor.css is created.

But we are getting an error in prerendering with **webpack2** that it is unable to create the font files

I think, we need to have a look in here @MarkPieszak .

**Comment by btmadison** [comment]
I am guessing the following problem may be related:

I have created a new project clone, have run dotnet restore and npm install.

from commandline I have tried:
set ASPNETCORE_ENVIRONMENT=Development
and then dotnet watch run

The site comes up fine at localhost 5000, but I notice that HMR is not active.  

the console output is as follows:
GET http://localhost:5000/dist/vendor.css  (failed, has red x next to it and hte file does not exist in a dist folder)
app.component.ts:37 oninit
vendor.js?v=I8uIFuvFr0UCrItxffQ02JVsVbJBN-hkqMoZiZt2xwk:2502 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
home.component.ts:19 Are we inside the Browser ? true

Additionally, I have found that when I change css files, the changes are not reflected after manually refreshing the site, or restarting the dotnet process and reloading the site.

**Comment by MarkPieszak** [comment]
@btmadison I'll take a look first thing tomorrow, I've had HMR working, but wasn't testing CSS. Thanks for letting me know!

**Comment by AbrarJahin** [comment]
To fix this issue, we need to un-comment this 2 lines-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L50

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L51

Then **vendor.css** will be generated.

But we will get issue with **asp-prerender** with webpack2 which is getting conflicts with font files of font awsome.

I think we should have take a look into this @MarkPieszak

**Comment by btmadison** [comment]
in the past when I imported font-awesome.css from my node modules, I also had to import the 5 webfont files individually from the font-awesome/fonts folder - maybe this will help.  I will try your suggestion and see if vendor.css generates though with uncommenting as you suggested.

**Comment by btmadison** [comment]
No luck with generating a vendor.css fil, I have tried your suggestions @AbrarJahin  - one thing I am not fully clear on though so this could be my error - other than setting the env var to dev and running dotnet restore, nom install, dotnet watch run (or dotnet run) - am I supposed to be manually running any other commands such as any of the webpack or other npm scripts?  For the readme, I only see mention of running webpack if attempting production mode with the production env var also.

**Comment by MarkPieszak** [comment]
Are you having errors with anything right now? Building webpack etc? @btmadison 
There are scripts you can run to just run both webpack & vendor webpack bundles.

Run `npm run postinstall -- --display-error-details` so we can see anything specific going on for you.

I'll try and fix the vendor.css issue today, I might leave fontawesome out of the mix for now (since that's its own issue with webpack2) but we need the vendor.css to be generating.

**Comment by MarkPieszak** [comment]
@btmadison For HMR have you set the ASPNETCORE_ENVIRONMENT by any chance? That's what triggers whether dotnet run will go into Dev mode and setup HMR.

> Note: set ASPNETCORE_ENVIRONMENT=Development on Windows. export ASPNETCORE_ENVIRONMENT=Development on Mac/Linux.

If you're using VSCode, when you push F5 (it automatically) sets it to Development mode through the launch.json.

**Comment by btmadison** [comment]
Yes I have. I will try more tonight Anna provide the requested debug output
from running the suggested commands. Thanks!

**Comment by MarkPieszak** [comment]
Ok great! Just tried with a fresh repo (in a new directory) and without manually setting the environment variable to Dev, .NET thinks it's Production mode, so within the StartUp.Cs file HMR mode doesn't get enabled. Setting that fixed it. Hope that helps!

**Comment by AbrarJahin** [comment]
@btmadison 

Procedure is-

1. UnComment this 2 lines-

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L50

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/webpack.config.vendor.js#L51

Then vendor.css will be generated.

If not generated, then run-

    node node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod
    node node_modules/webpack/bin/webpack.js --env.prod

In [CMD](http://www.computerhope.com/issues/chusedos.htm).

Should work.

**Comment by AbrarJahin** [comment]
Hi @MarkPieszak , is there any update regarding this issue?

**Comment by MarkPieszak** [comment]
Fixed 🍻 🍺 
via https://github.com/MarkPieszak/aspnetcore-angular2-universal/commit/a194af3cff77af6d5456ebbbf03af87558da6bb3 just now

**Comment by AbrarJahin** [comment]
Thanks @MarkPieszak for the great work 💯

**Comment by kwiniarski97** [comment]
I got another issue(i think). Should the vendor.css be recreated when i update node_module? I've updated bootstrap from 3.3.7 to 4.0.0, yet the vendor.css didn't update and still contains old bootstrap.

**Comment by peterdobson** [comment]
@kwiniarski97  have you run the following command?:

 webpack --config webpack.config.vendor.js

**Comment by crtjr64** [comment]
I got the same issue as peterdobson. I'm very new to VueJs but a very seasoned programmer and the client I have now just has to use VueJs and TypeScript with Core 2. I tried this but "webpack" is not recognized as an internal or external command... I've been struggling with this for about 3 weeks but my app is coming together, however, I needed to upgrade bootstrap and this did not work for me.
