### ISSUE TITLE
Chat example with SignalR

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#90]
We can use this-

 https://www.npmjs.com/package/ng2-signalr

For integrating signalR with angular2

**Comment by MarkPieszak** [comment]
100% Typescript don't see jQuery in that package.json perfect!

**Comment by MarkPieszak** [comment]
@hakonamatata Jan set this up for us! Merged into Master this morning :100: 
Closing this one out
