### ISSUE TITLE
bootstrap 4 customization requires scss

### ISSUE THREAD

**Issue by btmadison** [MarkPieszak/aspnetcore-angular2-universal#92]
Loading of Bootstrap 4 is hardcoded to the css cdn in _Layout.cshtml.  Is there a way to instead use the scss from node modules and elsewhere provide a _custom.scss file to provide default overrides to allow re-theme of colors and other options.

**Comment by MarkPieszak** [comment]
Definitely! 
Right now we just have it setup to at least apply the styles, there were some issues with webpack2 with bootstrap & fontawesome that I was looking into. (Related #84)
Ideally we definitely want it to be completely configurable like that!

There are a few options when it comes to setting it up (one being: https://github.com/shakacode/bootstrap-loader)

**Comment by btmadison** [comment]
I am not sure if this is a hack, but I have found if I enable scss loading, and remove the imports from the cshtml - instead of loading the scss in the vendor scripts, I have just placed the import in the root app component styleUrls listed app.component.scss file, and set the encapsulation mode to ViewEncapsulation.None, thus setting the bootstrap generated css available to the whole application.  Additionally the ncie thing I find about this is isntead of adding the variable resets to the _custom file, I can add the resets in the same file before doing the @import, thus giving full configuration.

**Comment by MarkPieszak** [comment]
Oh great, so you have it working? :100: 
Do you want to make a PR to add the functionality in?

**Comment by MarkPieszak** [comment]
@btmadison Apologies for the crazy delay, it's been absolutely crazy these past many weeks with all the changes going on, but I'm actually going to make this a standard for the repo (bootstrap w/ scss for theme-ing)

**Comment by MarkPieszak** [comment]
Merged in, we now have Bootstrap with SCSS built-in :)
ng2-bootstrap again as well!
