### ISSUE TITLE
npm test results in ForkCheckerPlugin error - remove construction from webpack test config

### ISSUE THREAD

**Issue by btmadison** [MarkPieszak/aspnetcore-angular2-universal#93]
when running npm test, the following error results:

> Error in config file!
>  TypeError: ForkCheckerPlugin is not a constructor
>     at Object.<anonymous> (C:\dev\aspnetcore-angular2-universal\webpack.config.te
> st.js:124:9)

commenting out line 124 in webpack.config.test.js as follows:
`// new ForkCheckerPlugin(),`
allows the single sample test to pass.

The ForkCheckerPlugin has been removed from the awesome-typescript-loader, and as mentioned in the following, can be removed with latest version.

https://github.com/s-panferov/awesome-typescript-loader/issues/274

**Comment by MarkPieszak** [comment]
Oh great, thanks for noticing that! There were recently build changes, I was actually just about to check Testing :)

Did you want to make a PR, if not I can make the fix.

👍

**Comment by btmadison** [comment]
@MarkPieszak I will do a PR for it but it may be a few hours

**Comment by btmadison** [comment]
I have created a pull request for this issue - https://github.com/MarkPieszak/aspnetcore-angular2-universal/pull/96
