### ISSUE TITLE
npm webpack hangs due to dashboard plugin

### ISSUE THREAD

**Issue by Ketrex** [MarkPieszak/aspnetcore-angular2-universal#95]
I just pulled commit `a814958` and when I run npm install it hangs while running the post install `webpack --progress` command. Removing the recent addition of the Dashboard plugin in the webpack.config fixes the problem. I tried this on two different computers and both hang.

**Comment by daveo1001** [comment]
We just can't win, @MarkPieszak.

**Comment by AbrarJahin** [comment]
I think it is not an issue.

What do u think @MarkPieszak ?

**Comment by MarkPieszak** [comment]
Crap, you're totally right... Might be why it was removed initially I need to fix it by passing some flags so that the plugin only gets initialized when running the dashboard npm script.

**Comment by MarkPieszak** [comment]
So it's fixed for hanging the `npm i` but there's still an underlying issue with dashboard :(

I'll re-open that issue so we can figure out the fix for it.

https://github.com/FormidableLabs/webpack-dashboard/issues/96
