### ISSUE TITLE
Make a common route file to add route easily in the project

### ISSUE THREAD

**Issue by AbrarJahin** [MarkPieszak/aspnetcore-angular2-universal#98]
In current configuration, if we need to add a route in the project, we need to do this thing-

1. Create a folder in `Client\Containers\`
2. Create a component in the folder
3. Add the container in the `Client\Containers\index.ts` (this is the "barrels" file for all containers)
4. Add the container in the `\Client\app\platform-modules\app.common.module.ts`
5. Add the container in the `\Client\app\app.routes.ts`

I think, there should be a more simplified way to do this.

No 1,2 and 3 are OK.

But is it possible to remove step 4 so that we need to add a route in only `app.routes.ts` and all configuration for no 4 will be done automatically?

It will be easy to code then and nearly this kind of way is used in **[this template](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ASPNETCoreTemplatePack)**.

It is just a request so that if we can make this template easier to use and manage for developers.

Waiting for suggestion @MarkPieszak 

Thanks

**Comment by MarkPieszak** [comment]
We could potentially put the Routes themselves **inside** of `app.routes.ts`, which slightly junks it up, but then again it'd be one less file & import (to do again).

Does anyone have any thoughts on this? @Ketrex @ORuban

**Comment by MarkPieszak** [comment]
Thought about it and I think you're right!
I also renamed & moved the `app.common.module` file to the general `/app/` directory, so it's next to `app.component` etc.

I removed app.routes and simply put them inside that main `app.module.ts` file, so when you add new components, it's just much easier and you can make the necessary changes right in there!

Should make the dev experience better 👍

**Comment by AbrarJahin** [comment]
Thanks for updating the code for better dev experience @MarkPieszak :1st_place_medal:
